/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/pascal_profile_manager/xx_pascal_profile_manager.h"

XX_FORMAT_DEFINE_READER_ADAPTER(pascal_profile_manager, XX_FILE_TYPE_PASCAL_PROFILE_MANAGER,
    xx_pascal_profile_manager_create(device, 0), xx_pascal_profile_manager_free, XX_READER_TYPE_FILL_UNKNOWN)

