/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 */
/* Bounded ACE 1.x/2.x LZ/Huffman stream decoder. */
#include "xxfclib/rt/xx_rt.h"
#include "xx_ace_dec.h"
#include "xxfclib/memory/xx_memory.h"
#include <string.h>

#define ACE_MAIN_BITS 11U
#define ACE_META_BITS 7U
#define ACE_MAIN_COUNT 284U
#define ACE_LENGTH_COUNT 256U
#define ACE_DICT_MIN 10U
#define ACE_DICT_MAX 22U

typedef struct ace_bits_s { const uint8_t *data; size_t size, position; bool bad; } ace_bits;
typedef struct ace_state_s {
    ace_bits bits; uint16_t main_table[1U<<ACE_MAIN_BITS], length_table[1U<<ACE_MAIN_BITS], meta_table[1U<<ACE_META_BITS];
    uint8_t main_width[ACE_MAIN_COUNT], length_width[ACE_LENGTH_COUNT], meta_width[16];
    uint8_t *dict; size_t dict_size, dict_pos, history, output_pos, output_size;
    uint32_t old_dist[4]; unsigned old_index, block_left; uint8_t *output;
    uint8_t next_mode, delta_dist, exe_mode; uint32_t delta_len;
} ace_state;
static uint32_t ace_word(const ace_bits *b,size_t offset){uint32_t value=0;unsigned i;for(i=0;i<4U&&offset+i<b->size;i++)value|=(uint32_t)b->data[offset+i]<<(8U*i);return value;}
/* ACE Huffman decoding reads a short zero-padded look-ahead window.  Bounds
 * are enforced when bits are consumed, rather than when they are inspected. */
static uint32_t ace_peek(ace_bits *b,unsigned n){size_t word,shift;uint64_t value;if(!b||n==0U||n>24U||b->position>b->size*8U){if(b)b->bad=true;return 0;}word=b->position/32U;shift=b->position%32U;value=(uint64_t)ace_word(b,word*4U)<<32U;value|=ace_word(b,(word+1U)*4U);return (uint32_t)((value<<shift)>>(64U-n));}
static void ace_skip(ace_bits *b,unsigned n){if(!b||b->position+n>b->size*8U)b->bad=true;else b->position+=n;}
static void ace_sort_range(uint8_t *frequency,uint16_t *symbol,int left,int right){int lo=left,hi=right;uint8_t pivot=frequency[right];do{while(frequency[lo]>pivot)++lo;while(frequency[hi]<pivot)--hi;if(lo<=hi){uint8_t f=frequency[lo];uint16_t s=symbol[lo];frequency[lo]=frequency[hi];symbol[lo]=symbol[hi];frequency[hi]=f;symbol[hi]=s;++lo;--hi;}}while(lo<hi);if(left<hi){if(left<hi-1)ace_sort_range(frequency,symbol,left,hi);else if(frequency[left]<frequency[hi]){uint8_t f=frequency[left];uint16_t s=symbol[left];frequency[left]=frequency[hi];symbol[left]=symbol[hi];frequency[hi]=f;symbol[hi]=s;}}if(right>lo){if(lo<right-1)ace_sort_range(frequency,symbol,lo,right);else if(frequency[lo]<frequency[right]){uint8_t f=frequency[lo];uint16_t s=symbol[lo];frequency[lo]=frequency[right];symbol[lo]=symbol[right];frequency[right]=f;symbol[right]=s;}}}
/* ACE's table construction preserves the original decoder's quick-sort tie
 * order.  That order is observable for intentionally degenerate tables. */
static bool ace_make_table(uint8_t *width,size_t count,unsigned bits,uint16_t *table){uint16_t symbol[ACE_MAIN_COUNT];uint8_t frequency[ACE_MAIN_COUNT];size_t i,nonzero=0,cursor=0;unsigned size=1U<<bits;if(!width||!table||count==0U||count>ACE_MAIN_COUNT||bits>ACE_MAIN_BITS)return false;for(i=0;i<count;i++){if(width[i]>bits)return false;frequency[i]=width[i];symbol[i]=(uint16_t)i;}if(count>1U)ace_sort_range(frequency,symbol,0,(int)count-1);while(nonzero<count&&frequency[nonzero])++nonzero;if(nonzero<2U){width[symbol[0]]=1U;if(!nonzero)nonzero=1U;}--nonzero;for(i=0;i<size;i++)table[i]=UINT16_MAX;for(;;){unsigned span=1U<<(bits-frequency[nonzero]);if(cursor+span>size)return false;while(span--)table[cursor++]=symbol[nonzero];if(nonzero==0U)break;--nonzero;}return true;}
static bool ace_read_widths(ace_state *s,unsigned bits,uint16_t *table,uint8_t *width,size_t capacity){unsigned number,lower,upper,i,j=0;if(!s||capacity==0)return false;xx_rt_memset(width,0,capacity);number=ace_peek(&s->bits,9);ace_skip(&s->bits,9);lower=ace_peek(&s->bits,4);ace_skip(&s->bits,4);upper=ace_peek(&s->bits,4);ace_skip(&s->bits,4);if(s->bits.bad||number>=capacity||upper>15U)return false;xx_rt_memset(s->meta_width,0,sizeof(s->meta_width));for(i=0;i<=upper;i++){s->meta_width[i]=(uint8_t)ace_peek(&s->bits,3);ace_skip(&s->bits,3);}if(s->bits.bad||!ace_make_table(s->meta_width,upper+1U,ACE_META_BITS,s->meta_table))return false;while(j<=number){unsigned symbol=ace_peek(&s->bits,ACE_META_BITS),run;if(symbol>=(1U<<ACE_META_BITS)||(symbol=s->meta_table[symbol])>upper||!s->meta_width[symbol])return false;ace_skip(&s->bits,s->meta_width[symbol]);if(symbol<upper)width[j++]=(uint8_t)symbol;else{run=ace_peek(&s->bits,4)+4U;ace_skip(&s->bits,4);while(run--&&j<=number)width[j++]=0U;}}if(s->bits.bad)return false;for(i=1;i<=number;i++)if(upper)width[i]=(uint8_t)((width[i]+width[i-1])%upper);for(i=0;i<=number;i++)if(width[i]){if(width[i]+lower>bits)return false;width[i]=(uint8_t)(width[i]+lower);}return ace_make_table(width,number+1U,bits,table);}
static bool ace_new_block(ace_state *s){if(!ace_read_widths(s,ACE_MAIN_BITS,s->main_table,s->main_width,ACE_MAIN_COUNT)||!ace_read_widths(s,ACE_MAIN_BITS,s->length_table,s->length_width,ACE_LENGTH_COUNT))return false;s->block_left=ace_peek(&s->bits,15);ace_skip(&s->bits,15);return !s->bits.bad&&s->block_left!=0U;}
static bool ace_byte(ace_state *s,uint8_t value){if(!s||s->output_pos>=s->output_size)return false;s->output[s->output_pos++]=value;s->dict[s->dict_pos++]=value;s->dict_pos&=s->dict_size-1U;if(s->history<s->dict_size)++s->history;return true;}
static bool ace_copy(ace_state *s,uint32_t distance,unsigned length){size_t p;if(!s||distance==0U||distance>s->dict_size||distance>s->history||length>259U||length>s->output_size-s->output_pos)return false;p=(s->dict_pos+s->dict_size-distance)&(s->dict_size-1U);while(length--){if(!ace_byte(s,s->dict[p]))return false;p=(p+1U)&(s->dict_size-1U);}return true;}
/* Returns 0 for output, 1 for an ACE 2 mode instruction and -1 for invalid
 * compressed data.  The mode marker is part of the ACE 2 main symbol tree. */
static int ace_symbol(ace_state *s,bool blocked){unsigned code,length_code,base=2U;uint32_t distance;if(!s->block_left&&!ace_new_block(s))return -1;code=ace_peek(&s->bits,ACE_MAIN_BITS);if(s->bits.bad||code>=(1U<<ACE_MAIN_BITS)||(code=s->main_table[code])>=ACE_MAIN_COUNT||!s->main_width[code])return -1;ace_skip(&s->bits,s->main_width[code]);--s->block_left;if(code==283U){if(!blocked)return -1;s->next_mode=(uint8_t)ace_peek(&s->bits,8);ace_skip(&s->bits,8);if(s->next_mode==1U){s->delta_dist=(uint8_t)ace_peek(&s->bits,8);ace_skip(&s->bits,8);s->delta_len=ace_peek(&s->bits,17);ace_skip(&s->bits,17);}else if(s->next_mode==2U){s->exe_mode=(uint8_t)ace_peek(&s->bits,8);ace_skip(&s->bits,8);}return s->bits.bad?-1:1;}if(code<256U)return ace_byte(s,(uint8_t)code)?0:-1;if(code>259U){unsigned exponent=code-260U;if(exponent>22U)return -1;if(exponent>1U){distance=ace_peek(&s->bits,exponent-1U)+(1U<<(exponent-1U));ace_skip(&s->bits,exponent-1U);}else distance=exponent;s->old_index=(s->old_index+1U)&3U;s->old_dist[s->old_index]=distance;if(distance>255U)++base;if(distance>8191U)++base;}else{unsigned ref=code&3U,k;distance=s->old_dist[(s->old_index-ref)&3U];for(k=ref+1U;k-- >0U;)s->old_dist[(s->old_index-k)&3U]=s->old_dist[(s->old_index-k+1U)&3U];s->old_dist[s->old_index]=distance;if(ref>1U)++base;}length_code=ace_peek(&s->bits,ACE_MAIN_BITS);if(s->bits.bad||length_code>=(1U<<ACE_MAIN_BITS)||(length_code=s->length_table[length_code])>=ACE_LENGTH_COUNT||!s->length_width[length_code])return -1;ace_skip(&s->bits,s->length_width[length_code]);return !s->bits.bad&&ace_copy(s,distance+1U,length_code+base)?0:-1;}
static bool ace_init(ace_state *s,const void *source,size_t source_size,void *destination,size_t destination_size,unsigned dictionary_bits){if((!source&&source_size)||!destination||source_size==0U||(source_size&3U)||dictionary_bits<ACE_DICT_MIN||dictionary_bits>ACE_DICT_MAX)return false;xx_rt_memset(s,0,sizeof(*s));s->bits.data=(const uint8_t *)source;s->bits.size=source_size;s->output=(uint8_t *)destination;s->output_size=destination_size;s->dict_size=(size_t)1U<<dictionary_bits;s->dict=(uint8_t *)xx_mem_calloc(s->dict_size,1U);return s->dict!=NULL;}
static bool ace_filter_delta(uint8_t *out,size_t start,size_t end,unsigned dist,uint32_t expected,uint8_t *last){uint8_t *tmp;size_t n=end-start,i,plane,pos;if(!dist||!expected||n!=expected||n%dist)return false;for(i=start;i<end;i++){out[i]=(uint8_t)(out[i]+*last);*last=out[i];}tmp=(uint8_t *)xx_mem_alloc(n);if(!tmp)return false;plane=n/dist;pos=0;for(i=0;i<plane;i++){size_t j;for(j=i;j<n;j+=plane)tmp[pos++]=out[start+j];}xx_rt_memcpy(out+start,tmp,n);xx_mem_free(tmp);return true;}
static void ace_filter_exe(uint8_t *out,size_t start,size_t end,unsigned mode){size_t i;for(i=start;i<end;i++){uint32_t v,pos=(uint32_t)i;if(out[i]==0xe8U&&i+2U<end){if(mode==0U){v=(uint32_t)out[i+1]|((uint32_t)out[i+2]<<8);v=(v-pos)&0xffffU;out[i+1]=(uint8_t)v;out[i+2]=(uint8_t)(v>>8);i+=2U;}else if(i+4U<end){v=(uint32_t)out[i+1]|((uint32_t)out[i+2]<<8)|((uint32_t)out[i+3]<<16)|((uint32_t)out[i+4]<<24);v-=pos;out[i+1]=(uint8_t)v;out[i+2]=(uint8_t)(v>>8);out[i+3]=(uint8_t)(v>>16);out[i+4]=(uint8_t)(v>>24);i+=4U;}}else if(out[i]==0xe9U&&i+2U<end){v=(uint32_t)out[i+1]|((uint32_t)out[i+2]<<8);v=(v-pos)&0xffffU;out[i+1]=(uint8_t)v;out[i+2]=(uint8_t)(v>>8);i+=2U;}}}
bool xx_ace_decode_lzh(const void *source,size_t source_size,void *destination,size_t destination_size,unsigned dictionary_bits){ace_state s;bool ok;if(!ace_init(&s,source,source_size,destination,destination_size,dictionary_bits))return false;while(s.output_pos<destination_size&&!s.bits.bad)if(ace_symbol(&s,false)!=0){s.bits.bad=true;break;}ok=!s.bits.bad&&s.output_pos==destination_size&&s.bits.position<=source_size*8U&&source_size*8U-s.bits.position<32U;xx_mem_free(s.dict);return ok;}
bool xx_ace_decode_blocked(const void *source,size_t source_size,void *destination,size_t destination_size,unsigned dictionary_bits){ace_state s;size_t begin=0;uint8_t mode=0,last_delta=0,delta_dist=0,exe_mode=0;uint32_t delta_len=0;bool ok=false;if(!ace_init(&s,source,source_size,destination,destination_size,dictionary_bits))return false;while(s.output_pos<destination_size&&!s.bits.bad){int got=ace_symbol(&s,true);if(got<0)break;if(got==1){if(mode==1U&&!ace_filter_delta(s.output,begin,s.output_pos,delta_dist,delta_len,&last_delta))break;if(mode==2U)ace_filter_exe(s.output,begin,s.output_pos,exe_mode);if(s.next_mode>2U){s.bits.bad=true;break;}mode=s.next_mode;delta_dist=s.delta_dist;delta_len=s.delta_len;exe_mode=s.exe_mode;begin=s.output_pos;}}if(!s.bits.bad){if(mode==1U)ok=ace_filter_delta(s.output,begin,s.output_pos,delta_dist,delta_len,&last_delta);else{if(mode==2U)ace_filter_exe(s.output,begin,s.output_pos,exe_mode);ok=true;}}ok=ok&&s.output_pos==destination_size&&s.bits.position<=source_size*8U&&source_size*8U-s.bits.position<32U;xx_mem_free(s.dict);return ok;}
