/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/quoted_printable_encoded_fil/xx_quoted_printable_encoded_fil.h"

XX_FORMAT_DEFINE_READER_ADAPTER(quoted_printable_encoded_fil, XX_FILE_TYPE_QUOTED_PRINTABLE_ENCODED_FIL,
    xx_quoted_printable_encoded_fil_create(device, 0), xx_quoted_printable_encoded_fil_free, XX_READER_TYPE_FILL_UNKNOWN)

