/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/acorn_dfs/xx_acorn_dfs.h"

XX_FORMAT_DEFINE_READER_ADAPTER(acorn_dfs, XX_FILE_TYPE_ACORN_DFS,
    xx_acorn_dfs_create(device, 0), xx_acorn_dfs_free, XX_READER_TYPE_FILL_UNKNOWN)

