/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/ti99_pc99/xx_ti99_pc99.h"

XX_FORMAT_DEFINE_READER_ADAPTER(ti99_pc99, XX_FILE_TYPE_TI99_PC99,
    xx_ti99_pc99_create(device, 0), xx_ti99_pc99_free, XX_READER_TYPE_FILL_UNKNOWN)

