/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/human68k_partitions/xx_human68k_partitions.h"

XX_FORMAT_DEFINE_READER_ADAPTER(human68k_partitions, XX_FILE_TYPE_HUMAN68K_PARTITIONS,
    xx_human68k_partitions_create(device, 0), xx_human68k_partitions_free, XX_READER_TYPE_FILL_UNKNOWN)

