/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 */

/* xx_riversoft_extractor.c - search raw data for RIVERSOFT.
 *
 * Scans for:
 *   52 69 76 65 72 53 6F 66 74 20 44 61 74 61 20 4C 69 62 72 61 72 79 1A at +0  ("RiverSoft Data Library.")
 * Offset 0 is always tried as well.
 * Each candidate must be accepted by the riversoft reader, which also measures it,
 * and named by the detector, both on a view that starts at the candidate.
 * See xx_format_extractor_engine.h.
 *
 * GENERATED by gen_extractors.py from the detector's prefilters.
 */

#include "../xx_format_extractor_engine.h"
#include "xxfclib/formats/riversoft/xx_riversoft.h"

static const uint8_t k_anchor0[] = { 0x52, 0x69, 0x76, 0x65, 0x72, 0x53, 0x6F, 0x66, 0x74, 0x20, 0x44, 0x61, 0x74, 0x61, 0x20, 0x4C, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x1A };

static const xx_format_search_anchor k_anchors[] = {
    { k_anchor0, sizeof(k_anchor0), 0U },
};

static const xx_file_type_t k_types[] = { XX_FILE_TYPE_RIVERSOFT };

static Abstractformat *xx_riversoft_search_open(xx_io_device *window) {
    xx_riversoft *reader = xx_riversoft_create(window, 0);
    return reader ? &reader->format : NULL;
}

static void xx_riversoft_search_close(Abstractformat *format) {
    /* The format is the first member, so this is the reader itself. */
    xx_riversoft_free((xx_riversoft *)format);
}

static const xx_format_search_desc k_desc = {
    k_types, sizeof(k_types) / sizeof(k_types[0]),
    k_anchors, sizeof(k_anchors) / sizeof(k_anchors[0]),
    xx_riversoft_search_open, xx_riversoft_search_close
};

static xx_format_search_state *xx_riversoft_create_format_search(
    xx_format_extractor *self, xx_io_device *device, const xx_list_s *options,
    xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_create(&k_desc, device, options, pd);
}

static const xx_format_search_info *xx_riversoft_get_current_format_info(
    xx_format_extractor *self, xx_format_search_state *state) {
    (void)self;
    return xx_format_search_current(state);
}

static bool xx_riversoft_format_search_find_next(xx_format_extractor *self,
                                          xx_format_search_state *state,
                                          xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_find_next(state, pd);
}

static void xx_riversoft_free_format_search(xx_format_extractor *self,
                                     xx_format_search_state *state) {
    (void)self;
    xx_format_search_free(state);
}

xx_format_extractor xx_riversoft_extractor = {
    xx_riversoft_create_format_search,
    xx_riversoft_get_current_format_info,
    xx_riversoft_format_search_find_next,
    xx_riversoft_free_format_search
};
