/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Bounded primary-layout reader. Payloads are never executed.
 */
/* Primary layout: https://www.rfc-editor.org/rfc/rfc7292.html */
#include "xxfclib/formats/pkcs12_pfx/xx_pkcs12_pfx.h"
#include "../common/xx_container_wire_helpers.h"

#include "../common/xx_asn1_der.h"
#include "xxfclib/algo/hash/xx_hash.h"
static bool pf_oid(memory_blob *b,der_tlv *t,const uint8_t *oid,size_t n) {return t->tag==6 && t->end-t->value==n && !xx_rt_memcmp(b->p+(size_t)t->value,oid,n);}
static bool pf_data(memory_blob *b,uint64_t *at,uint64_t end,der_tlv *info,der_tlv *octet) {static const uint8_t oid[]={42,134,72,134,247,13,1,7,1};der_tlv x,y;uint64_t p,q;if(!der_take(b,at,end,48,info)) return false;p=info->value;if(!der_take(b,&p,info->end,6,&x) || !pf_oid(b,&x,oid,sizeof(oid)) || !der_take(b,&p,info->end,160,&y) || p!=info->end) return false;q=y.value;return der_take(b,&q,y.end,4,octet) && q==y.end;}
static bool pf_key(memory_blob *b,der_tlv *t) {unsigned work=0;der_tlv x,y;uint64_t at=t->value,p;static const uint8_t rsa[]={42,134,72,134,247,13,1,1,1};if(t->tag!=48 || !der_take(b,&at,t->end,2,&x) || x.end-x.value!=1 || b->p[(size_t)x.value] || !der_take(b,&at,t->end,48,&x)) return false;p=x.value;if(!der_take(b,&p,x.end,6,&y) || !pf_oid(b,&y,rsa,sizeof(rsa)) || (p<x.end && (!der_take(b,&p,x.end,5,&y) || y.value!=y.end)) || p!=x.end || !der_take(b,&at,t->end,4,&x) || at!=t->end || !der_tree(b,x.value,x.end,0,&work)) return false;p=x.value;if(!der_take(b,&p,x.end,48,&y) || p!=x.end) return false;p=y.value;for(unsigned i=0;i<9;++i) {if(!der_take(b,&p,y.end,2,&x) || x.value==x.end || (b->p[(size_t)x.value]&128) || (i==0 && (x.end-x.value!=1 || b->p[(size_t)x.value]))) return false;}return p==y.end;}
static bool pf_bags(Abstractformat *f,pm_stream *s,memory_blob *b,uint64_t at,uint64_t end,unsigned depth,unsigned *bags,unsigned *work) {static const uint8_t prefix[]={42,134,72,134,247,13,1,12,10,1};static const uint8_t certoid[]={42,134,72,134,247,13,1,9,22,1};der_tlv root,bag,oid,wrap,value,x,y;uint64_t p,q,z;if(depth>16 || !der_tree(b,at,end,0,work) || !der_take(b,&at,end,48,&root) || at!=end) return false;at=root.value;while(at<root.end) {if(++*bags>1024 || !der_take(b,&at,root.end,48,&bag)) return false;p=bag.value;if(!der_take(b,&p,bag.end,6,&oid) || oid.end-oid.value!=11 || xx_rt_memcmp(b->p+(size_t)oid.value,prefix,10) || !der_take(b,&p,bag.end,160,&wrap)) return false;q=wrap.value;if(!der_read(b,&q,wrap.end,&value) || q!=wrap.end) return false;uint8_t kind=b->p[(size_t)oid.value+10];if(kind==1) {if(!pf_key(b,&value)) return false;}else if(kind==2) {q=value.value;if(value.tag!=48 || !der_take(b,&q,value.end,48,&x) || !der_alg(b,&x) || !der_take(b,&q,value.end,4,&x) || x.value==x.end || q!=value.end) return false;}else if(kind==3) {q=value.value;if(value.tag!=48 || !der_take(b,&q,value.end,6,&x) || !pf_oid(b,&x,certoid,sizeof(certoid)) || !der_take(b,&q,value.end,160,&x) || q!=value.end) return false;z=x.value;if(!der_take(b,&z,x.end,4,&y) || z!=x.end) return false;z=y.value;if(!der_tree(b,y.value,y.end,0,work) || !der_take(b,&z,y.end,48,&x) || z!=y.end || !der_cert(b,&x)) return false;}else if(kind==6) {if(!pf_bags(f,s,b,value.start,value.end,depth+1,bags,work)) return false;}else return false;if(p<bag.end && (!der_take(b,&p,bag.end,49,&x) || !der_attr(b,&x))) return false;if(p!=bag.end || !blob_add(f,s,b,kind==2 ? "encoded-encrypted-key-bag":"safe-bag",bag.start,bag.end-bag.start)) return false;}return at==root.end;}
static bool pf_mac(memory_blob *b,der_tlv *mac,der_tlv *auth) {static const uint8_t oid[]={96,134,72,1,101,3,4,2,1};der_tlv info,alg,digest,salt,it,x;uint64_t at=mac->value,p,iterations=1;uint8_t material[192],key[32],inner[32],outer[96],want[32],*buf=NULL;bool ok=false;if(!der_take(b,&at,mac->end,48,&info)) return false;p=info.value;if(!der_take(b,&p,info.end,48,&alg)) return false;uint64_t q=alg.value;if(!der_take(b,&q,alg.end,6,&x) || !pf_oid(b,&x,oid,sizeof(oid)) || (q<alg.end && (!der_take(b,&q,alg.end,5,&x) || x.value!=x.end)) || q!=alg.end || !der_take(b,&p,info.end,4,&digest) || p!=info.end || digest.end-digest.value!=32 || !der_take(b,&at,mac->end,4,&salt) || salt.value==salt.end || salt.end-salt.value>64) return false;if(at<mac->end) {if(!der_take(b,&at,mac->end,2,&it) || it.value==it.end || it.end-it.value>4 || (b->p[(size_t)it.value]&128)) return false;iterations=0;for(p=it.value;p<it.end;++p) iterations=(iterations<<8)|b->p[(size_t)p];}if(at!=mac->end || !iterations || iterations>100000) return false;xx_mem_zero(material,sizeof(material));for(unsigned i=0;i<64;++i) {material[i]=3;material[i+64]=b->p[(size_t)(salt.value+i%(salt.end-salt.value))];}if(!xx_sha256_memory(material,sizeof(material),key)) return false;for(uint64_t i=1;i<iterations;++i) if(binary_stop(b->pd) || !xx_sha256_memory(key,32,key)) return false;uint64_t n=auth->end-auth->value;if(n>67108736 || binary_stop(b->pd)) return false;buf=(uint8_t *)xx_mem_alloc((size_t)n+64);if(!buf) return false;for(unsigned i=0;i<64;++i) {buf[i]=(uint8_t)((i<32 ? key[i]:0)^0x36);outer[i]=(uint8_t)((i<32 ? key[i]:0)^0x5c);}xx_mem_copy(buf+64,b->p+(size_t)auth->value,(size_t)n);if(!xx_sha256_memory(buf,(size_t)n+64,inner)) goto done;xx_mem_copy(outer+64,inner,32);if(!xx_sha256_memory(outer,sizeof(outer),want) || binary_stop(b->pd)) goto done;ok=!xx_rt_memcmp(want,b->p+(size_t)digest.value,32);done:xx_mem_free(buf);return ok;}
static bool pm_parse(Abstractformat *f,pm_stream *s,xx_pd_struct *pd) {memory_blob b;der_tlv root,version,info,auth,safe,entry,content,mac;uint64_t at=0,p,q,z;unsigned work=0,bags=0,blocks=0;bool ok=false;if(!blob_load(f,&b,pd)) return false;BLOB_NEED(b.n>=24 && der_tree(&b,0,b.n,0,&work) && der_take(&b,&at,b.n,48,&root) && at==b.n);p=root.value;BLOB_NEED(der_take(&b,&p,root.end,2,&version) && version.end-version.value==1 && b.p[(size_t)version.value]==3 && blob_add(f,s,&b,"pfx-version",version.start,version.end-version.start) && pf_data(&b,&p,root.end,&info,&auth) && blob_add(f,s,&b,"authenticatedsafe-prefix",info.start,auth.value-info.start));q=auth.value;BLOB_NEED(der_tree(&b,auth.value,auth.end,0,&work) && der_take(&b,&q,auth.end,48,&safe) && q==auth.end);q=safe.value;while(q<safe.end) {BLOB_NEED(++blocks<=256 && pf_data(&b,&q,safe.end,&entry,&content) && blob_add(f,s,&b,"safecontents-prefix",entry.start,content.value-entry.start));z=content.value;BLOB_NEED(pf_bags(f,s,&b,z,content.end,0,&bags,&work));}BLOB_NEED(bags);if(p<root.end) BLOB_NEED(der_take(&b,&p,root.end,48,&mac) && pf_mac(&b,&mac,&auth) && blob_add(f,s,&b,"empty-password-sha256-mac",mac.start,mac.end-mac.start));BLOB_NEED(p==root.end);s->size=(int64_t)b.n;ok=true;done:xx_mem_free(b.p);return ok;}

void xx_pkcs12_pfx_init(xx_pkcs12_pfx *r,xx_io_device *d,int64_t b) { if(r) { xx_mem_zero(r,sizeof(*r)); pm_init(&r->format,d,b,XX_FILE_TYPE_PKCS12_PFX,"pfx"); } }
xx_pkcs12_pfx *xx_pkcs12_pfx_create(xx_io_device *d,int64_t b) { xx_pkcs12_pfx *r=(xx_pkcs12_pfx *)xx_mem_alloc(sizeof(*r)); if(r) xx_pkcs12_pfx_init(r,d,b); return r; }
void xx_pkcs12_pfx_destroy(xx_pkcs12_pfx *r) { if(r) xx_format_cleanup_extra_parameters(&r->format); }
void xx_pkcs12_pfx_free(xx_pkcs12_pfx *r) { if(r) { xx_pkcs12_pfx_destroy(r); xx_mem_free(r); } }
bool xx_pkcs12_pfx_check_is_valid(Abstractformat *f,xx_pd_struct *pd) { return pm_valid(f,pd); }
bool xx_pkcs12_pfx_handle_base_info(Abstractformat *f,xx_pd_struct *pd) { return pm_handle(f,pd); }
