/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/chromium_pak/xx_chromium_pak.h"

XX_FORMAT_DEFINE_READER_ADAPTER(chromium_pak, XX_FILE_TYPE_CHROMIUM_PAK,
    xx_chromium_pak_create(device, 0), xx_chromium_pak_free, XX_READER_TYPE_FILL_UNKNOWN)

