/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/vxfs/xx_vxfs.h"

XX_FORMAT_DEFINE_READER_ADAPTER(vxfs, XX_FILE_TYPE_VXFS,
    xx_vxfs_create(device, 0), xx_vxfs_free, XX_READER_TYPE_FILL_UNKNOWN)

