/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/htc_nbh_rom_image/xx_htc_nbh_rom_image.h"

XX_FORMAT_DEFINE_READER_ADAPTER(htc_nbh_rom_image, XX_FILE_TYPE_HTC_NBH_ROM_IMAGE,
    xx_htc_nbh_rom_image_create(device, 0), xx_htc_nbh_rom_image_free, XX_READER_TYPE_FILL_UNKNOWN)

