/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/d_link_alpha_encimg_v2/xx_d_link_alpha_encimg_v2.h"

XX_FORMAT_DEFINE_READER_ADAPTER(d_link_alpha_encimg_v2, XX_FILE_TYPE_D_LINK_ALPHA_ENCIMG_V2,
    xx_d_link_alpha_encimg_v2_create(device, 0), xx_d_link_alpha_encimg_v2_free, XX_READER_TYPE_FILL_UNKNOWN)

