/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 */

/* xx_vmsdb_extractor.c - search raw data for VMSDatabase.
 *
 * Scans for:
 *   FF FF 74 80 A0 80 80 01 01 81 01 00 at +0  ("..t.........")
 * Offset 0 is always tried as well.
 * Each candidate must be accepted by the vmsdb reader, which also measures it,
 * and named by the detector, both on a view that starts at the candidate.
 * See xx_format_extractor_engine.h.
 *
 * GENERATED by gen_extractors.py from the detector's prefilters.
 */

#include "../xx_format_extractor_engine.h"
#include "xxfclib/formats/vmsdb/xx_vmsdb.h"

static const uint8_t k_anchor0[] = { 0xFF, 0xFF, 0x74, 0x80, 0xA0, 0x80, 0x80, 0x01, 0x01, 0x81, 0x01, 0x00 };

static const xx_format_search_anchor k_anchors[] = {
    { k_anchor0, sizeof(k_anchor0), 0U },
};

static const xx_file_type_t k_types[] = { XX_FILE_TYPE_VMSDB };

static Abstractformat *xx_vmsdb_search_open(xx_io_device *window) {
    xx_vmsdb *reader = xx_vmsdb_create(window, 0);
    return reader ? &reader->format : NULL;
}

static void xx_vmsdb_search_close(Abstractformat *format) {
    /* The format is the first member, so this is the reader itself. */
    xx_vmsdb_free((xx_vmsdb *)format);
}

static const xx_format_search_desc k_desc = {
    k_types, sizeof(k_types) / sizeof(k_types[0]),
    k_anchors, sizeof(k_anchors) / sizeof(k_anchors[0]),
    xx_vmsdb_search_open, xx_vmsdb_search_close
};

static xx_format_search_state *xx_vmsdb_create_format_search(
    xx_format_extractor *self, xx_io_device *device, const xx_list_s *options,
    xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_create(&k_desc, device, options, pd);
}

static const xx_format_search_info *xx_vmsdb_get_current_format_info(
    xx_format_extractor *self, xx_format_search_state *state) {
    (void)self;
    return xx_format_search_current(state);
}

static bool xx_vmsdb_format_search_find_next(xx_format_extractor *self,
                                          xx_format_search_state *state,
                                          xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_find_next(state, pd);
}

static void xx_vmsdb_free_format_search(xx_format_extractor *self,
                                     xx_format_search_state *state) {
    (void)self;
    xx_format_search_free(state);
}

xx_format_extractor xx_vmsdb_extractor = {
    xx_vmsdb_create_format_search,
    xx_vmsdb_get_current_format_info,
    xx_vmsdb_format_search_find_next,
    xx_vmsdb_free_format_search
};
