/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 */

/* xx_macho_extractor.c - search raw data for MACH-O32.
 *
 * Scans for:
 *   CE FA ED FE at +0  ("....")
 *   CF FA ED FE at +0  ("....")
 *   FE ED FA CE at +0  ("....")
 *   FE ED FA CF at +0  ("....")
 * Offset 0 is always tried as well.
 * Each candidate must be accepted by the macho reader, which also measures it,
 * and named by the detector, both on a view that starts at the candidate.
 * See xx_format_extractor_engine.h.
 *
 * GENERATED by gen_extractors.py from the detector's prefilters.
 */

#include "../xx_format_extractor_engine.h"
#include "xxfclib/formats/macho/xx_macho.h"

static const uint8_t k_anchor0[] = { 0xCE, 0xFA, 0xED, 0xFE };
static const uint8_t k_anchor1[] = { 0xCF, 0xFA, 0xED, 0xFE };
static const uint8_t k_anchor2[] = { 0xFE, 0xED, 0xFA, 0xCE };
static const uint8_t k_anchor3[] = { 0xFE, 0xED, 0xFA, 0xCF };

static const xx_format_search_anchor k_anchors[] = {
    { k_anchor0, sizeof(k_anchor0), 0U },
    { k_anchor1, sizeof(k_anchor1), 0U },
    { k_anchor2, sizeof(k_anchor2), 0U },
    { k_anchor3, sizeof(k_anchor3), 0U },
};

static const xx_file_type_t k_types[] = { XX_FILE_TYPE_MACHO32, XX_FILE_TYPE_MACHO64 };

static Abstractformat *xx_macho_search_open(xx_io_device *window) {
    xx_macho *reader = xx_macho_create(window, 0);
    return reader ? &reader->format : NULL;
}

static void xx_macho_search_close(Abstractformat *format) {
    /* The format is the first member, so this is the reader itself. */
    xx_macho_free((xx_macho *)format);
}

static const xx_format_search_desc k_desc = {
    k_types, sizeof(k_types) / sizeof(k_types[0]),
    k_anchors, sizeof(k_anchors) / sizeof(k_anchors[0]),
    xx_macho_search_open, xx_macho_search_close
};

static xx_format_search_state *xx_macho_create_format_search(
    xx_format_extractor *self, xx_io_device *device, const xx_list_s *options,
    xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_create(&k_desc, device, options, pd);
}

static const xx_format_search_info *xx_macho_get_current_format_info(
    xx_format_extractor *self, xx_format_search_state *state) {
    (void)self;
    return xx_format_search_current(state);
}

static bool xx_macho_format_search_find_next(xx_format_extractor *self,
                                          xx_format_search_state *state,
                                          xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_find_next(state, pd);
}

static void xx_macho_free_format_search(xx_format_extractor *self,
                                     xx_format_search_state *state) {
    (void)self;
    xx_format_search_free(state);
}

xx_format_extractor xx_macho_extractor = {
    xx_macho_create_format_search,
    xx_macho_get_current_format_info,
    xx_macho_format_search_find_next,
    xx_macho_free_format_search
};
