/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/larc_pfx/xx_larc_pfx.h"

XX_FORMAT_DEFINE_READER_ADAPTER(larc_pfx, XX_FILE_TYPE_LARC_PFX,
    xx_larc_pfx_create(device, 0), xx_larc_pfx_free, XX_READER_TYPE_FILL_UNKNOWN)

