/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/smart_install_maker/xx_smart_install_maker.h"

XX_FORMAT_DEFINE_READER_ADAPTER(smart_install_maker, XX_FILE_TYPE_SMART_INSTALL_MAKER,
    xx_smart_install_maker_create(device, 0), xx_smart_install_maker_free, XX_READER_TYPE_FILL_UNKNOWN)

