/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/xenix_fs/xx_xenix_fs.h"

XX_FORMAT_DEFINE_READER_ADAPTER(xenix_fs, XX_FILE_TYPE_XENIX_FS,
    xx_xenix_fs_create(device, 0), xx_xenix_fs_free, XX_READER_TYPE_FILL_UNKNOWN)

