/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/applelink_pe/xx_applelink_pe.h"

XX_FORMAT_DEFINE_READER_ADAPTER(applelink_pe, XX_FILE_TYPE_APPLELINK_PE,
    xx_applelink_pe_create(device, 0), xx_applelink_pe_free, XX_READER_TYPE_FILL_UNKNOWN)

