/* SPDX-License-Identifier: MIT
 * Primary reference: https://www.csc.kth.se/~weinkauf/notes/amiramesh.html
 * AmiraMesh2.1 BINARY-LITTLE-ENDIAN uniform float lattice: complete dimensions/bounding-box/coordinate-type/field declaration and exact finite interleaved scalar/vector payload with optional single LF or CRLF terminator. Original ASCII descriptor and typed lattice planes exported; compressed/ASCII/unstructured/multiple-field extensions declined.
 * Bounded32MiB input,4096 components and bounded work.
 */
#include "xxfclib/formats/amira_mesh/xx_amira_mesh.h"
#include "../wbmp_image/xx_fifteenth_games.h"
static bool vg_quick(Abstractformat *f,uint64_t n) {uint8_t b[43];return n>=64&&pm_read(f,0,b,sizeof(b))&&vg_tag(b,"# AmiraMesh BINARY-LITTLE-ENDIAN 2.1",36);}
static bool vg_parse(Abstractformat *f,pm_stream *s,const uint8_t *b,uint64_t n,xx_pd_struct *pd) {vg_text t={b,0,n,0,0,0};vg_lex q;uint64_t at=0,p,plane,bytes;int32_t dim[3],channels=1;double box[6];unsigned i;char label[48];if(!vg_line(&t)||t.stop!=36||!vg_tag(b,"# AmiraMesh BINARY-LITTLE-ENDIAN 2.1",36))return false;at=t.p;while(t.p<n&&t.p<65536){if(!vg_line(&t))return false;if(false){at=t.p;break;}if(t.stop-t.start==2&&vg_tag(b+t.start,"@1",2)){at=t.p;break;}}if(at<=36||at>65536||!vg_utf(b,at,true,pd))return false;q.b=b;q.p=36;q.n=at;q.pd=pd;q.work=0;q.hash=true;q.commas=true;q.comments=false;if(!vg_kw(&q,"define")||!vg_kw(&q,"Lattice"))return false;for(i=0;i<3;++i)if(!vg_integer(&q,&dim[i])||dim[i]<1||dim[i]>4096)return false;if(dim[2]>4095||!vg_kw(&q,"Parameters")||!vg_char(&q,'{')||!vg_kw(&q,"BoundingBox"))return false;for(i=0;i<6;++i)if(!vg_number(&q,&box[i]))return false;for(i=0;i<3;++i)if(box[i*2]>=box[i*2+1])return false;if(!vg_kw(&q,"CoordType")||!vg_quoted(&q,'"',&p,&bytes)||bytes!=7||!vg_tag(b+p,"uniform",7)||!vg_char(&q,'}')||!vg_kw(&q,"Lattice")||!vg_char(&q,'{')||!vg_kw(&q,"float"))return false;if(vg_skip(&q)&&q.p<q.n&&b[q.p]=='['){if(!vg_char(&q,'[')||!vg_integer(&q,&channels)||channels<1||channels>16||!vg_char(&q,']'))return false;}{int32_t marker;if(!vg_kw(&q,"Data")||!vg_char(&q,'}')||!vg_char(&q,'@')||!vg_integer(&q,&marker)||marker!=1||!vg_char(&q,'@')||!vg_integer(&q,&marker)||marker!=1||!vg_end(&q))return false;}
 plane=(uint64_t)dim[0]*dim[1]*(unsigned)channels*4;bytes=plane*(unsigned)dim[2];if(bytes>33554432||(n-at!=bytes&&!(n-at==bytes+1&&b[n-1]==10)&&!(n-at==bytes+2&&b[n-2]==13&&b[n-1]==10))||!vg_emit(f,s,"descriptor.am",0,at,n))return false;for(p=at;p<at+bytes;p+=4)if(((p&4095)==0&&vg_stop(pd))||!vg_f32(xx_data_get_u32(b+p, 4, 0, false)))return false;for(i=0;i<(unsigned)dim[2];++i){xx_rt_snprintf(label,sizeof(label),"lattice-plane-%u.f32le",i);if(!vg_emit(f,s,label,at+(uint64_t)i*plane,plane,n))return false;}return n==at+bytes||vg_emit(f,s,"terminator.am",at+bytes,n-at-bytes,n);}

void xx_amira_mesh_init(xx_amira_mesh *r,xx_io_device *d,int64_t at) {if(r){xx_mem_zero(r,sizeof(*r));pm_init(&r->format,d,at,XX_FILE_TYPE_AMIRA_MESH,"am");}}
xx_amira_mesh *xx_amira_mesh_create(xx_io_device *d,int64_t at) {xx_amira_mesh *r=(xx_amira_mesh *)xx_mem_alloc(sizeof(*r));if(r)xx_amira_mesh_init(r,d,at);return r;}
void xx_amira_mesh_destroy(xx_amira_mesh *r) {if(r)xx_format_cleanup_extra_parameters(&r->format);}
void xx_amira_mesh_free(xx_amira_mesh *r) {if(r){xx_amira_mesh_destroy(r);xx_mem_free(r);}}
bool xx_amira_mesh_check_is_valid(Abstractformat *f,xx_pd_struct *pd) {return pm_valid(f,pd);}
bool xx_amira_mesh_handle_base_info(Abstractformat *f,xx_pd_struct *pd) {return pm_handle(f,pd);}
