/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/thomson_sap/xx_thomson_sap.h"

XX_FORMAT_DEFINE_READER_ADAPTER(thomson_sap, XX_FILE_TYPE_THOMSON_SAP,
    xx_thomson_sap_create(device, 0), xx_thomson_sap_free, XX_READER_TYPE_FILL_UNKNOWN)

