/* Copyright (c)2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT. Bounded typed components; payloads never executed.
 */
/* Primary: https://github.com/openssh/openssh-portable/blob/V_9_9_P2/PROTOCOL.certkeys */
#include "xxfclib/formats/openssh_certificate/xx_openssh_certificate.h"
#include "xxfclib/data/xx_data.h"
#include "../xx_fourteenth_wrappers.h"

static bool stringlist(nh_blob *b,uint64_t p,uint64_t end,bool pairs,bool critical){unsigned count=0;uint64_t prev=0,prevn=0;while(p<end){uint64_t v,n;if(++count>256||!fw_string(b,&p,end,&v,&n,true)||!n)return false;if(pairs){if(prevn&&ec_cmp(b->p+(size_t)prev,prevn,b->p+(size_t)v,n)>=0)return false;prev=v;prevn=n;if(!fw_string(b,&p,end,&v,&n,false))return false;if(critical&&(th_eq(b,prev,prevn,"force-command")||th_eq(b,prev,prevn,"source-address"))){uint64_t q=v,z,w;if(!fw_string(b,&q,v+n,&z,&w,true)||q!=v+n)return false;}else if(!critical&&(th_eq(b,prev,prevn,"permit-X11-forwarding")||th_eq(b,prev,prevn,"permit-agent-forwarding")||th_eq(b,prev,prevn,"permit-port-forwarding")||th_eq(b,prev,prevn,"permit-pty")||th_eq(b,prev,prevn,"permit-user-rc"))&&n)return false;}}return p==end;}
static bool keyblob(nh_blob *b,uint64_t p,uint64_t end,bool sig){uint64_t v,n;if(!fw_string(b,&p,end,&v,&n,false)||!th_eq(b,v,n,"ssh-ed25519")||!fw_string(b,&p,end,&v,&n,false)||n!=(sig?64U:32U))return false;return p==end;}
static bool pm_parse(Abstractformat *f,pm_stream *s,xx_pd_struct *pd){nh_blob b;bool ok=false;uint64_t at=0,v,n,start;if(!nh_load(f,&b,pd))return false;NH_NEED(fw_string(&b,&at,b.n,&v,&n,false)&&th_eq(&b,v,n,"ssh-ed25519-cert-v01@openssh.com")&&nh_add(f,s,&b,"certificate-algorithm",v,n));NH_NEED(fw_string(&b,&at,b.n,&v,&n,false)&&n>0&&nh_add(f,s,&b,"nonce",v,n));NH_NEED(fw_string(&b,&at,b.n,&v,&n,false)&&n==32&&nh_add(f,s,&b,"subject-public-key",v,n));start=at;NH_NEED(th_take(&b,&at,b.n,12)&&(xx_data_get_u32(b.p+(size_t)at-4, 4, 0, true)==1||xx_data_get_u32(b.p+(size_t)at-4, 4, 0, true)==2)&&nh_add(f,s,&b,"serial-type",start,12));NH_NEED(fw_string(&b,&at,b.n,&v,&n,true)&&nh_add(f,s,&b,"key-id",v,n));NH_NEED(fw_string(&b,&at,b.n,&v,&n,false)&&stringlist(&b,v,v+n,false,false)&&nh_add(f,s,&b,"principals",v,n));start=at;NH_NEED(th_take(&b,&at,b.n,16)&&xx_data_get_u64(b.p+(size_t)start, 8, 0, true)<xx_data_get_u64(b.p+(size_t)start+8, 8, 0, true)&&nh_add(f,s,&b,"validity",start,16));for(unsigned i=0;i<2;++i)NH_NEED(fw_string(&b,&at,b.n,&v,&n,false)&&stringlist(&b,v,v+n,true,i==0)&&nh_add(f,s,&b,i?"extensions":"critical-options",v,n));NH_NEED(fw_string(&b,&at,b.n,&v,&n,false)&&!n);NH_NEED(fw_string(&b,&at,b.n,&v,&n,false)&&keyblob(&b,v,v+n,false)&&nh_add(f,s,&b,"signing-key",v,n));NH_NEED(fw_string(&b,&at,b.n,&v,&n,false)&&keyblob(&b,v,v+n,true)&&nh_add(f,s,&b,"encoded-signature",v,n)&&at==b.n);s->size=(int64_t)b.n;ok=true;done:xx_mem_free(b.p);return ok;}

void xx_openssh_certificate_init(xx_openssh_certificate *r,xx_io_device *d,int64_t b){if(r){xx_mem_zero(r,sizeof(*r));pm_init(&r->format,d,b,XX_FILE_TYPE_OPENSSH_CERTIFICATE,"bin");}}
xx_openssh_certificate *xx_openssh_certificate_create(xx_io_device *d,int64_t b){xx_openssh_certificate *r=(xx_openssh_certificate *)xx_mem_alloc(sizeof(*r));if(r)xx_openssh_certificate_init(r,d,b);return r;}
void xx_openssh_certificate_destroy(xx_openssh_certificate *r){if(r)xx_format_cleanup_extra_parameters(&r->format);}
void xx_openssh_certificate_free(xx_openssh_certificate *r){if(r){xx_openssh_certificate_destroy(r);xx_mem_free(r);}}
bool xx_openssh_certificate_check_is_valid(Abstractformat *f,xx_pd_struct *pd){return pm_valid(f,pd);}
bool xx_openssh_certificate_handle_base_info(Abstractformat *f,xx_pd_struct *pd){return pm_handle(f,pd);}
