/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Bounded primary-layout reader. Payloads are never executed.
 */
/* Primary layout: https://www.erlang.org/doc/apps/erts/erl_ext_dist.html */
#include "xxfclib/formats/erlang_external_term/xx_erlang_external_term.h"
#include "../nix_nar/xx_eleventh_containers.h"

static bool et_atom(nh_blob *b,uint64_t *at) {uint8_t c;uint64_t n;if(!nh_span(b,*at,1)) return false;c=b->p[(size_t)(*at)++];if(c==115 || c==119) {if(!nh_span(b,*at,1)) return false;n=b->p[(size_t)(*at)++];}else if(c==100 || c==118) {if(!nh_span(b,*at,2)) return false;n=xx_data_get_u16(b->p+(size_t)*at, 2, 0, true);*at+=2;}else return false;if(n>1020 || !nh_span(b,*at,n) || ((c==118 || c==119) && !ec_utf(b,*at,n))) return false;uint64_t chars=0;for(uint64_t i=0;i<n;++i) if((c!=118 && c!=119) || (b->p[(size_t)(*at+i)]&192)!=128) ++chars;if(chars>255) return false;*at+=n;return true;}
static bool et_value(nh_blob *b,uint64_t *at,unsigned depth,unsigned *work) {uint8_t c;uint64_t n=0,i;unsigned width=0;if(depth>32 || ++*work>1048576 || !nh_span(b,*at,1)) return false;c=b->p[(size_t)(*at)++];if(c==100 || c==115 || c==118 || c==119) {--*at;return et_atom(b,at);}if(c==106) return true;if(c==97) n=1;else if(c==98) n=4;else if(c==70) {if(!nh_span(b,*at,8) || !sv_finite64(xx_data_get_u64(b->p+(size_t)*at, 8, 0, true))) return false;n=8;}else if(c==99) {if(!nh_span(b,*at,31)) return false;uint64_t len=0;while(len<31 && b->p[(size_t)(*at+len)]) ++len;if(len==31 || !ec_number(b->p+(size_t)*at,len,true)) return false;n=31;}else if(c==107) {if(!nh_span(b,*at,2)) return false;n=xx_data_get_u16(b->p+(size_t)*at, 2, 0, true);*at+=2;}else if(c==109 || c==77) {if(!nh_span(b,*at,4)) return false;n=xx_data_get_u32(b->p+(size_t)*at, 4, 0, true);*at+=4;if(c==77) {uint8_t bits;if(!nh_span(b,*at,1)) return false;bits=b->p[(size_t)(*at)++];if(!n || !bits || bits>8 || !nh_span(b,*at,n) || (b->p[(size_t)(*at+n-1)]&((1U<<(8-bits))-1))) return false;}}
    else if(c==104 || c==105 || c==108 || c==116) {width=c==104 ? 1:4;if(!nh_span(b,*at,width)) return false;n=width==1 ? b->p[(size_t)*at]:xx_data_get_u32(b->p+(size_t)*at, 4, 0, true);*at+=width;if(n>65536) return false;for(i=0;i<n*(c==116 ? 2U:1U);++i) if(!et_value(b,at,depth+1,work)) return false;return c!=108 || et_value(b,at,depth+1,work);}
    else if(c==110 || c==111) {width=c==110 ? 1:4;if(!nh_span(b,*at,width)) return false;n=width==1 ? b->p[(size_t)*at]:xx_data_get_u32(b->p+(size_t)*at, 4, 0, true);*at+=width;if(n>4096 || !nh_span(b,*at,1) || b->p[(size_t)(*at)++]>1) return false;}
    else if(c==103 || c==88 || c==102 || c==89 || c==120 || c==101 || c==114 || c==90) {uint64_t ids=1;if(c==114 || c==90) {if(!nh_span(b,*at,2)) return false;ids=xx_data_get_u16(b->p+(size_t)*at, 2, 0, true);*at+=2;if(!ids || ids>5) return false;}if(!et_atom(b,at)) return false;if(c==103 || c==88) n=c==103 ? 9:12;else if(c==102 || c==89) n=c==102 ? 5:8;else if(c==120) n=12;else if(c==101) n=5;else {n=(c==90 ? 4U:1U)+ids*4;}if(!nh_span(b,*at,n)) return false;if(c==103 && (xx_data_get_u32(b->p+(size_t)*at, 4, 0, true)>32767 || xx_data_get_u32(b->p+(size_t)*at+4, 4, 0, true)>8191 || b->p[(size_t)*at+8]>3)) return false;if((c==102 || c==101) && b->p[(size_t)*at+4]>3) return false;if(c==114 && b->p[(size_t)*at]>3) return false;}
    else { return false; } if(!nh_span(b,*at,n)) return false;*at+=n;return true;
}
static bool pm_parse(Abstractformat *f,pm_stream *s,xx_pd_struct *pd) {nh_blob b;uint64_t at=1,start=1,n,i;uint8_t c;unsigned work=0;bool ok=false;if(!nh_load(f,&b,pd)) return false;NH_NEED(nh_span(&b,0,2) && b.p[0]==131 && nh_add(f,s,&b,"etf-version",0,1));c=b.p[1];if(c==104 || c==105 || c==108 || c==116) {++at;NH_NEED(nh_span(&b,at,c==104 ? 1:4));n=c==104 ? b.p[(size_t)at]:xx_data_get_u32(b.p+(size_t)at, 4, 0, true);at+=c==104 ? 1U:4U;NH_NEED(n && n<=2048 && nh_add(f,s,&b,"term-container",1,at-1));for(i=0;i<n;++i) {start=at;NH_NEED(et_value(&b,&at,0,&work));if(c==116) NH_NEED(et_value(&b,&at,0,&work));NH_NEED(nh_add(f,s,&b,"encoded-term",start,at-start));}if(c==108) {start=at;NH_NEED(et_value(&b,&at,0,&work) && nh_add(f,s,&b,"list-tail",start,at-start));}}else NH_NEED(et_value(&b,&at,0,&work) && nh_add(f,s,&b,"encoded-term",start,at-start));NH_NEED(at==b.n);s->size=(int64_t)b.n;ok=true;done:xx_mem_free(b.p);return ok;}

void xx_erlang_external_term_init(xx_erlang_external_term *r,xx_io_device *d,int64_t b) { if(r) { xx_mem_zero(r,sizeof(*r)); pm_init(&r->format,d,b,XX_FILE_TYPE_ERLANG_EXTERNAL_TERM,"etf"); } }
xx_erlang_external_term *xx_erlang_external_term_create(xx_io_device *d,int64_t b) { xx_erlang_external_term *r=(xx_erlang_external_term *)xx_mem_alloc(sizeof(*r)); if(r) xx_erlang_external_term_init(r,d,b); return r; }
void xx_erlang_external_term_destroy(xx_erlang_external_term *r) { if(r) xx_format_cleanup_extra_parameters(&r->format); }
void xx_erlang_external_term_free(xx_erlang_external_term *r) { if(r) { xx_erlang_external_term_destroy(r); xx_mem_free(r); } }
bool xx_erlang_external_term_check_is_valid(Abstractformat *f,xx_pd_struct *pd) { return pm_valid(f,pd); }
bool xx_erlang_external_term_handle_base_info(Abstractformat *f,xx_pd_struct *pd) { return pm_handle(f,pd); }
