/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/valve_xzp/xx_valve_xzp.h"

XX_FORMAT_DEFINE_READER_ADAPTER(valve_xzp, XX_FILE_TYPE_VALVE_XZP,
    xx_valve_xzp_create(device, 0), xx_valve_xzp_free, XX_READER_TYPE_FILL_UNKNOWN)

