/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/stuffitx/xx_stuffitx.h"

XX_FORMAT_DEFINE_READER_ADAPTER(stuffitx, XX_FILE_TYPE_STUFFITX,
    xx_stuffitx_create(device, 0), xx_stuffitx_free, XX_READER_TYPE_FILL_UNKNOWN)

