/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/ray_dim/xx_ray_dim.h"

XX_FORMAT_DEFINE_READER_ADAPTER(ray_dim, XX_FILE_TYPE_RAY_DIM,
    xx_ray_dim_create(device, 0), xx_ray_dim_free, XX_READER_TYPE_FILL_UNKNOWN)

