/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/arc_cbm/xx_arc_cbm.h"

XX_FORMAT_DEFINE_READER_ADAPTER(arc_cbm, XX_FILE_TYPE_ARC_CBM,
    xx_arc_cbm_create(device, 0), xx_arc_cbm_free, XX_READER_TYPE_FILL_UNKNOWN)

