/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/fdx68_fdx/xx_fdx68_fdx.h"

XX_FORMAT_DEFINE_READER_ADAPTER(fdx68_fdx, XX_FILE_TYPE_FDX68_FDX,
    xx_fdx68_fdx_create(device, 0), xx_fdx68_fdx_free, XX_READER_TYPE_FILL_UNKNOWN)

