/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/apple_dos33_32/xx_apple_dos33_32.h"

XX_FORMAT_DEFINE_READER_ADAPTER(apple_dos33_32, XX_FILE_TYPE_APPLE_DOS33_32,
    xx_apple_dos33_32_create(device, 0), xx_apple_dos33_32_free, XX_READER_TYPE_FILL_UNKNOWN)

