/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/legacy_archive_engine/xx_legacy_archive_engine.h"

XX_FORMAT_DEFINE_READER_ADAPTER(dgca, XX_FILE_TYPE_DGCA,
    xx_dgca_create(device, 0), xx_legacy_archive_free, XX_READER_TYPE_FILL_UNKNOWN)

