/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/ensoniq_gkh/xx_ensoniq_gkh.h"

XX_FORMAT_DEFINE_READER_ADAPTER(ensoniq_gkh, XX_FILE_TYPE_ENSONIQ_GKH,
    xx_ensoniq_gkh_create(device, 0), xx_ensoniq_gkh_free, XX_READER_TYPE_FILL_UNKNOWN)

