/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 */

#ifndef XXFCLIB_FORMAT_PE_H
#define XXFCLIB_FORMAT_PE_H

#include "xxfclib/formats/xx_format.h"

#ifdef __cplusplus
extern "C" {
#endif

#define XX_PE_SIGNATURE UINT32_C(0x00004550)
#define XX_PE_MAGIC_32  UINT16_C(0x010b)
#define XX_PE_MAGIC_64  UINT16_C(0x020b)

typedef enum xx_pe_data_struct_id_e {
    XX_PE_DATA_STRUCT_UNKNOWN = 0,
    XX_PE_DATA_STRUCT_DOS_HEADER,
    XX_PE_DATA_STRUCT_NT_SIGNATURE,
    XX_PE_DATA_STRUCT_FILE_HEADER,
    XX_PE_DATA_STRUCT_OPTIONAL_HEADER32,
    XX_PE_DATA_STRUCT_DATA_DIRECTORY,
    XX_PE_DATA_STRUCT_SECTION_HEADER,
    XX_PE_DATA_STRUCT_OPTIONAL_HEADER64,
    XX_PE_DATA_STRUCT_DOS_STUB,
    XX_PE_DATA_STRUCT_COFF_SYMBOL,
    XX_PE_DATA_STRUCT_COFF_AUX_SYMBOL,
    XX_PE_DATA_STRUCT_COFF_AUX_FUNCTION_DEFINITION,
    XX_PE_DATA_STRUCT_COFF_AUX_BF_EF,
    XX_PE_DATA_STRUCT_COFF_AUX_WEAK_EXTERNAL,
    XX_PE_DATA_STRUCT_COFF_AUX_FILE,
    XX_PE_DATA_STRUCT_COFF_AUX_SECTION_DEFINITION,
    XX_PE_DATA_STRUCT_COFF_AUX_CLR_TOKEN,
    XX_PE_DATA_STRUCT_COFF_STRING_TABLE_HEADER,
    XX_PE_DATA_STRUCT_COFF_STRING,
    XX_PE_DATA_STRUCT_COFF_RELOCATION,
    XX_PE_DATA_STRUCT_COFF_LINE_NUMBER,
    XX_PE_DATA_STRUCT_EXPORT_DIRECTORY,
    XX_PE_DATA_STRUCT_EXPORT_ADDRESS_TABLE,
    XX_PE_DATA_STRUCT_EXPORT_NAME_POINTER_TABLE,
    XX_PE_DATA_STRUCT_EXPORT_ORDINAL_TABLE,
    XX_PE_DATA_STRUCT_EXPORT_FORWARDER,
    XX_PE_DATA_STRUCT_IMPORT_DESCRIPTOR,
    XX_PE_DATA_STRUCT_THUNK32,
    XX_PE_DATA_STRUCT_THUNK64,
    XX_PE_DATA_STRUCT_IMPORT_BY_NAME,
    XX_PE_DATA_STRUCT_ASCII_STRING,
    XX_PE_DATA_STRUCT_RESOURCE_DIRECTORY,
    XX_PE_DATA_STRUCT_RESOURCE_DIRECTORY_ENTRY,
    XX_PE_DATA_STRUCT_RESOURCE_STRING,
    XX_PE_DATA_STRUCT_RESOURCE_DATA_ENTRY,
    XX_PE_DATA_STRUCT_RESOURCE_PAYLOAD,
    XX_PE_DATA_STRUCT_RUNTIME_FUNCTION_X64,
    XX_PE_DATA_STRUCT_RUNTIME_FUNCTION_IA64,
    XX_PE_DATA_STRUCT_RUNTIME_FUNCTION_ARM,
    XX_PE_DATA_STRUCT_RUNTIME_FUNCTION_ARM64,
    XX_PE_DATA_STRUCT_RUNTIME_FUNCTION_MIPS,
    XX_PE_DATA_STRUCT_RUNTIME_FUNCTION_ALPHA32,
    XX_PE_DATA_STRUCT_RUNTIME_FUNCTION_ALPHA64,
    XX_PE_DATA_STRUCT_RUNTIME_FUNCTION_CE,
    XX_PE_DATA_STRUCT_UNWIND_INFO,
    XX_PE_DATA_STRUCT_UNWIND_CODE,
    XX_PE_DATA_STRUCT_UNWIND_HANDLER,
    XX_PE_DATA_STRUCT_UNWIND_CHAINED_FUNCTION,
    XX_PE_DATA_STRUCT_ARM64_XDATA_HEADER,
    XX_PE_DATA_STRUCT_ARM64_XDATA_EXTENDED,
    XX_PE_DATA_STRUCT_ARM64_EPILOG_SCOPE,
    XX_PE_DATA_STRUCT_WIN_CERTIFICATE,
    XX_PE_DATA_STRUCT_BASE_RELOCATION_BLOCK,
    XX_PE_DATA_STRUCT_BASE_RELOCATION_ENTRY,
    XX_PE_DATA_STRUCT_DEBUG_DIRECTORY,
    XX_PE_DATA_STRUCT_DEBUG_COFF_SYMBOLS_HEADER,
    XX_PE_DATA_STRUCT_CODEVIEW_RSDS,
    XX_PE_DATA_STRUCT_CODEVIEW_NB10,
    XX_PE_DATA_STRUCT_DEBUG_MISC,
    XX_PE_DATA_STRUCT_DEBUG_FPO,
    XX_PE_DATA_STRUCT_DEBUG_OMAP,
    XX_PE_DATA_STRUCT_DEBUG_VC_FEATURE,
    XX_PE_DATA_STRUCT_DEBUG_POGO_HEADER,
    XX_PE_DATA_STRUCT_DEBUG_POGO_ENTRY,
    XX_PE_DATA_STRUCT_DEBUG_EMBEDDED_PORTABLE_PDB,
    XX_PE_DATA_STRUCT_DEBUG_REPRO_HASH_HEADER,
    XX_PE_DATA_STRUCT_DEBUG_GUID,
    XX_PE_DATA_STRUCT_DEBUG_EX_DLL_CHARACTERISTICS,
    XX_PE_DATA_STRUCT_DEBUG_RAW,
    XX_PE_DATA_STRUCT_ARCHITECTURE_HEADER,
    XX_PE_DATA_STRUCT_ARCHITECTURE_ENTRY,
    XX_PE_DATA_STRUCT_TLS_DIRECTORY32,
    XX_PE_DATA_STRUCT_TLS_DIRECTORY64,
    XX_PE_DATA_STRUCT_TLS_CALLBACK32,
    XX_PE_DATA_STRUCT_TLS_CALLBACK64,
    XX_PE_DATA_STRUCT_TLS_TEMPLATE,
    XX_PE_DATA_STRUCT_LOAD_CONFIG32,
    XX_PE_DATA_STRUCT_LOAD_CONFIG64,
    XX_PE_DATA_STRUCT_LOAD_CONFIG_CODE_INTEGRITY,
    XX_PE_DATA_STRUCT_LOAD_CONFIG_SE_HANDLER,
    XX_PE_DATA_STRUCT_LOAD_CONFIG_GUARD_FUNCTION,
    XX_PE_DATA_STRUCT_LOAD_CONFIG_GUARD_IAT_ENTRY,
    XX_PE_DATA_STRUCT_LOAD_CONFIG_GUARD_LONGJUMP,
    XX_PE_DATA_STRUCT_LOAD_CONFIG_GUARD_EH_CONTINUATION,
    XX_PE_DATA_STRUCT_DYNAMIC_RELOCATION_TABLE,
    XX_PE_DATA_STRUCT_DYNAMIC_RELOCATION32,
    XX_PE_DATA_STRUCT_DYNAMIC_RELOCATION64,
    XX_PE_DATA_STRUCT_DYNAMIC_RELOCATION32_V2,
    XX_PE_DATA_STRUCT_DYNAMIC_RELOCATION64_V2,
    XX_PE_DATA_STRUCT_DYNAMIC_RELOCATION_PROLOGUE,
    XX_PE_DATA_STRUCT_DYNAMIC_RELOCATION_EPILOGUE,
    XX_PE_DATA_STRUCT_DYNAMIC_RELOCATION_IMPORT_CONTROL,
    XX_PE_DATA_STRUCT_DYNAMIC_RELOCATION_ARM64_IMPORT_CONTROL,
    XX_PE_DATA_STRUCT_DYNAMIC_RELOCATION_INDIR,
    XX_PE_DATA_STRUCT_DYNAMIC_RELOCATION_SWITCHTABLE,
    XX_PE_DATA_STRUCT_FUNCTION_OVERRIDE_HEADER,
    XX_PE_DATA_STRUCT_FUNCTION_OVERRIDE_ENTRY,
    XX_PE_DATA_STRUCT_BDD_INFO,
    XX_PE_DATA_STRUCT_BDD_NODE,
    XX_PE_DATA_STRUCT_HOT_PATCH_INFO,
    XX_PE_DATA_STRUCT_HOT_PATCH_BASE,
    XX_PE_DATA_STRUCT_HOT_PATCH_MACHINE,
    XX_PE_DATA_STRUCT_HOT_PATCH_HASHES,
    XX_PE_DATA_STRUCT_ENCLAVE_CONFIG32,
    XX_PE_DATA_STRUCT_ENCLAVE_CONFIG64,
    XX_PE_DATA_STRUCT_ENCLAVE_IMPORT,
    XX_PE_DATA_STRUCT_VOLATILE_METADATA,
    XX_PE_DATA_STRUCT_BOUND_IMPORT_DESCRIPTOR,
    XX_PE_DATA_STRUCT_BOUND_FORWARDER_REF,
    XX_PE_DATA_STRUCT_DELAY_IMPORT_DESCRIPTOR,
    XX_PE_DATA_STRUCT_IAT32,
    XX_PE_DATA_STRUCT_IAT64,
    XX_PE_DATA_STRUCT_COR20_HEADER,
    XX_PE_DATA_STRUCT_CLR_METADATA_ROOT,
    XX_PE_DATA_STRUCT_CLR_METADATA_STORAGE_HEADER,
    XX_PE_DATA_STRUCT_CLR_STREAM_HEADER,
    XX_PE_DATA_STRUCT_CLR_VTABLE_FIXUP,
    XX_PE_DATA_STRUCT_CLR_RAW,
    XX_PE_DATA_STRUCT_RESERVED_DIRECTORY_RAW,
    XX_PE_DATA_STRUCT_ARM32_XDATA_HEADER,
    XX_PE_DATA_STRUCT_ARM32_EPILOG_SCOPE,
    XX_PE_DATA_STRUCT_DYNAMIC_RELOCATION_ARM64X,
    XX_PE_DATA_STRUCT_ARM64X_FIXUP,
    XX_PE_DATA_STRUCT_ARM64X_DELTA,
    XX_PE_DATA_STRUCT_DEBUG_PDB_CHECKSUM,
    XX_PE_DATA_STRUCT_DEBUG_R2R_PERFMAP,
    XX_PE_DATA_STRUCT_CHPE_METADATA,
    XX_PE_DATA_STRUCT_ARM64EC_METADATA,
    XX_PE_DATA_STRUCT_CHPE_CODE_RANGE_ENTRY,
    XX_PE_DATA_STRUCT_CHPE_CODE_RANGE_TO_ENTRY_POINT,
    XX_PE_DATA_STRUCT_CHPE_REDIRECTION_ENTRY,
    XX_PE_DATA_STRUCT_VOLATILE_ACCESS,
    XX_PE_DATA_STRUCT_VOLATILE_INFO_RANGE,
    XX_PE_DATA_STRUCT_ARM32_XDATA_EXTENDED,
    XX_PE_DATA_STRUCT_DEBUG_FUNCTION_ENTRY32,
    XX_PE_DATA_STRUCT_DEBUG_FUNCTION_ENTRY64,
    XX_PE_DATA_STRUCT_POLICY_METADATA,
    XX_PE_DATA_STRUCT_POLICY_ENTRY32,
    XX_PE_DATA_STRUCT_POLICY_ENTRY64,
    XX_PE_DATA_STRUCT_LAST = XX_PE_DATA_STRUCT_POLICY_ENTRY64
} xx_pe_data_struct_id_t;

/* Source compatibility with the original PE32-only identifier. */
#define XX_PE_DATA_STRUCT_OPTIONAL_HEADER \
    XX_PE_DATA_STRUCT_OPTIONAL_HEADER32

typedef struct xx_pe_section {
    char name[9];
    uint32_t virtual_size;
    uint32_t virtual_address;
    uint32_t raw_size;
    uint32_t raw_offset;
    uint32_t characteristics;
} xx_pe_section;

typedef struct xx_pe {
    Abstractformat format;
    uint32_t pe_offset;
    uint16_t machine;
    uint16_t number_of_sections;
    uint32_t timestamp;
    uint16_t optional_header_size;
    uint16_t characteristics;
    uint16_t optional_magic;
    uint32_t entry_point_rva;
    uint64_t image_base;
    uint32_t section_alignment;
    uint32_t file_alignment;
    uint32_t size_of_image;
    uint32_t size_of_headers;
    uint16_t subsystem;
    uint16_t dll_characteristics;
    uint32_t number_of_data_directories;
    uint32_t data_directory_rva[16];
    uint32_t data_directory_size[16];
    xx_pe_section *sections;
} xx_pe;

typedef xx_pe xx_pe_t;
typedef xx_pe XPE;

XXFC_API void xx_pe_init(xx_pe *pe, xx_io_device *device, int64_t base_address);
XXFC_API xx_pe *xx_pe_create(xx_io_device *device, int64_t base_address);
XXFC_API void xx_pe_destroy(xx_pe *pe);
XXFC_API void xx_pe_free(xx_pe *pe);

XXFC_API bool xx_pe_check_is_valid(Abstractformat *self, xx_pd_struct *pd);
XXFC_API bool xx_pe_handle_base_info(Abstractformat *self, xx_pd_struct *pd);
XXFC_API int64_t xx_pe_get_format_size(Abstractformat *self, xx_pd_struct *pd);
XXFC_API uint64_t xx_pe_get_number_of_imports(Abstractformat *self, xx_pd_struct *pd);
XXFC_API uint64_t xx_pe_get_number_of_exports(Abstractformat *self, xx_pd_struct *pd);
XXFC_API uint64_t xx_pe_get_number_of_resources(Abstractformat *self, xx_pd_struct *pd);
XXFC_API bool xx_pe_get_memory_map(Abstractformat *self,
                                   xx_memory_map_mode_t mode,
                                   xx_memory_map *output,
                                   xx_pd_struct *pd);

XXFC_API bool xx_pe_is_64(const xx_pe *pe);
XXFC_API uint16_t xx_pe_get_machine(const xx_pe *pe);
XXFC_API uint32_t xx_pe_get_entry_point_rva(const xx_pe *pe);
XXFC_API uint64_t xx_pe_get_image_base(const xx_pe *pe);
XXFC_API uint16_t xx_pe_get_number_of_sections(const xx_pe *pe);
XXFC_API const xx_pe_section *xx_pe_get_section(const xx_pe *pe, uint16_t index);

static inline Abstractformat *xx_pe_to_format(xx_pe *pe) {
    return pe ? &pe->format : NULL;
}

static inline const Abstractformat *xx_pe_to_format_const(const xx_pe *pe) {
    return pe ? &pe->format : NULL;
}

#ifdef __cplusplus
}
#endif

#endif
