/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 */

#ifndef XXFCLIB_LE_DEFS_H
#define XXFCLIB_LE_DEFS_H

#define XX_LINEAR_DOS_HEADER_SIZE 64U
#define XX_LINEAR_HEADER_CORE_SIZE UINT32_C(0xac)
#define XX_LINEAR_HEADER_FULL_SIZE UINT32_C(0xc4)
#define XX_LINEAR_OBJECT_SIZE UINT32_C(24)
#define XX_LE_PAGE_RECORD_SIZE UINT32_C(4)
#define XX_LX_PAGE_RECORD_SIZE UINT32_C(8)
#define XX_LINEAR_RESOURCE_RECORD_SIZE UINT32_C(14)

#define XX_LINEAR_OBJECT_EXECUTABLE UINT32_C(0x0004)
#define XX_LINEAR_MODULE_TYPE_MASK UINT32_C(0x00038000)
#define XX_LINEAR_MODULE_DLL UINT32_C(0x00008000)
#define XX_LINEAR_MODULE_PROTECTED_DLL UINT32_C(0x00018000)
#define XX_LINEAR_MODULE_PHYSICAL_DRIVER UINT32_C(0x00020000)
#define XX_LINEAR_MODULE_VIRTUAL_DRIVER UINT32_C(0x00028000)

#define XX_LINEAR_PAGE_VALID UINT16_C(0)
#define XX_LINEAR_PAGE_ITERATED UINT16_C(1)
#define XX_LINEAR_PAGE_INVALID UINT16_C(2)
#define XX_LINEAR_PAGE_ZEROED UINT16_C(3)
#define XX_LINEAR_PAGE_RANGE UINT16_C(4)
#define XX_LINEAR_PAGE_ITERATED_2 UINT16_C(5)

#endif /* XXFCLIB_LE_DEFS_H */
