/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 */
#include "xxfclib/rt/xx_rt.h"
#include "xxfclib/formats/ain/xx_ain.h"
#include "xxfclib/algo/ain/xx_ain.h"
#include "xxfclib/algo/store/xx_store.h"
#include "xxfclib/io/xx_io.h"
#include "xxfclib/memory/xx_memory.h"
#include "xxfclib/strings/xx_string.h"
#include <limits.h>
#include <stdio.h>
#include <string.h>
#define AIN_HEADER 24U
#define AIN_RECORD 29U
#define AIN_MAX_MEMBERS 65535U
#define AIN_MAX_DIRECTORY (16U*1024U*1024U)
#define AIN_NEWGROUP 0x10U
#define AIN_ENDGROUP 0x08U
typedef struct { int64_t data,packed,skip; uint32_t original,time; uint8_t method; bool encrypted; char *name; } ain_member;
typedef struct { ain_member *items; size_t count,index; int64_t end; } ain_stream;
static uint16_t u16(const uint8_t*p){return(uint16_t)(p[0]|((uint16_t)p[1]<<8U));}
static uint32_t u32(const uint8_t*p){return(uint32_t)u16(p)|((uint32_t)u16(p+2)<<16U);}
static bool read_at(xx_io_device*d,int64_t o,void*p,size_t n){size_t at=0;if(!d||o<0||o>LONG_MAX||xx_io_seek(d,(long)o,SEEK_SET))return false;while(at<n){ssize_t x=xx_io_read(d,(uint8_t*)p+at,n-at);if(x<=0||(size_t)x>n-at)return false;at+=(size_t)x;}return true;}
static void stream_free(void*p){ain_stream*s=(ain_stream*)p;size_t i;if(!s)return;for(i=0;i<s->count;i++)if(s->items[i].name)xx_str_free(s->items[i].name);if(s->items)xx_mem_free(s->items);xx_mem_free(s);}
static bool name_safe(const char*n){const char*s=n,*p;if(!n||!n[0]||n[0]=='/'||n[0]=='\\'||n[1]==':')return false;for(p=n;;p++){unsigned char c=(unsigned char)*p;if(c==':'||c=='<'||c=='>'||c=='"'||c=='|'||c=='?'||c=='*'||(c&&c<32))return false;if(c=='/'||c=='\\'||!c){size_t z=(size_t)(p-s);if(!z||(z==1&&s[0]=='.')||(z==2&&s[0]=='.'&&s[1]=='.'))return false;if(!c)return true;s=p+1;}}}
static bool parse(Abstractformat*f,ain_stream**out){uint8_t h[AIN_HEADER],*packed=NULL,*dir=NULL;uint16_t count;uint32_t off;uint64_t sum=0;int64_t total;size_t cap,i,pos=0,group_first=0;int64_t group_offset=-1,group_skip=0;bool encrypted;ain_stream*s=NULL;
 if(!f||!f->device||!out||(total=xx_io_total_size(f->device))-f->base_address<(int64_t)AIN_HEADER||!read_at(f->device,f->base_address,h,sizeof(h))||h[0]!='!')return false;
 if((h[1]&15U)<1U||(h[1]&15U)>4U||(h[1]>>4U)<1U||(h[1]>>4U)>3U||(u16(h+2)!=0U&&u16(h+2)!=0x8000U))return false;
 for(i=0;i<22U;i++)sum+=h[i];if((uint16_t)sum!=(uint16_t)(u16(h+22)^0x5555U))return false;count=u16(h+8);off=u32(h+14);if(!count||count>AIN_MAX_MEMBERS||off<AIN_HEADER||(int64_t)off>=total-f->base_address)return false;
 cap=(size_t)count*1053U+4096U;if(cap>AIN_MAX_DIRECTORY)cap=AIN_MAX_DIRECTORY;packed=(uint8_t*)xx_mem_alloc((size_t)(total-f->base_address-(int64_t)off));dir=(uint8_t*)xx_mem_calloc(cap,1);s=(ain_stream*)xx_mem_calloc(1,sizeof(*s));if(!packed||!dir||!s||!read_at(f->device,f->base_address+(int64_t)off,packed,(size_t)(total-f->base_address-(int64_t)off)))goto fail;
 /* AIN's directory is a self-terminating compressed stream. The decoder
    writes its valid prefix before returning at the stream terminator. */
 (void)xx_ain_decode_memory(packed,(size_t)(total-f->base_address-(int64_t)off),0,dir,cap,NULL);encrypted=u16(h+2)!=0U;
 for(i=0;i<count;i++){uint8_t*rec;size_t start;ain_member*m,*grown;uint32_t original,stored_packed,data_offset;uint8_t flags;
  if(pos>cap||cap-pos<AIN_RECORD)goto fail;rec=dir+pos;pos+=AIN_RECORD;start=pos;while(pos<cap&&dir[pos]){if(dir[pos]<0x20U||pos-start>=1024U)goto fail;++pos;}if(pos==start||pos>=cap)goto fail;++pos;if(pos>=cap||dir[pos]!=0)goto fail;++pos;
  flags=rec[22];if(flags&0xe7U)goto fail;original=u32(rec+5);stored_packed=u32(rec+9);data_offset=u32(rec+13);if(original>INT32_MAX)goto fail;if(flags&AIN_NEWGROUP){group_offset=data_offset;group_skip=0;group_first=s->count;}if(group_offset<0||f->base_address+group_offset>total)goto fail;
  grown=(ain_member*)xx_mem_realloc(s->items,(s->count+1U)*sizeof(*grown));if(!grown)goto fail;s->items=grown;m=&s->items[s->count];xx_mem_zero(m,sizeof(*m));m->name=(char*)xx_mem_alloc(pos-start);if(!m->name)goto fail;xx_rt_memcpy(m->name,dir+start,pos-start-1U);m->name[pos-start-1U]=0;for(size_t q=0;m->name[q];q++)if(m->name[q]=='\\')m->name[q]='/';m->data=f->base_address+group_offset;m->packed=total-m->data;m->skip=group_skip;m->original=original;m->time=(uint32_t)u16(rec+1)|((uint32_t)u16(rec+3)<<16U);m->method=h[1]&15U;m->encrypted=encrypted;
  if(m->method==4U){m->data=f->base_address+group_offset+group_skip;m->packed=original;m->skip=0;if(m->data<0||m->data>total||m->packed>total-m->data)goto fail;}++s->count;group_skip+=original;
  if(flags&AIN_ENDGROUP){if(m->method!=4U){int64_t n=stored_packed;if(n<0||m->data>total||n>total-m->data)n=total-m->data;for(size_t q=group_first;q<s->count;q++)s->items[q].packed=n;}group_offset=-1;}
 }
 if(group_offset>=0||!s->count)goto fail;s->end=total;xx_mem_free(packed);xx_mem_free(dir);*out=s;return true;
fail:if(packed)xx_mem_free(packed);if(dir)xx_mem_free(dir);stream_free(s);return false;}
static bool copy_options(xx_list_s*d,const xx_list_s*s){size_t i;if(!s)return true;for(i=0;i<s->count;i++){const xx_meta*m=(const xx_meta*)xx_list_at((const xx_list_t*)s,i);xx_meta c;if(!m)continue;xx_meta_init(&c,m->meta_id);if(!xx_var_copy(&c.var,&m->var)||!xx_list_append(d,&c)){xx_meta_cleanup(&c);return false;}}return true;}
static const xx_var*option(const xx_list_s*l,uint32_t id){size_t i;if(!l)return NULL;for(i=0;i<l->count;i++){const xx_meta*m=(const xx_meta*)xx_list_at((const xx_list_t*)l,i);if(m&&m->meta_id==id)return&m->var;}return NULL;}
static bool record(xx_archive_record*r,const ain_member*m){xx_archive_record_cleanup(r);xx_archive_record_init(r);r->data_offset=m->data;r->compressed_size=m->packed;return xx_archive_record_set_original_name(r,m->name)&&xx_archive_record_set_meta_u64(r,XX_META_ID_COMPRESSED_SIZE,m->packed)&&xx_archive_record_set_meta_u64(r,XX_META_ID_UNCOMPRESSED_SIZE,m->original)&&xx_archive_record_set_meta_u64(r,XX_META_ID_COMPRESSION_METHOD,m->method)&&xx_archive_record_set_meta_u64(r,XX_META_ID_TIMESTAMP,m->time)&&xx_archive_record_set_meta_bool(r,XX_META_ID_IS_ENCRYPTED,m->encrypted)&&xx_archive_record_set_meta_bool(r,XX_META_ID_IS_FOLDER,false);}
static bool decode(Abstractformat*f,const ain_member*m,uint8_t**out,size_t*size){uint8_t*p,*q;size_t wrote=0;if(m->encrypted||m->packed<0||m->original>SIZE_MAX)return false;p=(uint8_t*)xx_mem_alloc((size_t)m->packed);q=(uint8_t*)xx_mem_alloc(m->original?m->original:1U);if(!p||!q||(m->packed&&!read_at(f->device,m->data,p,(size_t)m->packed)))goto fail;if(m->method==4U){if((uint32_t)m->packed!=m->original)goto fail;if(m->original)xx_mem_copy(q,p,m->original);wrote=m->original;}else if(!xx_ain_decode_memory(p,(size_t)m->packed,(size_t)m->skip,q,m->original,&wrote)||wrote!=m->original)goto fail;xx_mem_free(p);*out=q;*size=wrote;return true;fail:if(p)xx_mem_free(p);if(q)xx_mem_free(q);return false;}
void xx_ain_init(xx_ain*a,xx_io_device*d,int64_t b){if(!a)return;xx_mem_zero(a,sizeof(*a));xx_format_init(&a->format,d,b);a->format.endian=XX_ENDIAN_LITTLE;a->format.file_type=XX_FILE_TYPE_AIN;a->format.format_type=XX_TYPE_ARCHIVE;a->format.is_archive=true;xx_format_set_mime_type(&a->format,"application/x-ain");xx_format_set_extension(&a->format,"ain");a->format.check_is_valid=xx_ain_check_is_valid;a->format.handle_base_info=xx_ain_handle_base_info;a->format.get_format_size=xx_ain_get_format_size;a->format.get_number_of_archive_records=xx_ain_get_number_of_archive_records;a->format.create_archive_records_reading=xx_ain_create_archive_records_reading;a->format.get_current_archive_record=xx_ain_get_current_archive_record;a->format.unpack_current_archive_record=xx_ain_unpack_current_archive_record;a->format.archive_record_move_to_next=xx_ain_archive_record_move_to_next;a->format.free_archive_records_reading=xx_ain_free_archive_records_reading;a->archive_end=-1;}
xx_ain*xx_ain_create(xx_io_device*d,int64_t b){xx_ain*a=(xx_ain*)xx_mem_alloc(sizeof(*a));if(a)xx_ain_init(a,d,b);return a;}void xx_ain_destroy(xx_ain*a){if(a)xx_format_cleanup_extra_parameters(&a->format);}void xx_ain_free(xx_ain*a){if(a){xx_ain_destroy(a);xx_mem_free(a);}}
bool xx_ain_check_is_valid(Abstractformat*f,xx_pd_struct*p){ain_stream*s;(void)p;if(!parse(f,&s))return false;stream_free(s);return true;}bool xx_ain_handle_base_info(Abstractformat*f,xx_pd_struct*p){ain_stream*s;xx_ain*a;(void)p;if(!f||!parse(f,&s))return false;a=(xx_ain*)f;a->number_of_records=s->count;a->archive_end=s->end;f->number_of_archive_records=s->count;f->format_size=s->end-f->base_address;f->is_valid=true;f->base_info_handled=true;stream_free(s);return true;}int64_t xx_ain_get_format_size(Abstractformat*f,xx_pd_struct*p){return f&&(f->base_info_handled||xx_ain_handle_base_info(f,p))?f->format_size:-1;}uint64_t xx_ain_get_number_of_archive_records(Abstractformat*f,xx_pd_struct*p){return f&&(f->base_info_handled||xx_ain_handle_base_info(f,p))?((xx_ain*)f)->number_of_records:0;}
xx_archive_record_state*xx_ain_create_archive_records_reading(Abstractformat*f,const xx_list_s*o,xx_pd_struct*p){ain_stream*s;xx_archive_record_state*r;(void)p;if(!parse(f,&s))return NULL;r=(xx_archive_record_state*)xx_mem_alloc(sizeof(*r));if(!r){stream_free(s);return NULL;}xx_archive_record_state_init(r,f);r->internal_state=s;r->free_internal=stream_free;r->total_records=s->count;if(!copy_options(&r->options,o)||!record(&r->current_record,&s->items[0])){xx_archive_record_state_free(r);return NULL;}r->has_record=true;return r;}const xx_archive_record*xx_ain_get_current_archive_record(Abstractformat*f,xx_archive_record_state*s){return f&&s&&s->format==f&&s->has_record?&s->current_record:NULL;}bool xx_ain_archive_record_move_to_next(Abstractformat*f,xx_archive_record_state*s,xx_pd_struct*p){ain_stream*x;(void)p;if(!f||!s||s->format!=f||!(x=(ain_stream*)s->internal_state)||++x->index>=x->count){if(s)s->has_record=false;return false;}s->current_index++;s->has_record=record(&s->current_record,&x->items[x->index]);return s->has_record;}
bool xx_ain_unpack_current_archive_record(Abstractformat*f,xx_archive_record_state*s,xx_pd_struct*p){ain_stream*x;ain_member*m;const xx_var*o;const char*base=NULL;char*owned=NULL,*path=NULL;uint8_t*plain=NULL;size_t n=0,at=0;bool ok=false;if(!f||!s||s->format!=f||!s->has_record||!(x=(ain_stream*)s->internal_state)||x->index>=x->count||(p&&xx_pd_is_stopped(p)))return false;m=&x->items[x->index];if(!name_safe(m->name)||!decode(f,m,&plain,&n))goto done;o=option(&s->options,XX_META_ID_OPT_UNPACK_PATH);if(!o){ok=true;goto done;}if(o->type==XX_VAR_TYPE_STRING||o->type==XX_VAR_TYPE_STRING_VIEW)base=xx_var_get_str(o);else if(o->type==XX_VAR_TYPE_WSTRING||o->type==XX_VAR_TYPE_WSTRING_VIEW){owned=xx_str_unicode_to_utf8(xx_var_get_wstr(o));base=owned;}if(!base)goto done;path=(base[0]&&base[xx_str_len(base)-1]!='/'&&base[xx_str_len(base)-1]!='\\')?xx_str_concat3(base,"/",m->name):xx_str_concat(base,m->name);if(!path||!xx_store_create_dirs_a(path,false))goto done;{xx_io_device*d=xx_io_file_open(path,"wb");if(!d)goto done;ok=true;while(at<n){ssize_t z=xx_io_write(d,plain+at,n-at);if(z<=0||(size_t)z>n-at){ok=false;break;}at+=(size_t)z;}xx_io_close(d);}done:if(!ok&&path)xx_rt_remove(path);if(plain)xx_mem_free(plain);if(path)xx_str_free(path);if(owned)xx_str_free(owned);return ok;}void xx_ain_free_archive_records_reading(Abstractformat*f,xx_archive_record_state*s){(void)f;xx_archive_record_state_free(s);}
