/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/wux/xx_wux.h"

XX_FORMAT_DEFINE_READER_ADAPTER(wux, XX_FILE_TYPE_WUX,
    xx_wux_create(device, 0), xx_wux_free, XX_READER_TYPE_FILL_UNKNOWN)

