/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/nitroplus_npk2/xx_nitroplus_npk2.h"

XX_FORMAT_DEFINE_READER_ADAPTER(nitroplus_npk2, XX_FILE_TYPE_NITROPLUS_NPK2,
    xx_nitroplus_npk2_create(device, 0), xx_nitroplus_npk2_free, XX_READER_TYPE_FILL_UNKNOWN)

