/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 */

/* xx_silmarilsft_extractor.c - search raw data for Silmarils.
 *
 * Scans for:
 *   81 01 00 at +3  ("...")
 *   A1 01 00 0B 09 at +3  (".....")
 *   00 01 0B 09 at +4  ("....")
 * Offset 0 is always tried as well.
 * Each candidate must be accepted by the silmarilsft reader, which also measures it,
 * and named by the detector, both on a view that starts at the candidate.
 * See xx_format_extractor_engine.h.
 *
 * GENERATED by gen_extractors.py from the detector's prefilters.
 */

#include "../xx_format_extractor_engine.h"
#include "xxfclib/formats/silmarilsft/xx_silmarilsft.h"

static const uint8_t k_anchor0[] = { 0x81, 0x01, 0x00 };
static const uint8_t k_anchor1[] = { 0xA1, 0x01, 0x00, 0x0B, 0x09 };
static const uint8_t k_anchor2[] = { 0x00, 0x01, 0x0B, 0x09 };

static const xx_format_search_anchor k_anchors[] = {
    { k_anchor0, sizeof(k_anchor0), 3U },
    { k_anchor1, sizeof(k_anchor1), 3U },
    { k_anchor2, sizeof(k_anchor2), 4U },
};

static const xx_file_type_t k_types[] = { XX_FILE_TYPE_SILMARILSFT };

static Abstractformat *xx_silmarilsft_search_open(xx_io_device *window) {
    xx_silmarilsft *reader = xx_silmarilsft_create(window, 0);
    return reader ? &reader->format : NULL;
}

static void xx_silmarilsft_search_close(Abstractformat *format) {
    /* The format is the first member, so this is the reader itself. */
    xx_silmarilsft_free((xx_silmarilsft *)format);
}

static const xx_format_search_desc k_desc = {
    k_types, sizeof(k_types) / sizeof(k_types[0]),
    k_anchors, sizeof(k_anchors) / sizeof(k_anchors[0]),
    xx_silmarilsft_search_open, xx_silmarilsft_search_close
};

static xx_format_search_state *xx_silmarilsft_create_format_search(
    xx_format_extractor *self, xx_io_device *device, const xx_list_s *options,
    xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_create(&k_desc, device, options, pd);
}

static const xx_format_search_info *xx_silmarilsft_get_current_format_info(
    xx_format_extractor *self, xx_format_search_state *state) {
    (void)self;
    return xx_format_search_current(state);
}

static bool xx_silmarilsft_format_search_find_next(xx_format_extractor *self,
                                          xx_format_search_state *state,
                                          xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_find_next(state, pd);
}

static void xx_silmarilsft_free_format_search(xx_format_extractor *self,
                                     xx_format_search_state *state) {
    (void)self;
    xx_format_search_free(state);
}

xx_format_extractor xx_silmarilsft_extractor = {
    xx_silmarilsft_create_format_search,
    xx_silmarilsft_get_current_format_info,
    xx_silmarilsft_format_search_find_next,
    xx_silmarilsft_free_format_search
};
