/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/virtual98/xx_virtual98.h"

XX_FORMAT_DEFINE_READER_ADAPTER(virtual98, XX_FILE_TYPE_VIRTUAL98,
    xx_virtual98_create(device, 0), xx_virtual98_free, XX_READER_TYPE_FILL_UNKNOWN)

