/* SPDX-License-Identifier: MIT
 * Primary reference: https://manual.q-chem.com/latest/Ch3.S3.html
 * Q-Chem molecule/rem input subset: balanced complete comment/rem/molecule sections, unique recognized settings, checked charge/multiplicity and finite element coordinates for H through Xe and consistent charge/spin electron parity. Original settings/molecule sections exported; includes, basis/ECP blocks, fragments, variables and job chains declined.
 * Bounded32MiB input,4096 components and bounded work.
 */
#include "xxfclib/formats/qchem_input/xx_qchem_input.h"
#include "../wbmp_image/xx_fifteenth_games.h"
static bool vg_quick(Abstractformat *f,uint64_t n) {uint8_t c;return n>=32&&pm_read(f,0,&c,1)&&(c=='$'||c==' '||c=='\n'||c=='\r');}
static bool vg_qtoken(vg_text *q,char *out,size_t capacity) {size_t z=0;vg_space(q);while(q->t<q->stop&&q->b[q->t]!=32&&q->b[q->t]!=9){uint8_t c=q->b[q->t++];if(z+1>=capacity||!((c>='a'&&c<='z')||(c>='A'&&c<='Z')||(c>='0'&&c<='9')||c=='_'||c=='-'||c=='+'||c=='('||c==')'||c=='.'))return false;if(c>='a'&&c<='z')c-=32;out[z++]=(char)c;}out[z]=0;return z!=0;}
static unsigned vg_element(const char *t) {static const char *const names[]={"H","HE","LI","BE","B","C","N","O","F","NE","NA","MG","AL","SI","P","S","CL","AR","K","CA","SC","TI","V","CR","MN","FE","CO","NI","CU","ZN","GA","GE","AS","SE","BR","KR","RB","SR","Y","ZR","NB","MO","TC","RU","RH","PD","AG","CD","IN","SN","SB","TE","I","XE"};unsigned i;for(i=0;i<54;++i)if(!xx_rt_strcmp(names[i],t))return i+1;return 0;}
static bool vg_parse(Abstractformat *f,pm_stream *s,const uint8_t *b,uint64_t n,xx_pd_struct *pd) {vg_text q={b,0,n,0,0,0};unsigned seen=0,section=0,settings=0,atoms=0,electrons=0;uint64_t start=0;int32_t charge=0,spin=0;bool first=false;char key[64],value[128];static const char *const rem[]={"JOBTYPE","METHOD","BASIS","SYM_IGNORE","SCF_CONVERGENCE","MAX_SCF_CYCLES","SCF_ALGORITHM","THRESH"};if(!vg_utf(b,n,true,pd))return false;while(vg_next(&q)){if(vg_stop(pd))return false;if(q.b[q.t]=='$'){unsigned next=0;if(vg_word_ci(&q,"$end")){if(!vg_done(&q)||!section||first||(section==2&&(settings&7)!=7)||(section==4&&!atoms))return false;if(!vg_emit(f,s,section==1?"comment.txt":section==2?"rem.txt":"molecule.txt",start,q.p-start,n))return false;section=0;continue;}if(vg_word_ci(&q,"$comment"))next=1;else if(vg_word_ci(&q,"$rem"))next=2;else if(vg_word_ci(&q,"$molecule"))next=4;else return false;if(section||!vg_done(&q)||(seen&next))return false;seen|=next;section=next;start=q.start;first=next==4;continue;}if(!section)return false;if(section==1)continue;if(section==2){unsigned i;int32_t number;if(!vg_qtoken(&q,key,sizeof(key)))return false;for(i=0;i<8&&xx_rt_strcmp(rem[i],key);++i){}if(i==8||(settings&(1U<<i)))return false;settings|=1U<<i;if(i==4||i==5||i==7){if(!vg_i(&q,&number)||number<1||number>10000)return false;}else {if(!vg_qtoken(&q,value,sizeof(value)))return false;if(i==0&&xx_rt_strcmp(value,"SP")&&xx_rt_strcmp(value,"OPT")&&xx_rt_strcmp(value,"FREQ"))return false;if(i==3&&xx_rt_strcmp(value,"TRUE")&&xx_rt_strcmp(value,"FALSE"))return false;if(i==6&&xx_rt_strcmp(value,"DIIS")&&xx_rt_strcmp(value,"GDM")&&xx_rt_strcmp(value,"DIIS_GDM"))return false;}if(!vg_done(&q))return false;}else {if(first){if(!vg_i(&q,&charge)||charge< -100||charge>100||!vg_i(&q,&spin)||spin<1||spin>100||!vg_done(&q))return false;first=false;}else {unsigned element;if(++atoms>4000||!vg_qtoken(&q,key,sizeof(key))||!(element=vg_element(key))||!vg_nums(&q,3))return false;electrons+=element;}}}if(q.p!=n||section||(seen&6)!=6||(int64_t)electrons-charge<spin-1||((int64_t)electrons-charge-(spin-1))%2)return false;return vg_cover(f,s,"whitespace.txt",n);}

void xx_qchem_input_init(xx_qchem_input *r,xx_io_device *d,int64_t at) {if(r){xx_mem_zero(r,sizeof(*r));pm_init(&r->format,d,at,XX_FILE_TYPE_QCHEM_INPUT,"inp");}}
xx_qchem_input *xx_qchem_input_create(xx_io_device *d,int64_t at) {xx_qchem_input *r=(xx_qchem_input *)xx_mem_alloc(sizeof(*r));if(r)xx_qchem_input_init(r,d,at);return r;}
void xx_qchem_input_destroy(xx_qchem_input *r) {if(r)xx_format_cleanup_extra_parameters(&r->format);}
void xx_qchem_input_free(xx_qchem_input *r) {if(r){xx_qchem_input_destroy(r);xx_mem_free(r);}}
bool xx_qchem_input_check_is_valid(Abstractformat *f,xx_pd_struct *pd) {return pm_valid(f,pd);}
bool xx_qchem_input_handle_base_info(Abstractformat *f,xx_pd_struct *pd) {return pm_handle(f,pd);}
