/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/thomson_fd/xx_thomson_fd.h"

XX_FORMAT_DEFINE_READER_ADAPTER(thomson_fd, XX_FILE_TYPE_THOMSON_FD,
    xx_thomson_fd_create(device, 0), xx_thomson_fd_free, XX_READER_TYPE_FILL_UNKNOWN)

