/* Copyright (c)2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT. Bounded typed components; payloads never executed.
 */
/* Primary: https://github.com/ggml-org/ggml/blob/master/docs/gguf.md */
#include "xxfclib/formats/gguf/xx_gguf.h"
#include "../xx_fourteenth_wrappers.h"

static bool string(nh_blob *b,uint64_t *p,uint64_t end,uint64_t *v,uint64_t *n){if(!th_take(b,p,end,8))return false;*n=ec_le64(b->p+(size_t)*p-8);*v=*p;return *n<=65536&&th_take(b,p,end,*n)&&ec_utf(b,*v,*n);}
static bool value(nh_blob *b,uint64_t *p,uint32_t type,unsigned depth,unsigned *work){static const unsigned width[]={1,1,2,2,4,4,4,1,0,0,8,8,8};if(++*work>65536||depth>1||type>12)return false;if(type==8){uint64_t v,n;return string(b,p,b->n,&v,&n);}if(type==9){if(!th_take(b,p,b->n,12))return false;uint32_t item=pm_le32(b->p+(size_t)*p-12);uint64_t n=ec_le64(b->p+(size_t)*p-8);if(item==9||item>12||n>4096)return false;for(uint64_t i=0;i<n;++i)if(!value(b,p,item,depth+1,work))return false;return true;}if(!th_take(b,p,b->n,width[type]))return false;return type!=7||b->p[(size_t)*p-1]<=1;}
typedef struct gg_tensor{uint64_t offset,bytes;}gg_tensor;
static bool pm_parse(Abstractformat *f,pm_stream *s,xx_pd_struct *pd){nh_blob b;bool ok=false;gg_tensor *t=NULL;uint64_t at=24,align=32,comparebytes=0;unsigned work=0,candidates=0;bool architecture=false;uint64_t keys[1024],lens[1024];if(!nh_load(f,&b,pd))return false;NH_NEED(b.n>=24&&!xx_rt_memcmp(b.p,"GGUF",4)&&pm_le32(b.p+4)==3);uint64_t nt=ec_le64(b.p+8),nk=ec_le64(b.p+16);NH_NEED(nt>0&&nt<=1024&&nk>0&&nk<=1024);t=(gg_tensor *)xx_mem_alloc((size_t)nt*sizeof(*t));NH_NEED(t&&nh_add(f,s,&b,"gguf-header",0,24));for(uint64_t i=0;i<nk;++i){uint64_t start=at,v,n;NH_NEED(string(&b,&at,b.n,&v,&n)&&n>0);for(uint64_t k=0;k<i;++k)NH_NEED(fw_distinct(&b,keys[k],lens[k],v,n,&candidates,&comparebytes));keys[i]=v;lens[i]=n;NH_NEED(th_take(&b,&at,b.n,4));uint32_t type=pm_le32(b.p+(size_t)at-4);if(th_eq(&b,v,n,"general.architecture")){NH_NEED(type==8&&nh_span(&b,at,8)&&ec_le64(b.p+(size_t)at)>0);architecture=true;}if(th_eq(&b,v,n,"general.alignment")){NH_NEED(type==4&&nh_span(&b,at,4));align=pm_le32(b.p+(size_t)at);NH_NEED(align>=1&&align<=4096&&!(align&(align-1)));}NH_NEED(value(&b,&at,type,0,&work)&&nh_add(f,s,&b,"metadata-entry",start,at-start));}NH_NEED(architecture);for(uint64_t i=0;i<nt;++i){uint64_t start=at,v,n,count=1;NH_NEED(string(&b,&at,b.n,&v,&n)&&n>0&&n<=64);for(uint64_t k=0;k<i;++k)NH_NEED(fw_distinct(&b,keys[k],lens[k],v,n,&candidates,&comparebytes));keys[i]=v;lens[i]=n;NH_NEED(th_take(&b,&at,b.n,4));uint32_t dim=pm_le32(b.p+(size_t)at-4);NH_NEED(dim>=1&&dim<=4);for(unsigned k=0;k<dim;++k){NH_NEED(th_take(&b,&at,b.n,8));uint64_t d=ec_le64(b.p+(size_t)at-8);NH_NEED(d>0&&d<=67108864&&count<=67108864/d);count*=d;}NH_NEED(th_take(&b,&at,b.n,12));uint32_t type=pm_le32(b.p+(size_t)at-12);unsigned width=type==0?4:type==1?2:type==24?1:type==25?2:type==26?4:type==27?8:type==28?8:0;NH_NEED(width&&count<=67108864/width);t[i].bytes=count*width;t[i].offset=ec_le64(b.p+(size_t)at-8);NH_NEED(!(t[i].offset&(align-1))&&nh_add(f,s,&b,"tensor-directory",start,at-start));}NH_NEED(ec_pad(&b,&at,align));uint64_t base=at,end=0;for(uint64_t k=0;k<nt;++k){uint64_t least=UINT64_MAX,index=nt;for(uint64_t i=0;i<nt;++i)if(t[i].offset<least){least=t[i].offset;index=i;}NH_NEED(index<nt&&least==end&&nh_add(f,s,&b,"stored-tensor",base+least,t[index].bytes));end=least+t[index].bytes;t[index].offset=UINT64_MAX;if(k+1<nt){uint64_t pad=(align-(end&(align-1)))&(align-1);NH_NEED(nh_zero(&b,base+end,pad));end+=pad;}}if(base+end!=b.n){uint64_t padding=(align-(end&(align-1)))&(align-1);NH_NEED(padding>0&&base+end+padding==b.n&&nh_zero(&b,base+end,padding));}s->size=(int64_t)b.n;ok=true;done:xx_mem_free(t);xx_mem_free(b.p);return ok;}

void xx_gguf_init(xx_gguf *r,xx_io_device *d,int64_t b){if(r){xx_mem_zero(r,sizeof(*r));pm_init(&r->format,d,b,XX_FILE_TYPE_GGUF,"bin");}}
xx_gguf *xx_gguf_create(xx_io_device *d,int64_t b){xx_gguf *r=(xx_gguf *)xx_mem_alloc(sizeof(*r));if(r)xx_gguf_init(r,d,b);return r;}
void xx_gguf_destroy(xx_gguf *r){if(r)xx_format_cleanup_extra_parameters(&r->format);}
void xx_gguf_free(xx_gguf *r){if(r){xx_gguf_destroy(r);xx_mem_free(r);}}
bool xx_gguf_check_is_valid(Abstractformat *f,xx_pd_struct *pd){return pm_valid(f,pd);}
bool xx_gguf_handle_base_info(Abstractformat *f,xx_pd_struct *pd){return pm_handle(f,pd);}
