"""Generate original, compressed sector maps from audited public geometry facts.

Usage: python generate_hxc_profiles.py raw-profile-facts.json
The facts record provenance for each layout. Existing source bytes take priority
over generation templates; sectors beyond the declared source use declared fill.
No upstream source code is incorporated in the generated implementation.
"""
import json
from pathlib import Path
import sys

facts = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
root = Path(__file__).resolve().parents[2]
profiles = facts["profiles"]
out = ["/* SPDX-License-Identifier: MIT. Geometry facts; generated by\n"
       " * samples/unpack/generate_hxc_profiles.py. Sources pinned to\n"
       f" * HxCFloppyEmulator {facts['upstream_commit']}. */\n"]
for index, profile in enumerate(profiles):
    source_size = profile["declared_file_size"] or profile["source_extent"]
    units = []
    for sector in sorted(profile["sectors"], key=lambda s: (s["c"], s["h"], s["id"])):
        at, size, fill = sector["offset"], sector["size"], sector["fill"]
        available = max(0, min(size, source_size - at))
        if available:
            units.append((at, available, fill, 0))
        if available < size:
            units.append((0, size - available, fill, 1))
    runs = []
    for at, size, fill, mode in units:
        if runs and runs[-1][1] == size and runs[-1][4:] == [fill, mode]:
            prev = runs[-1]
            delta = at - (prev[0] + prev[3] * (prev[2] - 1))
            if prev[2] == 1:
                prev[3] = delta
                prev[2] += 1
                continue
            if delta == prev[3]:
                prev[2] += 1
                continue
        runs.append([at, size, 1, size if mode == 0 else 0, fill, mode])
    assert runs and sum(r[1] * r[2] for r in runs) == profile["payload_bytes"]
    out.append(f"/* {profile['name']}: {profile['provenance']['url']} */\n")
    out.append(f"static const xx_hxc_raw_extent hx_extents_{index}[] = {{\n")
    for at, size, count, stride, fill, mode in runs:
        out.append(f"    {{ UINT64_C({at}), {size}U, {count}U, INT64_C({stride}), {fill}U, {mode}U, NULL }},\n")
    out.append("};\n")
out.append("static const xx_hxc_raw_profile hx_profiles[] = {\n")
for index, profile in enumerate(profiles):
    name = json.dumps(profile["name"], ensure_ascii=True)
    source_size = profile["declared_file_size"] or profile["source_extent"]
    out.append(f"    {{ {name}, {profile['cylinders']}U, {profile['heads']}U, UINT64_C({source_size}), hx_extents_{index}, sizeof(hx_extents_{index})/sizeof(hx_extents_{index}[0]) }},\n")
out.append("};\n")
target = root / "src/formats/hxc_raw_floppy/xx_hxc_raw_profiles.inc"
target.write_text("".join(out), encoding="utf-8")
print(f"Generated {len(profiles)} profiles, {sum(p['payload_bytes'] for p in profiles)} logical bytes: {target}")
