/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/blindwrite4/xx_blindwrite4.h"

XX_FORMAT_DEFINE_READER_ADAPTER(blindwrite4, XX_FILE_TYPE_BLINDWRITE4,
    xx_blindwrite4_create(device, 0), xx_blindwrite4_free, XX_READER_TYPE_FILL_UNKNOWN)

