/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/pce_pfdc/xx_pce_pfdc.h"

XX_FORMAT_DEFINE_READER_ADAPTER(pce_pfdc_v0, XX_FILE_TYPE_PCE_PFDC_V0,
    xx_pce_pfdc_create(device, 0, 0), xx_pce_pfdc_free, XX_READER_TYPE_FORCE)

XX_FORMAT_DEFINE_READER_ADAPTER(pce_pfdc_v1, XX_FILE_TYPE_PCE_PFDC_V1,
    xx_pce_pfdc_create(device, 0, 1), xx_pce_pfdc_free, XX_READER_TYPE_FORCE)

XX_FORMAT_DEFINE_READER_ADAPTER(pce_pfdc_v2, XX_FILE_TYPE_PCE_PFDC_V2,
    xx_pce_pfdc_create(device, 0, 2), xx_pce_pfdc_free, XX_READER_TYPE_FORCE)

XX_FORMAT_DEFINE_READER_ADAPTER(pce_pfdc_v4, XX_FILE_TYPE_PCE_PFDC_V4,
    xx_pce_pfdc_create(device, 0, 4), xx_pce_pfdc_free, XX_READER_TYPE_FORCE)

