/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/casio_fzf/xx_casio_fzf.h"

XX_FORMAT_DEFINE_READER_ADAPTER(casio_fzf, XX_FILE_TYPE_CASIO_FZF,
    xx_casio_fzf_create(device, 0), xx_casio_fzf_free, XX_READER_TYPE_FILL_UNKNOWN)

