/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/heathkit_h17/xx_heathkit_h17.h"

XX_FORMAT_DEFINE_READER_ADAPTER(heathkit_h17, XX_FILE_TYPE_HEATHKIT_H17,
    xx_heathkit_h17_create(device, 0), xx_heathkit_h17_free, XX_READER_TYPE_FILL_UNKNOWN)

