/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 */

/* xx_chieflz_extractor.c - search raw data for CHIEFLZ.
 *
 * Scans for:
 *   08 61 43 68 69 65 66 4D 23 at +0  (".aChiefM#")
 * Offset 0 is always tried as well.
 * Each candidate must be accepted by the chieflz reader, which also measures it,
 * and named by the detector, both on a view that starts at the candidate.
 * See xx_format_extractor_engine.h.
 *
 * GENERATED by gen_extractors.py from the detector's prefilters.
 */

#include "../xx_format_extractor_engine.h"
#include "xxfclib/formats/chieflz/xx_chieflz.h"

static const uint8_t k_anchor0[] = { 0x08, 0x61, 0x43, 0x68, 0x69, 0x65, 0x66, 0x4D, 0x23 };

static const xx_format_search_anchor k_anchors[] = {
    { k_anchor0, sizeof(k_anchor0), 0U },
};

static const xx_file_type_t k_types[] = { XX_FILE_TYPE_CHIEFLZ };

static Abstractformat *xx_chieflz_search_open(xx_io_device *window) {
    xx_chieflz *reader = xx_chieflz_create(window, 0);
    return reader ? &reader->format : NULL;
}

static void xx_chieflz_search_close(Abstractformat *format) {
    /* The format is the first member, so this is the reader itself. */
    xx_chieflz_free((xx_chieflz *)format);
}

static const xx_format_search_desc k_desc = {
    k_types, sizeof(k_types) / sizeof(k_types[0]),
    k_anchors, sizeof(k_anchors) / sizeof(k_anchors[0]),
    xx_chieflz_search_open, xx_chieflz_search_close
};

static xx_format_search_state *xx_chieflz_create_format_search(
    xx_format_extractor *self, xx_io_device *device, const xx_list_s *options,
    xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_create(&k_desc, device, options, pd);
}

static const xx_format_search_info *xx_chieflz_get_current_format_info(
    xx_format_extractor *self, xx_format_search_state *state) {
    (void)self;
    return xx_format_search_current(state);
}

static bool xx_chieflz_format_search_find_next(xx_format_extractor *self,
                                          xx_format_search_state *state,
                                          xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_find_next(state, pd);
}

static void xx_chieflz_free_format_search(xx_format_extractor *self,
                                     xx_format_search_state *state) {
    (void)self;
    xx_format_search_free(state);
}

xx_format_extractor xx_chieflz_extractor = {
    xx_chieflz_create_format_search,
    xx_chieflz_get_current_format_info,
    xx_chieflz_format_search_find_next,
    xx_chieflz_free_format_search
};
