/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 */

/* xx_unixpack_extractor.c - search raw data for UNIX PACK.
 *
 * Scans for:
 *   1F 1E at +0  ("..")
 *   1F 1F at +0  ("..")
 * Offset 0 is always tried as well.
 * Each candidate must be accepted by the unixpack reader, which also measures it,
 * and named by the detector, both on a view that starts at the candidate.
 * See xx_format_extractor_engine.h.
 *
 * GENERATED by gen_extractors.py from the detector's prefilters.
 */

#include "../xx_format_extractor_engine.h"
#include "xxfclib/formats/unixpack/xx_unixpack.h"

static const uint8_t k_anchor0[] = { 0x1F, 0x1E };
static const uint8_t k_anchor1[] = { 0x1F, 0x1F };

static const xx_format_search_anchor k_anchors[] = {
    { k_anchor0, sizeof(k_anchor0), 0U },
    { k_anchor1, sizeof(k_anchor1), 0U },
};

static const xx_file_type_t k_types[] = { XX_FILE_TYPE_UNIX_PACK };

static Abstractformat *xx_unixpack_search_open(xx_io_device *window) {
    xx_unixpack *reader = xx_unixpack_create(window, 0);
    return reader ? &reader->format : NULL;
}

static void xx_unixpack_search_close(Abstractformat *format) {
    /* The format is the first member, so this is the reader itself. */
    xx_unixpack_free((xx_unixpack *)format);
}

static const xx_format_search_desc k_desc = {
    k_types, sizeof(k_types) / sizeof(k_types[0]),
    k_anchors, sizeof(k_anchors) / sizeof(k_anchors[0]),
    xx_unixpack_search_open, xx_unixpack_search_close
};

static xx_format_search_state *xx_unixpack_create_format_search(
    xx_format_extractor *self, xx_io_device *device, const xx_list_s *options,
    xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_create(&k_desc, device, options, pd);
}

static const xx_format_search_info *xx_unixpack_get_current_format_info(
    xx_format_extractor *self, xx_format_search_state *state) {
    (void)self;
    return xx_format_search_current(state);
}

static bool xx_unixpack_format_search_find_next(xx_format_extractor *self,
                                          xx_format_search_state *state,
                                          xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_find_next(state, pd);
}

static void xx_unixpack_free_format_search(xx_format_extractor *self,
                                     xx_format_search_state *state) {
    (void)self;
    xx_format_search_free(state);
}

xx_format_extractor xx_unixpack_extractor = {
    xx_unixpack_create_format_search,
    xx_unixpack_get_current_format_info,
    xx_unixpack_format_search_find_next,
    xx_unixpack_free_format_search
};
