/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/windows_thumbnail_cache/xx_windows_thumbnail_cache.h"

XX_FORMAT_DEFINE_READER_ADAPTER(windows_thumbnail_cache, XX_FILE_TYPE_WINDOWS_THUMBNAIL_CACHE,
    xx_windows_thumbnail_cache_create(device, 0), xx_windows_thumbnail_cache_free, XX_READER_TYPE_FILL_UNKNOWN)

