/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/qlie_pack/xx_qlie_pack.h"

XX_FORMAT_DEFINE_READER_ADAPTER(qlie_pack, XX_FILE_TYPE_QLIE_PACK,
    xx_qlie_pack_create(device, 0), xx_qlie_pack_free, XX_READER_TYPE_FILL_UNKNOWN)

