/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 */

/* xx_bcw_extractor.c - search raw data for BCW.
 *
 * Scans for:
 *   0A 14 1E 28 01 at +0  ("...(.")
 *   0A 14 1E 28 02 at +0  ("...(.")
 * Offset 0 is always tried as well.
 * Each candidate must be accepted by the bcw reader, which also measures it,
 * and named by the detector, both on a view that starts at the candidate.
 * See xx_format_extractor_engine.h.
 *
 * GENERATED by gen_extractors.py from the detector's prefilters.
 */

#include "../xx_format_extractor_engine.h"
#include "xxfclib/formats/bcw/xx_bcw.h"

static const uint8_t k_anchor0[] = { 0x0A, 0x14, 0x1E, 0x28, 0x01 };
static const uint8_t k_anchor1[] = { 0x0A, 0x14, 0x1E, 0x28, 0x02 };

static const xx_format_search_anchor k_anchors[] = {
    { k_anchor0, sizeof(k_anchor0), 0U },
    { k_anchor1, sizeof(k_anchor1), 0U },
};

static const xx_file_type_t k_types[] = { XX_FILE_TYPE_BCW };

static Abstractformat *xx_bcw_search_open(xx_io_device *window) {
    xx_bcw *reader = xx_bcw_create(window, 0);
    return reader ? &reader->format : NULL;
}

static void xx_bcw_search_close(Abstractformat *format) {
    /* The format is the first member, so this is the reader itself. */
    xx_bcw_free((xx_bcw *)format);
}

static const xx_format_search_desc k_desc = {
    k_types, sizeof(k_types) / sizeof(k_types[0]),
    k_anchors, sizeof(k_anchors) / sizeof(k_anchors[0]),
    xx_bcw_search_open, xx_bcw_search_close
};

static xx_format_search_state *xx_bcw_create_format_search(
    xx_format_extractor *self, xx_io_device *device, const xx_list_s *options,
    xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_create(&k_desc, device, options, pd);
}

static const xx_format_search_info *xx_bcw_get_current_format_info(
    xx_format_extractor *self, xx_format_search_state *state) {
    (void)self;
    return xx_format_search_current(state);
}

static bool xx_bcw_format_search_find_next(xx_format_extractor *self,
                                          xx_format_search_state *state,
                                          xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_find_next(state, pd);
}

static void xx_bcw_free_format_search(xx_format_extractor *self,
                                     xx_format_search_state *state) {
    (void)self;
    xx_format_search_free(state);
}

xx_format_extractor xx_bcw_extractor = {
    xx_bcw_create_format_search,
    xx_bcw_get_current_format_info,
    xx_bcw_format_search_find_next,
    xx_bcw_free_format_search
};
