/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/mub/xx_mub.h"

XX_FORMAT_DEFINE_READER_ADAPTER(mub, XX_FILE_TYPE_MUB,
    xx_mub_create(device, 0), xx_mub_free, XX_READER_TYPE_FILL_UNKNOWN)

