/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 */

/* xx_sos_extractor.c - search raw data for SOS.
 *
 * Scans for:
 *   53 4F 53 31 at +16  ("SOS1")
 * Offset 0 is always tried as well.
 * Each candidate must be accepted by the sos reader, which also measures it,
 * and named by the detector, both on a view that starts at the candidate.
 * See xx_format_extractor_engine.h.
 *
 * GENERATED by gen_extractors.py from the detector's prefilters.
 */

#include "../xx_format_extractor_engine.h"
#include "xxfclib/formats/sos/xx_sos.h"

static const uint8_t k_anchor0[] = { 0x53, 0x4F, 0x53, 0x31 };

static const xx_format_search_anchor k_anchors[] = {
    { k_anchor0, sizeof(k_anchor0), 16U },
};

static const xx_file_type_t k_types[] = { XX_FILE_TYPE_SOS };

static Abstractformat *xx_sos_search_open(xx_io_device *window) {
    xx_sos *reader = xx_sos_create(window, 0);
    return reader ? &reader->format : NULL;
}

static void xx_sos_search_close(Abstractformat *format) {
    /* The format is the first member, so this is the reader itself. */
    xx_sos_free((xx_sos *)format);
}

static const xx_format_search_desc k_desc = {
    k_types, sizeof(k_types) / sizeof(k_types[0]),
    k_anchors, sizeof(k_anchors) / sizeof(k_anchors[0]),
    xx_sos_search_open, xx_sos_search_close
};

static xx_format_search_state *xx_sos_create_format_search(
    xx_format_extractor *self, xx_io_device *device, const xx_list_s *options,
    xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_create(&k_desc, device, options, pd);
}

static const xx_format_search_info *xx_sos_get_current_format_info(
    xx_format_extractor *self, xx_format_search_state *state) {
    (void)self;
    return xx_format_search_current(state);
}

static bool xx_sos_format_search_find_next(xx_format_extractor *self,
                                          xx_format_search_state *state,
                                          xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_find_next(state, pd);
}

static void xx_sos_free_format_search(xx_format_extractor *self,
                                     xx_format_search_state *state) {
    (void)self;
    xx_format_search_free(state);
}

xx_format_extractor xx_sos_extractor = {
    xx_sos_create_format_search,
    xx_sos_get_current_format_info,
    xx_sos_format_search_find_next,
    xx_sos_free_format_search
};
