/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/qnx4/xx_qnx4.h"

XX_FORMAT_DEFINE_READER_ADAPTER(qnx4, XX_FILE_TYPE_QNX4,
    xx_qnx4_create(device, 0), xx_qnx4_free, XX_READER_TYPE_FILL_UNKNOWN)

