/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/blindwrite_5_6_image/xx_blindwrite_5_6_image.h"

XX_FORMAT_DEFINE_READER_ADAPTER(blindwrite_5_6_image, XX_FILE_TYPE_BLINDWRITE_5_6_IMAGE,
    xx_blindwrite_5_6_image_create(device, 0), xx_blindwrite_5_6_image_free, XX_READER_TYPE_FILL_UNKNOWN)

