/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Bounded primary grammar. Payloads are never executed.
 */
/* Primary: https://github.com/LMDB/lmdb/blob/mdb.master/libraries/liblmdb/mdb.c */
#include "xxfclib/formats/lmdb_data/xx_lmdb_data.h"
#include "xxfclib/data/xx_data.h"
#include "../common/xx_protocol_framing.h"

typedef struct lm_state{Abstractformat *f;pm_stream *s;memory_blob *b;uint8_t *seen;uint64_t size,last,branches,leaves,overflows,entries,prev,prevn;unsigned work;}lm_state;
static bool meta(memory_blob *b,uint64_t at,uint64_t size){if(!blob_span(b,at,152)||xx_data_get_u64(b->p+(size_t)at, 8, 0, false)!=at/size||xx_data_get_u16(b->p+(size_t)at+8, 2, 0, false)||xx_data_get_u16(b->p+(size_t)at+10, 2, 0, false)!=8||xx_data_get_u32(b->p+(size_t)at+12, 4, 0, false)||xx_data_get_u32(b->p+(size_t)at+16, 4, 0, false)!=0xbeefc0deU||xx_data_get_u32(b->p+(size_t)at+20, 4, 0, false)!=1||xx_data_get_u64(b->p+(size_t)at+24, 8, 0, false)||xx_data_get_u32(b->p+(size_t)at+40, 4, 0, false)!=size||xx_data_get_u16(b->p+(size_t)at+44, 2, 0, false)!=8)return false;uint64_t mapsize=xx_data_get_u64(b->p+(size_t)at+32, 8, 0, false),last=xx_data_get_u64(b->p+(size_t)at+136, 8, 0, false);return mapsize>=b->n&&!(mapsize%size)&&mapsize<=0x100000000ULL&&last>=1&&last<b->n/size;}
static bool walk(lm_state *l,uint64_t pg,unsigned depth,unsigned expected,uint64_t *minimum,uint64_t *minn){memory_blob *b=l->b;uint64_t base=pg*l->size;uint16_t flags,lower,upper,count;uint64_t offsets[512],lengths[512],sum=0,previous=0,previousn=0;bool first=true;if(!depth||depth>32||pg<2||pg>l->last||l->seen[pg]||!blob_span(b,base,l->size))return false;l->seen[pg]=1;const uint8_t *page=b->p+(size_t)base;flags=xx_data_get_u16(page+10, 2, 0, false);lower=xx_data_get_u16(page+12, 2, 0, false);upper=xx_data_get_u16(page+14, 2, 0, false);if(xx_data_get_u64(page, 8, 0, false)!=pg||xx_data_get_u16(page+8, 2, 0, false)||flags!=(expected==1?2:1)||lower<16||lower>upper||upper>l->size||(lower&1)||(upper&1))return false;count=(uint16_t)((lower-16)/2);if(!count||count>512)return false;if(flags==1)++l->branches;else ++l->leaves;
 for(unsigned i=0;i<count;++i){if(++l->work>2000000||binary_stop(b->pd))return false;uint64_t off=xx_data_get_u16(page+16+i*2, 2, 0, false);if(off<upper||(off&1)||off+8>l->size)return false;const uint8_t *node=page+(size_t)off;uint64_t keyn=xx_data_get_u16(node+6, 2, 0, false),key=base+off+8,value=key+keyn,sz=xx_data_get_u32(node, 4, 0, false);uint16_t nf=xx_data_get_u16(node+4, 2, 0, false);if(keyn>511||!blob_span(b,key,keyn)||(!keyn&&(flags!=1||i))||(i&&serialized_cmp(b->p+(size_t)previous,previousn,b->p+(size_t)key,keyn)>=0))return false;previous=key;previousn=keyn;uint64_t length=8+keyn+(flags==1?0:(nf==1?8:sz));length=(length+1)&~1ULL;if(off+length>l->size)return false;for(unsigned j=0;j<i;++j){if(++l->work>2000000)return false;if(off<offsets[j]+lengths[j]&&offsets[j]<off+length)return false;}offsets[i]=off;lengths[i]=length;sum+=length;
 if(flags==1){uint64_t child=sz|((uint64_t)nf<<32),childkey,childn;if(!walk(l,child,depth+1,expected-1,&childkey,&childn)|| (i && serialized_cmp(b->p+(size_t)key,keyn,b->p+(size_t)childkey,childn)))return false;if(first){*minimum=childkey;*minn=childn;first=false;}}
 else{if(nf>1||!keyn||(l->prevn&&serialized_cmp(b->p+(size_t)l->prev,l->prevn,b->p+(size_t)key,keyn)>=0))return false;l->prev=key;l->prevn=keyn;++l->entries;if(first){*minimum=key;*minn=keyn;first=false;}if(!blob_add(l->f,l->s,b,"key",key,keyn))return false;
 if(nf==1){if(!blob_span(b,value,8))return false;uint64_t ov=xx_data_get_u64(b->p+(size_t)value, 8, 0, false),o=ov*l->size;if(ov<2||ov>l->last||!blob_span(b,o,16))return false;const uint8_t *header=b->p+(size_t)o;uint64_t pages=xx_data_get_u32(header+12, 4, 0, false),want=(16+sz+l->size-1)/l->size;if(xx_data_get_u64(header, 8, 0, false)!=ov||xx_data_get_u16(header+8, 2, 0, false)||xx_data_get_u16(header+10, 2, 0, false)!=4||!pages||pages!=want||pages>l->last-ov+1||sz<=l->size/2)return false;for(uint64_t j=0;j<pages;++j){if(l->seen[ov+j])return false;l->seen[ov+j]=1;}l->overflows+=pages;if(!blob_add(l->f,l->s,b,"overflow-value",o+16,sz))return false;}else if(!blob_add(l->f,l->s,b,"value",value,sz))return false;}}
 return sum==l->size-upper;}
static bool pm_parse(Abstractformat *f,pm_stream *s,xx_pd_struct *pd){memory_blob b;lm_state l;uint64_t size,selected,min,minn;bool ok=false;if(!blob_load(f,&b,pd))return false;xx_mem_zero(&l,sizeof(l));l.f=f;l.s=s;l.b=&b;BLOB_NEED(b.n>=8192);size=xx_data_get_u32(b.p+40, 4, 0, false);BLOB_NEED(size>=512&&size<=32768&&!(size&(size-1))&&!(b.n%size)&&meta(&b,0,size)&&meta(&b,size,size));uint64_t t0=xx_data_get_u64(b.p+144, 8, 0, false),t1=xx_data_get_u64(b.p+(size_t)size+144, 8, 0, false);BLOB_NEED(t0!=t1);selected=t1>t0?size:0;const uint8_t *m=b.p+(size_t)selected;uint64_t txn=xx_data_get_u64(m+144, 8, 0, false);BLOB_NEED((txn&1)==selected/size&&xx_data_get_u64(m+32, 8, 0, false)==xx_data_get_u64(b.p+(size_t)(selected?0:size)+32, 8, 0, false)&&xx_data_get_u16(m+46, 2, 0, false)==0&&container_wire_zero(&b,selected+48,32)&&xx_data_get_u64(m+80, 8, 0, false)==UINT64_MAX&&xx_data_get_u32(m+88, 4, 0, false)==0&&xx_data_get_u16(m+92, 2, 0, false)==0);unsigned depth=xx_data_get_u16(m+94, 2, 0, false);l.last=xx_data_get_u64(m+136, 8, 0, false);l.size=size;BLOB_NEED(l.last<=16383&&depth>=1&&depth<=32);l.seen=(uint8_t *)xx_mem_alloc((size_t)l.last+1);BLOB_NEED(l.seen);xx_mem_zero(l.seen,(size_t)l.last+1);BLOB_NEED(blob_add(f,s,&b,"meta-page-0",0,152)&&blob_add(f,s,&b,"meta-page-1",size,152)&&walk(&l,xx_data_get_u64(m+128, 8, 0, false),1,depth,&min,&minn)&&l.branches==xx_data_get_u64(m+96, 8, 0, false)&&l.leaves==xx_data_get_u64(m+104, 8, 0, false)&&l.overflows==xx_data_get_u64(m+112, 8, 0, false)&&l.entries==xx_data_get_u64(m+120, 8, 0, false));for(uint64_t pg=2;pg<=l.last;++pg)BLOB_NEED(!binary_stop(pd)&&l.seen[pg]);s->size=(int64_t)b.n;ok=true;done:xx_mem_free(l.seen);xx_mem_free(b.p);return ok;}

void xx_lmdb_data_init(xx_lmdb_data *r,xx_io_device *d,int64_t b) {if(r){xx_mem_zero(r,sizeof(*r));pm_init(&r->format,d,b,XX_FILE_TYPE_LMDB_DATA,"bin");}}
xx_lmdb_data *xx_lmdb_data_create(xx_io_device *d,int64_t b) {xx_lmdb_data *r=(xx_lmdb_data *)xx_mem_alloc(sizeof(*r));if(r)xx_lmdb_data_init(r,d,b);return r;}
void xx_lmdb_data_destroy(xx_lmdb_data *r) {if(r)xx_format_cleanup_extra_parameters(&r->format);}
void xx_lmdb_data_free(xx_lmdb_data *r) {if(r){xx_lmdb_data_destroy(r);xx_mem_free(r);}}
bool xx_lmdb_data_check_is_valid(Abstractformat *f,xx_pd_struct *pd) {return pm_valid(f,pd);}
bool xx_lmdb_data_handle_base_info(Abstractformat *f,xx_pd_struct *pd) {return pm_handle(f,pd);}
