/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/simh_disk/xx_simh_disk.h"

XX_FORMAT_DEFINE_READER_ADAPTER(simh_disk, XX_FILE_TYPE_SIMH_DISK,
    xx_simh_disk_create(device, 0), xx_simh_disk_free, XX_READER_TYPE_FILL_UNKNOWN)

