/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/amiga_pfs/xx_amiga_pfs.h"

XX_FORMAT_DEFINE_READER_ADAPTER(amiga_pfs, XX_FILE_TYPE_AMIGA_PFS,
    xx_amiga_pfs_create(device, 0), xx_amiga_pfs_free, XX_READER_TYPE_FILL_UNKNOWN)

