/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 */

/* xx_diskdupe_extractor.c - search raw data for DiskDupe.
 *
 * Scans for:
 *   4D 53 44 20 49 6D 61 67 65 20 56 65 72 73 69 6F 6E 20 31 20 1A at +0  ("MSD Image Version 1 .")
 * Offset 0 is always tried as well.
 * Each candidate must be accepted by the diskdupe reader, which also measures it,
 * and named by the detector, both on a view that starts at the candidate.
 * See xx_format_extractor_engine.h.
 *
 * GENERATED by gen_extractors.py from the detector's prefilters.
 */

#include "../xx_format_extractor_engine.h"
#include "xxfclib/formats/diskdupe/xx_diskdupe.h"

static const uint8_t k_anchor0[] = { 0x4D, 0x53, 0x44, 0x20, 0x49, 0x6D, 0x61, 0x67, 0x65, 0x20, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6F, 0x6E, 0x20, 0x31, 0x20, 0x1A };

static const xx_format_search_anchor k_anchors[] = {
    { k_anchor0, sizeof(k_anchor0), 0U },
};

static const xx_file_type_t k_types[] = { XX_FILE_TYPE_DISKDUPE };

static Abstractformat *xx_diskdupe_search_open(xx_io_device *window) {
    xx_diskdupe *reader = xx_diskdupe_create(window, 0);
    return reader ? &reader->format : NULL;
}

static void xx_diskdupe_search_close(Abstractformat *format) {
    /* The format is the first member, so this is the reader itself. */
    xx_diskdupe_free((xx_diskdupe *)format);
}

static const xx_format_search_desc k_desc = {
    k_types, sizeof(k_types) / sizeof(k_types[0]),
    k_anchors, sizeof(k_anchors) / sizeof(k_anchors[0]),
    xx_diskdupe_search_open, xx_diskdupe_search_close
};

static xx_format_search_state *xx_diskdupe_create_format_search(
    xx_format_extractor *self, xx_io_device *device, const xx_list_s *options,
    xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_create(&k_desc, device, options, pd);
}

static const xx_format_search_info *xx_diskdupe_get_current_format_info(
    xx_format_extractor *self, xx_format_search_state *state) {
    (void)self;
    return xx_format_search_current(state);
}

static bool xx_diskdupe_format_search_find_next(xx_format_extractor *self,
                                          xx_format_search_state *state,
                                          xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_find_next(state, pd);
}

static void xx_diskdupe_free_format_search(xx_format_extractor *self,
                                     xx_format_search_state *state) {
    (void)self;
    xx_format_search_free(state);
}

xx_format_extractor xx_diskdupe_extractor = {
    xx_diskdupe_create_format_search,
    xx_diskdupe_get_current_format_info,
    xx_diskdupe_format_search_find_next,
    xx_diskdupe_free_format_search
};
