/* SPDX-License-Identifier: MIT. Checked Android resource wire types. */
#ifndef XX_ANDROID_WIRE_H
#define XX_ANDROID_WIRE_H
typedef struct aw_chunk {uint16_t type,header;uint64_t at,end;} aw_chunk;
static bool aw_read(nh_blob *b,uint64_t at,uint64_t end,aw_chunk *c) {uint32_t n;if(!eh_span(at,8,end) || !nh_span(b,at,8)) return false;c->at=at;c->type=pm_le16(b->p+(size_t)at);c->header=pm_le16(b->p+(size_t)at+2);n=pm_le32(b->p+(size_t)at+4);if(c->header<8 || c->header>n || (n&3) || !eh_span(at,n,end) || !nh_span(b,at,n)) return false;c->end=at+n;return true;}
static bool aw_ref(uint32_t i,uint32_t count,bool nullable) {return i<count || (nullable && i==0xffffffffU);}
static bool aw_utf16(nh_blob *b,uint64_t at,uint64_t units) {uint64_t i;if(units>65536 || !nh_span(b,at,units*2)) return false;for(i=0;i<units;++i) {uint16_t c=pm_le16(b->p+(size_t)(at+i*2));if(c>=0xd800 && c<=0xdbff) {if(++i==units) return false;c=pm_le16(b->p+(size_t)(at+i*2));if(c<0xdc00 || c>0xdfff) return false;}else if(c>=0xdc00 && c<=0xdfff) return false;}return true;}
static bool aw_length(nh_blob *b,uint64_t *at,uint64_t end,bool utf8,uint64_t *n) {if(!eh_span(*at,utf8 ? 1U:2U,end)) return false;if(utf8) {*n=b->p[(size_t)(*at)++];if(*n&128) {if(*at>=end) return false;*n=((*n&127)<<8)|b->p[(size_t)(*at)++];}}else {*n=pm_le16(b->p+(size_t)*at);*at+=2;if(*n&32768) {if(!eh_span(*at,2,end)) return false;*n=((*n&32767)<<16)|pm_le16(b->p+(size_t)*at);*at+=2;}}return *n<=65536;}
static bool aw_pool(nh_blob *b,aw_chunk *c,uint32_t *count) {uint64_t at=c->at,i,table,start,limit,n,p,units,bytes;uint32_t styles,flags,styleStart;if(c->type!=1 || c->header!=28 || c->end-at<28) return false;*count=pm_le32(b->p+(size_t)at+8);styles=pm_le32(b->p+(size_t)at+12);flags=pm_le32(b->p+(size_t)at+16);start=pm_le32(b->p+(size_t)at+20);styleStart=pm_le32(b->p+(size_t)at+24);table=28+(uint64_t)*count*4;if(*count>4096 || styles || styleStart || (flags&~257U) || start<table || !eh_span(at,table,c->end) || !eh_span(at,start,c->end)) return false;limit=c->end;n=c->end-at-start;
    for(i=0;i<*count;++i) {uint32_t offset=pm_le32(b->p+(size_t)(at+28+i*4));if(offset>=n) return false;p=at+start+offset;if(!aw_length(b,&p,limit,(flags&256)!=0,&units)) return false;if(flags&256) {uint64_t actual=0;if(!aw_length(b,&p,limit,true,&bytes) || !eh_span(p,bytes+1,limit) || b->p[(size_t)(p+bytes)] || !ec_utf(b,p,bytes)) return false;for(uint64_t j=0;j<bytes;++j) {uint8_t a=b->p[(size_t)(p+j)];if((a&192)!=128) actual+=a>=240 ? 2U:1U;}if(actual!=units) return false;}else if(!eh_span(p,units*2+2,limit) || pm_le16(b->p+(size_t)(p+units*2)) || !aw_utf16(b,p,units)) return false;}
    return true;
}
static bool aw_value(nh_blob *b,uint64_t at,uint64_t end,uint32_t strings) {uint8_t t;if(!eh_span(at,8,end) || !nh_span(b,at,8) || pm_le16(b->p+(size_t)at)!=8 || b->p[(size_t)at+2]) return false;t=b->p[(size_t)at+3];return t<=8 ? (t!=3 || aw_ref(pm_le32(b->p+(size_t)at+4),strings,false)):((t>=16 && t<=18) || (t>=28 && t<=31));}
#endif
