/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/nowcompress/xx_nowcompress.h"

XX_FORMAT_DEFINE_READER_ADAPTER(nowcompress, XX_FILE_TYPE_NOWCOMPRESS,
    xx_nowcompress_create(device, 0), xx_nowcompress_free, XX_READER_TYPE_FILL_UNKNOWN)

