/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/maxis_far_archive/xx_maxis_far_archive.h"

XX_FORMAT_DEFINE_READER_ADAPTER(maxis_far_archive, XX_FILE_TYPE_MAXIS_FAR_ARCHIVE,
    xx_maxis_far_archive_create(device, 0), xx_maxis_far_archive_free, XX_READER_TYPE_FILL_UNKNOWN)

