/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/f2fs/xx_f2fs.h"

XX_FORMAT_DEFINE_READER_ADAPTER(f2fs, XX_FILE_TYPE_F2FS,
    xx_f2fs_create(device, 0), xx_f2fs_free, XX_READER_TYPE_FILL_UNKNOWN)

