/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/focusdrive/xx_focusdrive.h"

XX_FORMAT_DEFINE_READER_ADAPTER(focusdrive, XX_FILE_TYPE_FOCUSDRIVE,
    xx_focusdrive_create(device, 0), xx_focusdrive_free, XX_READER_TYPE_FILL_UNKNOWN)

