#!/usr/bin/env python3
"""Generate one C reader wrapper per Detect It Easy tracker/music label.

The authoritative recognition rules stay in Binary/audio.1.sg.  The generated
readers delegate to the shared DIE-backed reader, which matches the format ID
recorded when the original rule runs.  This keeps the original rule order and
shared JavaScript state intact while giving each format its own C file.
"""

from __future__ import annotations

import argparse
import ast
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parent
LIBRARY = ROOT.parents[2]
PUBLIC = LIBRARY / "include" / "xxfclib" / "formats" / "die_music"
RULE = LIBRARY / "src" / "die_engine" / "audio_db" / "Binary" / "audio.1.sg"
RULE_NAME = "Binary/audio.1.sg"
EXPECTED_COUNT = 408
FIRST_FILE_TYPE = 1600
MARKER = re.compile(r"//fmt\[([A-Z][A-Z0-9_]*)\]")
ASSIGNMENT = re.compile(r"\b(?:sName|sname)\s*=\s*")
HEURISTIC_START = "if(X.isHeuristicScan()) { //parallel block"


def first_string_after_assignment(line: str, marker_start: int, fallback: str) -> str:
    """Return the first JS string literal, used only as a display hint."""
    prefix = line[:marker_start]
    match = ASSIGNMENT.search(prefix)
    if match is None:
        raise ValueError(f"format marker lacks a name assignment: {line.strip()}")
    pos = match.end()
    while pos < len(prefix) and prefix[pos].isspace():
        pos += 1
    if pos >= len(prefix) or prefix[pos] not in ("'", '"'):
        # A few names are constructed from variables set by the rule.  The
        # runtime DIE result owns the finished human-readable name.
        return fallback
    quote = prefix[pos]
    end = pos + 1
    escaped = False
    while end < len(prefix):
        ch = prefix[end]
        if escaped:
            escaped = False
        elif ch == "\\":
            escaped = True
        elif ch == quote:
            return ast.literal_eval(prefix[pos : end + 1])
        end += 1
    raise ValueError(f"unterminated format name: {line.strip()}")


def c_literal(value: str) -> str:
    """ASCII-only C literal containing the UTF-8 bytes of value."""
    result = ['"']
    for byte in value.encode("utf-8"):
        if byte == 34:
            result.append('\\"')
        elif byte == 92:
            result.append("\\\\")
        elif 32 <= byte <= 126:
            result.append(chr(byte))
        else:
            result.append(f"\\{byte:03o}")
    result.append('"')
    return "".join(result)


def records_from_rule() -> list[dict[str, object]]:
    records: list[dict[str, object]] = []
    seen_ids: set[str] = set()
    seen_slugs: set[str] = set()
    heuristic = False
    for line_number, line in enumerate(RULE.read_text(encoding="utf-8").splitlines(), 1):
        if HEURISTIC_START in line:
            heuristic = True
        for marker in MARKER.finditer(line):
            format_id = marker.group(1)
            slug = format_id.lower()
            if format_id in seen_ids or slug in seen_slugs:
                raise ValueError(f"duplicate format ID or slug: {format_id}")
            seen_ids.add(format_id)
            seen_slugs.add(slug)
            records.append(
                {
                    "format_id": format_id,
                    "slug": slug,
                    "source_line": line_number,
                    "heuristic": heuristic,
                    "display_name": first_string_after_assignment(line, marker.start(), format_id),
                    "file_type": FIRST_FILE_TYPE + len(records),
                }
            )
    if len(records) != EXPECTED_COUNT:
        raise ValueError(f"expected {EXPECTED_COUNT} labels; found {len(records)}")
    if sum(bool(record["heuristic"]) for record in records) != 21:
        raise ValueError("DIE heuristic rule boundary changed; review generated layout")
    return records


def wrapper(record: dict[str, object]) -> str:
    slug = str(record["slug"])
    fmt = str(record["format_id"])
    display = str(record["display_name"])
    number = int(record["file_type"])
    line = int(record["source_line"])
    heuristic = "true" if record["heuristic"] else "false"
    return f"""/* Generated by generate_die_music_files.py; do not edit. */
/* SPDX-License-Identifier: MIT */
#include \"xxfclib/formats/die_music/xx_die_music.h\"
#include \"../../xx_format_extractor_engine.h\"
#include \"../../xx_format_abstract_extractor_adapter.h\"

const xx_die_music_descriptor xx_die_music_{slug}_descriptor = {{
    {c_literal(fmt)},
    {c_literal(display)},
    {c_literal(RULE_NAME)},
    {line}U,
    {heuristic},
    XX_FILE_TYPE_DIE_MUSIC_{fmt}
}};

XXFC_API Abstractformat *xx_die_music_{slug}_create(xx_io_device *device, int64_t base)
{{
    return xx_die_music_reader_create(&xx_die_music_{slug}_descriptor, device, base);
}}

XXFC_API void xx_die_music_{slug}_free(void *reader)
{{
    xx_die_music_reader_free(reader);
}}

static const xx_file_type_t xx_die_music_{slug}_types[] = {{
    XX_FILE_TYPE_DIE_MUSIC_{fmt}
}};

static Abstractformat *xx_die_music_{slug}_open(xx_io_device *window)
{{
    return xx_die_music_{slug}_create(window, 0);
}}

static void xx_die_music_{slug}_close(Abstractformat *format)
{{
    xx_die_music_{slug}_free(format);
}}

static const xx_format_search_desc xx_die_music_{slug}_search_desc = {{
    xx_die_music_{slug}_types, 1U, NULL, 0U,
    xx_die_music_{slug}_open, xx_die_music_{slug}_close, true
}};

static xx_format_search_state *xx_die_music_{slug}_create_search(
    xx_format_extractor *self, xx_io_device *device,
    const xx_list_s *options, xx_pd_struct *pd)
{{
    (void)self;
    return xx_format_search_create(&xx_die_music_{slug}_search_desc, device, options, pd);
}}

static const xx_format_search_info *xx_die_music_{slug}_current(
    xx_format_extractor *self, xx_format_search_state *state)
{{
    (void)self;
    return xx_format_search_current(state);
}}

static bool xx_die_music_{slug}_next(
    xx_format_extractor *self, xx_format_search_state *state, xx_pd_struct *pd)
{{
    (void)self;
    return xx_format_search_find_next(state, pd);
}}

static void xx_die_music_{slug}_free_search(
    xx_format_extractor *self, xx_format_search_state *state)
{{
    (void)self;
    xx_format_search_free(state);
}}

xx_format_extractor xx_die_music_{slug}_extractor = {{
    xx_die_music_{slug}_create_search,
    xx_die_music_{slug}_current,
    xx_die_music_{slug}_next,
    xx_die_music_{slug}_free_search
}};

XX_FORMAT_DEFINE_ABSTRACT_EXTRACTOR(
    die_music_{slug}, xx_die_music_{slug}_search_desc)
"""


def outputs(records: list[dict[str, object]]) -> dict[Path, str]:
    result: dict[Path, str] = {}
    manifest = {"source": RULE_NAME, "format_count": len(records), "formats": records}
    result[ROOT / "manifest.json"] = json.dumps(manifest, ensure_ascii=False, indent=2) + "\n"

    registry = ["/* Generated by generate_die_music_files.py; do not edit. */"]
    enums = ["/* Generated by generate_die_music_files.py; do not edit. */"]
    type_names = ["/* Generated by generate_die_music_files.py; do not edit. */"]
    cli_rows = ["/* Generated by generate_die_music_files.py; do not edit. */"]
    extractor_decls = ["/* Generated by generate_die_music_files.py; do not edit. */"]
    extractor_rows = ["/* Generated by generate_die_music_files.py; do not edit. */"]
    abstract_decls = ["/* Generated by generate_die_music_files.py; do not edit. */"]
    cmake = ["# Generated by generate_die_music_files.py; do not edit.", "set(XX_DIE_MUSIC_SOURCES"]
    for record in records:
        fmt = str(record["format_id"])
        slug = str(record["slug"])
        name = c_literal(str(record["display_name"]))
        file_type = int(record["file_type"])
        registry.append(f"XX_DIE_MUSIC_ENTRY({fmt}, {slug}, {file_type}, {name})")
        enums.append(f"XX_FILE_TYPE_DIE_MUSIC_{fmt} = {file_type},")
        type_names.append(f"XX_DIE_MUSIC_TYPE_NAME(XX_FILE_TYPE_DIE_MUSIC_{fmt}, {name})")
        cli_rows.append(f"XX_DIE_MUSIC_CLI_ROW(XX_FILE_TYPE_DIE_MUSIC_{fmt}, {slug})")
        extractor_decls.append(f"extern xx_format_extractor xx_die_music_{slug}_extractor;")
        abstract_decls.extend(
            (
                f"XXFC_API bool xx_die_music_{slug}_fast_detect(xx_io_device *device, "
                "int64_t base_address, bool is_mapped);",
                f"XXFC_API int64_t xx_die_music_{slug}_size(xx_io_device *device, "
                "int64_t base_address, bool is_mapped);",
                f"XXFC_API Abstractextractor *xx_die_music_{slug}_get_abstract_extractor(void);",
            )
        )
        extractor_rows.append(
            f"{{ XX_FILE_TYPE_DIE_MUSIC_{fmt}, &xx_die_music_{slug}_extractor }},"
        )
        relative = f"src/formats/die_music/{slug}/xx_die_music_{slug}.c"
        cmake.append(f"    ${{CMAKE_CURRENT_SOURCE_DIR}}/{relative}")
        result[ROOT / slug / f"xx_die_music_{slug}.c"] = wrapper(record)
    cmake.append(")")
    result[ROOT / "xx_die_music_registry.inc"] = "\n".join(registry) + "\n"
    result[ROOT / "xx_die_music_enums.inc"] = "\n".join(enums) + "\n"
    result[PUBLIC / "xx_die_music_enums.inc"] = result[ROOT / "xx_die_music_enums.inc"]
    result[ROOT / "xx_die_music_type_names.inc"] = "\n".join(type_names) + "\n"
    result[ROOT / "xx_die_music_cli_rows.inc"] = "\n".join(cli_rows) + "\n"
    result[ROOT / "xx_die_music_extractor_decls.inc"] = "\n".join(extractor_decls) + "\n"
    result[ROOT / "xx_die_music_extractor_rows.inc"] = "\n".join(extractor_rows) + "\n"
    result[PUBLIC / "xx_die_music_abstract_extractor_decls.inc"] = "\n".join(abstract_decls) + "\n"
    result[ROOT / "xx_die_music_sources.cmake"] = "\n".join(cmake) + "\n"
    return result


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify generated files without writing")
    args = parser.parse_args()
    files = outputs(records_from_rule())
    out_of_date: list[str] = []
    if args.check:
        for path in ROOT.glob("*/xx_die_music_*.c"):
            if path not in files:
                out_of_date.append(f"unexpected generated wrapper: {path}")
    for path, content in files.items():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                out_of_date.append(str(path))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    if out_of_date:
        raise SystemExit("Generated DIE music files are stale:\n" + "\n".join(out_of_date))
    print(f"{'Checked' if args.check else 'Generated'} {len(files)} files for {EXPECTED_COUNT} DIE music labels")


if __name__ == "__main__":
    main()
