/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/hxc_logic_analyzer/xx_hxc_logic_analyzer.h"

XX_FORMAT_DEFINE_READER_ADAPTER(hxc_logic_analyzer, XX_FILE_TYPE_HXC_LOGIC_ANALYZER,
    xx_hxc_logic_analyzer_create(device, 0), xx_hxc_logic_analyzer_free, XX_READER_TYPE_FILL_UNKNOWN)

