/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 */

/* xx_bvrp_extractor.c - search raw data for BVRP.
 *
 * Scans for:
 *   42 56 52 50 20 53 6F 66 74 77 61 72 65 at +10  ("BVRP Software")
 * Offset 0 is always tried as well.
 * Each candidate must be accepted by the bvrp reader, which also measures it,
 * and named by the detector, both on a view that starts at the candidate.
 * See xx_format_extractor_engine.h.
 *
 * GENERATED by gen_extractors.py from the detector's prefilters.
 */

#include "../xx_format_extractor_engine.h"
#include "xxfclib/formats/bvrp/xx_bvrp.h"

static const uint8_t k_anchor0[] = { 0x42, 0x56, 0x52, 0x50, 0x20, 0x53, 0x6F, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65 };

static const xx_format_search_anchor k_anchors[] = {
    { k_anchor0, sizeof(k_anchor0), 10U },
};

static const xx_file_type_t k_types[] = { XX_FILE_TYPE_BVRP };

static Abstractformat *xx_bvrp_search_open(xx_io_device *window) {
    xx_bvrp *reader = xx_bvrp_create(window, 0);
    return reader ? &reader->format : NULL;
}

static void xx_bvrp_search_close(Abstractformat *format) {
    /* The format is the first member, so this is the reader itself. */
    xx_bvrp_free((xx_bvrp *)format);
}

static const xx_format_search_desc k_desc = {
    k_types, sizeof(k_types) / sizeof(k_types[0]),
    k_anchors, sizeof(k_anchors) / sizeof(k_anchors[0]),
    xx_bvrp_search_open, xx_bvrp_search_close
};

static xx_format_search_state *xx_bvrp_create_format_search(
    xx_format_extractor *self, xx_io_device *device, const xx_list_s *options,
    xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_create(&k_desc, device, options, pd);
}

static const xx_format_search_info *xx_bvrp_get_current_format_info(
    xx_format_extractor *self, xx_format_search_state *state) {
    (void)self;
    return xx_format_search_current(state);
}

static bool xx_bvrp_format_search_find_next(xx_format_extractor *self,
                                          xx_format_search_state *state,
                                          xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_find_next(state, pd);
}

static void xx_bvrp_free_format_search(xx_format_extractor *self,
                                     xx_format_search_state *state) {
    (void)self;
    xx_format_search_free(state);
}

xx_format_extractor xx_bvrp_extractor = {
    xx_bvrp_create_format_search,
    xx_bvrp_get_current_format_info,
    xx_bvrp_format_search_find_next,
    xx_bvrp_free_format_search
};
