#!/usr/bin/env python3
"""Generate the built-in Detect It Easy audio signature bundle.

The sources under audio_db are the upstream Detect It Easy rules, retained with
their MIT license.  This script embeds raw-DEFLATE data so the library does not
need an external database path at runtime.
"""

from pathlib import Path
import re
import zlib


ROOT = Path(__file__).resolve().parent
DB = ROOT / "audio_db"
OUT = ROOT / "xx_die_audio_bundle.inc"
HELPERS = (
    "_init", "_debug", "_runtime_helpers", "language", "read",
    "chunkparsers", "soundchips", "bytecodeparsers", "duration",
    "vgmcodingutils",
)

# The upstream script stores all 408 tracker families in one long detect()
# function. Attach each source //fmt[ID] marker to the corresponding sName
# assignment without changing upstream source text or public result wording.
# Wrapping only the RHS preserves if/case control flow on the four lines that
# assign a name conditionally without braces. The callback returns the same
# string and records it with the tag so an unmarked later branch cannot inherit
# an ID from an unsuccessful marked branch.
MUSIC_MARKER = re.compile(
    rb"(?m)^([^\r\n]*?\b(?:sName|sname)[ \t]*=[ \t]*)"
    rb"([^;\r\n]+)(;[ \t]*//fmt\[([A-Z0-9_]+)\][^\r\n]*)(\r?)$"
)


def tag_music_rule(data: bytes) -> bytes:
    markers = re.findall(rb"//fmt\[([^]]+)\]", data)
    matches = list(MUSIC_MARKER.finditer(data))
    ids = [match.group(4) for match in matches]
    if len(markers) != 408 or len(matches) != 408 or len(set(ids)) != 408:
        raise ValueError("audio.1.sg format markers changed; review instrumentation")
    if sorted(markers) != sorted(ids):
        raise ValueError("audio.1.sg contains unmatched format markers")

    def replace(match: re.Match[bytes]) -> bytes:
        prefix, expression, suffix, fmt_id, newline = match.groups()
        return (prefix + b'_musicFmt("' + fmt_id + b'", ' + expression +
                b')' + suffix + newline)

    return MUSIC_MARKER.sub(replace, data)


def main() -> None:
    paths = [DB / name for name in HELPERS]
    paths.append(DB / "Binary" / "_init")
    paths.extend(sorted((DB / "Binary").glob("audio*.sg")))
    lines = [
        "/* Generated by generate_audio_bundle.py from audio_db; do not edit. */",
        "typedef struct {",
        "    const char *path;",
        "    const unsigned char *deflated;",
        "    size_t compressed_size;",
        "    size_t original_size;",
        "    XFileType file_type;",
        "} xx_die_audio_entry;",
    ]
    rows = []
    for index, path in enumerate(paths):
        data = path.read_bytes()
        if path.name == "audio.1.sg":
            data = tag_music_rule(data)
        compressor = zlib.compressobj(level=9, wbits=-15)
        packed = compressor.compress(data) + compressor.flush()
        relpath = path.relative_to(DB).as_posix()
        lines.append(f"static const unsigned char xx_die_audio_{index}[] = {{")
        for offset in range(0, len(packed), 20):
            chunk = packed[offset:offset + 20]
            lines.append("    " + ", ".join(f"0x{value:02x}" for value in chunk) + ",")
        lines.append("};")
        file_type = "XFT_BINARY" if relpath.startswith("Binary/") else "XFT_UNKNOWN"
        rows.append(
            f'    {{"{relpath}", xx_die_audio_{index}, '
            f'sizeof(xx_die_audio_{index}), {len(data)}U, {file_type}}},'
        )
    lines.append("static const xx_die_audio_entry xx_die_audio_entries[] = {")
    lines.extend(rows)
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n", encoding="ascii")
    print(f"Bundled {len(paths)} scripts in {OUT}")


if __name__ == "__main__":
    main()
