/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/microsoft_lit/xx_microsoft_lit.h"

XX_FORMAT_DEFINE_READER_ADAPTER(microsoft_lit, XX_FILE_TYPE_MICROSOFT_LIT,
    xx_microsoft_lit_create(device, 0), xx_microsoft_lit_free, XX_READER_TYPE_FILL_UNKNOWN)

