/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/acorn_adfs/xx_acorn_adfs.h"

XX_FORMAT_DEFINE_READER_ADAPTER(adfs, XX_FILE_TYPE_ADFS,
    xx_acorn_adfs_create(device, 0), xx_acorn_adfs_free, XX_READER_TYPE_FILL_UNKNOWN)

