/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/ue2_games/xx_ue2_games.h"

XX_FORMAT_DEFINE_READER_ADAPTER(bruns_media, XX_FILE_TYPE_BRUNS_MEDIA,
    xx_ue2_games_create(device, 0, XX_FILE_TYPE_BRUNS_MEDIA), xx_ue2_games_free, XX_READER_TYPE_FORCE)

XX_FORMAT_DEFINE_READER_ADAPTER(fallout_dat, XX_FILE_TYPE_FALLOUT_DAT,
    xx_ue2_games_create(device, 0, XX_FILE_TYPE_FALLOUT_DAT), xx_ue2_games_free, XX_READER_TYPE_FORCE)

XX_FORMAT_DEFINE_READER_ADAPTER(live_maker_gal, XX_FILE_TYPE_LIVE_MAKER_GAL,
    xx_ue2_games_create(device, 0, XX_FILE_TYPE_LIVE_MAKER_GAL), xx_ue2_games_free, XX_READER_TYPE_FORCE)

XX_FORMAT_DEFINE_READER_ADAPTER(rpg_maker_mv, XX_FILE_TYPE_RPG_MAKER_MV,
    xx_ue2_games_create(device, 0, XX_FILE_TYPE_RPG_MAKER_MV), xx_ue2_games_free, XX_READER_TYPE_FORCE)

XX_FORMAT_DEFINE_READER_ADAPTER(smile_game_pack, XX_FILE_TYPE_SMILE_GAME_PACK,
    xx_ue2_games_create(device, 0, XX_FILE_TYPE_SMILE_GAME_PACK), xx_ue2_games_free, XX_READER_TYPE_FORCE)

XX_FORMAT_DEFINE_READER_ADAPTER(unreal_pak, XX_FILE_TYPE_UNREAL_PAK,
    xx_ue2_games_create(device, 0, XX_FILE_TYPE_UNREAL_PAK), xx_ue2_games_free, XX_READER_TYPE_FORCE)

XX_FORMAT_DEFINE_READER_ADAPTER(utage_media, XX_FILE_TYPE_UTAGE_MEDIA,
    xx_ue2_games_create(device, 0, XX_FILE_TYPE_UTAGE_MEDIA), xx_ue2_games_free, XX_READER_TYPE_FORCE)

XX_FORMAT_DEFINE_READER_ADAPTER(ycg_image, XX_FILE_TYPE_YCG_IMAGE,
    xx_ue2_games_create(device, 0, XX_FILE_TYPE_YCG_IMAGE), xx_ue2_games_free, XX_READER_TYPE_FORCE)

