/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/bgi2/xx_bgi2.h"

XX_FORMAT_DEFINE_READER_ADAPTER(bgi2, XX_FILE_TYPE_BGI2,
    xx_bgi2_create(device, 0), xx_bgi2_free, XX_READER_TYPE_FILL_UNKNOWN)

