/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 */

#ifndef XXFCLIB_FORMAT_MACHO_H
#define XXFCLIB_FORMAT_MACHO_H

#include "xxfclib/formats/xx_format.h"

#ifdef __cplusplus
extern "C" {
#endif

#define XX_MACHO_MAGIC_32 UINT32_C(0xfeedface)
#define XX_MACHO_CIGAM_32 UINT32_C(0xcefaedfe)
#define XX_MACHO_MAGIC_64 UINT32_C(0xfeedfacf)
#define XX_MACHO_CIGAM_64 UINT32_C(0xcffaedfe)

#define XX_MACHO_FILE_OBJECT      UINT32_C(1)
#define XX_MACHO_FILE_EXECUTE     UINT32_C(2)
#define XX_MACHO_FILE_FVMLIB      UINT32_C(3)
#define XX_MACHO_FILE_CORE        UINT32_C(4)
#define XX_MACHO_FILE_PRELOAD     UINT32_C(5)
#define XX_MACHO_FILE_DYLIB       UINT32_C(6)
#define XX_MACHO_FILE_DYLINKER    UINT32_C(7)
#define XX_MACHO_FILE_BUNDLE      UINT32_C(8)
#define XX_MACHO_FILE_DYLIB_STUB  UINT32_C(9)
#define XX_MACHO_FILE_DSYM        UINT32_C(10)
#define XX_MACHO_FILE_KEXT_BUNDLE UINT32_C(11)
#define XX_MACHO_FILE_FILESET     UINT32_C(12)
#define XX_MACHO_FILE_GPU_EXECUTE UINT32_C(13)
#define XX_MACHO_FILE_GPU_DYLIB   UINT32_C(14)

#define XX_MACHO_LOAD_SEGMENT                  UINT32_C(0x00000001)
#define XX_MACHO_LOAD_SYMTAB                   UINT32_C(0x00000002)
#define XX_MACHO_LOAD_SYMSEG                   UINT32_C(0x00000003)
#define XX_MACHO_LOAD_THREAD                   UINT32_C(0x00000004)
#define XX_MACHO_LOAD_UNIXTHREAD               UINT32_C(0x00000005)
#define XX_MACHO_LOAD_FVMLIB                   UINT32_C(0x00000006)
#define XX_MACHO_LOAD_ID_FVMLIB                UINT32_C(0x00000007)
#define XX_MACHO_LOAD_IDENT                    UINT32_C(0x00000008)
#define XX_MACHO_LOAD_FVMFILE                  UINT32_C(0x00000009)
#define XX_MACHO_LOAD_PREPAGE                  UINT32_C(0x0000000a)
#define XX_MACHO_LOAD_DYSYMTAB                 UINT32_C(0x0000000b)
#define XX_MACHO_LOAD_DYLIB                    UINT32_C(0x0000000c)
#define XX_MACHO_LOAD_ID_DYLIB                 UINT32_C(0x0000000d)
#define XX_MACHO_LOAD_DYLINKER                 UINT32_C(0x0000000e)
#define XX_MACHO_LOAD_ID_DYLINKER              UINT32_C(0x0000000f)
#define XX_MACHO_LOAD_PREBOUND_DYLIB           UINT32_C(0x00000010)
#define XX_MACHO_LOAD_ROUTINES                 UINT32_C(0x00000011)
#define XX_MACHO_LOAD_SUB_FRAMEWORK            UINT32_C(0x00000012)
#define XX_MACHO_LOAD_SUB_UMBRELLA             UINT32_C(0x00000013)
#define XX_MACHO_LOAD_SUB_CLIENT               UINT32_C(0x00000014)
#define XX_MACHO_LOAD_SUB_LIBRARY              UINT32_C(0x00000015)
#define XX_MACHO_LOAD_TWOLEVEL_HINTS           UINT32_C(0x00000016)
#define XX_MACHO_LOAD_PREBIND_CKSUM            UINT32_C(0x00000017)
#define XX_MACHO_LOAD_WEAK_DYLIB               UINT32_C(0x80000018)
#define XX_MACHO_LOAD_SEGMENT_64               UINT32_C(0x00000019)
#define XX_MACHO_LOAD_ROUTINES_64              UINT32_C(0x0000001a)
#define XX_MACHO_LOAD_UUID                     UINT32_C(0x0000001b)
#define XX_MACHO_LOAD_RPATH                    UINT32_C(0x8000001c)
#define XX_MACHO_LOAD_CODE_SIGNATURE           UINT32_C(0x0000001d)
#define XX_MACHO_LOAD_SEGMENT_SPLIT_INFO       UINT32_C(0x0000001e)
#define XX_MACHO_LOAD_REEXPORT_DYLIB           UINT32_C(0x8000001f)
#define XX_MACHO_LOAD_LAZY_DYLIB               UINT32_C(0x00000020)
#define XX_MACHO_LOAD_ENCRYPTION_INFO          UINT32_C(0x00000021)
#define XX_MACHO_LOAD_DYLD_INFO                UINT32_C(0x00000022)
#define XX_MACHO_LOAD_DYLD_INFO_ONLY           UINT32_C(0x80000022)
#define XX_MACHO_LOAD_UPWARD_DYLIB             UINT32_C(0x80000023)
#define XX_MACHO_LOAD_VERSION_MIN_MACOSX       UINT32_C(0x00000024)
#define XX_MACHO_LOAD_VERSION_MIN_IPHONEOS     UINT32_C(0x00000025)
#define XX_MACHO_LOAD_FUNCTION_STARTS          UINT32_C(0x00000026)
#define XX_MACHO_LOAD_DYLD_ENVIRONMENT         UINT32_C(0x00000027)
#define XX_MACHO_LOAD_MAIN                     UINT32_C(0x80000028)
#define XX_MACHO_LOAD_DATA_IN_CODE             UINT32_C(0x00000029)
#define XX_MACHO_LOAD_SOURCE_VERSION           UINT32_C(0x0000002a)
#define XX_MACHO_LOAD_DYLIB_CODE_SIGN_DRS      UINT32_C(0x0000002b)
#define XX_MACHO_LOAD_ENCRYPTION_INFO_64       UINT32_C(0x0000002c)
#define XX_MACHO_LOAD_LINKER_OPTION            UINT32_C(0x0000002d)
#define XX_MACHO_LOAD_LINKER_OPTIMIZATION_HINT UINT32_C(0x0000002e)
#define XX_MACHO_LOAD_VERSION_MIN_TVOS         UINT32_C(0x0000002f)
#define XX_MACHO_LOAD_VERSION_MIN_WATCHOS      UINT32_C(0x00000030)
#define XX_MACHO_LOAD_NOTE                     UINT32_C(0x00000031)
#define XX_MACHO_LOAD_BUILD_VERSION            UINT32_C(0x00000032)
#define XX_MACHO_LOAD_DYLD_EXPORTS_TRIE        UINT32_C(0x80000033)
#define XX_MACHO_LOAD_DYLD_CHAINED_FIXUPS      UINT32_C(0x80000034)
#define XX_MACHO_LOAD_FILESET_ENTRY            UINT32_C(0x80000035)
#define XX_MACHO_LOAD_ATOM_INFO                UINT32_C(0x00000036)
#define XX_MACHO_LOAD_TARGET_TRIPLE             UINT32_C(0x00000039)

/** Mach-O structures exposed through Abstractformat's data-structure stream. */
typedef enum xx_macho_data_struct_id_e {
    XX_MACHO_DATA_STRUCT_UNKNOWN = 0,
    XX_MACHO_DATA_STRUCT_MACH_HEADER,
    XX_MACHO_DATA_STRUCT_MACH_HEADER_64,
    XX_MACHO_DATA_STRUCT_LOAD_COMMAND,
    XX_MACHO_DATA_STRUCT_SEGMENT_COMMAND,
    XX_MACHO_DATA_STRUCT_SEGMENT_COMMAND_64,
    XX_MACHO_DATA_STRUCT_SECTION,
    XX_MACHO_DATA_STRUCT_SECTION_64,
    XX_MACHO_DATA_STRUCT_DYLIB_COMMAND,
    XX_MACHO_DATA_STRUCT_DYLINKER_COMMAND,
    XX_MACHO_DATA_STRUCT_RPATH_COMMAND,
    XX_MACHO_DATA_STRUCT_SYMTAB_COMMAND,
    XX_MACHO_DATA_STRUCT_DYSYMTAB_COMMAND,
    XX_MACHO_DATA_STRUCT_UUID_COMMAND,
    XX_MACHO_DATA_STRUCT_VERSION_MIN_COMMAND,
    XX_MACHO_DATA_STRUCT_BUILD_VERSION_COMMAND,
    XX_MACHO_DATA_STRUCT_SOURCE_VERSION_COMMAND,
    XX_MACHO_DATA_STRUCT_ENTRY_POINT_COMMAND,
    XX_MACHO_DATA_STRUCT_ENCRYPTION_INFO_COMMAND,
    XX_MACHO_DATA_STRUCT_ENCRYPTION_INFO_COMMAND_64,
    XX_MACHO_DATA_STRUCT_LINKEDIT_DATA_COMMAND,
    XX_MACHO_DATA_STRUCT_DYLD_INFO_COMMAND,
    XX_MACHO_DATA_STRUCT_NLIST,
    XX_MACHO_DATA_STRUCT_NLIST_64,
    XX_MACHO_DATA_STRUCT_STRING_TABLE,
    XX_MACHO_DATA_STRUCT_INDIRECT_SYMBOL,
    XX_MACHO_DATA_STRUCT_FUNCTION_STARTS,
    XX_MACHO_DATA_STRUCT_DATA_IN_CODE,
    XX_MACHO_DATA_STRUCT_CHAINED_FIXUPS_HEADER,
    XX_MACHO_DATA_STRUCT_CHAINED_IMPORT,
    XX_MACHO_DATA_STRUCT_EXPORT,

    /* Complete thin-Mach-O load-command and fixed child layouts. */
    XX_MACHO_DATA_STRUCT_SYMSEG_COMMAND,
    XX_MACHO_DATA_STRUCT_THREAD_COMMAND,
    XX_MACHO_DATA_STRUCT_THREAD_STATE_HEADER,
    XX_MACHO_DATA_STRUCT_FVMLIB_COMMAND,
    XX_MACHO_DATA_STRUCT_FVMFILE_COMMAND,
    XX_MACHO_DATA_STRUCT_IDENT_COMMAND,
    XX_MACHO_DATA_STRUCT_PREBOUND_DYLIB_COMMAND,
    XX_MACHO_DATA_STRUCT_ROUTINES_COMMAND,
    XX_MACHO_DATA_STRUCT_ROUTINES_COMMAND_64,
    XX_MACHO_DATA_STRUCT_SUB_FRAMEWORK_COMMAND,
    XX_MACHO_DATA_STRUCT_SUB_UMBRELLA_COMMAND,
    XX_MACHO_DATA_STRUCT_SUB_CLIENT_COMMAND,
    XX_MACHO_DATA_STRUCT_SUB_LIBRARY_COMMAND,
    XX_MACHO_DATA_STRUCT_TWOLEVEL_HINTS_COMMAND,
    XX_MACHO_DATA_STRUCT_PREBIND_CKSUM_COMMAND,
    XX_MACHO_DATA_STRUCT_LINKER_OPTION_COMMAND,
    XX_MACHO_DATA_STRUCT_NOTE_COMMAND,
    XX_MACHO_DATA_STRUCT_BUILD_TOOL_VERSION,
    XX_MACHO_DATA_STRUCT_FILESET_ENTRY_COMMAND,
    XX_MACHO_DATA_STRUCT_DYLIB_MODULE,
    XX_MACHO_DATA_STRUCT_DYLIB_MODULE_64,
    XX_MACHO_DATA_STRUCT_DYLIB_TABLE_OF_CONTENTS,
    XX_MACHO_DATA_STRUCT_DYLIB_REFERENCE,
    XX_MACHO_DATA_STRUCT_RELOCATION_INFO,
    XX_MACHO_DATA_STRUCT_TWOLEVEL_HINT,
    XX_MACHO_DATA_STRUCT_CHAINED_STARTS_IN_IMAGE,
    XX_MACHO_DATA_STRUCT_CHAINED_STARTS_IN_SEGMENT,
    XX_MACHO_DATA_STRUCT_CHAINED_IMPORT_ADDEND,
    XX_MACHO_DATA_STRUCT_CHAINED_IMPORT_ADDEND64,
    XX_MACHO_DATA_STRUCT_CODE_SIGNATURE_SUPERBLOB,
    XX_MACHO_DATA_STRUCT_CODE_SIGNATURE_BLOB_INDEX,
    XX_MACHO_DATA_STRUCT_CODE_SIGNATURE_CODE_DIRECTORY,
    XX_MACHO_DATA_STRUCT_TARGET_TRIPLE_COMMAND,
    XX_MACHO_DATA_STRUCT_CHAINED_SEG_INFO_OFFSET,
    XX_MACHO_DATA_STRUCT_CHAINED_PAGE_START,
    XX_MACHO_DATA_STRUCT_CODE_SIGNATURE_BLOB,
    XX_MACHO_DATA_STRUCT_THREAD_STATE_WORD,
    XX_MACHO_DATA_STRUCT_X86_THREAD_STATE32,
    XX_MACHO_DATA_STRUCT_X86_THREAD_STATE64,
    XX_MACHO_DATA_STRUCT_ARM_THREAD_STATE32,
    XX_MACHO_DATA_STRUCT_ARM_THREAD_STATE64,
    XX_MACHO_DATA_STRUCT_PPC_THREAD_STATE32,
    XX_MACHO_DATA_STRUCT_PPC_THREAD_STATE64,
    XX_MACHO_DATA_STRUCT_CHAINED_STARTS_OFFSETS,
    XX_MACHO_DATA_STRUCT_CHAIN_START_OFFSET,
    XX_MACHO_DATA_STRUCT_CHAINED_CHAIN_START,
    XX_MACHO_DATA_STRUCT_TLV_DESCRIPTOR,
    XX_MACHO_DATA_STRUCT_TLV_DESCRIPTOR_64,
    XX_MACHO_DATA_STRUCT_CODE_SIGNATURE_SCATTER,
    XX_MACHO_DATA_STRUCT_SCATTERED_RELOCATION_INFO,
    XX_MACHO_DATA_STRUCT_CODE_SIGNATURE_REQUIREMENTS,
    XX_MACHO_DATA_STRUCT_CODE_SIGNATURE_REQUIREMENT,
    XX_MACHO_DATA_STRUCT_CHAINED_PTR_ARM64E_REBASE,
    XX_MACHO_DATA_STRUCT_CHAINED_PTR_ARM64E_BIND,
    XX_MACHO_DATA_STRUCT_CHAINED_PTR_ARM64E_AUTH_REBASE,
    XX_MACHO_DATA_STRUCT_CHAINED_PTR_ARM64E_AUTH_BIND,
    XX_MACHO_DATA_STRUCT_CHAINED_PTR_ARM64E_BIND24,
    XX_MACHO_DATA_STRUCT_CHAINED_PTR_ARM64E_AUTH_BIND24,
    XX_MACHO_DATA_STRUCT_CHAINED_PTR_64_REBASE,
    XX_MACHO_DATA_STRUCT_CHAINED_PTR_64_BIND,
    XX_MACHO_DATA_STRUCT_CHAINED_PTR_64_KERNEL_CACHE_REBASE,
    XX_MACHO_DATA_STRUCT_CHAINED_PTR_32_REBASE,
    XX_MACHO_DATA_STRUCT_CHAINED_PTR_32_BIND,
    XX_MACHO_DATA_STRUCT_CHAINED_PTR_32_CACHE_REBASE,
    XX_MACHO_DATA_STRUCT_CHAINED_PTR_32_FIRMWARE_REBASE,
    XX_MACHO_DATA_STRUCT_CHAINED_PTR_ARM64E_SHARED_CACHE_REBASE,
    XX_MACHO_DATA_STRUCT_CHAINED_PTR_ARM64E_SHARED_CACHE_AUTH_REBASE,
    XX_MACHO_DATA_STRUCT_CHAINED_PTR_ARM64E_SEGMENTED_REBASE,
    XX_MACHO_DATA_STRUCT_CHAINED_PTR_ARM64E_AUTH_SEGMENTED_REBASE,
    XX_MACHO_DATA_STRUCT_X86_FLOAT_STATE64,
    XX_MACHO_DATA_STRUCT_X86_EXCEPTION_STATE64,
    XX_MACHO_DATA_STRUCT_LAST =
        XX_MACHO_DATA_STRUCT_X86_EXCEPTION_STATE64
} xx_macho_data_struct_id_t;

typedef struct xx_macho_segment {
    char name[17];
    uint64_t virtual_address;
    uint64_t virtual_size;
    uint64_t file_offset;
    uint64_t file_size;
    uint32_t maximum_protection;
    uint32_t initial_protection;
    uint32_t section_count;
    uint32_t flags;
} xx_macho_segment;

typedef struct xx_macho {
    Abstractformat format;
    uint32_t magic;
    uint32_t cpu_type;
    uint32_t cpu_subtype;
    uint32_t macho_file_type;
    uint32_t command_count;
    uint32_t commands_size;
    uint32_t flags;
    uint32_t reserved;
    bool is_64;
    bool has_main_entry;
    uint64_t main_entry_offset;
    uint32_t segment_count;
    xx_macho_segment *segments;
} xx_macho;

typedef xx_macho xx_macho_t;
typedef xx_macho XMACHO;

XXFC_API void xx_macho_init(xx_macho *macho, xx_io_device *device,
                            int64_t base_address);
XXFC_API xx_macho *xx_macho_create(xx_io_device *device,
                                   int64_t base_address);
XXFC_API void xx_macho_destroy(xx_macho *macho);
XXFC_API void xx_macho_free(xx_macho *macho);

XXFC_API bool xx_macho_check_is_valid(Abstractformat *format,
                                      xx_pd_struct *pd);
XXFC_API bool xx_macho_handle_base_info(Abstractformat *format,
                                        xx_pd_struct *pd);
XXFC_API int64_t xx_macho_get_format_size(Abstractformat *format,
                                          xx_pd_struct *pd);
XXFC_API bool xx_macho_get_memory_map(Abstractformat *format,
                                      xx_memory_map_mode_t mode,
                                      xx_memory_map *output,
                                      xx_pd_struct *pd);

XXFC_API bool xx_macho_is_64(const xx_macho *macho);
XXFC_API uint32_t xx_macho_get_cpu_type(const xx_macho *macho);
XXFC_API uint32_t xx_macho_get_file_type(const xx_macho *macho);
XXFC_API uint32_t xx_macho_get_number_of_segments(const xx_macho *macho);
XXFC_API const xx_macho_segment *xx_macho_get_segment(
    const xx_macho *macho, uint32_t index);

static inline Abstractformat *xx_macho_to_format(xx_macho *macho) {
    return macho ? &macho->format : NULL;
}

static inline const Abstractformat *xx_macho_to_format_const(
    const xx_macho *macho) {
    return macho ? &macho->format : NULL;
}

#ifdef __cplusplus
}
#endif

#endif /* XXFCLIB_FORMAT_MACHO_H */
