/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/windows_ldm/xx_windows_ldm.h"

XX_FORMAT_DEFINE_READER_ADAPTER(windows_ldm, XX_FILE_TYPE_WINDOWS_LDM,
    xx_windows_ldm_create(device, 0), xx_windows_ldm_free, XX_READER_TYPE_FILL_UNKNOWN)

