/* Generated by generate_die_music_files.py; do not edit. */
/* SPDX-License-Identifier: MIT */
#include "xxfclib/formats/die_music/xx_die_music.h"
#include "../../xx_format_extractor_engine.h"
#include "../../xx_format_abstract_extractor_adapter.h"

const xx_die_music_descriptor xx_die_music_majortom_player2_arp_descriptor = {
    "MAJORTOM_PLAYER2_ARP",
    "Major Tom's Player 2 module (.ARP)",
    "Binary/audio.1.sg",
    394U,
    false,
    XX_FILE_TYPE_DIE_MUSIC_MAJORTOM_PLAYER2_ARP
};

XXFC_API Abstractformat *xx_die_music_majortom_player2_arp_create(xx_io_device *device, int64_t base)
{
    return xx_die_music_reader_create(&xx_die_music_majortom_player2_arp_descriptor, device, base);
}

XXFC_API void xx_die_music_majortom_player2_arp_free(void *reader)
{
    xx_die_music_reader_free(reader);
}

static const xx_file_type_t xx_die_music_majortom_player2_arp_types[] = {
    XX_FILE_TYPE_DIE_MUSIC_MAJORTOM_PLAYER2_ARP
};

static Abstractformat *xx_die_music_majortom_player2_arp_open(xx_io_device *window)
{
    return xx_die_music_majortom_player2_arp_create(window, 0);
}

static void xx_die_music_majortom_player2_arp_close(Abstractformat *format)
{
    xx_die_music_majortom_player2_arp_free(format);
}

static const xx_format_search_desc xx_die_music_majortom_player2_arp_search_desc = {
    xx_die_music_majortom_player2_arp_types, 1U, NULL, 0U,
    xx_die_music_majortom_player2_arp_open, xx_die_music_majortom_player2_arp_close, true
};

static xx_format_search_state *xx_die_music_majortom_player2_arp_create_search(
    xx_format_extractor *self, xx_io_device *device,
    const xx_list_s *options, xx_pd_struct *pd)
{
    (void)self;
    return xx_format_search_create(&xx_die_music_majortom_player2_arp_search_desc, device, options, pd);
}

static const xx_format_search_info *xx_die_music_majortom_player2_arp_current(
    xx_format_extractor *self, xx_format_search_state *state)
{
    (void)self;
    return xx_format_search_current(state);
}

static bool xx_die_music_majortom_player2_arp_next(
    xx_format_extractor *self, xx_format_search_state *state, xx_pd_struct *pd)
{
    (void)self;
    return xx_format_search_find_next(state, pd);
}

static void xx_die_music_majortom_player2_arp_free_search(
    xx_format_extractor *self, xx_format_search_state *state)
{
    (void)self;
    xx_format_search_free(state);
}

xx_format_extractor xx_die_music_majortom_player2_arp_extractor = {
    xx_die_music_majortom_player2_arp_create_search,
    xx_die_music_majortom_player2_arp_current,
    xx_die_music_majortom_player2_arp_next,
    xx_die_music_majortom_player2_arp_free_search
};

XX_FORMAT_DEFINE_ABSTRACT_EXTRACTOR(
    die_music_majortom_player2_arp, xx_die_music_majortom_player2_arp_search_desc)
