/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/nexas_pac/xx_nexas_pac.h"

XX_FORMAT_DEFINE_READER_ADAPTER(nexas_pac, XX_FILE_TYPE_NEXAS_PAC,
    xx_nexas_pac_create(device, 0), xx_nexas_pac_free, XX_READER_TYPE_FILL_UNKNOWN)

