#!/usr/bin/env python3
"""Build the Abstractextractor adapter map from the existing extractor list.

The legacy registry remains the authority for type order and shared aliases.
Run this after adding a legacy extractor and its get_abstract_extractor getter.
"""

from pathlib import Path
import re


HERE = Path(__file__).resolve().parent
DECLARATION = re.compile(r"^extern xx_format_extractor (xx_[A-Za-z0-9_]+_extractor);", re.M)
ROW = re.compile(r"\{\s*XX_FILE_TYPE_[A-Z0-9_]+\s*,\s*&(xx_[A-Za-z0-9_]+_extractor)\s*\}")


def symbols(path: Path) -> list[str]:
    names = DECLARATION.findall(path.read_text(errors="replace"))
    if len(names) != len(set(names)):
        raise ValueError(f"duplicate extractor declarations in {path}")
    return names


def getter(name: str) -> str:
    return name.removesuffix("_extractor") + "_get_abstract_extractor"


def main() -> None:
    legacy = HERE / "xx_format_extractor_list.inc"
    music_decls = HERE / "die_music" / "xx_die_music_extractor_decls.inc"
    base = symbols(legacy)
    music = symbols(music_decls)
    if set(base) & set(music):
        raise ValueError("duplicate base and die_music extractor declarations")
    legacy_rows = set(ROW.findall(legacy.read_text(errors="replace")))
    music_rows = set(ROW.findall((HERE / "die_music" / "xx_die_music_extractor_rows.inc")
                              .read_text(errors="replace")))
    if set(base) != legacy_rows or set(music) != music_rows:
        raise ValueError("extractor declarations and registry rows differ")

    lines = [
        "/* Generated by generate_abstract_extractor_list.py from",
        " * xx_format_extractor_list.inc and die_music/xx_die_music_extractor_decls.inc.",
        " * The legacy extractor pointer is the stable key, so shared file-type",
        " * aliases retain the same adapter. */",
        "",
        "typedef Abstractextractor *(*xx_abstract_extractor_getter)(void);",
        "",
    ]
    lines.extend(f"extern Abstractextractor *{getter(name)}(void);" for name in base)
    lines.append("#ifndef XXFC_FORMATS_ONLY")
    lines.extend(f"extern Abstractextractor *{getter(name)}(void);" for name in music)
    lines.extend([
        "#endif", "", "static const struct {",
        "    const xx_format_extractor *legacy;",
        "    xx_abstract_extractor_getter get;",
        "} g_xx_abstract_extractor_getters[] = {",
    ])
    lines.extend(f"    {{ &{name}, {getter(name)} }}," for name in base)
    lines.append("#ifndef XXFC_FORMATS_ONLY")
    lines.extend(f"    {{ &{name}, {getter(name)} }}," for name in music)
    lines.extend(["#endif", "};", ""])
    (HERE / "xx_format_abstract_extractor_list.inc").write_text("\n".join(lines))


if __name__ == "__main__":
    main()
