/* Copyright (c) 2026 hors<horsicq@gmail.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/* Pure format names. This catalog is shared by every build profile and
 * depends only on public format identifiers, never concrete readers.
 */
#include "xxfclib/formats/xx_format.h"

const char *xx_type_to_string(xx_format_type_t type) {
    switch (type) {
        case XX_TYPE_CONSOLE_APPLICATION: return "Console application";
        case XX_TYPE_GUI_APPLICATION:     return "GUI application";
        case XX_TYPE_LIBRARY:             return "Library";
        case XX_TYPE_DRIVER:              return "Driver";
        case XX_TYPE_STATIC_LIBRARY:      return "Static library";
        case XX_TYPE_SERVICE:             return "Service";
        case XX_TYPE_DAEMON:              return "Daemon";
        case XX_TYPE_BOOT:                return "Boot";
        case XX_TYPE_FIRMWARE:            return "Firmware";
        case XX_TYPE_OBJECT:              return "Object";
        case XX_TYPE_PACKAGE:             return "Package";
        case XX_TYPE_RAW:                 return "Raw";
        case XX_TYPE_ARCHIVE:             return "Archive";
        default:                          return "Unknown";
    }
}

const char *xx_arch_to_string(xx_arch_t arch) {
    switch (arch) {
        case XX_ARCH_X86_64:  return "x86_64";
        case XX_ARCH_X86:     return "x86";
        case XX_ARCH_X86_16:  return "x86_16";
        case XX_ARCH_ARM:     return "arm";
        case XX_ARCH_ARM64:   return "arm64";
        case XX_ARCH_MIPS:    return "mips";
        case XX_ARCH_MIPS64:  return "mips64";
        case XX_ARCH_PPC:     return "ppc";
        case XX_ARCH_PPC64:   return "ppc64";
        case XX_ARCH_RISCV:   return "riscv";
        case XX_ARCH_RISCV64: return "riscv64";
        case XX_ARCH_SPARC:   return "sparc";
        case XX_ARCH_SPARC64: return "sparc64";
        case XX_ARCH_M68K:    return "m68k";
        case XX_ARCH_AVR:     return "avr";
        case XX_ARCH_SH:      return "sh";
        case XX_ARCH_WASM:    return "wasm";
        case XX_ARCH_JVM:     return "jvm";
        case XX_ARCH_DOTNET:  return "cil";
        case XX_ARCH_DALVIK:  return "dalvik";
        case XX_ARCH_GENERIC: return "Generic";
        default:              return "Unknown";
    }
}

const char *xx_os_to_string(xx_os_t os) {
    switch (os) {
        case XX_OS_WINDOWS: return "Windows";
        case XX_OS_LINUX:   return "Linux";
        case XX_OS_MACOS:   return "macOS";
        case XX_OS_UNIX:    return "Unix";
        case XX_OS_DOS:     return "DOS";
        case XX_OS_FREEBSD: return "FreeBSD";
        case XX_OS_ANDROID: return "Android";
        case XX_OS_IOS:     return "iOS";
        case XX_OS_OS2:     return "OS/2";
        case XX_OS_GENERIC: return "Generic";
        default:            return "Unknown";
    }
}


const char *xx_data_struct_type_to_string(xx_data_struct_type_t type) {
    switch (type) {
        case XX_DATA_STRUCT_TYPE_STRUCT:    return "struct";
        case XX_DATA_STRUCT_TYPE_ENTRY:     return "entry";
        case XX_DATA_STRUCT_TYPE_FOOTER:    return "footer";
        case XX_DATA_STRUCT_TYPE_LOCATOR:   return "locator";
        case XX_DATA_STRUCT_TYPE_RAW_DATA:  return "raw_data";
        default:                            return "unknown";
    }
}

const char *xx_format_file_type_to_string(xx_file_type_t type) {
    switch (type) {
        case XX_FILE_TYPE_ZXML: return "ZXML compressed XML";
        case XX_FILE_TYPE_ZISOFS: return "ZISOFS compressed file";
        case XX_FILE_TYPE_NVP: return "NVP image/configuration container";
        case XX_FILE_TYPE_SQZE: return "SQZE compressed archive";
        case XX_FILE_TYPE_ZIP_PSC: return "PSC transformed ZIP";
        case XX_FILE_TYPE_CRX: return "Chromium CRX extension";
        case XX_FILE_TYPE_DCS: return "Windows DCS LZMS";
        case XX_FILE_TYPE_MSKN1: return "MediaMonkey MSKN v1 skin";
        case XX_FILE_TYPE_MSKN2: return "MediaMonkey MSKN v2 skin";
        case XX_FILE_TYPE_MSKN3: return "MediaMonkey MSKN v3 skin";
        case XX_FILE_TYPE_CSQ: return "CSQ compressed data";
        case XX_FILE_TYPE_ZOOT1: return "Zoot v1 notes";
        case XX_FILE_TYPE_RDFZ: return "RDFZ compressed image";
        case XX_FILE_TYPE_ZBEOS: return "Compressed BeOS boot image";
        case XX_FILE_TYPE_SOLARISPKG_ZIP: return "Solaris compressed package";
        case XX_FILE_TYPE_GTA_IMG: return "GTA IMG v2 archive";
        case XX_FILE_TYPE_PBO: return "Bohemia PBO archive";
        case XX_FILE_TYPE_PAM_PAK: return "PAM PAK archive";
        case XX_FILE_TYPE_PFPK: return "PFPK archive";
        case XX_FILE_TYPE_BIRDIES: return "Birdies archive";
        case XX_FILE_TYPE_XUIZ: return "Xbox XUIZ archive";
        case XX_FILE_TYPE_TITAN_QUEST: return "Titan Quest ARC archive";
        case XX_FILE_TYPE_SBPAK: return "South Park SBPAK archive";
        case XX_FILE_TYPE_CGJP: return "CGJP game archive";
        case XX_FILE_TYPE_PIRS: return "Xbox STFS PIRS/LIVE/CON package";
        case XX_FILE_TYPE_PX: return "PX named-resource package";
        case XX_FILE_TYPE_BINSH_STARKIT: return "Shell-prefixed Tcl Starkit";
        case XX_FILE_TYPE_EVD: return "EVD map images";
        case XX_FILE_TYPE_DESKSOFT: return "DeskSoft installer";
        case XX_FILE_TYPE_METAPRODUCTS: return "MetaProducts installer";
        case XX_FILE_TYPE_VISUALWARE: return "VisualWare installer";
        case XX_FILE_TYPE_LYME_SFX: return "Lyme SFX installer";
        case XX_FILE_TYPE_AUDIALS: return "Audials CMP resources";
        case XX_FILE_TYPE_PSA_DISK: return "PSA diagnostic FAT image";
        case XX_FILE_TYPE_WEBEXE: return "WebExe M2E container";
        case XX_FILE_TYPE_ASD: return "ASD compressed stream";
        case XX_FILE_TYPE_CFD: return "CFD compressed stream";
        case XX_FILE_TYPE_RDC: return "RDC compressed stream";
        case XX_FILE_TYPE_FOX_SQZ: return "Fox SQZ compressed archive";
        case XX_FILE_TYPE_SKF: return "SKF compressed stream";
        case XX_FILE_TYPE_OSL2000: return "OSL2000 compressed resources";
        case XX_FILE_TYPE_LDS: return "LDS compressed stream";
        case XX_FILE_TYPE_DCP_DISK: return "DCP floppy image";
        case XX_FILE_TYPE_SONY_IMAGE: return "Sony TCJN image";
        case XX_FILE_TYPE_GNU_GETTEXT_MO: return "GNU gettext message catalog";
        case XX_FILE_TYPE_QT_QM: return "Qt compiled message catalog";
        case XX_FILE_TYPE_MIME_MESSAGE: return "MIME email / HTML archive";
        case XX_FILE_TYPE_WINDOWS_HELP: return "Windows Help internal filesystem";
        case XX_FILE_TYPE_MICROSOFT_LIT: return "Microsoft Reader LIT";
        case XX_FILE_TYPE_BRUNS_MEDIA: return "Bruns encrypted media";
        case XX_FILE_TYPE_GAME_ARCHIVE: return "GARbro game archive";
        case XX_FILE_TYPE_RPG_MAKER_MV: return "RPG Maker MV encrypted media";
        case XX_FILE_TYPE_UTAGE_MEDIA: return "UTAGE encrypted media";
        case XX_FILE_TYPE_YCG_IMAGE: return "YU-RIS YCG image";
        case XX_FILE_TYPE_UNREAL_PAK: return "Unreal Engine PAK";
        case XX_FILE_TYPE_FALLOUT_DAT: return "Fallout DAT";
        case XX_FILE_TYPE_LIVE_MAKER_GAL: return "LiveMaker GAL layered image";
        case XX_FILE_TYPE_SMILE_GAME_PACK: return "Smile Game Builder pack";
        case XX_FILE_TYPE_CHROMIUM_PAK: return "Chromium DataPack";
        case XX_FILE_TYPE_WINDOWS_THUMBNAIL_CACHE: return "Windows thumbnail cache";
        case XX_FILE_TYPE_ENIGMA_VIRTUAL_BOX: return "Enigma Virtual Box filesystem";
        case XX_FILE_TYPE_BITROCK: return "BitRock CookFS installer";
        case XX_FILE_TYPE_SMART_INSTALL_MAKER: return "Smart Install Maker installer";
        case XX_FILE_TYPE_UPX: return "UPX packed executable";
        case XX_FILE_TYPE_MOLEBOX: return "MoleBox SVFS package";
        case XX_FILE_TYPE_EXCELSIOR_INSTALLER: return "Excelsior Installer";
        case XX_FILE_TYPE_NETOPSYSTEMS_FEAD: return "Netopsystems FEAD installer";
        case XX_FILE_TYPE_DGCA: return "DGCA archive";
        case XX_FILE_TYPE_SUPERDAT: return "SuperDAT update archive";
        case XX_FILE_TYPE_PARSEC_DTC: return "Parsec DTC driver";
        case XX_FILE_TYPE_PARSEC_DMA: return "Parsec DMA driver";
        case XX_FILE_TYPE_PALLADIX_MUS: return "Palladix MUS driver";
        case XX_FILE_TYPE_PALLADIX_SND: return "Palladix SND driver";
        case XX_FILE_TYPE_PALLADIX_PMA: return "Palladix PMA music";
        case XX_FILE_TYPE_MDH: return "MDH music";
        case XX_FILE_TYPE_SM8: return "SM8 PCM audio";
        case XX_FILE_TYPE_APKS: return "Android APK Set";
        case XX_FILE_TYPE_DER: return "DER definite-length envelope";
        case XX_FILE_TYPE_RZIP: return "RZIP archive";
        case XX_FILE_TYPE_CHZ: return "ChArc archive";
        case XX_FILE_TYPE_ECM: return "ECM CD image";
        case XX_FILE_TYPE_HE_TLKB: return "Humongous TLKB archive";
        case XX_FILE_TYPE_SAR: return "SAR archive";
        case XX_FILE_TYPE_IS_STORED: return "Atari stored wrapper";
        case XX_FILE_TYPE_LARC_PFX: return "Atari LARC PFX";
        case XX_FILE_TYPE_WII_WAD: return "Wii WAD package";
        case XX_FILE_TYPE_BINSH_SFX: return "Shell tail archive";
        case XX_FILE_TYPE_INSTALIT_DATA: return "Instalit data streams";
        case XX_FILE_TYPE_TEXT: return "Text";
        case XX_FILE_TYPE_ASF: return "ASF / Windows Media";
        case XX_FILE_TYPE_AUDIBLE_AA: return "Audible AA audio";
#include "xx_format_gap_type_strings.inc"
        case XX_FILE_TYPE_BZIP1: return "BZIP1";
        case XX_FILE_TYPE_FREEZE: return "Freeze";
        case XX_FILE_TYPE_LPAK: return "LPAK";
        case XX_FILE_TYPE_EXFAT: return "exFAT";
        case XX_FILE_TYPE_MAJIRO: return "Majiro";
        case XX_FILE_TYPE_WUX: return "WUX";
        case XX_FILE_TYPE_SDI: return "SDI";
        case XX_FILE_TYPE_NHD: return "NHD";
        case XX_FILE_TYPE_VIRTUAL98: return "Virtual98";
        case XX_FILE_TYPE_ANEX86_HDI: return "Anex86 HDI";
        case XX_FILE_TYPE_THOMSON_SAP: return "Thomson SAP";
        case XX_FILE_TYPE_NITROPLUS_NPK2: return "Nitroplus NPK2";
        case XX_FILE_TYPE_APPLE_PASCAL: return "Apple Pascal";
        case XX_FILE_TYPE_DMK: return "DMK";
        case XX_FILE_TYPE_MFS: return "Macintosh MFS";
        case XX_FILE_TYPE_HFS: return "Macintosh HFS";
        case XX_FILE_TYPE_CATSYSTEM_KIF: return "CatSystem KIF";
        case XX_FILE_TYPE_MALIE_LIB: return "Malie LIB";
        case XX_FILE_TYPE_NEXAS_PAC: return "NeXAS PAC";
        case XX_FILE_TYPE_NITROPLUS_NPA: return "Nitroplus NPA";
        case XX_FILE_TYPE_UFS1: return "BSD UFS1";
        case XX_FILE_TYPE_CPM: return "CP/M";
        case XX_FILE_TYPE_XVA: return "Xen XVA";
        case XX_FILE_TYPE_QLIE_PACK: return "Qlie PACK";
        case XX_FILE_TYPE_HFSPLUS: return "HFS+/HFSX";
        case XX_FILE_TYPE_PARTIMAGE: return "Partimage";
        case XX_FILE_TYPE_AARUFORMAT: return "AaruFormat";
        case XX_FILE_TYPE_ADFS: return "Acorn ADFS";
        case XX_FILE_TYPE_GDI: return "Dreamcast GDI";
        case XX_FILE_TYPE_MDS: return "Alcohol 120% MDS/MDF";
        case XX_FILE_TYPE_CBM_D64: return "Commodore D64";
        case XX_FILE_TYPE_CBM_D71: return "Commodore D71";
        case XX_FILE_TYPE_CBM_D81: return "Commodore D81";
        case XX_FILE_TYPE_CCD: return "CloneCD CCD/IMG/SUB";
        case XX_FILE_TYPE_CDRDAO_TOC: return "CDRDAO TOC";
        case XX_FILE_TYPE_DISKCOPY42: return "Apple DiskCopy 4.2";
        case XX_FILE_TYPE_ACORN_DFS: return "Acorn DFS";
        case XX_FILE_TYPE_FDCOPY_CFI: return "FDCOPY CFI";
        case XX_FILE_TYPE_ATARI_DOS2: return "Atari DOS 2.x filesystem";
        case XX_FILE_TYPE_APRIDISK: return "ApriDisk";
        case XX_FILE_TYPE_TI99_DSK: return "TI-99/4A DSK filesystem";
        case XX_FILE_TYPE_APPLE_DOS32: return "Apple DOS 3.2";
        case XX_FILE_TYPE_APPLE_DOS33_32: return "Apple DOS 3.3 32-sector";
        case XX_FILE_TYPE_CBM_D8X: return "Commodore 8050/8250 D80/D82";
        case XX_FILE_TYPE_CBM_D67: return "Commodore 2040 DOS 1 D67";
        case XX_FILE_TYPE_CBM_D90: return "Commodore D9060/D9090 D90";
        case XX_FILE_TYPE_SIMH_DISK: return "SIMH CP/M disk image";
        case XX_FILE_TYPE_SNATCHIT_CP2: return "Snatch-it CP2 disk image";
        case XX_FILE_TYPE_NORTHSTAR_NSI: return "North Star NSI disk image";
        case XX_FILE_TYPE_THOMSON_FD: return "Thomson FD disk image";
        case XX_FILE_TYPE_CMD_D1M: return "Commodore CMD D1M disk image";
        case XX_FILE_TYPE_CMD_D2M: return "Commodore CMD D2M disk image";
        case XX_FILE_TYPE_CMD_D4M: return "Commodore CMD D4M disk image";
        case XX_FILE_TYPE_PCE_PRI: return "PCE PRI bitstream disk image";
        case XX_FILE_TYPE_PCE_PFI: return "PCE PFI flux disk image";
        case XX_FILE_TYPE_PCE_PFDC_V0: return "PCE PFDC v0 sector disk image";
        case XX_FILE_TYPE_PCE_PFDC_V1: return "PCE PFDC v1 sector disk image";
        case XX_FILE_TYPE_PCE_PFDC_V2: return "PCE PFDC v2 sector disk image";
        case XX_FILE_TYPE_PCE_PFDC_V4: return "PCE PFDC v4 sector disk image";
        case XX_FILE_TYPE_PCE_PBI: return "PCE PBI block disk image";
        case XX_FILE_TYPE_PCE_PBIT: return "PCE PBIT bitstream disk image";
        case XX_FILE_TYPE_PCE_TC: return "PCE TransCopy TC bitstream disk image";
        case XX_FILE_TYPE_PCE_ANADISK: return "AnaDisk sector disk image";
        case XX_FILE_TYPE_PCE_XDF: return "PCE XDF 1.84 MB sector disk image";
        case XX_FILE_TYPE_EROFS: return "EROFS filesystem image";
        case XX_FILE_TYPE_OS9_RBF: return "Microware OS-9 RBF filesystem";
        case XX_FILE_TYPE_LDBS: return "LibDsk LDBS disk image";
        case XX_FILE_TYPE_LDBST: return "LibDsk LDBST text disk image";
        case XX_FILE_TYPE_BYTEKILLER: return "ByteKiller";
        case XX_FILE_TYPE_APPLE_DOS33: return "Apple DOS3.3";
        case XX_FILE_TYPE_ACORN_ATOM_DISK: return "acorn_atom_disk";
        case XX_FILE_TYPE_APOLLO_AFD: return "apollo_afd";
        case XX_FILE_TYPE_BGA: return "bga";
        case XX_FILE_TYPE_BGI: return "bgi";
        case XX_FILE_TYPE_BGI2: return "bgi2";
        case XX_FILE_TYPE_BINSCII: return "binscii";
        case XX_FILE_TYPE_BLINDWRITE_5_6_IMAGE: return "blindwrite_5_6_image";
        case XX_FILE_TYPE_BTRFS_STREAM: return "btrfs_stream";
        case XX_FILE_TYPE_CAMPUTERS_LYNX_LDF: return "camputers_lynx_ldf";
        case XX_FILE_TYPE_CPK: return "cpk";
        case XX_FILE_TYPE_CRT: return "crt";
        case XX_FILE_TYPE_D_LINK_ALPHA_ENCIMG_V2: return "d_link_alpha_encimg_v2";
        case XX_FILE_TYPE_D_LINK_FPKG_CPKG: return "d_link_fpkg_cpkg";
        case XX_FILE_TYPE_DAEMON_TOOLS_MDX: return "daemon_tools_mdx";
        case XX_FILE_TYPE_DART: return "dart";
        case XX_FILE_TYPE_DDD: return "ddd";
        case XX_FILE_TYPE_DIET_COMPRESSION: return "diet_compression";
        case XX_FILE_TYPE_DXA: return "dxa";
        case XX_FILE_TYPE_EA_FSH: return "ea_fsh";
        case XX_FILE_TYPE_EWF2_EX01: return "ewf2_ex01";
        case XX_FILE_TYPE_EWF2_LX01: return "ewf2_lx01";
        case XX_FILE_TYPE_EWF_L01: return "ewf_l01";
        case XX_FILE_TYPE_FMOD_SAMPLE_BANK: return "fmod_sample_bank";
        case XX_FILE_TYPE_GBI: return "gbi";
        case XX_FILE_TYPE_GOLDSRC_BSP: return "goldsrc_bsp";
        case XX_FILE_TYPE_HSF: return "hsf";
        case XX_FILE_TYPE_HTC_NBH_ROM_IMAGE: return "htc_nbh_rom_image";
        case XX_FILE_TYPE_HXC_HFE_EXTENDED: return "hxc_hfe_extended";
        case XX_FILE_TYPE_HXC_HFE_HDDD_A2_VARIANT: return "hxc_hfe_hddd_a2_variant";
        case XX_FILE_TYPE_HXC_HFE_V3: return "hxc_hfe_v3";
        case XX_FILE_TYPE_HXS: return "hxs";
        case XX_FILE_TYPE_JFFS2_OLD: return "jffs2_old";
        case XX_FILE_TYPE_JVC: return "jvc";
        case XX_FILE_TYPE_KGB_ARCHIVER: return "kgb_archiver";
        case XX_FILE_TYPE_KRYOFLUX_STREAM: return "kryoflux_stream";
        case XX_FILE_TYPE_LIVEMAKER: return "livemaker";
        case XX_FILE_TYPE_LZMA86: return "lzma86";
        case XX_FILE_TYPE_MAXIS_FAR_ARCHIVE: return "maxis_far_archive";
        case XX_FILE_TYPE_MGT: return "mgt";
        case XX_FILE_TYPE_MINIX: return "minix";
        case XX_FILE_TYPE_MOOF: return "moof";
        case XX_FILE_TYPE_MS_DOS_BACKUP2: return "ms_dos_backup2";
        case XX_FILE_TYPE_MUB: return "mub";
        case XX_FILE_TYPE_NOA: return "noa";
        case XX_FILE_TYPE_OUTLOOK_EXPRESS_DBX_MAILBOX: return "outlook_express_dbx_mailbox";
        case XX_FILE_TYPE_PARTCLONE_IMAGE: return "partclone_image";
        case XX_FILE_TYPE_PPMD: return "ppmd";
        case XX_FILE_TYPE_QUOTED_PRINTABLE_ENCODED_FIL: return "quoted_printable_encoded_fil";
        case XX_FILE_TYPE_RISC_OS_SPRITE: return "risc_os_sprite";
        case XX_FILE_TYPE_RPG_MAKER_RGSSAD: return "rpg_maker_rgssad";
        case XX_FILE_TYPE_SFARK_COMPRESSED_SOUNDFONT: return "sfark_compressed_soundfont";
        case XX_FILE_TYPE_SIS: return "sis";
        case XX_FILE_TYPE_SPECTRUM_UDI: return "spectrum_udi";
        case XX_FILE_TYPE_SQUASHFS_SQLZ: return "squashfs_sqlz";
        case XX_FILE_TYPE_STOS_MEMORY_BANK: return "stos_memory_bank";
        case XX_FILE_TYPE_STUFFITX: return "stuffitx";
        case XX_FILE_TYPE_SUFS: return "sufs";
        case XX_FILE_TYPE_SUNVTOC: return "sunvtoc";
        case XX_FILE_TYPE_TELLTALE_TTARCH: return "telltale_ttarch";
        case XX_FILE_TYPE_UFS2: return "ufs2";
        case XX_FILE_TYPE_UIF: return "uif";
        case XX_FILE_TYPE_VALVE_GCF_CACHE: return "valve_gcf_cache";
        case XX_FILE_TYPE_VALVE_XZP: return "valve_xzp";
        case XX_FILE_TYPE_VMDK_COWD_SPARSE: return "vmdk_cowd_sparse";
        case XX_FILE_TYPE_VMDK_SESPARSE: return "vmdk_sesparse";
        case XX_FILE_TYPE_XIAOMI_HDR1: return "xiaomi_hdr1";
        case XX_FILE_TYPE_XIAOMI_HDR2: return "xiaomi_hdr2";
        case XX_FILE_TYPE_XPK_COMPRESSED_FILE: return "xpk_compressed_file";
        case XX_FILE_TYPE_YENC_ENCODED_FILE: return "yenc_encoded_file";
        case XX_FILE_TYPE_YPF: return "ypf";

        case XX_FILE_TYPE_ZIP:    return "ZIP";
        case XX_FILE_TYPE_ZIP64:  return "ZIP64";
        case XX_FILE_TYPE_7ZIP:   return "7ZIP";
        case XX_FILE_TYPE_RAR:    return "RAR";
        case XX_FILE_TYPE_AR:     return "AR";
        case XX_FILE_TYPE_BZ2:    return "BZ2";
        case XX_FILE_TYPE_GZ:     return "GZ";
        case XX_FILE_TYPE_XZ:     return "XZ";
        case XX_FILE_TYPE_TAR:    return "TAR";
        case XX_FILE_TYPE_JAR:    return "JAR";
        case XX_FILE_TYPE_APK:    return "APK";
        case XX_FILE_TYPE_IPA:    return "IPA";
        case XX_FILE_TYPE_NPM:    return "NPM";
        case XX_FILE_TYPE_TAR_GZ: return "TAR.GZ";
        case XX_FILE_TYPE_TAR_BZ2:return "TAR.BZ2";
        case XX_FILE_TYPE_TAR_XZ: return "TAR.XZ";
        case XX_FILE_TYPE_TAR_ZSTD: return "TAR.ZST";
        case XX_FILE_TYPE_ZSTD: return "ZSTD";
        case XX_FILE_TYPE_CPIO: return "CPIO";
        case XX_FILE_TYPE_MTREE: return "MTREE";
        case XX_FILE_TYPE_TAR_NEXTSTEP: return "TAR NEXTSTEP";
        case XX_FILE_TYPE_TAR_COMPRESS: return "TAR.Z";
        case XX_FILE_TYPE_UNIX_PACK: return "UNIX PACK";
        case XX_FILE_TYPE_ZLIB: return "ZLIB";
        case XX_FILE_TYPE_UNIX_COMPRESS: return "UNIX COMPRESS";
        case XX_FILE_TYPE_GIT_OBJECT: return "GIT OBJECT";
        case XX_FILE_TYPE_MS_COMPRESS: return "MS COMPRESS";
        case XX_FILE_TYPE_ASH0: return "ASH0";
        case XX_FILE_TYPE_WII_LZ77: return "WII LZ77";
        case XX_FILE_TYPE_LZV1: return "LZV1";
        case XX_FILE_TYPE_ORACLE_SQUEEZE: return "ORACLE SQUEEZE";
        case XX_FILE_TYPE_SOFTRONICS: return "SOFTRONICS";
        case XX_FILE_TYPE_LOGITECH_COMPRESS: return "LOGITECH COMPRESS";
        case XX_FILE_TYPE_DMA_PACKED: return "DMA PACKED";
        case XX_FILE_TYPE_GAS_HUFF: return "GAS HUFF";
        case XX_FILE_TYPE_HUF: return "HUF";
        case XX_FILE_TYPE_LZDIET: return "LZDIET";
        case XX_FILE_TYPE_ZIE: return "ZIE";
        case XX_FILE_TYPE_XEDITPACK: return "XEDITPACK";
        case XX_FILE_TYPE_WPK: return "WPK";
        case XX_FILE_TYPE_WINTERSOFT: return "WINTERSOFT";
        case XX_FILE_TYPE_VMARC: return "VMARC";
        case XX_FILE_TYPE_TIVOLI: return "TIVOLI";
        case XX_FILE_TYPE_TI99ARC: return "TI99ARC";
        case XX_FILE_TYPE_STYLUS: return "STYLUS";
        case XX_FILE_TYPE_RTPATCH: return "RTPATCH";
        case XX_FILE_TYPE_RTA: return "RTA";
        case XX_FILE_TYPE_ROMPAQ: return "ROMPAQ";
        case XX_FILE_TYPE_RID: return "RID";
        case XX_FILE_TYPE_QNXBASE: return "QNXBASE";
        case XX_FILE_TYPE_QDA: return "QDA";
        case XX_FILE_TYPE_PKT: return "PKT";
        case XX_FILE_TYPE_LOFI: return "LOFI";
        case XX_FILE_TYPE_LIM: return "LIM";
        case XX_FILE_TYPE_KOLIBRIKPACK: return "KOLIBRIKPACK";
        case XX_FILE_TYPE_IVT: return "IVT";
        case XX_FILE_TYPE_IRWINPAC: return "IRWINPAC";
        case XX_FILE_TYPE_HAP: return "HAP";
        case XX_FILE_TYPE_COMPACTPRO: return "COMPACTPRO";
        case XX_FILE_TYPE_IMP: return "IMP";
        case XX_FILE_TYPE_SQX: return "SQX";
        case XX_FILE_TYPE_ZOO: return "ZOO";
        case XX_FILE_TYPE_TERSE: return "TERSE";
        case XX_FILE_TYPE_STK: return "STK";
        case XX_FILE_TYPE_PCOMMOS2: return "PCOMMOS2";
        case XX_FILE_TYPE_JBF: return "JBF";
        case XX_FILE_TYPE_IBMSPACK: return "IBMSPACK";
        case XX_FILE_TYPE_GTU: return "GTU";
        case XX_FILE_TYPE_GLU: return "GLU";
        case XX_FILE_TYPE_ZTC: return "ZTC";
        case XX_FILE_TYPE_NETWAREPACKED: return "NETWAREPACKED";
        case XX_FILE_TYPE_ZPAK: return "ZPAK";
        case XX_FILE_TYPE_ZCMP: return "ZCMP";
        case XX_FILE_TYPE_SCL: return "SCL";
        case XX_FILE_TYPE_PAKLEO: return "PAKLEO";
        case XX_FILE_TYPE_NPACK: return "NPACK";
        case XX_FILE_TYPE_MI10: return "MI10";
        case XX_FILE_TYPE_LZWD: return "LZWD";
        case XX_FILE_TYPE_LZHCXP: return "LZHCXP";
        case XX_FILE_TYPE_KBOOM: return "KBOOM";
        case XX_FILE_TYPE_HZL: return "HZL";
        case XX_FILE_TYPE_HA: return "HA";
        case XX_FILE_TYPE_GENIUS: return "GENIUS";
        case XX_FILE_TYPE_FLS: return "FLS";
        case XX_FILE_TYPE_EAREFPACK: return "EAREFPACK";
        case XX_FILE_TYPE_EALIB: return "EALIB";
        case XX_FILE_TYPE_ELM: return "ELM";
        case XX_FILE_TYPE_EA: return "EA";
        case XX_FILE_TYPE_DISKDOUBLER: return "DISKDOUBLER";
        case XX_FILE_TYPE_CMP: return "CMP";
        case XX_FILE_TYPE_CLP: return "CLP";
        case XX_FILE_TYPE_CHIEFLZMULTI: return "CHIEFLZMULTI";
        case XX_FILE_TYPE_CHIEFLZ: return "CHIEFLZ";
        case XX_FILE_TYPE_BWCF: return "BWCF";
        case XX_FILE_TYPE_ASYMETRIX: return "ASYMETRIX";
        case XX_FILE_TYPE_SEAARC: return "SEAARC";
        case XX_FILE_TYPE_AMIGAHUNK: return "AMIGAHUNK";
        case XX_FILE_TYPE_ATARIST: return "ATARIST";
        case XX_FILE_TYPE_DOS16M: return "DOS16M";
        case XX_FILE_TYPE_DOS4G: return "DOS4G";
        case XX_FILE_TYPE_COM: return "COM";
        case XX_FILE_TYPE_AMIGALZX: return "AMIGALZX";
        case XX_FILE_TYPE_SPIS: return "SPIS";
        case XX_FILE_TYPE_LHA: return "LHA";
        case XX_FILE_TYPE_XAR: return "XAR";
        case XX_FILE_TYPE_FMC1: return "FMC1";
        case XX_FILE_TYPE_PYZ: return "PYZ";
        case XX_FILE_TYPE_ASCENDBACKUP: return "ASCENDBACKUP";
        case XX_FILE_TYPE_STORK: return "STORK";
        case XX_FILE_TYPE_ZAP: return "ZAP";
        case XX_FILE_TYPE_BWF: return "BWF";
        case XX_FILE_TYPE_QUALITAS: return "QUALITAS";
        case XX_FILE_TYPE_JETBBS: return "JETBBS";
        case XX_FILE_TYPE_ECMPACKED: return "ECMPACKED";
        case XX_FILE_TYPE_BORLANDPACK: return "BORLANDPACK";
        case XX_FILE_TYPE_JGPAK: return "JGPAK";
        case XX_FILE_TYPE_ZZZ: return "ZZZ";
        case XX_FILE_TYPE_ZZ: return "ZZ";
        case XX_FILE_TYPE_ZLWB: return "ZLWB";
        case XX_FILE_TYPE_TRC: return "TRC";
        case XX_FILE_TYPE_TGCF: return "TGCF";
        case XX_FILE_TYPE_SWAG: return "SWAG";
        case XX_FILE_TYPE_RIVERSOFT: return "RIVERSOFT";
        case XX_FILE_TYPE_RCF: return "RCF";
        case XX_FILE_TYPE_QUARTERDECKQP: return "QUARTERDECKQP";
        case XX_FILE_TYPE_QIP1: return "QIP1";
        case XX_FILE_TYPE_POWERARC: return "POWERARC";
        case XX_FILE_TYPE_POVLABLZH: return "POVLABLZH";
        case XX_FILE_TYPE_MVA: return "MVA";
        case XX_FILE_TYPE_MIZ: return "MIZ";
        case XX_FILE_TYPE_LSZ: return "LSZ";
        case XX_FILE_TYPE_JM93: return "JM93";
        case XX_FILE_TYPE_INTEDUFT: return "INTEDUFT";
        case XX_FILE_TYPE_IGF2: return "IGF2";
        case XX_FILE_TYPE_IGF1: return "IGF1";
        case XX_FILE_TYPE_IBMZPAK: return "IBMZPAK";
        case XX_FILE_TYPE_FLD: return "FLD";
        case XX_FILE_TYPE_FIZ: return "FIZ";
        case XX_FILE_TYPE_DTPACKED: return "DTPACKED";
        case XX_FILE_TYPE_DSL2: return "DSL2";
        case XX_FILE_TYPE_DPK: return "DPK";
        case XX_FILE_TYPE_CFL: return "CFL";
        case XX_FILE_TYPE_TRCPAK: return "TRCPAK";
        case XX_FILE_TYPE_SWAGPACKET: return "SWAGPACKET";
        case XX_FILE_TYPE_SW: return "SW";
        case XX_FILE_TYPE_SOS: return "SOS";
        case XX_FILE_TYPE_SECONDNATURE: return "SECONDNATURE";
        case XX_FILE_TYPE_SEADATA: return "SEADATA";
        case XX_FILE_TYPE_SCI: return "SCI";
        case XX_FILE_TYPE_POWERBOARDBBS: return "POWERBOARDBBS";
        case XX_FILE_TYPE_MINIDUMP: return "MINIDUMP";
        case XX_FILE_TYPE_LBRCOBOL: return "LBRCOBOL";
        case XX_FILE_TYPE_KRML: return "KRML";
        case XX_FILE_TYPE_JAM: return "JAM";
        case XX_FILE_TYPE_IRIXSA: return "IRIXSA";
        case XX_FILE_TYPE_HLB: return "HLB";
        case XX_FILE_TYPE_FRONTPAGETHEME: return "FRONTPAGETHEME";
        case XX_FILE_TYPE_CRU: return "CRU";
        case XX_FILE_TYPE_BIGAF: return "BIGAF";
        case XX_FILE_TYPE_TWS: return "TWS";
        case XX_FILE_TYPE_PACKIT: return "PACKIT";
        case XX_FILE_TYPE_ZFSF: return "ZFSF";
        case XX_FILE_TYPE_MARC: return "MARC";
        case XX_FILE_TYPE_BIGF: return "BIGF";
        case XX_FILE_TYPE_ASCEND: return "ASCEND";
        case XX_FILE_TYPE_ASAR: return "ASAR";
        case XX_FILE_TYPE_ARQ: return "ARQ";
        case XX_FILE_TYPE_AP4: return "AP4";
        case XX_FILE_TYPE_FREEARC: return "FREEARC";
        case XX_FILE_TYPE_ZPAQ: return "ZPAQ";
        case XX_FILE_TYPE_PEA: return "PEA";
        case XX_FILE_TYPE_LPAQ8: return "LPAQ8";
        case XX_FILE_TYPE_BCM: return "BCM";
        case XX_FILE_TYPE_TAR_LZIP: return "TAR.LZ";
        case XX_FILE_TYPE_LZIP: return "LZIP";
        case XX_FILE_TYPE_TAR_LZMA: return "TAR.LZMA";
        case XX_FILE_TYPE_LZMA: return "LZMA";
        case XX_FILE_TYPE_TAR_LZOP: return "TAR.LZO";
        case XX_FILE_TYPE_TARX1: return "TARX1";
        case XX_FILE_TYPE_TARX2: return "TARX2";
        case XX_FILE_TYPE_ACE: return "ACE";
        case XX_FILE_TYPE_SFX_NULLSOFT_PIMP: return "Nullsoft PiMP";
        case XX_FILE_TYPE_SFX_SYDEX_DISKETTE_IMAGE: return "Sydex diskette image";
        case XX_FILE_TYPE_SFX_COMPAQ_SOFTPAQ: return "Compaq SoftPaq v1";
        case XX_FILE_TYPE_SFX_WASP_WINDOWS_AUTO: return "WASP installer";
        case XX_FILE_TYPE_WISE_INSTALLATION_SYSTEM: return "Wise Installation System";
        case XX_FILE_TYPE_ESCHALON_SETUP_EPSF: return "Eschalon EPSF";
        case XX_FILE_TYPE_GENTEE_INSTALLER: return "Gentee installer";
        case XX_FILE_TYPE_CLICKTEAM_INSTALL_CREATOR: return "Clickteam Install Creator";
        case XX_FILE_TYPE_CREATEINSTALL_INSTCRIN_EXTRACTOR: return "CreateInstall";
        case XX_FILE_TYPE_SFXSTART: return "SFXSTART";
        case XX_FILE_TYPE_MODBUS_TCP: return "modbus tcp";
        case XX_FILE_TYPE_SOMEIP_MESSAGE: return "someip message";
        case XX_FILE_TYPE_DDS_RTPS: return "dds rtps";
        case XX_FILE_TYPE_RIP_MESSAGE: return "rip message";
        case XX_FILE_TYPE_VRRP_MESSAGE: return "vrrp message";
        case XX_FILE_TYPE_IGMP_MESSAGE: return "igmp message";
        case XX_FILE_TYPE_PIM_MESSAGE: return "pim message";
        case XX_FILE_TYPE_LDP_MESSAGE: return "ldp message";
        case XX_FILE_TYPE_GRE_PACKET: return "gre packet";
        case XX_FILE_TYPE_L2TP_PACKET: return "l2tp packet";
        case XX_FILE_TYPE_LLDP_MESSAGE: return "lldp message";
        case XX_FILE_TYPE_NETFLOW_DATAGRAM: return "netflow datagram";
        case XX_FILE_TYPE_NTLM_MESSAGE: return "ntlm message";
        case XX_FILE_TYPE_DCERPC_PDU: return "dcerpc pdu";
        case XX_FILE_TYPE_ETHEREUM_RLP: return "ethereum rlp";
        case XX_FILE_TYPE_IMAGEMAGICK_MIFF: return "imagemagick miff";
        case XX_FILE_TYPE_AVS_IMAGE: return "avs image";
        case XX_FILE_TYPE_SCANALYTICS_IPLAB: return "scanalytics iplab";
        case XX_FILE_TYPE_MTV_IMAGE: return "mtv image";
        case XX_FILE_TYPE_NOKIA_OTA_BITMAP: return "nokia ota bitmap";
        case XX_FILE_TYPE_APPLE_PICT: return "apple pict";
        case XX_FILE_TYPE_WORDPERFECT_WPG: return "wordperfect wpg";
        case XX_FILE_TYPE_NASA_VICAR: return "nasa vicar";
        case XX_FILE_TYPE_KHOROS_VIFF: return "khoros viff";
        case XX_FILE_TYPE_IMAGEMAGICK_MVG: return "imagemagick mvg";
        case XX_FILE_TYPE_MOTIF_UIL: return "motif uil";
        case XX_FILE_TYPE_IGES_MODEL: return "iges model";
        case XX_FILE_TYPE_OPENUSD_USDA: return "openusd usda";
        case XX_FILE_TYPE_UFO_GLIF: return "ufo glif";
        case XX_FILE_TYPE_UNIFONT_HEX: return "unifont hex";
        case XX_FILE_TYPE_ADLIB_SOP: return "adlib sop";
        case XX_FILE_TYPE_CUDFM_CFF: return "cudfm cff";
        case XX_FILE_TYPE_ADLIB_JBM: return "adlib jbm";
        case XX_FILE_TYPE_CERES_MSC: return "ceres msc";
        case XX_FILE_TYPE_ADLIB_XSM: return "adlib xsm";
        case XX_FILE_TYPE_KEN_KSM: return "ken ksm";
        case XX_FILE_TYPE_IMPLAY_MUSIC: return "implay music";
        case XX_FILE_TYPE_ADLIB_MTR: return "adlib mtr";
        case XX_FILE_TYPE_RDOS_RAW: return "rdos raw";
        case XX_FILE_TYPE_MAD_TRACKER: return "mad tracker";
        case XX_FILE_TYPE_VASP_POSCAR: return "vasp poscar";
        case XX_FILE_TYPE_QUANTUM_ESPRESSO_INPUT: return "quantum espresso input";
        case XX_FILE_TYPE_CP2K_INPUT: return "cp2k input";
        case XX_FILE_TYPE_NWCHEM_INPUT: return "nwchem input";
        case XX_FILE_TYPE_GAMESS_INPUT: return "gamess input";
        case XX_FILE_TYPE_GAUSSIAN_INPUT: return "gaussian input";
        case XX_FILE_TYPE_ABINIT_INPUT: return "abinit input";
        case XX_FILE_TYPE_AIMS_GEOMETRY: return "aims geometry";
        case XX_FILE_TYPE_ORCA_INPUT: return "orca input";
        case XX_FILE_TYPE_DEMON_INPUT: return "demon input";
        case XX_FILE_TYPE_ETHERNET_FRAME: return "ethernet frame";
        case XX_FILE_TYPE_IP_PACKET: return "ip packet";
        case XX_FILE_TYPE_ARP_PACKET: return "arp packet";
        case XX_FILE_TYPE_ICMP_MESSAGE: return "icmp message";
        case XX_FILE_TYPE_SIP_MESSAGE: return "sip message";
        case XX_FILE_TYPE_RTSP_MESSAGE: return "rtsp message";
        case XX_FILE_TYPE_DIAMETER_MESSAGE: return "diameter message";
        case XX_FILE_TYPE_TACACS_PACKET: return "tacacs packet";
        case XX_FILE_TYPE_GTP_MESSAGE: return "gtp message";
        case XX_FILE_TYPE_PFCP_MESSAGE: return "pfcp message";
        case XX_FILE_TYPE_PPTP_MESSAGE: return "pptp message";
        case XX_FILE_TYPE_RSVP_MESSAGE: return "rsvp message";
        case XX_FILE_TYPE_AGE_ENCRYPTED: return "age encrypted";
        case XX_FILE_TYPE_KERBEROS_CCACHE: return "kerberos ccache";
        case XX_FILE_TYPE_JOSE_JWS: return "jose jws";
        case XX_FILE_TYPE_WBMP_IMAGE: return "wbmp image";
        case XX_FILE_TYPE_DEC_SIXEL: return "dec sixel";
        case XX_FILE_TYPE_PALM_BITMAP: return "palm bitmap";
        case XX_FILE_TYPE_ADOBE_ACV: return "adobe acv";
        case XX_FILE_TYPE_ADOBE_ACT: return "adobe act";
        case XX_FILE_TYPE_OGRE_SKELETON: return "ogre skeleton";
        case XX_FILE_TYPE_CAL3D_SKELETON: return "cal3d skeleton";
        case XX_FILE_TYPE_COLLADA_DAE: return "collada dae";
        case XX_FILE_TYPE_LIGHTWAVE_SCENE: return "lightwave scene";
        case XX_FILE_TYPE_DSN6_DENSITY: return "dsn6 density";
        case XX_FILE_TYPE_CRYSTALLOGRAPHY_MTZ: return "crystallography mtz";
        case XX_FILE_TYPE_AMIRA_MESH: return "amira mesh";
        case XX_FILE_TYPE_TETGEN_MESH: return "tetgen mesh";
        case XX_FILE_TYPE_JEDEC_FUSE: return "jedec fuse";
        case XX_FILE_TYPE_QCHEM_INPUT: return "qchem input";
        case XX_FILE_TYPE_ADLIB_BAM: return "adlib bam";
        case XX_FILE_TYPE_ADLIB_BMF: return "adlib bmf";
        case XX_FILE_TYPE_CREATIVE_CMF: return "creative cmf";
        case XX_FILE_TYPE_ADLIB_DFM: return "adlib dfm";
        case XX_FILE_TYPE_ADLIB_LDS: return "adlib lds";
        case XX_FILE_TYPE_ADLIB_MKJ: return "adlib mkj";
        case XX_FILE_TYPE_ADLIB_ROL: return "adlib rol";
        case XX_FILE_TYPE_ADLIB_SA2: return "adlib sa2";
        case XX_FILE_TYPE_FAUST_FMC: return "faust fmc";
        case XX_FILE_TYPE_SOFTSTAR_RIX: return "softstar rix";
        case XX_FILE_TYPE_GENOMICS_BED: return "genomics bed";
        case XX_FILE_TYPE_GENOMICS_WIGGLE: return "genomics wiggle";
        case XX_FILE_TYPE_GENOMICS_GTF: return "genomics gtf";
        case XX_FILE_TYPE_GENOMICS_AGP: return "genomics agp";
        case XX_FILE_TYPE_SEQUENCING_ABIF: return "sequencing abif";
        case XX_FILE_TYPE_SEQUENCING_SCF: return "sequencing scf";
        case XX_FILE_TYPE_GENOMICS_SFF: return "genomics sff";
        case XX_FILE_TYPE_LUT_SPI1D: return "lut spi1d";
        case XX_FILE_TYPE_LUT_SPI3D: return "lut spi3d";
        case XX_FILE_TYPE_LUT_CINESPACE_CSP: return "lut cinespace csp";
        case XX_FILE_TYPE_NTP_MESSAGE: return "ntp message";
        case XX_FILE_TYPE_RTP_RTCP: return "rtp rtcp";
        case XX_FILE_TYPE_BGP_MESSAGES: return "bgp messages";
        case XX_FILE_TYPE_OSPF_PACKET: return "ospf packet";
        case XX_FILE_TYPE_SCTP_PACKET: return "sctp packet";
        case XX_FILE_TYPE_ISAKMP_MESSAGE: return "isakmp message";
        case XX_FILE_TYPE_SSH_TRANSPORT: return "ssh transport";
        case XX_FILE_TYPE_SMTP_TRANSCRIPT: return "smtp transcript";
        case XX_FILE_TYPE_PKCS8_PRIVATE_KEY: return "pkcs8 private key";
        case XX_FILE_TYPE_PUTTY_PPK: return "putty ppk";
        case XX_FILE_TYPE_OPENSSH_CERTIFICATE: return "openssh certificate";
        case XX_FILE_TYPE_SAFETENSORS: return "safetensors";
        case XX_FILE_TYPE_GGUF: return "gguf";
        case XX_FILE_TYPE_CDB_DATABASE: return "cdb database";
        case XX_FILE_TYPE_STOMP_FRAMES: return "stomp frames";
        case XX_FILE_TYPE_FONTFORGE_SFD: return "fontforge sfd";
        case XX_FILE_TYPE_GRUB_PFF2: return "grub pff2";
        case XX_FILE_TYPE_OPENGEX_MODEL: return "opengex model";
        case XX_FILE_TYPE_BVH_MOTION: return "bvh motion";
        case XX_FILE_TYPE_DIRECTX_X: return "directx x";
        case XX_FILE_TYPE_GTS_SURFACE: return "gts surface";
        case XX_FILE_TYPE_MEDIT_MESH: return "medit mesh";
        case XX_FILE_TYPE_GOCAD_MODEL: return "gocad model";
        case XX_FILE_TYPE_NASTRAN_BULK: return "nastran bulk";
        case XX_FILE_TYPE_ABAQUS_INPUT: return "abaqus input";
        case XX_FILE_TYPE_ENSIGHT_GOLD_GEOMETRY: return "ensight gold geometry";
        case XX_FILE_TYPE_GMV_MESH: return "gmv mesh";
        case XX_FILE_TYPE_USGS_DEM: return "usgs dem";
        case XX_FILE_TYPE_DTED_ELEVATION: return "dted elevation";
        case XX_FILE_TYPE_MAPINFO_MIF: return "mapinfo mif";
        case XX_FILE_TYPE_TRACKER_COCONIZER: return "tracker coconizer";
        case XX_FILE_TYPE_TRACKER_REAL: return "tracker real";
        case XX_FILE_TYPE_TRACKER_MEGATRACKER: return "tracker megatracker";
        case XX_FILE_TYPE_AMOS_MUSIC_BANK: return "amos music bank";
        case XX_FILE_TYPE_ADLIB_RAD: return "adlib rad";
        case XX_FILE_TYPE_ADLIB_AMD: return "adlib amd";
        case XX_FILE_TYPE_ADLIB_HSC: return "adlib hsc";
        case XX_FILE_TYPE_ADLIB_D00: return "adlib d00";
        case XX_FILE_TYPE_ADLIB_BNK: return "adlib bnk";
        case XX_FILE_TYPE_DOSBOX_DRO: return "dosbox dro";
        case XX_FILE_TYPE_GENOMICS_GENBANK: return "genomics genbank";
        case XX_FILE_TYPE_GENOMICS_EMBL: return "genomics embl";
        case XX_FILE_TYPE_GENOMICS_SWISSPROT: return "genomics swissprot";
        case XX_FILE_TYPE_ALIGNMENT_CLUSTAL: return "alignment clustal";
        case XX_FILE_TYPE_ALIGNMENT_STOCKHOLM: return "alignment stockholm";
        case XX_FILE_TYPE_ALIGNMENT_PHYLIP: return "alignment phylip";
        case XX_FILE_TYPE_ALIGNMENT_MAF: return "alignment maf";
        case XX_FILE_TYPE_ALIGNMENT_MAUVE: return "alignment mauve";
        case XX_FILE_TYPE_UCSC_NIB: return "ucsc nib";
        case XX_FILE_TYPE_ASSEMBLY_GFA: return "assembly gfa";
        case XX_FILE_TYPE_HTTP1_MESSAGE: return "http1 message";
        case XX_FILE_TYPE_WEBSOCKET_FRAMES: return "websocket frames";
        case XX_FILE_TYPE_COAP_MESSAGE: return "coap message";
        case XX_FILE_TYPE_STUN_MESSAGE: return "stun message";
        case XX_FILE_TYPE_DHCP_MESSAGE: return "dhcp message";
        case XX_FILE_TYPE_RADIUS_PACKET: return "radius packet";
        case XX_FILE_TYPE_SNMP_MESSAGE: return "snmp message";
        case XX_FILE_TYPE_LDAP_MESSAGE: return "ldap message";
        case XX_FILE_TYPE_TLS_RECORDS: return "tls records";
        case XX_FILE_TYPE_JKS_KEYSTORE: return "jks keystore";
        case XX_FILE_TYPE_JAVA_SERIALIZATION: return "java serialization";
        case XX_FILE_TYPE_X509_CRL: return "x509 crl";
        case XX_FILE_TYPE_OCSP_RESPONSE: return "ocsp response";
        case XX_FILE_TYPE_LMDB_DATA: return "lmdb data";
        case XX_FILE_TYPE_GDBM_DUMP: return "gdbm dump";
        case XX_FILE_TYPE_ADOBE_ACB: return "adobe acb";
        case XX_FILE_TYPE_JASC_PALETTE: return "jasc palette";
        case XX_FILE_TYPE_X11_XBM: return "x11 xbm";
        case XX_FILE_TYPE_JPEG2000_PGX: return "jpeg2000 pgx";
        case XX_FILE_TYPE_AMIGA_DISKOBJECT: return "amiga diskobject";
        case XX_FILE_TYPE_TEX_VF: return "tex vf";
        case XX_FILE_TYPE_ESRI_ASCII_GRID: return "esri ascii grid";
        case XX_FILE_TYPE_SURFER_GRID: return "surfer grid";
        case XX_FILE_TYPE_GXF_GRID: return "gxf grid";
        case XX_FILE_TYPE_OGC_WKT: return "ogc wkt";
        case XX_FILE_TYPE_STEP_PART21: return "step part21";
        case XX_FILE_TYPE_GERBER_RS274X: return "gerber rs274x";
        case XX_FILE_TYPE_EXCELLON_DRILL: return "excellon drill";
        case XX_FILE_TYPE_VRML_SCENE: return "vrml scene";
        case XX_FILE_TYPE_RENDERMAN_RIB: return "renderman rib";
        case XX_FILE_TYPE_ASYLUM_AMF: return "asylum amf";
        case XX_FILE_TYPE_TRACKER_STX: return "tracker stx";
        case XX_FILE_TYPE_TRACKER_DTM: return "tracker dtm";
        case XX_FILE_TYPE_TRACKER_SOUNDFX: return "tracker soundfx";
        case XX_FILE_TYPE_TRACKER_FUNK: return "tracker funk";
        case XX_FILE_TYPE_TRACKER_ARCHIMEDES: return "tracker archimedes";
        case XX_FILE_TYPE_PCE_PSI: return "pce psi";
        case XX_FILE_TYPE_PC98_D88: return "pc98 d88";
        case XX_FILE_TYPE_HXC_MFM: return "hxc mfm";
        case XX_FILE_TYPE_YAZE_YDSK: return "yaze ydsk";
        case XX_FILE_TYPE_LAMMPS_DATA: return "lammps data";
        case XX_FILE_TYPE_LAMMPS_DUMP: return "lammps dump";
        case XX_FILE_TYPE_SHELX_RES: return "shelx res";
        case XX_FILE_TYPE_TURBOMOLE_COORD: return "turbomole coord";
        case XX_FILE_TYPE_CHARMM_CRD: return "charmm crd";
        case XX_FILE_TYPE_CASTEP_CELL: return "castep cell";
        case XX_FILE_TYPE_CRYSTAL_FORT34: return "crystal fort34";
        case XX_FILE_TYPE_SIESTA_XV: return "siesta xv";
        case XX_FILE_TYPE_HARWELL_BOEING: return "harwell boeing";
        case XX_FILE_TYPE_OPENFOAM_POINTS: return "openfoam points";
        case XX_FILE_TYPE_MINECRAFT_NBT: return "minecraft nbt";
        case XX_FILE_TYPE_AMAZON_ION_BINARY: return "amazon ion binary";
        case XX_FILE_TYPE_LEVELDB_LOG: return "leveldb log";
        case XX_FILE_TYPE_DNS_MESSAGE: return "dns message";
        case XX_FILE_TYPE_ROCKSDB_BLOB: return "rocksdb blob";
        case XX_FILE_TYPE_MONGODB_WIRE: return "mongodb wire";
        case XX_FILE_TYPE_REDIS_RESP: return "redis resp";
        case XX_FILE_TYPE_MQTT_PACKETS: return "mqtt packets";
        case XX_FILE_TYPE_AMQP_FRAMES: return "amqp frames";
        case XX_FILE_TYPE_THRIFT_COMPACT: return "thrift compact";
        case XX_FILE_TYPE_X509_CERTIFICATE: return "x509 certificate";
        case XX_FILE_TYPE_PKCS10_CSR: return "pkcs10 csr";
        case XX_FILE_TYPE_PKCS12_PFX: return "pkcs12 pfx";
        case XX_FILE_TYPE_OPENSSH_PRIVATE_KEY: return "openssh private key";
        case XX_FILE_TYPE_KERBEROS_KEYTAB: return "kerberos keytab";
        case XX_FILE_TYPE_GIMP_GPL: return "gimp gpl";
        case XX_FILE_TYPE_GIMP_GGR: return "gimp ggr";
        case XX_FILE_TYPE_IRIDAS_CUBE_LUT: return "iridas cube lut";
        case XX_FILE_TYPE_HPGL_PLOT: return "hpgl plot";
        case XX_FILE_TYPE_PAINTSHOP_PSP: return "paintshop psp";
        case XX_FILE_TYPE_PHOTOSHOP_PAT: return "photoshop pat";
        case XX_FILE_TYPE_MMD_PMX: return "mmd pmx";
        case XX_FILE_TYPE_METASEQUOIA_MQO: return "metasequoia mqo";
        case XX_FILE_TYPE_CALMA_GDSII: return "calma gdsii";
        case XX_FILE_TYPE_AUTODESK_ASE: return "autodesk ase";
        case XX_FILE_TYPE_FREESURFER_SURFACE: return "freesurfer surface";
        case XX_FILE_TYPE_GMSH_MSH: return "gmsh msh";
        case XX_FILE_TYPE_NETGEN_VOL: return "netgen vol";
        case XX_FILE_TYPE_FONT_AFM: return "font afm";
        case XX_FILE_TYPE_TILED_TMX: return "tiled tmx";
        case XX_FILE_TYPE_NINTENDO_SDAT: return "nintendo sdat";
        case XX_FILE_TYPE_SONY_VAB: return "sony vab";
        case XX_FILE_TYPE_YAMAHA_YM: return "yamaha ym";
        case XX_FILE_TYPE_ZX_AYEMUL: return "zx ayemul";
        case XX_FILE_TYPE_DRAGON_VDK: return "dragon vdk";
        case XX_FILE_TYPE_APPLE_A2R: return "apple a2r";
        case XX_FILE_TYPE_ATARI_ATR: return "atari atr";
        case XX_FILE_TYPE_ATARI_PASTI_STX: return "atari pasti stx";
        case XX_FILE_TYPE_AMIGA_IPF: return "amiga ipf";
        case XX_FILE_TYPE_TRACKER_DTT: return "tracker dtt";
        case XX_FILE_TYPE_GAUSSIAN_CUBE: return "gaussian cube";
        case XX_FILE_TYPE_MOLECULE_XYZ: return "molecule xyz";
        case XX_FILE_TYPE_MDL_MOLFILE: return "mdl molfile";
        case XX_FILE_TYPE_TRIPOS_MOL2: return "tripos mol2";
        case XX_FILE_TYPE_XCRYSDEN_XSF: return "xcrysden xsf";
        case XX_FILE_TYPE_AMBER_PRMTOP: return "amber prmtop";
        case XX_FILE_TYPE_AMBER_RESTART: return "amber restart";
        case XX_FILE_TYPE_GAUSSIAN_FCHK: return "gaussian fchk";
        case XX_FILE_TYPE_JCAMP_DX: return "jcamp dx";
        case XX_FILE_TYPE_DL_POLY_CONFIG: return "dl poly config";
        case XX_FILE_TYPE_NIX_NAR: return "nix nar";
        case XX_FILE_TYPE_REDIS_RDB: return "redis rdb";
        case XX_FILE_TYPE_POSTGRES_CUSTOM: return "postgres custom";
        case XX_FILE_TYPE_MYSQL_BINLOG: return "mysql binlog";
        case XX_FILE_TYPE_KAFKA_RECORD_BATCH: return "kafka record batch";
        case XX_FILE_TYPE_ANDROID_BINARY_XML: return "android binary xml";
        case XX_FILE_TYPE_ANDROID_RESOURCES_ARSC: return "android resources arsc";
        case XX_FILE_TYPE_MSGPACK: return "msgpack";
        case XX_FILE_TYPE_UBJSON: return "ubjson";
        case XX_FILE_TYPE_BITTORRENT_METAINFO: return "bittorrent metainfo";
        case XX_FILE_TYPE_ERLANG_EXTERNAL_TERM: return "erlang external term";
        case XX_FILE_TYPE_CAPNPROTO_MESSAGE: return "capnproto message";
        case XX_FILE_TYPE_DBUS_MESSAGE: return "dbus message";
        case XX_FILE_TYPE_WINDOWS_SHELL_LINK: return "windows shell link";
        case XX_FILE_TYPE_PKCS7_CMS: return "pkcs7 cms";
        case XX_FILE_TYPE_WAVEFRONT_OBJ: return "wavefront obj";
        case XX_FILE_TYPE_OFF_MESH: return "off mesh";
        case XX_FILE_TYPE_AC3D_MODEL: return "ac3d model";
        case XX_FILE_TYPE_QUBICLE_QB: return "qubicle qb";
        case XX_FILE_TYPE_TERRAGEN_TER: return "terragen ter";
        case XX_FILE_TYPE_GIMP_XCF: return "gimp xcf";
        case XX_FILE_TYPE_PHOTOSHOP_ABR: return "photoshop abr";
        case XX_FILE_TYPE_SOFTIMAGE_PIC: return "softimage pic";
        case XX_FILE_TYPE_ALIAS_PIX: return "alias pix";
        case XX_FILE_TYPE_QT_QPICTURE: return "qt qpicture";
        case XX_FILE_TYPE_FONT_TYPE1_PFB: return "font type1 pfb";
        case XX_FILE_TYPE_FONT_GEM_FNT: return "font gem fnt";
        case XX_FILE_TYPE_TEX_GF: return "tex gf";
        case XX_FILE_TYPE_BPG_IMAGE: return "bpg image";
        case XX_FILE_TYPE_MNG_ANIMATION: return "mng animation";
        case XX_FILE_TYPE_ATARI_7800_A78: return "atari 7800 a78";
        case XX_FILE_TYPE_COMMODORE_PC64: return "commodore pc64";
        case XX_FILE_TYPE_ATARI_CAS: return "atari cas";
        case XX_FILE_TYPE_MSX_CAS: return "msx cas";
        case XX_FILE_TYPE_ORIC_TAP: return "oric tap";
        case XX_FILE_TYPE_DRAGON_CAS: return "dragon cas";
        case XX_FILE_TYPE_AMIGA_AHX: return "amiga ahx";
        case XX_FILE_TYPE_AMSTRAD_CPC_SNA: return "amstrad cpc sna";
        case XX_FILE_TYPE_VTECH_VZ: return "vtech vz";
        case XX_FILE_TYPE_ZX_HOBETA: return "zx hobeta";
        case XX_FILE_TYPE_GENOMICS_FASTA: return "genomics fasta";
        case XX_FILE_TYPE_GENOMICS_FASTQ: return "genomics fastq";
        case XX_FILE_TYPE_GENOMICS_SAM: return "genomics sam";
        case XX_FILE_TYPE_OPENDX_FIELD: return "opendx field";
        case XX_FILE_TYPE_GENOMICS_VCF: return "genomics vcf";
        case XX_FILE_TYPE_GENOMICS_GFF3: return "genomics gff3";
        case XX_FILE_TYPE_PROTEIN_PDB: return "protein pdb";
        case XX_FILE_TYPE_PROTEIN_MMCIF: return "protein mmcif";
        case XX_FILE_TYPE_MATRIX_MARKET: return "matrix market";
        case XX_FILE_TYPE_GROMACS_GRO: return "gromacs gro";
        case XX_FILE_TYPE_MICROSOFT_MSF: return "microsoft msf";
        case XX_FILE_TYPE_WINDOWS_REGISTRY_HIVE: return "windows registry hive";
        case XX_FILE_TYPE_WINDOWS_EVTX: return "windows evtx";
        case XX_FILE_TYPE_BINARY_PLIST: return "binary plist";
        case XX_FILE_TYPE_MONGODB_BSON: return "mongodb bson";
        case XX_FILE_TYPE_CBOR: return "cbor";
        case XX_FILE_TYPE_OPENZIM: return "openzim";
        case XX_FILE_TYPE_APACHE_ORC: return "apache orc";
        case XX_FILE_TYPE_HADOOP_SEQUENCEFILE: return "hadoop sequencefile";
        case XX_FILE_TYPE_LEVELDB_SSTABLE: return "leveldb sstable";
        case XX_FILE_TYPE_SNAPPY_FRAMED: return "snappy framed";
        case XX_FILE_TYPE_LZF_STREAM: return "lzf stream";
        case XX_FILE_TYPE_FASTLZ_SIXPACK: return "fastlz sixpack";
        case XX_FILE_TYPE_LINUX_BTF: return "linux btf";
        case XX_FILE_TYPE_FLATGEOBUF: return "flatgeobuf";
        case XX_FILE_TYPE_ASTC_TEXTURE: return "astc texture";
        case XX_FILE_TYPE_PKM_TEXTURE: return "pkm texture";
        case XX_FILE_TYPE_BASIS_TEXTURE: return "basis texture";
        case XX_FILE_TYPE_OPENCTM_MESH: return "openctm mesh";
        case XX_FILE_TYPE_FONT_BDF: return "font bdf";
        case XX_FILE_TYPE_FONT_PCF: return "font pcf";
        case XX_FILE_TYPE_FONT_PSF: return "font psf";
        case XX_FILE_TYPE_FONT_WINDOWS_FNT: return "font windows fnt";
        case XX_FILE_TYPE_TEX_TFM: return "tex tfm";
        case XX_FILE_TYPE_TEX_PK: return "tex pk";
        case XX_FILE_TYPE_TEX_DVI: return "tex dvi";
        case XX_FILE_TYPE_NETPBM_PFM: return "netpbm pfm";
        case XX_FILE_TYPE_STEINBERG_VST3PRESET: return "steinberg vst3preset";
        case XX_FILE_TYPE_FONT_BMFONT: return "font bmfont";
        case XX_FILE_TYPE_PROCESSING_VLW: return "processing vlw";
        case XX_FILE_TYPE_SNES_SPC: return "snes spc";
        case XX_FILE_TYPE_GAMEBOY_GBS: return "gameboy gbs";
        case XX_FILE_TYPE_SEGA_SGC: return "sega sgc";
        case XX_FILE_TYPE_S98_LOG: return "s98 log";
        case XX_FILE_TYPE_ATARI_SAP: return "atari sap";
        case XX_FILE_TYPE_SC68_MUSIC: return "sc68 music";
        case XX_FILE_TYPE_ZX_SPECTRUM_PZX: return "zx spectrum pzx";
        case XX_FILE_TYPE_ACORN_UEF: return "acorn uef";
        case XX_FILE_TYPE_NINTENDO_UNIF: return "nintendo unif";
        case XX_FILE_TYPE_NINTENDO_FDS: return "nintendo fds";
        case XX_FILE_TYPE_UCSC_BIGWIG: return "ucsc bigwig";
        case XX_FILE_TYPE_UCSC_BIGBED: return "ucsc bigbed";
        case XX_FILE_TYPE_PHYLO_NEXUS: return "phylo nexus";
        case XX_FILE_TYPE_PHYLO_NEWICK: return "phylo newick";
        case XX_FILE_TYPE_SQLITE_ROLLBACK_JOURNAL: return "sqlite rollback journal";
        case XX_FILE_TYPE_NEUROSCAN_CNT: return "neuroscan cnt";
        case XX_FILE_TYPE_AXONA_TETRODE: return "axona tetrode";
        case XX_FILE_TYPE_PYTHON_PICKLE: return "python pickle";
        case XX_FILE_TYPE_INIVATION_AEDAT: return "inivation aedat";
        case XX_FILE_TYPE_PYTHON_MARSHAL: return "python marshal";
        case XX_FILE_TYPE_VICE_X64: return "vice x64";
        case XX_FILE_TYPE_VICE_SNAPSHOT: return "vice snapshot";
        case XX_FILE_TYPE_COMMODORE_G64: return "commodore g64";
        case XX_FILE_TYPE_COMMODORE_P64: return "commodore p64";
        case XX_FILE_TYPE_COMMODORE_TAP: return "commodore tap";
        case XX_FILE_TYPE_ZX_SPECTRUM_TZX: return "zx spectrum tzx";
        case XX_FILE_TYPE_ZX_SPECTRUM_SZX: return "zx spectrum szx";
        case XX_FILE_TYPE_AMSTRAD_CPC_DSK: return "amstrad cpc dsk";
        case XX_FILE_TYPE_ATARI_ST_MSA: return "atari st msa";
        case XX_FILE_TYPE_SUPERCARD_SCP: return "supercard scp";
        case XX_FILE_TYPE_APPLE_WOZ: return "apple woz";
        case XX_FILE_TYPE_NINTENDO_NSF: return "nintendo nsf";
        case XX_FILE_TYPE_VGM_LOG: return "vgm log";
        case XX_FILE_TYPE_PSID_SID: return "psid sid";
        case XX_FILE_TYPE_HES_SOUND: return "hes sound";
        case XX_FILE_TYPE_AUDIO_DOLBY_AC3: return "audio dolby ac3";
        case XX_FILE_TYPE_AUDIO_MPEG_MP3: return "audio mpeg mp3";
        case XX_FILE_TYPE_AUDIO_AAC_ADTS: return "audio aac adts";
        case XX_FILE_TYPE_AUDIO_MONKEYS_APE: return "audio monkeys ape";
        case XX_FILE_TYPE_MPEG_TRANSPORT_STREAM: return "mpeg transport stream";
        case XX_FILE_TYPE_MPEG_PROGRAM_STREAM: return "mpeg program stream";
        case XX_FILE_TYPE_REALMEDIA_RM: return "realmedia rm";
        case XX_FILE_TYPE_IDTECH_ROQ: return "idtech roq";
        case XX_FILE_TYPE_RAD_BINK: return "rad bink";
        case XX_FILE_TYPE_RAD_SMACKER: return "rad smacker";
        case XX_FILE_TYPE_INTERPLAY_MVE: return "interplay mve";
        case XX_FILE_TYPE_WESTWOOD_VQA: return "westwood vqa";
        case XX_FILE_TYPE_AUTODESK_FLIC: return "autodesk flic";
        case XX_FILE_TYPE_IDTECH_MD5ANIM: return "idtech md5anim";
        case XX_FILE_TYPE_STEREOLITHOGRAPHY_STL: return "stereolithography stl";
        case XX_FILE_TYPE_GARMIN_FIT: return "garmin fit";
        case XX_FILE_TYPE_ROSBAG1: return "rosbag1";
        case XX_FILE_TYPE_MCAP: return "mcap";
        case XX_FILE_TYPE_SEISMIC_SAC: return "seismic sac";
        case XX_FILE_TYPE_SEISMIC_SEG2: return "seismic seg2";
        case XX_FILE_TYPE_UCSC_TWOBIT: return "ucsc twobit";
        case XX_FILE_TYPE_GENOMICS_BGEN: return "genomics bgen";
        case XX_FILE_TYPE_OPENEPHYS_CONTINUOUS: return "openephys continuous";
        case XX_FILE_TYPE_MOUNTAINSORT_MDA: return "mountainsort mda";
        case XX_FILE_TYPE_IGOR_IBW: return "igor ibw";
        case XX_FILE_TYPE_PRINCETON_SPE: return "princeton spe";
        case XX_FILE_TYPE_MICROSCOPY_SPIDER: return "microscopy spider";
        case XX_FILE_TYPE_WMO_GRIB: return "wmo grib";
        case XX_FILE_TYPE_WMO_BUFR: return "wmo bufr";
        case XX_FILE_TYPE_AUTOCAD_DXF: return "autocad dxf";
        case XX_FILE_TYPE_BLACKROCK_NSX: return "blackrock nsx";
        case XX_FILE_TYPE_BLACKROCK_NEV: return "blackrock nev";
        case XX_FILE_TYPE_LECROY_TRC: return "lecroy trc";
        case XX_FILE_TYPE_TEKTRONIX_ISF: return "tektronix isf";
        case XX_FILE_TYPE_IRCAM_SDIF: return "ircam sdif";
        case XX_FILE_TYPE_TRACKER_LIQUID: return "tracker dsm";
        case XX_FILE_TYPE_TRACKER_DMF: return "tracker dmf";
        case XX_FILE_TYPE_TRACKER_PTM: return "tracker ptm";
        case XX_FILE_TYPE_TRACKER_AMS: return "tracker ams";
        case XX_FILE_TYPE_TRACKER_DIGI: return "tracker digi";
        case XX_FILE_TYPE_TRACKER_EMOD: return "tracker emod";
        case XX_FILE_TYPE_TRACKER_MT2: return "tracker mt2";
        case XX_FILE_TYPE_AUDIO_DSF: return "audio dsf";
        case XX_FILE_TYPE_AUDIO_DFF: return "audio dff";
        case XX_FILE_TYPE_AUDIO_WAVE64: return "audio wave64";
        case XX_FILE_TYPE_AUDIO_ADX: return "audio adx";
        case XX_FILE_TYPE_AUDIO_AST: return "audio ast";
        case XX_FILE_TYPE_AUDIO_HCA: return "audio hca";
        case XX_FILE_TYPE_IFF_8SVX: return "iff 8svx";
        case XX_FILE_TYPE_AUDIO_WAVPACK: return "audio wavpack";
        case XX_FILE_TYPE_BLENDER_BLEND: return "blender blend";
        case XX_FILE_TYPE_AUTODESK_FBX: return "autodesk fbx";
        case XX_FILE_TYPE_AUTODESK_3DS: return "autodesk 3ds";
        case XX_FILE_TYPE_LIGHTWAVE_LWO2: return "lightwave lwo2";
        case XX_FILE_TYPE_LIGHTWAVE_MDD: return "lightwave mdd";
        case XX_FILE_TYPE_SONY_PSP_PBP: return "sony psp pbp";
        case XX_FILE_TYPE_FLASH_VIDEO_FLV: return "flash video flv";
        case XX_FILE_TYPE_NINTENDO_N64_ROM: return "nintendo n64 rom";
        case XX_FILE_TYPE_NINTENDO_GB_ROM: return "nintendo gb rom";
        case XX_FILE_TYPE_NINTENDO_GBA_ROM: return "nintendo gba rom";
        case XX_FILE_TYPE_SEGA_MEGADRIVE_ROM: return "sega megadrive rom";
        case XX_FILE_TYPE_SPRING_S3O: return "spring s3o";
        case XX_FILE_TYPE_XNA_XNB: return "xna xnb";
        case XX_FILE_TYPE_LUA_BYTECODE51: return "lua bytecode51";
        case XX_FILE_TYPE_QUAKE_MD5MESH: return "quake md5mesh";
        case XX_FILE_TYPE_TRACKER_MOD: return "tracker mod";
        case XX_FILE_TYPE_TRACKER_FAR: return "tracker far";
        case XX_FILE_TYPE_TRACKER_MDL: return "tracker mdl";
        case XX_FILE_TYPE_TRACKER_GDM: return "tracker gdm";
        case XX_FILE_TYPE_TRACKER_DBM: return "tracker dbm";
        case XX_FILE_TYPE_TRACKER_MED: return "tracker med";
        case XX_FILE_TYPE_TRACKER_IMF: return "tracker imf";
        case XX_FILE_TYPE_TRACKER_AMF: return "tracker amf";
        case XX_FILE_TYPE_TRACKER_PSM: return "tracker psm";
        case XX_FILE_TYPE_STEINBERG_FXB: return "steinberg fxb";
        case XX_FILE_TYPE_ASTRONOMY_SER: return "astronomy ser";
        case XX_FILE_TYPE_PHOTONTIMING_PTU: return "photontiming ptu";
        case XX_FILE_TYPE_PHOTONTIMING_PHU: return "photontiming phu";
        case XX_FILE_TYPE_CHARMM_DCD: return "charmm dcd";
        case XX_FILE_TYPE_GROMACS_TRR: return "gromacs trr";
        case XX_FILE_TYPE_MICROSCOPY_ICS: return "microscopy ics";
        case XX_FILE_TYPE_TECPLOT_PLT: return "tecplot plt";
        case XX_FILE_TYPE_FUJIFILM_RAF: return "fujifilm raf";
        case XX_FILE_TYPE_SIGMA_X3F: return "sigma x3f";
        case XX_FILE_TYPE_MINOLTA_MRW: return "minolta mrw";
        case XX_FILE_TYPE_SFX_IMP: return "sfx imp";
        case XX_FILE_TYPE_SFX_RED: return "sfx red";
        case XX_FILE_TYPE_SFX_HA: return "sfx ha";
        case XX_FILE_TYPE_SFX_LZX: return "sfx lzx";
        case XX_FILE_TYPE_SFX_SQX: return "sfx sqx";
        case XX_FILE_TYPE_SFX_AIN: return "sfx ain";
        case XX_FILE_TYPE_SFX_HAP: return "sfx hap";
        case XX_FILE_TYPE_SFX_ZOO: return "sfx zoo";
        case XX_FILE_TYPE_SFX_CAZIP: return "sfx cazip";
        case XX_FILE_TYPE_SFX_TGCF: return "sfx tgcf";
        case XX_FILE_TYPE_SFX_STARKIT: return "sfx starkit";
        case XX_FILE_TYPE_SFX_ALZ: return "sfx alz";
        case XX_FILE_TYPE_SFX_CHM: return "sfx chm";
        case XX_FILE_TYPE_EGG: return "egg";
        case XX_FILE_TYPE_NUFX: return "nufx";
        case XX_FILE_TYPE_NINTENDO_DOL: return "nintendo dol";
        case XX_FILE_TYPE_NINTENDO_J3D_BMD: return "nintendo j3d bmd";
        case XX_FILE_TYPE_NINTENDO_J3D_BTK: return "nintendo j3d btk";
        case XX_FILE_TYPE_NINTENDO_BRSTM: return "nintendo brstm";
        case XX_FILE_TYPE_NINTENDO_BRWAV: return "nintendo brwav";
        case XX_FILE_TYPE_NINTENDO_BRLYT: return "nintendo brlyt";
        case XX_FILE_TYPE_NINTENDO_BRLAN: return "nintendo brlan";
        case XX_FILE_TYPE_NINTENDO_BFSHA: return "nintendo bfsha";
        case XX_FILE_TYPE_CRI_USM: return "cri usm";
        case XX_FILE_TYPE_CRI_UTF: return "cri utf";
        case XX_FILE_TYPE_IDTECH_IQM: return "idtech iqm";
        case XX_FILE_TYPE_UNREAL_PSK: return "unreal psk";
        case XX_FILE_TYPE_UNREAL_PSA: return "unreal psa";
        case XX_FILE_TYPE_TORQUE_DTS: return "torque dts";
        case XX_FILE_TYPE_MAGICAVOXEL_VOX: return "magicavoxel vox";
        case XX_FILE_TYPE_AUDIO_AU: return "audio au";
        case XX_FILE_TYPE_CREATIVE_VOC: return "creative voc";
        case XX_FILE_TYPE_TRACKER_XM: return "tracker xm";
        case XX_FILE_TYPE_TRACKER_S3M: return "tracker s3m";
        case XX_FILE_TYPE_TRACKER_IT: return "tracker it";
        case XX_FILE_TYPE_TRACKER_MTM: return "tracker mtm";
        case XX_FILE_TYPE_TRACKER_STM: return "tracker stm";
        case XX_FILE_TYPE_TRACKER_669: return "tracker 669";
        case XX_FILE_TYPE_TRACKER_ULT: return "tracker ult";
        case XX_FILE_TYPE_TRACKER_OKT: return "tracker okt";
        case XX_FILE_TYPE_NIFTI2: return "nifti2";
        case XX_FILE_TYPE_LIDAR_LAS: return "lidar las";
        case XX_FILE_TYPE_ESRI_SHP: return "esri shp";
        case XX_FILE_TYPE_POLYGON_PLY: return "polygon ply";
        case XX_FILE_TYPE_POINTCLOUD_PCD: return "pointcloud pcd";
        case XX_FILE_TYPE_MATLAB_MAT4: return "matlab mat4";
        case XX_FILE_TYPE_SEISMIC_SEGY: return "seismic segy";
        case XX_FILE_TYPE_BIOMEDICAL_BDF: return "biomedical bdf";
        case XX_FILE_TYPE_ERLANG_BEAM: return "erlang beam";
        case XX_FILE_TYPE_JAVA_JMOD: return "java jmod";
        case XX_FILE_TYPE_SFX_ARCV2: return "sfx arcv2";
        case XX_FILE_TYPE_SFX_CHZ: return "sfx chz";
        case XX_FILE_TYPE_SFX_SZDD: return "sfx szdd";
        case XX_FILE_TYPE_SFX_MPQ: return "sfx mpq";
        case XX_FILE_TYPE_SFX_SWAG: return "sfx swag";
        case XX_FILE_TYPE_SFX_ZPAK: return "sfx zpak";
        case XX_FILE_TYPE_SFX_DISKEXPRESS: return "sfx diskexpress";
        case XX_FILE_TYPE_SFX_BZIP2: return "sfx bzip2";
        case XX_FILE_TYPE_SFX_GZIP: return "sfx gzip";
        case XX_FILE_TYPE_SFX_TAR: return "sfx tar";
        case XX_FILE_TYPE_SFX_CAB: return "sfx cab";
        case XX_FILE_TYPE_PMARC_SFX: return "pmarc sfx";
        case XX_FILE_TYPE_SFX_7ZIP: return "sfx 7zip";
        case XX_FILE_TYPE_SFX_ACE: return "sfx ace";
        case XX_FILE_TYPE_SFX_ZIPCENTRAL: return "sfx zipcentral";
        case XX_FILE_TYPE_SONY_PSX_EXE: return "sony psx exe";
        case XX_FILE_TYPE_SONY_PSF: return "sony psf";
        case XX_FILE_TYPE_XBOX_XDVDFS: return "xbox xdvdfs";
        case XX_FILE_TYPE_NINTENDO_WBFS: return "nintendo wbfs";
        case XX_FILE_TYPE_GODOT_CTEX: return "godot ctex";
        case XX_FILE_TYPE_UNITY_SERIALIZED: return "unity serialized";
        case XX_FILE_TYPE_IDTECH_MDL: return "idtech mdl";
        case XX_FILE_TYPE_VALVE_STUDIO_MDL: return "valve studio mdl";
        case XX_FILE_TYPE_BLITZ3D_B3D: return "blitz3d b3d";
        case XX_FILE_TYPE_MILKSHAPE_MS3D: return "milkshape ms3d";
        case XX_FILE_TYPE_NINTENDO_BCH: return "nintendo bch";
        case XX_FILE_TYPE_NINTENDO_CGFX: return "nintendo cgfx";
        case XX_FILE_TYPE_NINTENDO_BYAML: return "nintendo byaml";
        case XX_FILE_TYPE_RELIC_CHUNKY: return "relic chunky";
        case XX_FILE_TYPE_OGRE_MESH: return "ogre mesh";
        case XX_FILE_TYPE_ADOBE_ASE: return "adobe ase";
        case XX_FILE_TYPE_ADOBE_ACO: return "adobe aco";
        case XX_FILE_TYPE_GIMP_GBR: return "gimp gbr";
        case XX_FILE_TYPE_GIMP_GIH: return "gimp gih";
        case XX_FILE_TYPE_GIMP_PAT: return "gimp pat";
        case XX_FILE_TYPE_JBIG2: return "jbig2";
        case XX_FILE_TYPE_DJVU: return "djvu";
        case XX_FILE_TYPE_EMF: return "emf";
        case XX_FILE_TYPE_WMF: return "wmf";
        case XX_FILE_TYPE_XFIG: return "xfig";
        case XX_FILE_TYPE_NIFTI1: return "nifti1";
        case XX_FILE_TYPE_NRRD: return "nrrd";
        case XX_FILE_TYPE_MRC: return "mrc";
        case XX_FILE_TYPE_METAIMAGE: return "metaimage";
        case XX_FILE_TYPE_VTK_LEGACY: return "vtk legacy";
        case XX_FILE_TYPE_GIPL: return "gipl";
        case XX_FILE_TYPE_FREESURFER_MGH: return "freesurfer mgh";
        case XX_FILE_TYPE_EDF: return "edf";
        case XX_FILE_TYPE_FCS: return "fcs";
        case XX_FILE_TYPE_TENSORFLOW_TFRECORD: return "tensorflow tfrecord";
        case XX_FILE_TYPE_SFX_ARC: return "sfx arc";
        case XX_FILE_TYPE_SFX_ARJ: return "sfx arj";
        case XX_FILE_TYPE_SFX_BSN: return "sfx bsn";
        case XX_FILE_TYPE_SFX_ARQ: return "sfx arq";
        case XX_FILE_TYPE_SFX_GXL: return "sfx gxl";
        case XX_FILE_TYPE_SFX_ASYMETRIX: return "sfx asymetrix";
        case XX_FILE_TYPE_SFX_RTA: return "sfx rta";
        case XX_FILE_TYPE_SFX_RTPATCH: return "sfx rtpatch";
        case XX_FILE_TYPE_ESP_ARCHIVE: return "esp archive";
        case XX_FILE_TYPE_SFX_KWAJ: return "sfx kwaj";
        case XX_FILE_TYPE_GEMDOS_LHA: return "gemdos lha";
        case XX_FILE_TYPE_WINIMAGE_ZIP: return "winimage zip";
        case XX_FILE_TYPE_HP3000_WRQ: return "hp3000 wrq";
        case XX_FILE_TYPE_ICU_DATA_PACKAGE: return "icu data package";
        case XX_FILE_TYPE_SFX_SQZ: return "sfx sqz";
        case XX_FILE_TYPE_NINTENDO_BFSTM: return "nintendo bfstm";
        case XX_FILE_TYPE_NINTENDO_BFWAV: return "nintendo bfwav";
        case XX_FILE_TYPE_NINTENDO_BCWAV: return "nintendo bcwav";
        case XX_FILE_TYPE_NINTENDO_BFRES: return "nintendo bfres";
        case XX_FILE_TYPE_NINTENDO_BFLYT: return "nintendo bflyt";
        case XX_FILE_TYPE_NINTENDO_BCLYT: return "nintendo bclyt";
        case XX_FILE_TYPE_NINTENDO_BFNT: return "nintendo bfnt";
        case XX_FILE_TYPE_NINTENDO_BCFNT: return "nintendo bcfnt";
        case XX_FILE_TYPE_NINTENDO_3DSX: return "nintendo 3dsx";
        case XX_FILE_TYPE_SONY_TIM2: return "sony tim2";
        case XX_FILE_TYPE_SONY_PAMF: return "sony pamf";
        case XX_FILE_TYPE_SEGA_GVR: return "sega gvr";
        case XX_FILE_TYPE_MICROSOFT_XWB: return "microsoft xwb";
        case XX_FILE_TYPE_MICROSOFT_XSB: return "microsoft xsb";
        case XX_FILE_TYPE_RELIC_SGA: return "relic sga";
        case XX_FILE_TYPE_XPM: return "xpm";
        case XX_FILE_TYPE_PCX: return "pcx";
        case XX_FILE_TYPE_IFF_ILBM: return "iff ilbm";
        case XX_FILE_TYPE_UTAH_RLE: return "utah rle";
        case XX_FILE_TYPE_RADIANCE_HDR: return "radiance hdr";
        case XX_FILE_TYPE_DPX: return "dpx";
        case XX_FILE_TYPE_CINEON: return "cineon";
        case XX_FILE_TYPE_XWD: return "xwd";
        case XX_FILE_TYPE_SGI_RGB: return "sgi rgb";
        case XX_FILE_TYPE_ASEPRITE: return "aseprite";
        case XX_FILE_TYPE_NUMPY_NPY: return "numpy npy";
        case XX_FILE_TYPE_MATLAB_MAT5: return "matlab mat5";
        case XX_FILE_TYPE_NETCDF_CLASSIC: return "netcdf classic";
        case XX_FILE_TYPE_HDF4: return "hdf4";
        case XX_FILE_TYPE_DBASE_DBF: return "dbase dbf";
        case XX_FILE_TYPE_SAS_XPORT: return "sas xport";
        case XX_FILE_TYPE_SPSS_SAV: return "spss sav";
        case XX_FILE_TYPE_STATA_DTA: return "stata dta";
        case XX_FILE_TYPE_APACHE_ARROW_FILE: return "apache arrow file";
        case XX_FILE_TYPE_APACHE_PARQUET: return "apache parquet";
        case XX_FILE_TYPE_MAKESELF: return "makeself";
        case XX_FILE_TYPE_SUN_JAVA_BINSH: return "sun java binsh";
        case XX_FILE_TYPE_INSTALLANYWHERE_UNIX: return "installanywhere unix";
        case XX_FILE_TYPE_SFX_PACKAGEFORTHEWEB: return "sfx packagefortheweb";
        case XX_FILE_TYPE_SFX_SPIS: return "sfx spis";
        case XX_FILE_TYPE_SFX_LHA: return "sfx lha";
        case XX_FILE_TYPE_LMD_CONTAINER: return "lmd container";
        case XX_FILE_TYPE_TOTALANNIHILATION_HPI: return "totalannihilation hpi";
        case XX_FILE_TYPE_RAVENSOFT_RFF: return "ravensoft rff";
        case XX_FILE_TYPE_TERMINALREALITY_POD: return "terminalreality pod";
        case XX_FILE_TYPE_VOLITION_VPP: return "volition vpp";
        case XX_FILE_TYPE_KIRIKIRI_XP3: return "kirikiri xp3";
        case XX_FILE_TYPE_FROMSOFTWARE_BINDER: return "fromsoftware binder";
        case XX_FILE_TYPE_MYTHIC_MYP: return "mythic myp";
        case XX_FILE_TYPE_LITHTECH_REZ: return "lithtech rez";
        case XX_FILE_TYPE_NINTENDO_NCCH: return "nintendo ncch";
        case XX_FILE_TYPE_NINTENDO_NCSD: return "nintendo ncsd";
        case XX_FILE_TYPE_NINTENDO_CIA: return "nintendo cia";
        case XX_FILE_TYPE_NINTENDO_NDS: return "nintendo nds";
        case XX_FILE_TYPE_NINTENDO_GCM: return "nintendo gcm";
        case XX_FILE_TYPE_NINTENDO_TPL: return "nintendo tpl";
        case XX_FILE_TYPE_SONY_TIM: return "sony tim";
        case XX_FILE_TYPE_SONY_VAG: return "sony vag";
        case XX_FILE_TYPE_LARIAN_LSPK: return "larian lspk";
        case XX_FILE_TYPE_LARIAN_LSF: return "larian lsf";
        case XX_FILE_TYPE_VALVE_HPAK: return "valve hpak";
        case XX_FILE_TYPE_RENPY_RPA: return "renpy rpa";
        case XX_FILE_TYPE_UNREAL_PACKAGE: return "unreal package";
        case XX_FILE_TYPE_SEGA_PVR2: return "sega pvr2";
        case XX_FILE_TYPE_NINTENDO_BNTX: return "nintendo bntx";
        case XX_FILE_TYPE_ICNS: return "icns";
        case XX_FILE_TYPE_XCURSOR: return "xcursor";
        case XX_FILE_TYPE_ICC: return "icc";
        case XX_FILE_TYPE_QOI: return "qoi";
        case XX_FILE_TYPE_FARBFELD: return "farbfeld";
        case XX_FILE_TYPE_PNM: return "pnm";
        case XX_FILE_TYPE_TGA: return "tga";
        case XX_FILE_TYPE_SUN_RASTER: return "sun raster";
        case XX_FILE_TYPE_FITS: return "fits";
        case XX_FILE_TYPE_DICOM: return "dicom";
        case XX_FILE_TYPE_PCAP: return "pcap";
        case XX_FILE_TYPE_BTSNOOP: return "btsnoop";
        case XX_FILE_TYPE_JAVA_CLASS: return "java class";
        case XX_FILE_TYPE_SFNT_COLLECTION: return "sfnt collection";
        case XX_FILE_TYPE_SQLITE3: return "sqlite3";
        case XX_FILE_TYPE_SQLITE_WAL: return "sqlite wal";
        case XX_FILE_TYPE_AVRO_OBJECT: return "avro object";
        case XX_FILE_TYPE_GLB: return "glb";
        case XX_FILE_TYPE_SPIRV: return "spirv";
        case XX_FILE_TYPE_BETHESDA_BSA: return "bethesda bsa";
        case XX_FILE_TYPE_BETHESDA_BA2: return "bethesda ba2";
        case XX_FILE_TYPE_UNITYFS: return "unityfs";
        case XX_FILE_TYPE_BIOWARE_BIFF: return "bioware biff";
        case XX_FILE_TYPE_BIOWARE_ERF: return "bioware erf";
        case XX_FILE_TYPE_BIOWARE_RIM: return "bioware rim";
        case XX_FILE_TYPE_LUCAS_LAB: return "lucas lab";
        case XX_FILE_TYPE_LUCAS_BUN: return "lucas bun";
        case XX_FILE_TYPE_IDTECH_BSP: return "idtech bsp";
        case XX_FILE_TYPE_VALVE_BSP: return "valve bsp";
        case XX_FILE_TYPE_IDTECH_MD2: return "idtech md2";
        case XX_FILE_TYPE_IDTECH_MD3: return "idtech md3";
        case XX_FILE_TYPE_IDTECH_QVM: return "idtech qvm";
        case XX_FILE_TYPE_MOHAWK_MHK: return "mohawk mhk";
        case XX_FILE_TYPE_QUAKE_SPRITE: return "quake sprite";
        case XX_FILE_TYPE_NINTENDO_NARC: return "nintendo narc";
        case XX_FILE_TYPE_NINTENDO_SARC: return "nintendo sarc";
        case XX_FILE_TYPE_NINTENDO_PFS0: return "nintendo pfs0";
        case XX_FILE_TYPE_NINTENDO_HFS0: return "nintendo hfs0";
        case XX_FILE_TYPE_NINTENDO_BRRES: return "nintendo brres";
        case XX_FILE_TYPE_NINTENDO_BCSTM: return "nintendo bcstm";
        case XX_FILE_TYPE_NINTENDO_BFSAR: return "nintendo bfsar";
        case XX_FILE_TYPE_NINTENDO_BCSAR: return "nintendo bcsar";
        case XX_FILE_TYPE_SONY_PSARC: return "sony psarc";
        case XX_FILE_TYPE_KTX: return "ktx";
        case XX_FILE_TYPE_KTX2: return "ktx2";
        case XX_FILE_TYPE_DDS: return "dds";
        case XX_FILE_TYPE_PVR: return "pvr";
        case XX_FILE_TYPE_VALVE_VTF: return "valve vtf";
        case XX_FILE_TYPE_XBOX_XBE: return "xbox xbe";
        case XX_FILE_TYPE_FLAC: return "flac";
        case XX_FILE_TYPE_OGG: return "ogg";
        case XX_FILE_TYPE_MP4: return "mp4";
        case XX_FILE_TYPE_MATROSKA: return "matroska";
        case XX_FILE_TYPE_AIFF: return "aiff";
        case XX_FILE_TYPE_CAF: return "caf";
        case XX_FILE_TYPE_PHOTOSHOP_PSD: return "photoshop psd";
        case XX_FILE_TYPE_TIFF: return "tiff";
        case XX_FILE_TYPE_OPENEXR: return "openexr";
        case XX_FILE_TYPE_JPEG2000_JP2: return "jpeg2000 jp2";
        case XX_FILE_TYPE_ANDROID_VENDOR_BOOT: return "android vendor boot";
        case XX_FILE_TYPE_ANDROID_DTBO: return "android dtbo";
        case XX_FILE_TYPE_ANDROID_VBMETA: return "android vbmeta";
        case XX_FILE_TYPE_ESPRESSIF_IMAGE: return "espressif image";
        case XX_FILE_TYPE_WASM: return "wasm";
        case XX_FILE_TYPE_LLVM_BITCODE_WRAPPER: return "llvm bitcode wrapper";
        case XX_FILE_TYPE_DOTNET_METADATA: return "dotnet metadata";
        case XX_FILE_TYPE_SFNT: return "sfnt";
        case XX_FILE_TYPE_WOFF: return "woff";
        case XX_FILE_TYPE_WOFF2: return "woff2";
        case XX_FILE_TYPE_ACT_APRICOT_PC_XI_RAW: return "act apricot pc xi raw";
        case XX_FILE_TYPE_ADAM: return "adam";
        case XX_FILE_TYPE_BASE16: return "base16";
        case XX_FILE_TYPE_BONDWELL_2_DISK: return "bondwell 2 disk";
        case XX_FILE_TYPE_CASIO_FZ_1_DISK: return "casio fz 1 disk";
        case XX_FILE_TYPE_ISZ: return "isz";
        case XX_FILE_TYPE_MAME_FLOPPY_IMAGE_MFI: return "mame floppy image mfi";
        case XX_FILE_TYPE_PARALLELS_HDD: return "parallels hdd";
        case XX_FILE_TYPE_PC_MAGAZINE_FLP: return "pc magazine flp";
        case XX_FILE_TYPE_PCHROM: return "pchrom";
        case XX_FILE_TYPE_PEM: return "pem";
        case XX_FILE_TYPE_PRODOS: return "prodos";
        case XX_FILE_TYPE_QEMU_ENHANCED_DISK: return "qemu enhanced disk";
        case XX_FILE_TYPE_RAWCD: return "rawcd";
        case XX_FILE_TYPE_RSDOS_FS: return "rsdos fs";
        case XX_FILE_TYPE_SAR_NS: return "sar ns";
        case XX_FILE_TYPE_SWF: return "swf";
        case XX_FILE_TYPE_T64: return "t64";
        case XX_FILE_TYPE_UUE: return "uue";
        case XX_FILE_TYPE_VDI: return "vdi";
        case XX_FILE_TYPE_BMP: return "bmp";
        case XX_FILE_TYPE_CFE: return "cfe";
        case XX_FILE_TYPE_DXBC: return "dxbc";
        case XX_FILE_TYPE_GIF: return "gif";
        case XX_FILE_TYPE_JPEG: return "jpeg";
        case XX_FILE_TYPE_LINUX_ARM64: return "linuxarm64";
        case XX_FILE_TYPE_LINUXBOOT: return "linuxboot";
        case XX_FILE_TYPE_LINUX_ZIMAGE: return "linuxzimage";
        case XX_FILE_TYPE_PCAPNG: return "pcapng";
        case XX_FILE_TYPE_PJL: return "pjl";
        case XX_FILE_TYPE_PNG: return "png";
        case XX_FILE_TYPE_RIFF: return "riff";
        case XX_FILE_TYPE_SVG: return "svg";
        case XX_FILE_TYPE_QUAKE_PAK: return "quake pak";
        case XX_FILE_TYPE_MOZILLA_MAR: return "Mozilla MAR";
        case XX_FILE_TYPE_WESTWOOD_PAK: return "Westwood PAK";
        case XX_FILE_TYPE_FATX: return "Xbox FATX filesystem";
        case XX_FILE_TYPE_SOUNDFONT2: return "SoundFont 2";
        case XX_FILE_TYPE_IVF: return "IVF video";
        case XX_FILE_TYPE_WINDOWS_ANI: return "Windows animated cursor (ANI)";
        case XX_FILE_TYPE_INTERPLAY_ACM: return "Interplay ACM";
        case XX_FILE_TYPE_CRI_AHX: return "CRI AHX";
        case XX_FILE_TYPE_ADOBE_DIRECTOR_CXT: return "Adobe Director CXT";
        case XX_FILE_TYPE_OLYMPUS_DSS: return "Olympus DSS/DS2";
        case XX_FILE_TYPE_EA_EXA: return "EA EXA/SCHl audio";
        case XX_FILE_TYPE_AUDIO_NITRO_STRM: return "Nintendo DS STRM audio";
        case XX_FILE_TYPE_AUDIO_WWISE_WEM: return "Wwise WEM audio";
        case XX_FILE_TYPE_AUDIO_SCUMM_SOU: return "SCUMM SOU voice";
        case XX_FILE_TYPE_AUDIO_RIFF_IMA: return "RIFF IMA audio";
        case XX_FILE_TYPE_HMI_MIDI: return "HMI MIDI song";
        case XX_FILE_TYPE_ENSONIQ_PAF: return "Ensoniq PAF audio";
        case XX_FILE_TYPE_ABYLIGHT_STRM: return "Abylight 3DS STRM audio";
        case XX_FILE_TYPE_LEGO_ALP: return "LEGO Racers ALP/TUN audio";
        case XX_FILE_TYPE_AUDIO_PVF: return "Portable Voice Format audio";
        case XX_FILE_TYPE_AUDIO_RIFX_WAVE: return "RIFX big-endian WAVE audio";
        case XX_FILE_TYPE_AUDIO_SHOCKWAVE_SWA: return "Shockwave Audio (SWA)";
        case XX_FILE_TYPE_CKP: return "CKP game archive";
        case XX_FILE_TYPE_EDP: return "EdgeDataPak archive";
        case XX_FILE_TYPE_PARSEC_RIB: return "Parsec RIB compressed resource";
        case XX_FILE_TYPE_PARSEC_ARCHIVE: return "Parsec resource archive";
        case XX_FILE_TYPE_PARSEC_PMM: return "Parsec PSM 2.00 music module";
        case XX_FILE_TYPE_MACHOFAT: return "MACHOFAT";
        case XX_FILE_TYPE_CFBF: return "CFBF";
        case XX_FILE_TYPE_NUMBERED_SPLIT: return "Numbered split file";
        case XX_FILE_TYPE_PDF: return "PDF";
        case XX_FILE_TYPE_PYC: return "Python bytecode";
        case XX_FILE_TYPE_SFX_INFTOOL: return "sfx inftool";
        case XX_FILE_TYPE_AMIGA_EXT_ADF: return "amiga ext adf";
        case XX_FILE_TYPE_AMIGA_OLD_EXT_ADF: return "amiga old ext adf";
        case XX_FILE_TYPE_ATARI_DIM: return "atari dim";
        case XX_FILE_TYPE_ATARI_STT: return "atari stt";
        case XX_FILE_TYPE_ATARI_STW: return "atari stw";
        case XX_FILE_TYPE_DISCFERRET_DFI: return "discferret dfi";
        case XX_FILE_TYPE_HXC_AFI: return "hxc afi";
        case XX_FILE_TYPE_HXC_QD: return "hxc qd";
        case XX_FILE_TYPE_HXC_STREAM: return "hxc stream";
        case XX_FILE_TYPE_SVD: return "svd";
        case XX_FILE_TYPE_SDU: return "sdu";
        case XX_FILE_TYPE_FEI: return "fei";
        case XX_FILE_TYPE_ORIC_DSK: return "oric dsk";
        case XX_FILE_TYPE_ENSONIQ_GKH: return "ensoniq gkh";
        case XX_FILE_TYPE_ENSONIQ_EDE: return "ensoniq ede";
        case XX_FILE_TYPE_SAMCOUPE_SAD: return "samcoupe sad";
        case XX_FILE_TYPE_APPLE_NIB: return "apple nib";
        case XX_FILE_TYPE_TI99_PC99: return "ti99 pc99";
        case XX_FILE_TYPE_EMAX_DISK: return "emax disk";
        case XX_FILE_TYPE_EMULATORII_EII: return "emulatorii eii";
        case XX_FILE_TYPE_CASIO_FZF: return "casio fzf";
        case XX_FILE_TYPE_VTR_DISK: return "vtr disk";
        case XX_FILE_TYPE_SPECCYDOS_SDD: return "speccydos sdd";
        case XX_FILE_TYPE_HXC_RAW_FLOPPY: return "hxc raw floppy";
        case XX_FILE_TYPE_HXC_XML_DISK_LAYOUT: return "hxc xml disk layout";

        case XX_FILE_TYPE_PTERO_BIGF: return "Ptero-Engine BIGF/ZBL archive";
        case XX_FILE_TYPE_RVZ: return "Dolphin RVZ GameCube image";
#define XX_DIE_MUSIC_TYPE_NAME(type, name) case type: return name;
#include "die_music/xx_die_music_type_names.inc"
#undef XX_DIE_MUSIC_TYPE_NAME
        case XX_FILE_TYPE_DOOM_WAD: return "doom wad";
        case XX_FILE_TYPE_QUAKE_WAD2: return "quake wad2";
        case XX_FILE_TYPE_HALFLIFE_WAD3: return "halflife wad3";
        case XX_FILE_TYPE_BUILD_GRP: return "build grp";
        case XX_FILE_TYPE_CRI_AFS: return "cri afs";
        case XX_FILE_TYPE_CRI_AWB: return "cri awb";
        case XX_FILE_TYPE_VALVE_VPK: return "valve vpk";
        case XX_FILE_TYPE_NINTENDO_U8: return "nintendo u8";
        case XX_FILE_TYPE_NINTENDO_RARC: return "nintendo rarc";
        case XX_FILE_TYPE_ANDROID_AB: return "android ab";
        case XX_FILE_TYPE_NES_ROM: return "nes rom";
        case XX_FILE_TYPE_LYNX_LNX: return "lynx lnx";
        case XX_FILE_TYPE_COMMODORE_CRT: return "commodore crt";
        case XX_FILE_TYPE_UF2: return "uf2";
        case XX_FILE_TYPE_ICO: return "ico";
        case XX_FILE_TYPE_MIDI: return "midi";
        case XX_FILE_TYPE_ADVANCED_INSTALLER_BOOTSTRAPPER: return "Advanced Installer bootstrapper";
        case XX_FILE_TYPE_ARDI_INSTALLER: return "ARDI OS/2 installer";
        case XX_FILE_TYPE_ARNI_INSTALLER_CONTAINER: return "ARNI installer container";
        case XX_FILE_TYPE_EJ_TECHNOLOGIES_INSTALL: return "ej-technologies install4j / exe4j";
        case XX_FILE_TYPE_FINSTALL: return "F Install disk data";
        case XX_FILE_TYPE_GHOST_INSTALLER: return "Ghost Installer";
        case XX_FILE_TYPE_IBM_ZPAK_INSTALLER: return "IBM ZPAK installer";
        case XX_FILE_TYPE_IFAH_INSTALLER: return "IFAH installer package";
        case XX_FILE_TYPE_INNO_SETUP: return "Inno Setup";
        case XX_FILE_TYPE_INSTALLER_VISE_WINDOWS: return "Installer VISE for Windows";
        case XX_FILE_TYPE_INSTALLSHIELD_12_SETUP: return "InstallShield 12-2012 Setup";
        case XX_FILE_TYPE_INSTALLSHIELD_3: return "InstallShield 3.x/5.x SFX";
        case XX_FILE_TYPE_INSTALLSHIELD_7_SETUP: return "InstallShield 7 All-in-One Setup";
        case XX_FILE_TYPE_INSTALLSHIELD_7_SETUP2: return "InstallShield 7 setup.boot";
        case XX_FILE_TYPE_INSTALLSHIELD_DEVELOPER: return "InstallShield Developer 7";
        case XX_FILE_TYPE_INSTALLSHIELD_ISSETUPSTREAM: return "InstallShield ISSetupStream";
        case XX_FILE_TYPE_INSTALLSHIELD_MULTIPLATFORM: return "InstallShield MultiPlatform";
        case XX_FILE_TYPE_INSTALLSHIELD_SKIN: return "InstallShield skin";
        case XX_FILE_TYPE_MICROFOX_PUT: return "MicroFox PUT";
        case XX_FILE_TYPE_O_SETUP: return "O'Setup";
        case XX_FILE_TYPE_PC_INSTALL_SETUP: return "PC-Install";
        case XX_FILE_TYPE_PYINSTALLER_ONE_EXECUTABLE: return "PyInstaller CArchive";
        case XX_FILE_TYPE_QSETUP_INSTALLATION_SUITE: return "QSetup";
        case XX_FILE_TYPE_RTPATCH_SETUP_DATA: return "RTPatch Setup volume";
        case XX_FILE_TYPE_SETUP_FACTORY: return "Setup Factory";
        case XX_FILE_TYPE_SFX_EBOOK_COMPILER_EXECUTABLES: return "eBook Creator / SBook Builder";
        case XX_FILE_TYPE_SPOON_INSTALLER: return "Spoon Installer";
        case XX_FILE_TYPE_TARMA_INSTALLER: return "Tarma Installer";
        case XX_FILE_TYPE_ADF: return "Amiga ADF";
        case XX_FILE_TYPE_APM: return "Apple Partition Map";
        case XX_FILE_TYPE_VHDX: return "VHDX";
        case XX_FILE_TYPE_BASE64: return "Base64";
        case XX_FILE_TYPE_BTOA: return "btoa / Ascii85";
        case XX_FILE_TYPE_CHD: return "MAME CHD";
        case XX_FILE_TYPE_CHM: return "Microsoft CHM";
        case XX_FILE_TYPE_CLOOP: return "cloop / geom_uzip";
        case XX_FILE_TYPE_CUE: return "CDRWIN CUE sheet";
        case XX_FILE_TYPE_DAHUA_ZIP: return "Dahua ZIP firmware";
        case XX_FILE_TYPE_DMSFW: return "DMS swapped firmware";
        case XX_FILE_TYPE_EWF: return "Expert Witness / EnCase EWF v1";
        case XX_FILE_TYPE_GODOT_ENGINE_PCK: return "Godot PCK resource pack";
        case XX_FILE_TYPE_GPG_SIGNED: return "OpenPGP ZIP-compressed packet";
        case XX_FILE_TYPE_IHEX: return "Intel HEX image";
        case XX_FILE_TYPE_KWAJ: return "Microsoft KWAJ stream";
        case XX_FILE_TYPE_LBR: return "CP/M LU LBR library";
        case XX_FILE_TYPE_LZFSE: return "LZFSE / LZVN stream";
        case XX_FILE_TYPE_NRG: return "Nero NRG disc image";
        case XX_FILE_TYPE_PACKIT_MAC: return "Macintosh PackIt";
        case XX_FILE_TYPE_RPM: return "RPM package";
        case XX_FILE_TYPE_STUFFIT5: return "StuffIt 5 archive";
        case XX_FILE_TYPE_MSDOS: return "MSDOS";
        case XX_FILE_TYPE_SFX_ANALOGX_EMUCORE_FFS: return "AnalogX FFS";
        case XX_FILE_TYPE_SFX_KRZIP: return "KRZIP self-extractor";
        case XX_FILE_TYPE_SFX_WARPIN_PACKAGE: return "WarpIN package";
        case XX_FILE_TYPE_SFX_HCI_INSTALIT: return "HCI Instalit";
        case XX_FILE_TYPE_SFX_CLICKTEAM_MULTIMEDIA_FUSION: return "Clickteam Multimedia Fusion";
        case XX_FILE_TYPE_SFX_ABBYY_FINE_OBJECTS: return "ABBYY FineObjects";
        case XX_FILE_TYPE_SFX_FLASHJESTER_JUGGLOR: return "FlashJester Jugglor";
        case XX_FILE_TYPE_SFX_JGSOFT_DEPLOYMASTER_PACKAGE: return "JGsoft DeployMaster";
        case XX_FILE_TYPE_SFX_ARDI_DISKETTE_IMAGE: return "ARDI diskette image";
        case XX_FILE_TYPE_SFX_SBX_EXTRACTOR: return "SBX self-extractor";
        case XX_FILE_TYPE_PE32: return "PE32";
        case XX_FILE_TYPE_PE64: return "PE64";
        case XX_FILE_TYPE_DOTNET: return "DotNet";
        case XX_FILE_TYPE_BINARY: return "BINARY";
        case XX_FILE_TYPE_AIN: return "AIN";
        case XX_FILE_TYPE_ALDUS: return "ALDUS";
        case XX_FILE_TYPE_ALZ: return "ALZ";
        case XX_FILE_TYPE_AMPK: return "AMPK";
        case XX_FILE_TYPE_AODOS: return "AODOS";
        case XX_FILE_TYPE_ARCFS: return "ARCFS";
        case XX_FILE_TYPE_PDP11AR: return "PDP11AR";
        case XX_FILE_TYPE_ARTIPACK: return "ARTIPACK";
        case XX_FILE_TYPE_ARCV2: return "ARCV2";
        case XX_FILE_TYPE_ARCV4: return "ARCV4";
        case XX_FILE_TYPE_WARC: return "WARC";
        case XX_FILE_TYPE_ISO9660: return "ISO9660";
        case XX_FILE_TYPE_TRX: return "TRX";
        case XX_FILE_TYPE_SEAMA: return "SEAMA";
        case XX_FILE_TYPE_CHK: return "CHK";
        case XX_FILE_TYPE_PACKIMG: return "PACKIMG";
        case XX_FILE_TYPE_DLOB: return "DLOB";
        case XX_FILE_TYPE_WINCE: return "Windows CE binary image";
        case XX_FILE_TYPE_BINHDR: return "BIN firmware header";
        case XX_FILE_TYPE_RTK: return "RTK firmware header";
        case XX_FILE_TYPE_CSMAN: return "CSman DAT file";
        case XX_FILE_TYPE_VXWORKS: return "VxWorks symbol table";
        case XX_FILE_TYPE_UEFI_FV: return "UEFI firmware volume";
        case XX_FILE_TYPE_UEFI_CAPSULE: return "UEFI capsule";
        case XX_FILE_TYPE_QCOW: return "QCOW";
        case XX_FILE_TYPE_QNX6: return "QNX6";
        case XX_FILE_TYPE_LUKS: return "LUKS";
        case XX_FILE_TYPE_APFS: return "APFS";
        case XX_FILE_TYPE_BTRFS: return "Btrfs";
        case XX_FILE_TYPE_LOGFS: return "LogFS";
        case XX_FILE_TYPE_DMG: return "DMG";
        case XX_FILE_TYPE_DMS: return "DMS";
        case XX_FILE_TYPE_XAMARIN_COMPRESSED_ASSEMBLY: return "Xamarin compressed assembly (XALZ)";
        case XX_FILE_TYPE_X68000_DIM: return "X68000 DIM floppy image";
        case XX_FILE_TYPE_VISIONAIRE_STUDIO_VIS: return "Visionaire Studio VIS";
        case XX_FILE_TYPE_UHARC: return "UHARC";
        case XX_FILE_TYPE_TRS_80_JV3: return "TRS-80 JV3";
        case XX_FILE_TYPE_TRS_80_JV1: return "TRS-80 JV1";
        case XX_FILE_TYPE_T98_NEXT_NFD: return "T98-Next NFD";
        case XX_FILE_TYPE_STUFFIT_SPLIT_FILE: return "StuffIt split file";
        case XX_FILE_TYPE_RDB: return "Amiga Rigid Disk Block (RDB) hard disk";
        case XX_FILE_TYPE_QNAP_NAS_FIRMWARE: return "QNAP NAS firmware";
        case XX_FILE_TYPE_QCOW1: return "QCOW1";
        case XX_FILE_TYPE_NSA: return "NScripter NSA archive";
        case XX_FILE_TYPE_NS2: return "NScripter NS2 archive";
        case XX_FILE_TYPE_NEC_PC_98_FDI: return "NEC PC-98 FDI";
        case XX_FILE_TYPE_MS_DOS_BACKUP: return "MS-DOS BACKUP (v2.0-3.2)";
        case XX_FILE_TYPE_HXC_STREAM_HFE: return "HxC Stream HFE";
        case XX_FILE_TYPE_ENCRYPTED_APPLE_DISK_IMAGE: return "Encrypted Apple disk image";
        case XX_FILE_TYPE_APPLE_SPARSE_BUNDLE: return "Apple sparse bundle";
        case XX_FILE_TYPE_APPLE_DISK_COPY_6_NDIF_IMAGE: return "Apple Disk Copy 6 NDIF image";
        case XX_FILE_TYPE_RAW_DEFLATE_COMPRESSED_DATA: return "Raw Deflate";
        case XX_FILE_TYPE_LZOP: return "LZOP";
        case XX_FILE_TYPE_SREC: return "Motorola S-record";
        case XX_FILE_TYPE_DCLRAW: return "DCLMultiStream";
        case XX_FILE_TYPE_XPAK: return "XPAK";
        case XX_FILE_TYPE_PDB: return "Palm PDB";
        case XX_FILE_TYPE_INFOGRAMESFT: return "Infogrames PAK";
        case XX_FILE_TYPE_UBOOT_ENV: return "U-Boot environment";
        case XX_FILE_TYPE_TWRX: return "TWRX";
        case XX_FILE_TYPE_TPLINK: return "TP-Link firmware";
        case XX_FILE_TYPE_SILMARILSFT: return "Silmarils";
        case XX_FILE_TYPE_SHRS: return "D-Link SHRS";
        case XX_FILE_TYPE_MH01: return "D-Link MH01";
        case XX_FILE_TYPE_MATTER_OTA: return "Matter OTA image";
        case XX_FILE_TYPE_LZ4DEMO: return "LZ4Demo";
        case XX_FILE_TYPE_LINGVOARC: return "LingvoArc";
        case XX_FILE_TYPE_JBOOT: return "JBOOT";
        case XX_FILE_TYPE_ENCRPTED_IMG: return "D-Link encrpted_img";
        case XX_FILE_TYPE_ENCFW: return "D-Link encfw encrypted firmware";
        case XX_FILE_TYPE_ECOS: return "eCos kernel";
        case XX_FILE_TYPE_DLKE: return "DLKE";
        case XX_FILE_TYPE_DLINK_TLV: return "D-Link TLV firmware";
        case XX_FILE_TYPE_DKBS: return "DKBS";
        case XX_FILE_TYPE_AUTEL: return "AUTEL";
        case XX_FILE_TYPE_ARCADYAN: return "Arcadyan obfuscated LZMA";
        case XX_FILE_TYPE_ANDROIDBOOT: return "Android boot image";
        case XX_FILE_TYPE_RAWSTAC: return "RawStac";
        case XX_FILE_TYPE_VMSSAVESET: return "VMSSaveset";
        case XX_FILE_TYPE_BOO: return "BOO";
        case XX_FILE_TYPE_WOLFFT: return "Wolf";
        case XX_FILE_TYPE_SETTLERSFT: return "Settlers";
        case XX_FILE_TYPE_TEACY: return "Teacy";
        case XX_FILE_TYPE_RSC: return "RSC";
        case XX_FILE_TYPE_RES: return "RES";
        case XX_FILE_TYPE_BSN: return "BSN";
        case XX_FILE_TYPE_WINTERMUTEDCP: return "WintermuteDCP";
        case XX_FILE_TYPE_VOLITIONVPFT: return "VolitionVP";
        case XX_FILE_TYPE_AGIS: return "AGIS";
        case XX_FILE_TYPE_HOG: return "HOG";
        case XX_FILE_TYPE_LZPIS2: return "LZPIS2";
        case XX_FILE_TYPE_RNCA: return "RNCA";
        case XX_FILE_TYPE_PAPERPORT: return "PaperPort";
        case XX_FILE_TYPE_STARKIT: return "Starkit";
        case XX_FILE_TYPE_LSPACK10: return "LSPack10";
        case XX_FILE_TYPE_IXA: return "IXA";
        case XX_FILE_TYPE_MLB_FT: return "MLB_FT";
        case XX_FILE_TYPE_FSS: return "FSS";
        case XX_FILE_TYPE_EPF: return "EPF";
        case XX_FILE_TYPE_DFC: return "DFC";
        case XX_FILE_TYPE_PPD: return "PPD";
        case XX_FILE_TYPE_SFX_AD01: return "SFX AD01";
        case XX_FILE_TYPE_SFX_NSS: return "SFX NSS";
        case XX_FILE_TYPE_SFX_RSFX: return "SFX RSFX";
        case XX_FILE_TYPE_SFX_SOFTPAQ4: return "Compaq SoftPaq 4";
        case XX_FILE_TYPE_KA: return "KA";
        case XX_FILE_TYPE_NEXTSTEP_DISKIMAGE: return "NeXTSTEP disk image";
        case XX_FILE_TYPE_DN: return "DN";
        case XX_FILE_TYPE_INSA: return "INSA";
        case XX_FILE_TYPE_SFX_VMS_DCX: return "SFX VMS DCX";
        case XX_FILE_TYPE_OBERON: return "Oberon";
        case XX_FILE_TYPE_SOLITAIRE_DELUXE: return "Solitaire Deluxe";
        case XX_FILE_TYPE_THEBAT_MSB: return "The Bat! MSB";
        case XX_FILE_TYPE_SFX_LOCALZIP: return "SFX embedded archive";
        case XX_FILE_TYPE_LIF: return "LIF";
        case XX_FILE_TYPE_QIP2: return "QIP2";
        case XX_FILE_TYPE_EMT: return "EMT";
        case XX_FILE_TYPE_BAGF: return "BAGF";
        case XX_FILE_TYPE_WRZL: return "WRZL";
        case XX_FILE_TYPE_SPK: return "SPK";
        case XX_FILE_TYPE_STAC: return "Stac";
        case XX_FILE_TYPE_DBZ: return "DBZ";
        case XX_FILE_TYPE_SQUEEZE2: return "Squeeze2";
        case XX_FILE_TYPE_SQ: return "SQ";
        case XX_FILE_TYPE_PHAR: return "Phar";
        case XX_FILE_TYPE_MPQ: return "MPQ";
        case XX_FILE_TYPE_SABDU: return "SABDU";
        case XX_FILE_TYPE_APRICOT: return "Apricot";
        case XX_FILE_TYPE_HDCOPY: return "HDCopy";
        case XX_FILE_TYPE_COPYDISK: return "CopyDisk";
        case XX_FILE_TYPE_CISO: return "CISO";
        case XX_FILE_TYPE_CISO2: return "CISO v2";
        case XX_FILE_TYPE_ZISO: return "ZISO";
        case XX_FILE_TYPE_DAX: return "DAX compressed ISO";
        case XX_FILE_TYPE_MYZ80: return "MYZ80 disk image";
        case XX_FILE_TYPE_NANOWASP: return "NanoWasp Microbee disk image";
        case XX_FILE_TYPE_GOTEK: return "Gotek disk collection";
        case XX_FILE_TYPE_VMDK: return "VMDK";
        case XX_FILE_TYPE_VHDDYNAMIC: return "VHDDynamic";
        case XX_FILE_TYPE_WIM: return "WIM";
        case XX_FILE_TYPE_SOFTPAQ2: return "SoftPaq2";
        case XX_FILE_TYPE_AIAFF: return "AIAFF";
        case XX_FILE_TYPE_GXL: return "GXL";
        case XX_FILE_TYPE_SHRINKWRAP: return "ShrinkWrap";
        case XX_FILE_TYPE_RED: return "RED";
        case XX_FILE_TYPE_DISKEXPRESS: return "DiskExpress";
        case XX_FILE_TYPE_CPX: return "CPX";
        case XX_FILE_TYPE_CPX4: return "CPX4";
        case XX_FILE_TYPE_SMSIPAK: return "SMSIPAK";
        case XX_FILE_TYPE_BND: return "BND";
        case XX_FILE_TYPE_CAT: return "CAT";
        case XX_FILE_TYPE_CSIDOS: return "CSIDOS";
        case XX_FILE_TYPE_BINDER: return "Binder";
        case XX_FILE_TYPE_JASC: return "JASC";
        case XX_FILE_TYPE_RECOGNITA: return "Recognita";
        case XX_FILE_TYPE_SCF: return "SCF";
        case XX_FILE_TYPE_BCW: return "BCW";
        case XX_FILE_TYPE_BVRP: return "BVRP";
        case XX_FILE_TYPE_SSM: return "SSM";
        case XX_FILE_TYPE_MDCD: return "MDCD";
        case XX_FILE_TYPE_XLAS: return "XLAS";
        case XX_FILE_TYPE_PAIN: return "PAIN";
        case XX_FILE_TYPE_QRST: return "QRST";
        case XX_FILE_TYPE_OPC: return "OPC";
        case XX_FILE_TYPE_TNEF: return "TNEF";
        case XX_FILE_TYPE_MCC: return "MCC";
        case XX_FILE_TYPE_NOTETAB: return "NoteTab";
        case XX_FILE_TYPE_STUNTS: return "Stunts";
        case XX_FILE_TYPE_MEGATECHVOL: return "MegatechVol";
        case XX_FILE_TYPE_GRASP: return "GRASP";
        case XX_FILE_TYPE_PSN: return "PSNCompress";
        case XX_FILE_TYPE_SINNER: return "Sinner";
        case XX_FILE_TYPE_HOG2: return "HOG2";
        case XX_FILE_TYPE_PCXLIB: return "PCXLib";
        case XX_FILE_TYPE_VMSDB: return "VMSDatabase";
        case XX_FILE_TYPE_VMSPCSI: return "VMSPCSI";
        case XX_FILE_TYPE_BEOSPKG: return "BeOSPackage";
        case XX_FILE_TYPE_SOLARISPKG: return "SolarisPackage";
        case XX_FILE_TYPE_PAX: return "PAX";
        case XX_FILE_TYPE_COPYQMEXE: return "CopyQMOverlay";
        case XX_FILE_TYPE_DISKJUGGLER: return "DiskJuggler";
        case XX_FILE_TYPE_PMDISKCOPY: return "PMDiskcopy";
        case XX_FILE_TYPE_DISKDUPE: return "DiskDupe";
        case XX_FILE_TYPE_IMD: return "IMD";
        case XX_FILE_TYPE_TWOIMG: return "2IMG";
        case XX_FILE_TYPE_FDI: return "FDI";
        case XX_FILE_TYPE_HFE: return "HFE";
        case XX_FILE_TYPE_TELEDISK: return "TeleDisk";
        case XX_FILE_TYPE_COPYQM: return "CopyQM";
        case XX_FILE_TYPE_PCINSTALL: return "PCInstall";
        case XX_FILE_TYPE_GKSETUP: return "GkSetup";
        case XX_FILE_TYPE_IS11: return "IS11";
        case XX_FILE_TYPE_IZPACK: return "IzPack";
        case XX_FILE_TYPE_SQUEEZE1: return "Squeeze1";
        case XX_FILE_TYPE_TRDOS: return "TRDOS";
        case XX_FILE_TYPE_LIFKD: return "LIFKD";
        case XX_FILE_TYPE_ARCV: return "ARCV";
        case XX_FILE_TYPE_CPOINT: return "CPOINT";
        case XX_FILE_TYPE_COMPAQLZH: return "CompaqLZH";
        case XX_FILE_TYPE_LZK00: return "LZK00";
        case XX_FILE_TYPE_PMA: return "PMA";
        case XX_FILE_TYPE_BINHEX: return "BinHex";
        case XX_FILE_TYPE_BINARYII: return "BinaryII";
        case XX_FILE_TYPE_STUFFIT: return "StuffIt";
        case XX_FILE_TYPE_DCLFT: return "DCLStream";
        case XX_FILE_TYPE_DEBUGSCR: return "DebugScript";
        case XX_FILE_TYPE_GOB: return "GOB";
        case XX_FILE_TYPE_SAVEDSKF: return "SaveDskF";
        case XX_FILE_TYPE_EDILZSS: return "EDILZSS";
        case XX_FILE_TYPE_IS7INX: return "IS7INX";
        case XX_FILE_TYPE_IS5: return "IS5";
        case XX_FILE_TYPE_IS3: return "IS3";
        case XX_FILE_TYPE_PSDC: return "PSDC";
        case XX_FILE_TYPE_UNIX_COMPACT: return "UnixCompact";
        case XX_FILE_TYPE_SCO: return "SCO";
        case XX_FILE_TYPE_GPFPACK: return "GPFPACK";
        case XX_FILE_TYPE_FTCOMP: return "FTCOMP";
        case XX_FILE_TYPE_WINLINK: return "WinLink";
        case XX_FILE_TYPE_GST: return "GST";
        case XX_FILE_TYPE_FINEAR: return "FinEAR";
        case XX_FILE_TYPE_MWAVE: return "Mwave";
        case XX_FILE_TYPE_XORARCHIVE: return "XORArchive";
        case XX_FILE_TYPE_MXS: return "MXS";
        case XX_FILE_TYPE_EDC: return "EDC";
        case XX_FILE_TYPE_MRNZ: return "MRNZ";
        case XX_FILE_TYPE_TPWM: return "TPWM";
        case XX_FILE_TYPE_CAZIP: return "CAZIP";
        case XX_FILE_TYPE_IBMPACK: return "IBMPACK";
        case XX_FILE_TYPE_RNC: return "RNC";
        case XX_FILE_TYPE_SHAR: return "SHAR";
        case XX_FILE_TYPE_NETWARE2: return "NetWare2";
        case XX_FILE_TYPE_MATHCAD: return "MathCAD";
        case XX_FILE_TYPE_PERFORM: return "PerFORM";
        case XX_FILE_TYPE_BATTLEISLE: return "BattleIsle";
        case XX_FILE_TYPE_KPCK: return "KPCK";
        case XX_FILE_TYPE_BEATTHEHOUSE: return "BeatTheHouse";
        case XX_FILE_TYPE_PP20: return "PP20";
        case XX_FILE_TYPE_MACBINARY: return "MacBinary";
        case XX_FILE_TYPE_APPLESINGLE: return "AppleSingle";
        case XX_FILE_TYPE_RESOURCEFORK: return "ResourceFork";
        case XX_FILE_TYPE_CRAMFS: return "CRAMFS";
        case XX_FILE_TYPE_JFFS2: return "JFFS2";
        case XX_FILE_TYPE_YAFFS: return "YAFFS";
        case XX_FILE_TYPE_UBI: return "UBI";
        case XX_FILE_TYPE_UBIFS: return "UBIFS";
        case XX_FILE_TYPE_EXT: return "ext2/3/4";
        case XX_FILE_TYPE_FAT: return "FAT";
        case XX_FILE_TYPE_MBR: return "MBR";
        case XX_FILE_TYPE_GPT: return "GPT";
        case XX_FILE_TYPE_SPARSE: return "Android sparse image";
        case XX_FILE_TYPE_UIMAGE: return "U-Boot uImage";
        case XX_FILE_TYPE_DTB: return "Device Tree Blob";
        case XX_FILE_TYPE_SQUASHFS: return "SquashFS";
        case XX_FILE_TYPE_NTFS: return "NTFS";
        case XX_FILE_TYPE_UDF: return "UDF";
        case XX_FILE_TYPE_ROMFS: return "ROMFS";
        case XX_FILE_TYPE_SQZ: return "SQZ";
        case XX_FILE_TYPE_TOPSPEED: return "TopSpeed";
        case XX_FILE_TYPE_TPS: return "TPS";
        case XX_FILE_TYPE_ULEAD: return "ULEAD";
        case XX_FILE_TYPE_QUANTUM: return "Quantum archive";
        case XX_FILE_TYPE_ZXZIP: return "ZXZIP";
        case XX_FILE_TYPE_ZOOM: return "Zoom disk image";
        case XX_FILE_TYPE_SFPACK: return "SFPack";
        case XX_FILE_TYPE_CLAYLZ: return "CLAYLZ";
        case XX_FILE_TYPE_C64WRAPTOR: return "C64WRAPTOR";
        case XX_FILE_TYPE_CORELLTEC: return "CORELLTEC";
        case XX_FILE_TYPE_PCSECURE: return "PCSECURE";
        case XX_FILE_TYPE_RSVK: return "RSVK";
        case XX_FILE_TYPE_RAW_LZW15V: return "RAW_LZW15V";
        case XX_FILE_TYPE_SAF: return "SAF";
        case XX_FILE_TYPE_SLS: return "SLS";
        case XX_FILE_TYPE_NID: return "NID";
        case XX_FILE_TYPE_GAMOS: return "GAMOS";
        case XX_FILE_TYPE_PANORAMA: return "PANORAMA";
        case XX_FILE_TYPE_FPAK: return "FPAK";
        case XX_FILE_TYPE_TAR_LZ4: return "TAR.LZ4";
        case XX_FILE_TYPE_LZ4: return "LZ4";
        case XX_FILE_TYPE_LZ5: return "LZ5";
        case XX_FILE_TYPE_LIZARD: return "LIZARD";
        case XX_FILE_TYPE_BROTLI: return "BROTLI";
        case XX_FILE_TYPE_ARJ: return "ARJ";
        case XX_FILE_TYPE_CAB: return "CAB";
        case XX_FILE_TYPE_AIXBFF: return "BFF";
        case XX_FILE_TYPE_ARX: return "ARX";
        case XX_FILE_TYPE_ELF32: return "ELF32";
        case XX_FILE_TYPE_ELF64: return "ELF64";
        case XX_FILE_TYPE_MACHO32: return "MACH-O32";
        case XX_FILE_TYPE_MACHO64: return "MACH-O64";
        case XX_FILE_TYPE_NE: return "NE";
        case XX_FILE_TYPE_LE: return "LE";
        case XX_FILE_TYPE_LX: return "LX";
        case XX_FILE_TYPE_DEX: return "DEX";
        default:                 return "UNKNOWN";
    }
}
