/* SPDX-License-Identifier: MIT. Fifteenth private typed framing primitives. */
#ifndef XX_FIFTEENTH_WRAPPERS_H
#define XX_FIFTEENTH_WRAPPERS_H
#include "xx_fourteenth_wrappers.h"
static bool f15_ascii(nh_blob *b,uint64_t at,uint64_t n,bool space){if(!n||n>65536||!nh_span(b,at,n))return false;for(uint64_t i=0;i<n;++i){uint8_t c=b->p[(size_t)(at+i)];if(c<(space?32:33)||c>126)return false;}return true;}
static bool f15_utf(nh_blob *b,uint64_t at,uint64_t n){if(!n||n>65536||!ec_utf(b,at,n))return false;for(uint64_t i=0;i<n;++i)if(!b->p[(size_t)(at+i)]||b->p[(size_t)(at+i)]==127||b->p[(size_t)(at+i)]<32)return false;return true;}
static uint32_t f15_sum(nh_blob *b,uint64_t at,uint64_t n,uint32_t sum){if(!nh_span(b,at,n))return UINT32_MAX;for(uint64_t i=0;i<n;i+=2){if((i&65535)==0&&fd_stop(b->pd))return UINT32_MAX;sum+=(uint32_t)b->p[(size_t)(at+i)]<<8;if(i+1<n)sum+=b->p[(size_t)(at+i+1)];sum=(sum&65535)+(sum>>16);}return sum;}
static bool f15_checksum(nh_blob *b,uint64_t at,uint64_t n,uint32_t sum){sum=f15_sum(b,at,n,sum);if(sum==UINT32_MAX)return false;while(sum>>16)sum=(sum&65535)+(sum>>16);return sum==65535;}
static bool f15_ip(nh_blob *b,uint64_t start,uint64_t n,uint64_t *header){uint64_t h;uint32_t sum=0;unsigned version;if(n<28||n>65575||!nh_span(b,start,n))return false;version=b->p[(size_t)start]>>4;if(version==4){h=(uint64_t)(b->p[(size_t)start]&15)*4;if(h<20||h>60||h+8>=n||pm_be16(b->p+(size_t)start+2)!=n||(pm_be16(b->p+(size_t)start+6)&0xbfff)||!b->p[(size_t)start+8]||b->p[(size_t)start+9]!=17||!f15_checksum(b,start,h,0))return false;uint64_t p=start+20;while(p<start+h){unsigned t=b->p[(size_t)p++];if(!t){if(!nh_zero(b,p,start+h-p))return false;break;}if(t==1)continue;if(p==start+h)return false;unsigned z=b->p[(size_t)p++];if(z<2||!th_take(b,&p,start+h,z-2))return false;}sum=f15_sum(b,start+12,8,0);}else if(version==6){h=40;if(n<=48||pm_be16(b->p+(size_t)start+4)!=n-40||b->p[(size_t)start+6]!=17||!b->p[(size_t)start+7])return false;sum=f15_sum(b,start+8,32,0);}else return false;uint64_t u=start+h,un=n-h;if(pm_be16(b->p+(size_t)u+4)!=un||!pm_be16(b->p+(size_t)u)||!pm_be16(b->p+(size_t)u+2)||!pm_be16(b->p+(size_t)u+6))return false;sum+=17+(uint32_t)un;if(!f15_checksum(b,u,un,sum))return false;*header=h;return true;}
static bool f15_ip_add(Abstractformat *f,pm_stream *s,nh_blob *b,uint64_t start,uint64_t n){uint64_t h;if(!f15_ip(b,start,n,&h))return false;return nh_add(f,s,b,"ip-header",start,h)&&nh_add(f,s,b,"udp-header",start+h,8)&&nh_add(f,s,b,"encoded-udp-payload",start+h+8,n-h-8);}
static bool f15_decoded(Abstractformat *f,pm_stream *s,const char *label,uint8_t **p,uint64_t n){if(!*p||!n||s->count>=4096)return false;return th_mem(f,s,label,p,n);}

static bool f15_b64(nh_blob *b,uint64_t at,uint64_t n,bool url,uint8_t **out,uint64_t *bytes){uint8_t *tmp=NULL;nh_blob view;uint64_t padded=(n+3)&~3ULL;bool ok=false;if(!n||n%4==1||n>1048576||!nh_span(b,at,n))return false;tmp=(uint8_t *)xx_mem_alloc((size_t)padded);if(!tmp)return false;for(uint64_t i=0;i<n;++i){uint8_t c=b->p[(size_t)(at+i)];if(fd_stop(b->pd))goto done;if(url){if(c=='-')c='+';else if(c=='_')c='/';else if(c=='+'||c=='/')goto done;}if(fw_b64c(c)<0)goto done;tmp[i]=c;}for(uint64_t i=n;i<padded;++i)tmp[i]='=';view.p=tmp;view.n=padded;view.pd=b->pd;ok=fw_b64(&view,0,padded,out,bytes);done:xx_mem_free(tmp);return ok;}
static bool f15_zstr(nh_blob *b,uint64_t at,uint64_t n,uint64_t *len){uint64_t p=0;if(!nh_span(b,at,n))return false;while(p<n&&b->p[(size_t)(at+p)])++p;if(!p||p==n||!f15_ascii(b,at,p,true)||!nh_zero(b,at+p,n-p))return false;*len=p;return true;}
#endif
