/* SPDX-License-Identifier: MIT. Checked twelfth DER primitives; structural validation, no signature authentication. */
#ifndef XX_TWELFTH_DER_H
#define XX_TWELFTH_DER_H
typedef struct cm_tlv {uint8_t tag;uint64_t start,value,end;} cm_tlv;
static bool cm_read(nh_blob *b,uint64_t *at,uint64_t end,cm_tlv *t) {uint64_t n;uint8_t c;unsigned w;if(!eh_span(*at,2,end) || !nh_span(b,*at,2)) return false;t->start=*at;t->tag=b->p[(size_t)(*at)++];if((t->tag&31)==31 || !t->tag) return false;c=b->p[(size_t)(*at)++];n=c;if(c&128) {w=c&127;if(!w || w>4 || !eh_span(*at,w,end) || !nh_span(b,*at,w) || !b->p[(size_t)*at]) return false;n=0;for(unsigned i=0;i<w;++i) n=(n<<8)|b->p[(size_t)(*at)++];if(n<128) return false;}t->value=*at;if(!eh_span(*at,n,end) || !nh_span(b,*at,n)) return false;t->end=*at+n;*at=t->end;return true;}
static bool cm_take(nh_blob *b,uint64_t *at,uint64_t end,uint8_t tag,cm_tlv *t) {return cm_read(b,at,end,t) && t->tag==tag;}
static bool cm_oid(nh_blob *b,cm_tlv *t) {uint64_t i=t->value;unsigned width=0;if(t->tag!=6 || i==t->end) return false;while(i<t->end) {uint8_t c=b->p[(size_t)i++];if(!width && c==128) return false;if(++width>10) return false;if(!(c&128)) width=0;}return !width;}
static bool cm_date(const uint8_t *v,uint64_t n,uint8_t tag) {unsigned base=tag==23 ? 2:4,year=0,values[5],month,days;if(n!=(tag==23 ? 13U:15U) || v[n-1]!='Z') return false;for(uint64_t i=0;i<n-1;++i) if(v[i]<'0' || v[i]>'9') return false;for(unsigned i=0;i<base;++i) year=year*10+(unsigned)(v[i]-'0');if(tag==23) year+=year>=50 ? 1900U:2000U;for(unsigned i=0;i<5;++i) values[i]=(unsigned)(v[base+i*2]-'0')*10+(unsigned)(v[base+i*2+1]-'0');month=values[0];if(!month || month>12 || !values[1] || values[2]>23 || values[3]>59 || values[4]>59) return false;days=month==2 ? 28U+(year%4==0 && (year%100!=0 || year%400==0)):month==4 || month==6 || month==9 || month==11 ? 30U:31U;return values[1]<=days;}
static bool cm_tree(nh_blob *b,uint64_t at,uint64_t end,unsigned depth,unsigned *work) {cm_tlv t;uint64_t prev=0,prevn=0;if(depth>32) return false;while(at<end) {if(++*work>65536 || !cm_read(b,&at,end,&t)) return false;uint64_t n=t.end-t.value;uint8_t *v=b->p+(size_t)t.value;if(!(t.tag&192) && (t.tag&32) && t.tag!=48 && t.tag!=49) return false;if(t.tag&32) {if(!cm_tree(b,t.value,t.end,depth+1,work)) return false;if(t.tag==49) {uint64_t pos=t.value;cm_tlv a;while(pos<t.end) {if(!cm_read(b,&pos,t.end,&a) || (prevn && ec_cmp(b->p+(size_t)prev,prevn,b->p+(size_t)a.start,a.end-a.start)>0)) return false;prev=a.start;prevn=a.end-a.start;}prevn=0;}}
        else if(t.tag==1) {if(n!=1 || (*v!=0 && *v!=255)) return false;}else if(t.tag==2) {if(!n || (n>1 && ((v[0]==0 && !(v[1]&128)) || (v[0]==255 && (v[1]&128))))) return false;}else if(t.tag==3) {if(!n || v[0]>7 || (n==1 && v[0]) || (n>1 && (v[n-1]&((1U<<v[0])-1)))) return false;}else if(t.tag==5) {if(n) return false;}else if(t.tag==6) {if(!cm_oid(b,&t)) return false;}else if(t.tag==12) {if(!ec_utf(b,t.value,n)) return false;}else if(t.tag==23 || t.tag==24) {if(!cm_date(v,n,t.tag)) return false;}else if(t.tag==19) {for(uint64_t i=0;i<n;++i) {uint8_t c=v[i];if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<'0' || c>'9') && c!=' ' && c!=39 && c!='(' && c!=')' && c!='+' && c!=',' && c!='-' && c!='.' && c!='/' && c!=':' && c!='=' && c!='?') return false;}}else if(t.tag==22) {for(uint64_t i=0;i<n;++i) if(v[i]>127) return false;}else if(t.tag==30) {if(n&1) return false;for(uint64_t i=0;i<n;i+=2) {uint16_t c=pm_be16(v+(size_t)i);if(c>=0xd800 && c<=0xdfff) return false;}}else if(t.tag!=4 && t.tag!=20 && (t.tag&192)!=128) return false;}
    return at==end;
}
static bool cm_alg(nh_blob *b,cm_tlv *t) {uint64_t at=t->value;cm_tlv a;if(t->tag!=48 || !cm_take(b,&at,t->end,6,&a) || !cm_oid(b,&a)) return false;if(at<t->end && !cm_read(b,&at,t->end,&a)) return false;return at==t->end;}
static bool ci_name(nh_blob *b,cm_tlv *t,bool empty) {uint64_t at=t->value,p,q;cm_tlv rdn,entry,oid,value;if(t->tag!=48 || (!empty && at==t->end)) return false;while(at<t->end) {if(!cm_take(b,&at,t->end,49,&rdn) || rdn.value==rdn.end) return false;p=rdn.value;while(p<rdn.end) {if(!cm_take(b,&p,rdn.end,48,&entry)) return false;q=entry.value;if(!cm_take(b,&q,entry.end,6,&oid) || !cm_oid(b,&oid) || !cm_read(b,&q,entry.end,&value) || q!=entry.end || (value.tag!=12 && value.tag!=19 && value.tag!=20 && value.tag!=22 && value.tag!=30)) return false;}}return at==t->end;}
static bool ci_bits(nh_blob *b,cm_tlv *t,bool nonempty) {uint64_t n=t->end-t->value;const uint8_t *v=b->p+(size_t)t->value;return n && (!nonempty || (n>1 && !v[0])) && v[0]<=7 && (n!=1 || !v[0]) && (n<2 || !(v[n-1]&((1U<<v[0])-1)));}
static uint64_t ci_time(nh_blob *b,cm_tlv *t) {uint64_t n=0;const uint8_t *v=b->p+(size_t)t->value;unsigned i=0;if(t->tag==23) {unsigned year=(v[0]-48U)*10U+v[1]-48U;n=year>=50 ? 19:20;}for(;i<t->end-t->value-1;++i) n=n*10+(v[i]-48U);return n;}
static bool ci_extensions(nh_blob *b,cm_tlv *t) {uint64_t at=t->value,p,q,seen[1024],length[1024];unsigned count=0,work=0;cm_tlv list,entry,oid,critical,value;if(!cm_take(b,&at,t->end,48,&list) || at!=t->end || list.value==list.end) return false;at=list.value;while(at<list.end) {if(count>=1024 || !cm_take(b,&at,list.end,48,&entry)) return false;p=entry.value;if(!cm_take(b,&p,entry.end,6,&oid) || !cm_oid(b,&oid)) return false;for(unsigned i=0;i<count;++i) if(length[i]==oid.end-oid.value && !xx_rt_memcmp(b->p+(size_t)seen[i],b->p+(size_t)oid.value,(size_t)length[i])) return false;seen[count]=oid.value;length[count++]=oid.end-oid.value;if(p<entry.end && b->p[(size_t)p]==1) {if(!cm_take(b,&p,entry.end,1,&critical) || critical.end-critical.value!=1 || b->p[(size_t)critical.value]!=255) return false;}if(!cm_take(b,&p,entry.end,4,&value) || value.value==value.end || p!=entry.end) return false;q=value.value;if(!cm_tree(b,value.value,value.end,0,&work) || !cm_read(b,&q,value.end,&critical) || q!=value.end) return false;}return at==list.end;}
static bool cm_cert(nh_blob *b,cm_tlv *t) {uint64_t at=t->value,p,q;uint8_t version=0,last=128;cm_tlv x,y,z,outer,before,after;if(t->tag!=48 || !cm_take(b,&at,t->end,48,&x) || !cm_take(b,&at,t->end,48,&y) || !cm_alg(b,&y) || !cm_take(b,&at,t->end,3,&z) || !ci_bits(b,&z,true) || at!=t->end) return false;outer=y;p=x.value;if(p<x.end && b->p[(size_t)p]==160) {cm_tlv ver,integer;if(!cm_take(b,&p,x.end,160,&ver)) return false;q=ver.value;if(!cm_take(b,&q,ver.end,2,&integer) || q!=ver.end || integer.end-integer.value!=1 || !(version=b->p[(size_t)integer.value]) || version>2) return false;}if(!cm_take(b,&p,x.end,2,&z) || z.end==z.value || z.end-z.value>21 || (b->p[(size_t)z.value]&128) || (z.end-z.value==1 && !b->p[(size_t)z.value]) || !cm_take(b,&p,x.end,48,&z) || !cm_alg(b,&z) || z.end-z.start!=outer.end-outer.start || xx_rt_memcmp(b->p+(size_t)z.start,b->p+(size_t)outer.start,(size_t)(z.end-z.start)) || !cm_take(b,&p,x.end,48,&z) || !ci_name(b,&z,false) || !cm_take(b,&p,x.end,48,&z)) return false;q=z.value;if(!cm_read(b,&q,z.end,&before) || (before.tag!=23 && before.tag!=24) || !cm_read(b,&q,z.end,&after) || (after.tag!=23 && after.tag!=24) || q!=z.end || ci_time(b,&before)>ci_time(b,&after) || !cm_take(b,&p,x.end,48,&z) || !ci_name(b,&z,true) || !cm_take(b,&p,x.end,48,&z)) return false;q=z.value;if(!cm_take(b,&q,z.end,48,&y) || !cm_alg(b,&y) || !cm_take(b,&q,z.end,3,&y) || !ci_bits(b,&y,true) || q!=z.end) return false;while(p<x.end) {if(!cm_read(b,&p,x.end,&z) || z.tag<=last || (z.tag!=129 && z.tag!=130 && z.tag!=163)) return false;if(z.tag==163 ? version!=2 || !ci_extensions(b,&z):!version || !ci_bits(b,&z,false)) return false;last=z.tag;}return p==x.end;}
static bool cm_attr(nh_blob *b,cm_tlv *t) {uint64_t at=t->value,prev=0,prevn=0;cm_tlv a,x,y;unsigned count=0;while(at<t->end) {if(++count>1024 || !cm_take(b,&at,t->end,48,&a)) return false;if(prevn && ec_cmp(b->p+(size_t)prev,prevn,b->p+(size_t)a.start,a.end-a.start)>0) return false;prev=a.start;prevn=a.end-a.start;uint64_t p=a.value;if(!cm_take(b,&p,a.end,6,&x) || !cm_oid(b,&x) || !cm_take(b,&p,a.end,49,&y) || y.value==y.end || p!=a.end) return false;}return count>0;}

#endif
