/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/ue2_documents/xx_ue2_documents.h"

XX_FORMAT_DEFINE_READER_ADAPTER(gnu_gettext_mo, XX_FILE_TYPE_GNU_GETTEXT_MO,
    xx_ue2_documents_create(device, 0, XX_FILE_TYPE_GNU_GETTEXT_MO), xx_ue2_documents_free, XX_READER_TYPE_FORCE)

XX_FORMAT_DEFINE_READER_ADAPTER(mime_message, XX_FILE_TYPE_MIME_MESSAGE,
    xx_ue2_documents_create(device, 0, XX_FILE_TYPE_MIME_MESSAGE), xx_ue2_documents_free, XX_READER_TYPE_FORCE)

XX_FORMAT_DEFINE_READER_ADAPTER(qt_qm, XX_FILE_TYPE_QT_QM,
    xx_ue2_documents_create(device, 0, XX_FILE_TYPE_QT_QM), xx_ue2_documents_free, XX_READER_TYPE_FORCE)

XX_FORMAT_DEFINE_READER_ADAPTER(windows_help, XX_FILE_TYPE_WINDOWS_HELP,
    xx_ue2_documents_create(device, 0, XX_FILE_TYPE_WINDOWS_HELP), xx_ue2_documents_free, XX_READER_TYPE_FORCE)

