/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/rt11_fs/xx_rt11_fs.h"

XX_FORMAT_DEFINE_READER_ADAPTER(rt11_fs, XX_FILE_TYPE_RT11_FS,
    xx_rt11_fs_create(device, 0), xx_rt11_fs_free, XX_READER_TYPE_FILL_UNKNOWN)

