/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/snatchit_cp2/xx_snatchit_cp2.h"

XX_FORMAT_DEFINE_READER_ADAPTER(snatchit_cp2, XX_FILE_TYPE_SNATCHIT_CP2,
    xx_snatchit_cp2_create(device, 0), xx_snatchit_cp2_free, XX_READER_TYPE_FILL_UNKNOWN)

