/* Copyright (c)2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT. Bounded typed components; payloads never executed.
 */
/* Primary: https://stomp.github.io/stomp-specification-1.2.html */
#include "xxfclib/formats/stomp_frames/xx_stomp_frames.h"
#include "../xx_fourteenth_wrappers.h"

static bool unescape(nh_blob *b,uint64_t p,uint64_t n,char *out,size_t cap,bool escaped){size_t z=0;for(uint64_t i=0;i<n;++i){uint8_t c=b->p[(size_t)(p+i)];if(c<32||c==127||z+1>=cap)return false;if(escaped&&c==92){if(++i==n)return false;c=b->p[(size_t)(p+i)];if(c=='n')c=10;else if(c=='r')c=13;else if(c=='c')c=':';else if(c!=92)return false;}out[z++]=(char)c;}out[z]=0;return fourth_utf8((uint8_t *)out,z,b->pd);}
static bool line(nh_blob *b,uint64_t *at,uint64_t *p,uint64_t *n){if(!th_line(b,at,p,n,false))return false;if(*n&&b->p[(size_t)(*p+*n-1)]==13)--*n;return true;}
static bool pm_parse(Abstractformat *f,pm_stream *s,xx_pd_struct *pd){nh_blob b;bool ok=false;char *header_storage=NULL;char (*keys)[256]=NULL;char (*values)[1024]=NULL;uint64_t at=0;unsigned frames=0,sends=0;bool connected=false,terminal=false;if(!nh_load(f,&b,pd))return false;header_storage=(char *)xx_mem_alloc(256U*(256U+1024U));NH_NEED(header_storage);keys=(char (*)[256])header_storage;values=(char (*)[1024])(header_storage+256U*256U);while(at<b.n){uint64_t start=at,p,n;NH_NEED(!terminal&&++frames<=256&&line(&b,&at,&p,&n));unsigned type=th_eq(&b,p,n,"STOMP")?1:th_eq(&b,p,n,"CONNECT")?2:th_eq(&b,p,n,"SEND")?3:th_eq(&b,p,n,"DISCONNECT")?4:0;NH_NEED(type>0&&(connected?(type==3||type==4):(type<=2)));unsigned headers=0;bool host=false,version=false,destination=false,length=false;uint64_t bytes=0;while(at<b.n){NH_NEED(line(&b,&at,&p,&n));if(!n)break;NH_NEED(headers<256);uint64_t colon=0;while(colon<n&&b.p[(size_t)(p+colon)]!=':')++colon;NH_NEED(colon>0&&colon<n&&unescape(&b,p,colon,keys[headers],256,type!=2)&&unescape(&b,p+colon+1,n-colon-1,values[headers],1024,type!=2));bool duplicate=false;for(unsigned i=0;i<headers;++i)if(!xx_rt_strcmp(keys[i],keys[headers]))duplicate=true;if(!duplicate){char *value=values[headers];if(!xx_rt_strcmp(keys[headers],"host"))host=value[0]!=0;else if(!xx_rt_strcmp(keys[headers],"accept-version")){uint64_t vp=0,vn=xx_rt_strlen(value);while(vp<vn){uint64_t end=vp;while(end<vn&&value[end]!=',')++end;if(end-vp==3&&!xx_rt_memcmp(value+vp,"1.2",3))version=true;vp=end+1;}}else if(!xx_rt_strcmp(keys[headers],"destination"))destination=value[0]!=0;else if(!xx_rt_strcmp(keys[headers],"content-length")){nh_blob vb={(uint8_t *)value,xx_rt_strlen(value),pd};NH_NEED(th_dec(&vb,0,vb.n,&bytes));length=true;}}++headers;}NH_NEED(nh_add(f,s,&b,"stomp-command-headers",start,at-start));uint64_t body=at;if(length){NH_NEED(th_take(&b,&at,b.n,bytes)&&th_take(&b,&at,b.n,1)&&!b.p[(size_t)at-1]);}else{while(at<b.n&&b.p[(size_t)at]){NH_NEED(nh_span(&b,at,1));++at;}NH_NEED(at<b.n);bytes=at-body;++at;}if(type<=2){NH_NEED(!bytes&&host&&version);connected=true;}else if(type==3){NH_NEED(destination&&nh_add(f,s,&b,"message-body",body,bytes));++sends;}else{NH_NEED(!bytes&&sends>0);terminal=true;}while(at<b.n&&(b.p[(size_t)at]==10||b.p[(size_t)at]==13)){if(b.p[(size_t)at]==13){NH_NEED(th_take(&b,&at,b.n,2)&&b.p[(size_t)at-1]==10);}else ++at;}}NH_NEED(frames>=3&&sends>0&&terminal&&at==b.n);s->size=(int64_t)b.n;ok=true;done:xx_mem_free(header_storage);xx_mem_free(b.p);return ok;}

void xx_stomp_frames_init(xx_stomp_frames *r,xx_io_device *d,int64_t b){if(r){xx_mem_zero(r,sizeof(*r));pm_init(&r->format,d,b,XX_FILE_TYPE_STOMP_FRAMES,"bin");}}
xx_stomp_frames *xx_stomp_frames_create(xx_io_device *d,int64_t b){xx_stomp_frames *r=(xx_stomp_frames *)xx_mem_alloc(sizeof(*r));if(r)xx_stomp_frames_init(r,d,b);return r;}
void xx_stomp_frames_destroy(xx_stomp_frames *r){if(r)xx_format_cleanup_extra_parameters(&r->format);}
void xx_stomp_frames_free(xx_stomp_frames *r){if(r){xx_stomp_frames_destroy(r);xx_mem_free(r);}}
bool xx_stomp_frames_check_is_valid(Abstractformat *f,xx_pd_struct *pd){return pm_valid(f,pd);}
bool xx_stomp_frames_handle_base_info(Abstractformat *f,xx_pd_struct *pd){return pm_handle(f,pd);}
