/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/hammer_fs/xx_hammer_fs.h"

XX_FORMAT_DEFINE_READER_ADAPTER(hammer_fs, XX_FILE_TYPE_HAMMER_FS,
    xx_hammer_fs_create(device, 0), xx_hammer_fs_free, XX_READER_TYPE_FILL_UNKNOWN)

