/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/amplus/xx_amplus.h"

XX_FORMAT_DEFINE_READER_ADAPTER(amplus, XX_FILE_TYPE_AMPLUS,
    xx_amplus_create(device, 0), xx_amplus_free, XX_READER_TYPE_FILL_UNKNOWN)

