/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/coff_object/xx_coff_object.h"

XX_FORMAT_DEFINE_READER_ADAPTER(coff_object, XX_FILE_TYPE_COFF_OBJECT,
    xx_coff_object_create(device, 0), xx_coff_object_free, XX_READER_TYPE_FILL_UNKNOWN)

