/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Bounded primary grammar. Payloads are never executed.
 */
/* Primary: https://www.rfc-editor.org/rfc/rfc6960.html */
#include "xxfclib/formats/ocsp_response/xx_ocsp_response.h"
#include "xxfclib/data/xx_data.h"
#include "../xx_thirteenth_wrappers.h"

static bool pm_parse(Abstractformat *f,pm_stream *s,xx_pd_struct *pd){nh_blob b;cm_tlv root,status,wrapper,response,oid,value,basic,tbs,alg,sig,x,y,z;uint64_t at=0,p,q,k,u;unsigned work=0,answers=0;bool ok=false;static const uint8_t basic_oid[]={43,6,1,5,5,7,48,1,1};if(!nh_load(f,&b,pd))return false;NH_NEED(th_tree(&b,0,b.n,0,&work)&&cm_take(&b,&at,b.n,48,&root)&&at==b.n);p=root.value;NH_NEED(cm_take(&b,&p,root.end,10,&status)&&th_uint(&b,&status,&u)&&!u&&cm_take(&b,&p,root.end,160,&wrapper)&&p==root.end);p=wrapper.value;NH_NEED(cm_take(&b,&p,wrapper.end,48,&response)&&p==wrapper.end);p=response.value;NH_NEED(cm_take(&b,&p,response.end,6,&oid)&&oid.end-oid.value==sizeof(basic_oid)&&!xx_rt_memcmp(b.p+(size_t)oid.value,basic_oid,sizeof(basic_oid))&&cm_take(&b,&p,response.end,4,&value)&&p==response.end);p=value.value;NH_NEED(th_tree(&b,p,value.end,0,&work)&&cm_take(&b,&p,value.end,48,&basic)&&p==value.end);p=basic.value;NH_NEED(cm_take(&b,&p,basic.end,48,&tbs)&&cm_take(&b,&p,basic.end,48,&alg)&&cm_alg(&b,&alg)&&cm_take(&b,&p,basic.end,3,&sig)&&ci_bits(&b,&sig,true));if(p<basic.end){NH_NEED(cm_take(&b,&p,basic.end,160,&x));q=x.value;NH_NEED(cm_take(&b,&q,x.end,48,&y)&&q==x.end);q=y.value;unsigned certs=0;while(q<y.end){NH_NEED(++certs<=16&&cm_take(&b,&q,y.end,48,&z)&&cm_cert(&b,&z)&&th_tlv_add(f,s,&b,"responder-certificate",&z));}}NH_NEED(p==basic.end);p=tbs.value;if(p<tbs.end&&b.p[(size_t)p]==160){NH_NEED(cm_take(&b,&p,tbs.end,160,&x));q=x.value;NH_NEED(cm_take(&b,&q,x.end,2,&y)&&th_uint(&b,&y,&u)&&!u&&q==x.end);}NH_NEED(cm_read(&b,&p,tbs.end,&x)&&(x.tag==161||x.tag==162));q=x.value;if(x.tag==161){NH_NEED(cm_take(&b,&q,x.end,48,&y)&&ci_name(&b,&y,false)&&q==x.end);}else NH_NEED(cm_take(&b,&q,x.end,4,&y)&&y.end-y.value==20&&q==x.end);NH_NEED(th_tlv_add(f,s,&b,"responder-id",&x)&&cm_take(&b,&p,tbs.end,24,&x)&&th_tlv_add(f,s,&b,"produced-at",&x)&&cm_take(&b,&p,tbs.end,48,&x));q=x.value;
 while(q<x.end){cm_tlv item,id,before,after,state;NH_NEED(++answers<=512&&cm_take(&b,&q,x.end,48,&item));k=item.value;NH_NEED(cm_take(&b,&k,item.end,48,&id));uint64_t h=id.value;cm_tlv hash,key,name,serial;NH_NEED(cm_take(&b,&h,id.end,48,&hash)&&cm_alg(&b,&hash)&&cm_take(&b,&h,id.end,4,&name)&&name.end>name.value&&name.end-name.value<=64&&cm_take(&b,&h,id.end,4,&key)&&key.end-key.value==name.end-name.value&&cm_take(&b,&h,id.end,2,&serial)&&serial.end>serial.value&&serial.end-serial.value<=21&&!(b.p[(size_t)serial.value]&128)&&h==id.end);NH_NEED(cm_read(&b,&k,item.end,&state)&&(state.tag==128||state.tag==161||state.tag==130));if(state.tag==161){h=state.value;NH_NEED(cm_take(&b,&h,state.end,24,&hash));if(h<state.end){NH_NEED(cm_take(&b,&h,state.end,160,&hash));uint64_t j=hash.value;NH_NEED(cm_take(&b,&j,hash.end,10,&key)&&th_uint(&b,&key,&u)&&u<=10&&j==hash.end);}NH_NEED(h==state.end);}else NH_NEED(state.value==state.end);NH_NEED(cm_take(&b,&k,item.end,24,&before));if(k<item.end&&b.p[(size_t)k]==160){NH_NEED(cm_take(&b,&k,item.end,160,&after));h=after.value;NH_NEED(cm_take(&b,&h,after.end,24,&hash)&&h==after.end&&ci_time(&b,&before)<=ci_time(&b,&hash));}if(k<item.end){NH_NEED(cm_take(&b,&k,item.end,161,&after)&&th_extensions(&b,&after));}NH_NEED(k==item.end&&th_tlv_add(f,s,&b,"single-response",&item));}
 if(p<tbs.end){NH_NEED(cm_take(&b,&p,tbs.end,161,&x)&&th_extensions(&b,&x)&&th_tlv_add(f,s,&b,"response-extensions",&x));}NH_NEED(answers&&p==tbs.end&&th_tlv_add(f,s,&b,"signature-algorithm",&alg)&&th_tlv_add(f,s,&b,"signature",&sig));s->size=(int64_t)b.n;ok=true;done:xx_mem_free(b.p);return ok;}

void xx_ocsp_response_init(xx_ocsp_response *r,xx_io_device *d,int64_t b) {if(r){xx_mem_zero(r,sizeof(*r));pm_init(&r->format,d,b,XX_FILE_TYPE_OCSP_RESPONSE,"bin");}}
xx_ocsp_response *xx_ocsp_response_create(xx_io_device *d,int64_t b) {xx_ocsp_response *r=(xx_ocsp_response *)xx_mem_alloc(sizeof(*r));if(r)xx_ocsp_response_init(r,d,b);return r;}
void xx_ocsp_response_destroy(xx_ocsp_response *r) {if(r)xx_format_cleanup_extra_parameters(&r->format);}
void xx_ocsp_response_free(xx_ocsp_response *r) {if(r){xx_ocsp_response_destroy(r);xx_mem_free(r);}}
bool xx_ocsp_response_check_is_valid(Abstractformat *f,xx_pd_struct *pd) {return pm_valid(f,pd);}
bool xx_ocsp_response_handle_base_info(Abstractformat *f,xx_pd_struct *pd) {return pm_handle(f,pd);}
