/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Bounded primary grammar. Payloads are never executed.
 */
/* Primary: https://www.rfc-editor.org/rfc/rfc6960.html */
#include "xxfclib/formats/ocsp_response/xx_ocsp_response.h"
#include "xxfclib/data/xx_data.h"
#include "../common/xx_protocol_framing.h"

static bool pm_parse(Abstractformat *f,pm_stream *s,xx_pd_struct *pd){memory_blob b;der_tlv root,status,wrapper,response,oid,value,basic,tbs,alg,sig,x,y,z;uint64_t at=0,p,q,k,u;unsigned work=0,answers=0;bool ok=false;static const uint8_t basic_oid[]={43,6,1,5,5,7,48,1,1};if(!blob_load(f,&b,pd))return false;BLOB_NEED(protocol_tree(&b,0,b.n,0,&work)&&der_take(&b,&at,b.n,48,&root)&&at==b.n);p=root.value;BLOB_NEED(der_take(&b,&p,root.end,10,&status)&&protocol_uint(&b,&status,&u)&&!u&&der_take(&b,&p,root.end,160,&wrapper)&&p==root.end);p=wrapper.value;BLOB_NEED(der_take(&b,&p,wrapper.end,48,&response)&&p==wrapper.end);p=response.value;BLOB_NEED(der_take(&b,&p,response.end,6,&oid)&&oid.end-oid.value==sizeof(basic_oid)&&!xx_rt_memcmp(b.p+(size_t)oid.value,basic_oid,sizeof(basic_oid))&&der_take(&b,&p,response.end,4,&value)&&p==response.end);p=value.value;BLOB_NEED(protocol_tree(&b,p,value.end,0,&work)&&der_take(&b,&p,value.end,48,&basic)&&p==value.end);p=basic.value;BLOB_NEED(der_take(&b,&p,basic.end,48,&tbs)&&der_take(&b,&p,basic.end,48,&alg)&&der_alg(&b,&alg)&&der_take(&b,&p,basic.end,3,&sig)&&x509_bits(&b,&sig,true));if(p<basic.end){BLOB_NEED(der_take(&b,&p,basic.end,160,&x));q=x.value;BLOB_NEED(der_take(&b,&q,x.end,48,&y)&&q==x.end);q=y.value;unsigned certs=0;while(q<y.end){BLOB_NEED(++certs<=16&&der_take(&b,&q,y.end,48,&z)&&der_cert(&b,&z)&&protocol_tlv_add(f,s,&b,"responder-certificate",&z));}}BLOB_NEED(p==basic.end);p=tbs.value;if(p<tbs.end&&b.p[(size_t)p]==160){BLOB_NEED(der_take(&b,&p,tbs.end,160,&x));q=x.value;BLOB_NEED(der_take(&b,&q,x.end,2,&y)&&protocol_uint(&b,&y,&u)&&!u&&q==x.end);}BLOB_NEED(der_read(&b,&p,tbs.end,&x)&&(x.tag==161||x.tag==162));q=x.value;if(x.tag==161){BLOB_NEED(der_take(&b,&q,x.end,48,&y)&&x509_name(&b,&y,false)&&q==x.end);}else BLOB_NEED(der_take(&b,&q,x.end,4,&y)&&y.end-y.value==20&&q==x.end);BLOB_NEED(protocol_tlv_add(f,s,&b,"responder-id",&x)&&der_take(&b,&p,tbs.end,24,&x)&&protocol_tlv_add(f,s,&b,"produced-at",&x)&&der_take(&b,&p,tbs.end,48,&x));q=x.value;
 while(q<x.end){der_tlv item,id,before,after,state;BLOB_NEED(++answers<=512&&der_take(&b,&q,x.end,48,&item));k=item.value;BLOB_NEED(der_take(&b,&k,item.end,48,&id));uint64_t h=id.value;der_tlv hash,key,name,serial;BLOB_NEED(der_take(&b,&h,id.end,48,&hash)&&der_alg(&b,&hash)&&der_take(&b,&h,id.end,4,&name)&&name.end>name.value&&name.end-name.value<=64&&der_take(&b,&h,id.end,4,&key)&&key.end-key.value==name.end-name.value&&der_take(&b,&h,id.end,2,&serial)&&serial.end>serial.value&&serial.end-serial.value<=21&&!(b.p[(size_t)serial.value]&128)&&h==id.end);BLOB_NEED(der_read(&b,&k,item.end,&state)&&(state.tag==128||state.tag==161||state.tag==130));if(state.tag==161){h=state.value;BLOB_NEED(der_take(&b,&h,state.end,24,&hash));if(h<state.end){BLOB_NEED(der_take(&b,&h,state.end,160,&hash));uint64_t j=hash.value;BLOB_NEED(der_take(&b,&j,hash.end,10,&key)&&protocol_uint(&b,&key,&u)&&u<=10&&j==hash.end);}BLOB_NEED(h==state.end);}else BLOB_NEED(state.value==state.end);BLOB_NEED(der_take(&b,&k,item.end,24,&before));if(k<item.end&&b.p[(size_t)k]==160){BLOB_NEED(der_take(&b,&k,item.end,160,&after));h=after.value;BLOB_NEED(der_take(&b,&h,after.end,24,&hash)&&h==after.end&&x509_time(&b,&before)<=x509_time(&b,&hash));}if(k<item.end){BLOB_NEED(der_take(&b,&k,item.end,161,&after)&&protocol_extensions(&b,&after));}BLOB_NEED(k==item.end&&protocol_tlv_add(f,s,&b,"single-response",&item));}
 if(p<tbs.end){BLOB_NEED(der_take(&b,&p,tbs.end,161,&x)&&protocol_extensions(&b,&x)&&protocol_tlv_add(f,s,&b,"response-extensions",&x));}BLOB_NEED(answers&&p==tbs.end&&protocol_tlv_add(f,s,&b,"signature-algorithm",&alg)&&protocol_tlv_add(f,s,&b,"signature",&sig));s->size=(int64_t)b.n;ok=true;done:xx_mem_free(b.p);return ok;}

void xx_ocsp_response_init(xx_ocsp_response *r,xx_io_device *d,int64_t b) {if(r){xx_mem_zero(r,sizeof(*r));pm_init(&r->format,d,b,XX_FILE_TYPE_OCSP_RESPONSE,"bin");}}
xx_ocsp_response *xx_ocsp_response_create(xx_io_device *d,int64_t b) {xx_ocsp_response *r=(xx_ocsp_response *)xx_mem_alloc(sizeof(*r));if(r)xx_ocsp_response_init(r,d,b);return r;}
void xx_ocsp_response_destroy(xx_ocsp_response *r) {if(r)xx_format_cleanup_extra_parameters(&r->format);}
void xx_ocsp_response_free(xx_ocsp_response *r) {if(r){xx_ocsp_response_destroy(r);xx_mem_free(r);}}
bool xx_ocsp_response_check_is_valid(Abstractformat *f,xx_pd_struct *pd) {return pm_valid(f,pd);}
bool xx_ocsp_response_handle_base_info(Abstractformat *f,xx_pd_struct *pd) {return pm_handle(f,pd);}
