/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 */

/* xx_wintersoft_extractor.c - search raw data for WINTERSOFT.
 *
 * Scans for:
 *   2A 2A 2B 2B 4C 5A 57 20 at +0  ("..++LZW ")
 *   2A 2A 2B 2B 48 55 46 46 at +0  ("..++HUFF")
 * Offset 0 is always tried as well.
 * Each candidate must be accepted by the wintersoft reader, which also measures it,
 * and named by the detector, both on a view that starts at the candidate.
 * See xx_format_extractor_engine.h.
 *
 * GENERATED by gen_extractors.py from the detector's prefilters.
 */

#include "../xx_format_extractor_engine.h"
#include "xxfclib/formats/wintersoft/xx_wintersoft.h"

static const uint8_t k_anchor0[] = { 0x2A, 0x2A, 0x2B, 0x2B, 0x4C, 0x5A, 0x57, 0x20 };
static const uint8_t k_anchor1[] = { 0x2A, 0x2A, 0x2B, 0x2B, 0x48, 0x55, 0x46, 0x46 };

static const xx_format_search_anchor k_anchors[] = {
    { k_anchor0, sizeof(k_anchor0), 0U },
    { k_anchor1, sizeof(k_anchor1), 0U },
};

static const xx_file_type_t k_types[] = { XX_FILE_TYPE_WINTERSOFT };

static Abstractformat *xx_wintersoft_search_open(xx_io_device *window) {
    xx_wintersoft *reader = xx_wintersoft_create(window, 0);
    return reader ? &reader->format : NULL;
}

static void xx_wintersoft_search_close(Abstractformat *format) {
    /* The format is the first member, so this is the reader itself. */
    xx_wintersoft_free((xx_wintersoft *)format);
}

static const xx_format_search_desc k_desc = {
    k_types, sizeof(k_types) / sizeof(k_types[0]),
    k_anchors, sizeof(k_anchors) / sizeof(k_anchors[0]),
    xx_wintersoft_search_open, xx_wintersoft_search_close
};

static xx_format_search_state *xx_wintersoft_create_format_search(
    xx_format_extractor *self, xx_io_device *device, const xx_list_s *options,
    xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_create(&k_desc, device, options, pd);
}

static const xx_format_search_info *xx_wintersoft_get_current_format_info(
    xx_format_extractor *self, xx_format_search_state *state) {
    (void)self;
    return xx_format_search_current(state);
}

static bool xx_wintersoft_format_search_find_next(xx_format_extractor *self,
                                          xx_format_search_state *state,
                                          xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_find_next(state, pd);
}

static void xx_wintersoft_free_format_search(xx_format_extractor *self,
                                     xx_format_search_state *state) {
    (void)self;
    xx_format_search_free(state);
}

xx_format_extractor xx_wintersoft_extractor = {
    xx_wintersoft_create_format_search,
    xx_wintersoft_get_current_format_info,
    xx_wintersoft_format_search_find_next,
    xx_wintersoft_free_format_search
};
