/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/hpofs/xx_hpofs.h"

XX_FORMAT_DEFINE_READER_ADAPTER(hpofs, XX_FILE_TYPE_HPOFS,
    xx_hpofs_create(device, 0), xx_hpofs_free, XX_READER_TYPE_FILL_UNKNOWN)

