/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/mac_ts/xx_mac_ts.h"

XX_FORMAT_DEFINE_READER_ADAPTER(mac_ts, XX_FILE_TYPE_MAC_TS,
    xx_mac_ts_create(device, 0), xx_mac_ts_free, XX_READER_TYPE_FILL_UNKNOWN)

