/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 */

/* xx_binaryii_extractor.c - search raw data for BinaryII.
 *
 * Scans for:
 *   0A 47 4C at +0  (".GL")
 * Offset 0 is always tried as well.
 * Each candidate must be accepted by the binaryii reader, which also measures it,
 * and named by the detector, both on a view that starts at the candidate.
 * See xx_format_extractor_engine.h.
 *
 * GENERATED by gen_extractors.py from the detector's prefilters.
 */

#include "../xx_format_extractor_engine.h"
#include "xxfclib/formats/binaryii/xx_binaryii.h"

static const uint8_t k_anchor0[] = { 0x0A, 0x47, 0x4C };

static const xx_format_search_anchor k_anchors[] = {
    { k_anchor0, sizeof(k_anchor0), 0U },
};

static const xx_file_type_t k_types[] = { XX_FILE_TYPE_BINARYII };

static Abstractformat *xx_binaryii_search_open(xx_io_device *window) {
    xx_binaryii *reader = xx_binaryii_create(window, 0);
    return reader ? &reader->format : NULL;
}

static void xx_binaryii_search_close(Abstractformat *format) {
    /* The format is the first member, so this is the reader itself. */
    xx_binaryii_free((xx_binaryii *)format);
}

static const xx_format_search_desc k_desc = {
    k_types, sizeof(k_types) / sizeof(k_types[0]),
    k_anchors, sizeof(k_anchors) / sizeof(k_anchors[0]),
    xx_binaryii_search_open, xx_binaryii_search_close
};

static xx_format_search_state *xx_binaryii_create_format_search(
    xx_format_extractor *self, xx_io_device *device, const xx_list_s *options,
    xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_create(&k_desc, device, options, pd);
}

static const xx_format_search_info *xx_binaryii_get_current_format_info(
    xx_format_extractor *self, xx_format_search_state *state) {
    (void)self;
    return xx_format_search_current(state);
}

static bool xx_binaryii_format_search_find_next(xx_format_extractor *self,
                                          xx_format_search_state *state,
                                          xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_find_next(state, pd);
}

static void xx_binaryii_free_format_search(xx_format_extractor *self,
                                     xx_format_search_state *state) {
    (void)self;
    xx_format_search_free(state);
}

xx_format_extractor xx_binaryii_extractor = {
    xx_binaryii_create_format_search,
    xx_binaryii_get_current_format_info,
    xx_binaryii_format_search_find_next,
    xx_binaryii_free_format_search
};
