/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 */

/* xx_qnx6_extractor.c - search raw data for QNX6.
 *
 * Scans for:
 *   22 11 19 68 at +8192  ("...h")
 *   68 19 11 22 at +8192  ("h...")
 * (hand-written: the detector establishes this signature outside its
 * 64-byte prefilter window)
 * Offset 0 is always tried as well.
 * Each candidate must be accepted by the qnx6 reader, which also measures it,
 * and named by the detector, both on a view that starts at the candidate.
 * See xx_format_extractor_engine.h.
 *
 * GENERATED by gen_extractors.py from the detector's prefilters.
 */

#include "../xx_format_extractor_engine.h"
#include "xxfclib/formats/qnx6/xx_qnx6.h"

static const uint8_t k_anchor0[] = { 0x22, 0x11, 0x19, 0x68 };
static const uint8_t k_anchor1[] = { 0x68, 0x19, 0x11, 0x22 };

static const xx_format_search_anchor k_anchors[] = {
    { k_anchor0, sizeof(k_anchor0), 8192U },
    { k_anchor1, sizeof(k_anchor1), 8192U },
};

static const xx_file_type_t k_types[] = { XX_FILE_TYPE_QNX6 };

static Abstractformat *xx_qnx6_search_open(xx_io_device *window) {
    xx_qnx6 *reader = xx_qnx6_create(window, 0);
    return reader ? &reader->format : NULL;
}

static void xx_qnx6_search_close(Abstractformat *format) {
    /* The format is the first member, so this is the reader itself. */
    xx_qnx6_free((xx_qnx6 *)format);
}

static const xx_format_search_desc k_desc = {
    k_types, sizeof(k_types) / sizeof(k_types[0]),
    k_anchors, sizeof(k_anchors) / sizeof(k_anchors[0]),
    xx_qnx6_search_open, xx_qnx6_search_close
};

static xx_format_search_state *xx_qnx6_create_format_search(
    xx_format_extractor *self, xx_io_device *device, const xx_list_s *options,
    xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_create(&k_desc, device, options, pd);
}

static const xx_format_search_info *xx_qnx6_get_current_format_info(
    xx_format_extractor *self, xx_format_search_state *state) {
    (void)self;
    return xx_format_search_current(state);
}

static bool xx_qnx6_format_search_find_next(xx_format_extractor *self,
                                          xx_format_search_state *state,
                                          xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_find_next(state, pd);
}

static void xx_qnx6_free_format_search(xx_format_extractor *self,
                                     xx_format_search_state *state) {
    (void)self;
    xx_format_search_free(state);
}

xx_format_extractor xx_qnx6_extractor = {
    xx_qnx6_create_format_search,
    xx_qnx6_get_current_format_info,
    xx_qnx6_format_search_find_next,
    xx_qnx6_free_format_search
};
