/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/ms_dos_backup2/xx_ms_dos_backup2.h"

XX_FORMAT_DEFINE_READER_ADAPTER(ms_dos_backup2, XX_FILE_TYPE_MS_DOS_BACKUP2,
    xx_ms_dos_backup2_create(device, 0), xx_ms_dos_backup2_free, XX_READER_TYPE_FILL_UNKNOWN)

