/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 */

/* xx_lofi_extractor.c - search raw data for LOFI.
 *
 * Scans for:
 *   6C 7A 6D 61 00 at +0  ("lzma.")
 * Offset 0 is always tried as well.
 * Each candidate must be accepted by the lofi reader, which also measures it,
 * and named by the detector, both on a view that starts at the candidate.
 * See xx_format_extractor_engine.h.
 *
 * GENERATED by gen_extractors.py from the detector's prefilters.
 */

#include "../xx_format_extractor_engine.h"
#include "xxfclib/formats/lofi/xx_lofi.h"

static const uint8_t k_anchor0[] = { 0x6C, 0x7A, 0x6D, 0x61, 0x00 };

static const xx_format_search_anchor k_anchors[] = {
    { k_anchor0, sizeof(k_anchor0), 0U },
};

static const xx_file_type_t k_types[] = { XX_FILE_TYPE_LOFI };

static Abstractformat *xx_lofi_search_open(xx_io_device *window) {
    xx_lofi *reader = xx_lofi_create(window, 0);
    return reader ? &reader->format : NULL;
}

static void xx_lofi_search_close(Abstractformat *format) {
    /* The format is the first member, so this is the reader itself. */
    xx_lofi_free((xx_lofi *)format);
}

static const xx_format_search_desc k_desc = {
    k_types, sizeof(k_types) / sizeof(k_types[0]),
    k_anchors, sizeof(k_anchors) / sizeof(k_anchors[0]),
    xx_lofi_search_open, xx_lofi_search_close
};

static xx_format_search_state *xx_lofi_create_format_search(
    xx_format_extractor *self, xx_io_device *device, const xx_list_s *options,
    xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_create(&k_desc, device, options, pd);
}

static const xx_format_search_info *xx_lofi_get_current_format_info(
    xx_format_extractor *self, xx_format_search_state *state) {
    (void)self;
    return xx_format_search_current(state);
}

static bool xx_lofi_format_search_find_next(xx_format_extractor *self,
                                          xx_format_search_state *state,
                                          xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_find_next(state, pd);
}

static void xx_lofi_free_format_search(xx_format_extractor *self,
                                     xx_format_search_state *state) {
    (void)self;
    xx_format_search_free(state);
}

xx_format_extractor xx_lofi_extractor = {
    xx_lofi_create_format_search,
    xx_lofi_get_current_format_info,
    xx_lofi_format_search_find_next,
    xx_lofi_free_format_search
};
