/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/goldsrc_bsp/xx_goldsrc_bsp.h"

XX_FORMAT_DEFINE_READER_ADAPTER(goldsrc_bsp, XX_FILE_TYPE_GOLDSRC_BSP,
    xx_goldsrc_bsp_create(device, 0), xx_goldsrc_bsp_free, XX_READER_TYPE_FILL_UNKNOWN)

