/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 */

/* xx_lbrcobol_extractor.c - search raw data for LBRCOBOL.
 *
 * Scans for:
 *   4D 69 63 72 6F 20 46 6F 63 75 73 20 43 4F 42 4F 4C 20 4C 69 62 72 61 72 79 20 46 69 6C 65 at +0  ("Micro Focus COBOL Library File")
 * Offset 0 is always tried as well.
 * Each candidate must be accepted by the lbrcobol reader, which also measures it,
 * and named by the detector, both on a view that starts at the candidate.
 * See xx_format_extractor_engine.h.
 *
 * GENERATED by gen_extractors.py from the detector's prefilters.
 */

#include "../xx_format_extractor_engine.h"
#include "xxfclib/formats/lbrcobol/xx_lbrcobol.h"

static const uint8_t k_anchor0[] = { 0x4D, 0x69, 0x63, 0x72, 0x6F, 0x20, 0x46, 0x6F, 0x63, 0x75, 0x73, 0x20, 0x43, 0x4F, 0x42, 0x4F, 0x4C, 0x20, 0x4C, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x20, 0x46, 0x69, 0x6C, 0x65 };

static const xx_format_search_anchor k_anchors[] = {
    { k_anchor0, sizeof(k_anchor0), 0U },
};

static const xx_file_type_t k_types[] = { XX_FILE_TYPE_LBRCOBOL };

static Abstractformat *xx_lbrcobol_search_open(xx_io_device *window) {
    xx_lbrcobol *reader = xx_lbrcobol_create(window, 0);
    return reader ? &reader->format : NULL;
}

static void xx_lbrcobol_search_close(Abstractformat *format) {
    /* The format is the first member, so this is the reader itself. */
    xx_lbrcobol_free((xx_lbrcobol *)format);
}

static const xx_format_search_desc k_desc = {
    k_types, sizeof(k_types) / sizeof(k_types[0]),
    k_anchors, sizeof(k_anchors) / sizeof(k_anchors[0]),
    xx_lbrcobol_search_open, xx_lbrcobol_search_close
};

static xx_format_search_state *xx_lbrcobol_create_format_search(
    xx_format_extractor *self, xx_io_device *device, const xx_list_s *options,
    xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_create(&k_desc, device, options, pd);
}

static const xx_format_search_info *xx_lbrcobol_get_current_format_info(
    xx_format_extractor *self, xx_format_search_state *state) {
    (void)self;
    return xx_format_search_current(state);
}

static bool xx_lbrcobol_format_search_find_next(xx_format_extractor *self,
                                          xx_format_search_state *state,
                                          xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_find_next(state, pd);
}

static void xx_lbrcobol_free_format_search(xx_format_extractor *self,
                                     xx_format_search_state *state) {
    (void)self;
    xx_format_search_free(state);
}

xx_format_extractor xx_lbrcobol_extractor = {
    xx_lbrcobol_create_format_search,
    xx_lbrcobol_get_current_format_info,
    xx_lbrcobol_format_search_find_next,
    xx_lbrcobol_free_format_search
};
