/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/xpk_compressed_file/xx_xpk_compressed_file.h"

XX_FORMAT_DEFINE_READER_ADAPTER(xpk_compressed_file, XX_FILE_TYPE_XPK_COMPRESSED_FILE,
    xx_xpk_compressed_file_create(device, 0), xx_xpk_compressed_file_free, XX_READER_TYPE_FILL_UNKNOWN)

