/* SPDX-License-Identifier: MIT
 * Primary reference: https://raw.githubusercontent.com/project-gemmi/gemmi/master/include/gemmi/mtz.hpp
 * CCP4 MTZ little-endian reflection tables: complete counted finite/missing-value columns and typed80-byte footer records, local datasets/columns/cell/symmetry metadata and exact EOF. Original descriptor, reflection table and header records exported; batch blocks, big-endian and unknown extensions declined.
 * Bounded32MiB input,4096 components and bounded work.
 */
#include "xxfclib/formats/crystallography_mtz/xx_crystallography_mtz.h"
#include "../wbmp_image/xx_fifteenth_games.h"
static bool vg_quick(Abstractformat *f,uint64_t n) {uint8_t b[12];return n>=160&&pm_read(f,0,b,12)&&vg_tag(b,"MTZ ",4)&&b[8]==0x44&&b[9]==0x41&&b[10]==0&&b[11]==0;}
typedef struct vg_column {char name[64];uint8_t type;int32_t dataset;bool source;} vg_column;
static bool vg_mtoken(vg_text *q,char *out,size_t z) {size_t k=0;vg_space(q);while(q->t<q->stop&&q->b[q->t]!=32&&q->b[q->t]!=9){uint8_t c=q->b[q->t++];if(k+1>=z||c<33||c>126)return false;out[k++]=(char)c;}out[k]=0;return k!=0;}
static bool vg_mcell(vg_text *q) {double v;unsigned i;for(i=0;i<6;++i)if(!vg_num(q,&v)||v<=0||(i>=3&&v>=180))return false;return vg_done(q);}
static bool vg_sym(vg_text *q) {unsigned axis;for(axis=0;axis<3;++axis){unsigned terms=0,variables=0;while(q->t<q->stop){uint8_t c;vg_space(q);if(q->t==q->stop)break;c=q->b[q->t];if(c=='+'||c=='-'){++q->t;vg_space(q);}else if(terms)return false;if(q->t==q->stop||++terms>8)return false;c=q->b[q->t++];if(c=='X'||c=='Y'||c=='Z'){unsigned bit=1U<<(c-'X');if(variables&bit)return false;variables|=bit;}else if(c>='0'&&c<='9'){unsigned num=c-'0',den=1;while(q->t<q->stop&&q->b[q->t]>='0'&&q->b[q->t]<='9'){num=num*10+q->b[q->t++]-'0';if(num>96)return false;}if(q->t<q->stop&&q->b[q->t]=='/'){++q->t;den=0;while(q->t<q->stop&&q->b[q->t]>='0'&&q->b[q->t]<='9'){den=den*10+q->b[q->t++]-'0';if(den>48)return false;}if(!den)return false;}}else return false;vg_space(q);if(q->t==q->stop||q->b[q->t]==',')break;}if(!terms||!variables)return false;if(axis<2){if(q->t==q->stop||q->b[q->t++]!=',')return false;}else if(!vg_done(q))return false;}return true;}
static bool vg_parse(Abstractformat *f,pm_stream *s,const uint8_t *b,uint64_t n,xx_pd_struct *pd) {uint64_t start,p,data;vg_column *cols=NULL;uint8_t datasets[128];uint32_t nc=0,nref=0,ncols=0,sym=0,expected_sym=0,ndif=0,history=0,flags=0;bool missing=false,ended=false,final=false,ok=false;char name[128],label[48];unsigned records=0,i;xx_mem_zero(datasets,sizeof(datasets));if(n<160||!vg_tag(b,"MTZ ",4)||b[8]!=0x44||b[9]!=0x41||b[10]||b[11]||pm_le32(b+4)<21||!vg_zero(b+12,68))return false;start=((uint64_t)pm_le32(b+4)-1)*4;if(start<80||start>=n||(n-start)%80||(n-start)/80>4000)return false;data=start-80;cols=(vg_column *)xx_mem_alloc(sizeof(*cols)*512);if(!cols)return false;xx_mem_zero(cols,sizeof(*cols)*512);if(!vg_emit(f,s,"descriptor.mtz",0,80,n)||!vg_emit(f,s,"reflections.f32le",80,data,n))goto done;for(p=start;p<n;p+=80){vg_text q={b,p,p+80,p,p+80,p};double v,w;int32_t a,c;unsigned field;if(vg_stop(pd)||!vg_utf(b+p,80,true,pd))goto done;if(final)goto done;if(history){--history;}else if(ended){if(vg_word(&q,"MTZHIST")){if(!vg_i(&q,&a)||a<0||a>1000||!vg_done(&q))goto done;history=(uint32_t)a;}else if(vg_word(&q,"MTZENDOFHEADERS")&&vg_done(&q)){final=true;}else goto done;}
 else if(vg_word(&q,"VERS")){if((flags&1)||!vg_word(&q,"MTZ:V1.1")||!vg_done(&q))goto done;flags|=1;}
 else if(vg_word(&q,"TITLE")){if(flags&2)goto done;flags|=2;}
 else if(vg_word(&q,"NCOL")){if((flags&4)||!vg_i(&q,&a)||a<1||a>512)goto done;nc=(uint32_t)a;if(!vg_i(&q,&a)||a<1||a>1000000)goto done;nref=(uint32_t)a;if(!vg_i(&q,&a)||a||!vg_done(&q)||data!=(uint64_t)nc*nref*4)goto done;flags|=4;}
 else if(vg_word(&q,"CELL")){if((flags&8)||!vg_mcell(&q))goto done;flags|=8;}
 else if(vg_word(&q,"SORT")){if(flags&16)goto done;for(i=0;i<5;++i)if(!vg_i(&q,&a)||a<0||a>(int32_t)nc)goto done;if(!vg_done(&q))goto done;flags|=16;}
 else if(vg_word(&q,"SYMINF")){uint64_t at,z;if((flags&32)||!vg_i(&q,&a)||a<1||a>192)goto done;expected_sym=(uint32_t)a;if(!vg_i(&q,&c)||c<1||c>a||!vg_mtoken(&q,name,sizeof(name))||xx_rt_strlen(name)!=1||!xx_rt_strchr("PABCIFR",name[0])||!vg_i(&q,&a)||a<1||a>230)goto done;vg_space(&q);at=q.t;if(at==q.stop||b[q.t++]!='\'')goto done;z=q.t;while(q.t<q.stop&&b[q.t]!='\'')++q.t;if(q.t==q.stop||q.t-z<1||q.t-z>40)goto done;++q.t;if(!vg_mtoken(&q,name,sizeof(name))||!vg_done(&q))goto done;flags|=32;}
 else if(vg_word(&q,"SYMM")){if(!(flags&32)||++sym>expected_sym||!vg_sym(&q))goto done;}
 else if(vg_word(&q,"RESO")){if((flags&64)||!vg_num(&q,&v)||!vg_num(&q,&w)||v<=0||w<v||!vg_done(&q))goto done;flags|=64;}
 else if(vg_word(&q,"VALM")){if(flags&128)goto done;if(vg_word(&q,"NAN"))missing=true;else if(!vg_num(&q,&v))goto done;if(!vg_done(&q))goto done;flags|=128;}
 else if(vg_word(&q,"COLUMN")){char type[8];if(!(flags&4)||ncols>=nc||!vg_mtoken(&q,cols[ncols].name,64)||!vg_mtoken(&q,type,sizeof(type))||xx_rt_strlen(type)!=1||!xx_rt_strchr("HFJDQGLKMEPWABYIR",type[0])||!vg_num(&q,&v)||!vg_num(&q,&w)||w<v||!vg_i(&q,&a)||a<0||a>=128||!vg_done(&q))goto done;for(i=0;i<ncols;++i)if(cols[i].dataset==a&&!xx_rt_strcmp(cols[i].name,cols[ncols].name))goto done;cols[ncols].dataset=a;cols[ncols++].type=(uint8_t)type[0];}
 else if(vg_word(&q,"COLSRC")){if(!vg_mtoken(&q,name,sizeof(name)))goto done;{char date[64];if(!vg_mtoken(&q,date,sizeof(date))||!vg_i(&q,&a)||!vg_done(&q))goto done;}for(i=0;i<ncols;++i)if(cols[i].dataset==a&&!xx_rt_strcmp(cols[i].name,name))break;if(i==ncols||cols[i].source)goto done;cols[i].source=true;}
 else if(vg_word(&q,"NDIF")){if((flags&256)||!vg_i(&q,&a)||a<1||a>128||!vg_done(&q))goto done;ndif=(uint32_t)a;flags|=256;}
 else {vg_text copy=q;field=0;if(vg_word(&q,"PROJECT"))field=1;else if(vg_word(&q,"CRYSTAL"))field=2;else if(vg_word(&q,"DATASET"))field=4;else if(vg_word(&q,"DCELL"))field=8;else if(vg_word(&q,"DWAVEL"))field=16;if(field){if(!(flags&256)||!vg_i(&q,&a)||a<0||a>=128||(datasets[a]&field))goto done;if(field==8){if(!vg_mcell(&q))goto done;}else if(field==16){if(!vg_num(&q,&v)||v<0||!vg_done(&q))goto done;}else if(!vg_mtoken(&q,name,sizeof(name))||!vg_done(&q))goto done;datasets[a]|=(uint8_t)field;}else {q=copy;if(!vg_word(&q,"END")||!vg_done(&q))goto done;ended=true;}}
 xx_rt_snprintf(label,sizeof(label),"header-record-%u.mtz",records++);if(!vg_emit(f,s,label,p,80,n))goto done;}
 if(!final||history||flags!=511||ncols!=nc||sym!=expected_sym) {goto done; } {unsigned found=0;for(i=0;i<128;++i)if(datasets[i]){if(datasets[i]!=31)goto done;++found;}if(found!=ndif)goto done;}for(i=0;i<ncols;++i)if(datasets[cols[i].dataset]!=31)goto done;for(p=80;p<start;p+=4){uint32_t u=pm_le32(b+p),column=(uint32_t)((p-80)/4%nc);if(((p&4095)==0&&vg_stop(pd)))goto done;if((u&0x7f800000U)==0x7f800000U){if(!missing||!(u&0x007fffffU))goto done;}else if(cols[column].type=='H'){union {uint32_t u;float f;} val;val.u=u;if(val.f< -32768||val.f>32767||val.f!=(float)(int32_t)val.f)goto done;}}ok=true;done:if(cols)xx_mem_free(cols);return ok;}

void xx_crystallography_mtz_init(xx_crystallography_mtz *r,xx_io_device *d,int64_t at) {if(r){xx_mem_zero(r,sizeof(*r));pm_init(&r->format,d,at,XX_FILE_TYPE_CRYSTALLOGRAPHY_MTZ,"mtz");}}
xx_crystallography_mtz *xx_crystallography_mtz_create(xx_io_device *d,int64_t at) {xx_crystallography_mtz *r=(xx_crystallography_mtz *)xx_mem_alloc(sizeof(*r));if(r)xx_crystallography_mtz_init(r,d,at);return r;}
void xx_crystallography_mtz_destroy(xx_crystallography_mtz *r) {if(r)xx_format_cleanup_extra_parameters(&r->format);}
void xx_crystallography_mtz_free(xx_crystallography_mtz *r) {if(r){xx_crystallography_mtz_destroy(r);xx_mem_free(r);}}
bool xx_crystallography_mtz_check_is_valid(Abstractformat *f,xx_pd_struct *pd) {return pm_valid(f,pd);}
bool xx_crystallography_mtz_handle_base_info(Abstractformat *f,xx_pd_struct *pd) {return pm_handle(f,pd);}
