/* Generated by generate_die_music_files.py; do not edit. */
/* SPDX-License-Identifier: MIT */
#include "xxfclib/formats/die_music/xx_die_music.h"
#include "../../xx_format_extractor_engine.h"
#include "../../xx_format_abstract_extractor_adapter.h"

const xx_die_music_descriptor xx_die_music_eeben_pollytracker_mod_descriptor = {
    "EEBEN_POLLYTRACKER_MOD",
    "Aleksi Eeben's Polly Tracker module (.MOD)",
    "Binary/audio.1.sg",
    13330U,
    false,
    XX_FILE_TYPE_DIE_MUSIC_EEBEN_POLLYTRACKER_MOD
};

XXFC_API Abstractformat *xx_die_music_eeben_pollytracker_mod_create(xx_io_device *device, int64_t base)
{
    return xx_die_music_reader_create(&xx_die_music_eeben_pollytracker_mod_descriptor, device, base);
}

XXFC_API void xx_die_music_eeben_pollytracker_mod_free(void *reader)
{
    xx_die_music_reader_free(reader);
}

static const xx_file_type_t xx_die_music_eeben_pollytracker_mod_types[] = {
    XX_FILE_TYPE_DIE_MUSIC_EEBEN_POLLYTRACKER_MOD
};

static Abstractformat *xx_die_music_eeben_pollytracker_mod_open(xx_io_device *window)
{
    return xx_die_music_eeben_pollytracker_mod_create(window, 0);
}

static void xx_die_music_eeben_pollytracker_mod_close(Abstractformat *format)
{
    xx_die_music_eeben_pollytracker_mod_free(format);
}

static const xx_format_search_desc xx_die_music_eeben_pollytracker_mod_search_desc = {
    xx_die_music_eeben_pollytracker_mod_types, 1U, NULL, 0U,
    xx_die_music_eeben_pollytracker_mod_open, xx_die_music_eeben_pollytracker_mod_close, true
};

static xx_format_search_state *xx_die_music_eeben_pollytracker_mod_create_search(
    xx_format_extractor *self, xx_io_device *device,
    const xx_list_s *options, xx_pd_struct *pd)
{
    (void)self;
    return xx_format_search_create(&xx_die_music_eeben_pollytracker_mod_search_desc, device, options, pd);
}

static const xx_format_search_info *xx_die_music_eeben_pollytracker_mod_current(
    xx_format_extractor *self, xx_format_search_state *state)
{
    (void)self;
    return xx_format_search_current(state);
}

static bool xx_die_music_eeben_pollytracker_mod_next(
    xx_format_extractor *self, xx_format_search_state *state, xx_pd_struct *pd)
{
    (void)self;
    return xx_format_search_find_next(state, pd);
}

static void xx_die_music_eeben_pollytracker_mod_free_search(
    xx_format_extractor *self, xx_format_search_state *state)
{
    (void)self;
    xx_format_search_free(state);
}

xx_format_extractor xx_die_music_eeben_pollytracker_mod_extractor = {
    xx_die_music_eeben_pollytracker_mod_create_search,
    xx_die_music_eeben_pollytracker_mod_current,
    xx_die_music_eeben_pollytracker_mod_next,
    xx_die_music_eeben_pollytracker_mod_free_search
};

XX_FORMAT_DEFINE_ABSTRACT_EXTRACTOR(
    die_music_eeben_pollytracker_mod, xx_die_music_eeben_pollytracker_mod_search_desc)
