/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 */

/* xx_csman_extractor.c - search raw data for CSman DAT file.
 *
 * Scans for:
 *   43 53 at +0  ("CS")
 *   53 43 at +0  ("SC")
 * Offset 0 is always tried as well.
 * Each candidate must be accepted by the csman reader, which also measures it,
 * and named by the detector, both on a view that starts at the candidate.
 * See xx_format_extractor_engine.h.
 *
 * GENERATED by gen_extractors.py from the detector's prefilters.
 */

#include "../xx_format_extractor_engine.h"
#include "xxfclib/formats/csman/xx_csman.h"

static const uint8_t k_anchor0[] = { 0x43, 0x53 };
static const uint8_t k_anchor1[] = { 0x53, 0x43 };

static const xx_format_search_anchor k_anchors[] = {
    { k_anchor0, sizeof(k_anchor0), 0U },
    { k_anchor1, sizeof(k_anchor1), 0U },
};

static const xx_file_type_t k_types[] = { XX_FILE_TYPE_CSMAN };

static Abstractformat *xx_csman_search_open(xx_io_device *window) {
    xx_csman *reader = xx_csman_create(window, 0);
    return reader ? &reader->format : NULL;
}

static void xx_csman_search_close(Abstractformat *format) {
    /* The format is the first member, so this is the reader itself. */
    xx_csman_free((xx_csman *)format);
}

static const xx_format_search_desc k_desc = {
    k_types, sizeof(k_types) / sizeof(k_types[0]),
    k_anchors, sizeof(k_anchors) / sizeof(k_anchors[0]),
    xx_csman_search_open, xx_csman_search_close
};

static xx_format_search_state *xx_csman_create_format_search(
    xx_format_extractor *self, xx_io_device *device, const xx_list_s *options,
    xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_create(&k_desc, device, options, pd);
}

static const xx_format_search_info *xx_csman_get_current_format_info(
    xx_format_extractor *self, xx_format_search_state *state) {
    (void)self;
    return xx_format_search_current(state);
}

static bool xx_csman_format_search_find_next(xx_format_extractor *self,
                                          xx_format_search_state *state,
                                          xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_find_next(state, pd);
}

static void xx_csman_free_format_search(xx_format_extractor *self,
                                     xx_format_search_state *state) {
    (void)self;
    xx_format_search_free(state);
}

xx_format_extractor xx_csman_extractor = {
    xx_csman_create_format_search,
    xx_csman_get_current_format_info,
    xx_csman_format_search_find_next,
    xx_csman_free_format_search
};
