/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 */

/* xx_tar_extractor.c - search raw data for TAR.
 *
 * Scans for:
 *   75 73 74 61 72 at +257  ("ustar")
 * (hand-written: the detector establishes this signature outside its
 * 64-byte prefilter window)
 * Offset 0 is always tried as well.
 * Each candidate must be accepted by the tar reader, which also measures it,
 * and named by the detector, both on a view that starts at the candidate.
 * See xx_format_extractor_engine.h.
 *
 * GENERATED by gen_extractors.py from the detector's prefilters.
 */

#include "../xx_format_extractor_engine.h"
#include "xxfclib/formats/tar/xx_tar.h"

static const uint8_t k_anchor0[] = { 0x75, 0x73, 0x74, 0x61, 0x72 };

static const xx_format_search_anchor k_anchors[] = {
    { k_anchor0, sizeof(k_anchor0), 257U },
};

static const xx_file_type_t k_types[] = { XX_FILE_TYPE_TAR };

static Abstractformat *xx_tar_search_open(xx_io_device *window) {
    xx_tar *reader = xx_tar_create(window, 0);
    return reader ? &reader->format : NULL;
}

static void xx_tar_search_close(Abstractformat *format) {
    /* The format is the first member, so this is the reader itself. */
    xx_tar_free((xx_tar *)format);
}

static const xx_format_search_desc k_desc = {
    k_types, sizeof(k_types) / sizeof(k_types[0]),
    k_anchors, sizeof(k_anchors) / sizeof(k_anchors[0]),
    xx_tar_search_open, xx_tar_search_close
};

static xx_format_search_state *xx_tar_create_format_search(
    xx_format_extractor *self, xx_io_device *device, const xx_list_s *options,
    xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_create(&k_desc, device, options, pd);
}

static const xx_format_search_info *xx_tar_get_current_format_info(
    xx_format_extractor *self, xx_format_search_state *state) {
    (void)self;
    return xx_format_search_current(state);
}

static bool xx_tar_format_search_find_next(xx_format_extractor *self,
                                          xx_format_search_state *state,
                                          xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_find_next(state, pd);
}

static void xx_tar_free_format_search(xx_format_extractor *self,
                                     xx_format_search_state *state) {
    (void)self;
    xx_format_search_free(state);
}

xx_format_extractor xx_tar_extractor = {
    xx_tar_create_format_search,
    xx_tar_get_current_format_info,
    xx_tar_format_search_find_next,
    xx_tar_free_format_search
};
