/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 */

/* xx_diskexpress_extractor.c - search raw data for DiskExpress.
 *
 * Scans for:
 *   41 53 01 01 20 03 at +0  ("AS.. .")
 *   41 53 01 01 41 03 at +0  ("AS..A.")
 *   41 53 01 01 61 03 at +0  ("AS..a.")
 *   41 53 01 04 20 03 at +0  ("AS.. .")
 *   41 53 01 04 41 03 at +0  ("AS..A.")
 *   41 53 01 04 61 03 at +0  ("AS..a.")
 *   41 53 02 00 20 03 at +0  ("AS.. .")
 *   41 53 02 00 41 03 at +0  ("AS..A.")
 *   41 53 02 00 61 03 at +0  ("AS..a.")
 *   41 53 02 1E 20 03 at +0  ("AS.. .")
 *   41 53 02 1E 41 03 at +0  ("AS..A.")
 *   41 53 02 1E 61 03 at +0  ("AS..a.")
 *   41 53 01 01 20 04 at +0  ("AS.. .")
 *   41 53 01 01 41 04 at +0  ("AS..A.")
 *   41 53 01 01 61 04 at +0  ("AS..a.")
 *   41 53 01 04 20 04 at +0  ("AS.. .")
 *   41 53 01 04 41 04 at +0  ("AS..A.")
 *   41 53 01 04 61 04 at +0  ("AS..a.")
 *   41 53 02 00 20 04 at +0  ("AS.. .")
 *   41 53 02 00 41 04 at +0  ("AS..A.")
 *   41 53 02 00 61 04 at +0  ("AS..a.")
 *   41 53 02 1E 20 04 at +0  ("AS.. .")
 *   41 53 02 1E 41 04 at +0  ("AS..A.")
 *   41 53 02 1E 61 04 at +0  ("AS..a.")
 *   41 53 01 01 20 05 at +0  ("AS.. .")
 *   41 53 01 01 41 05 at +0  ("AS..A.")
 *   41 53 01 01 61 05 at +0  ("AS..a.")
 *   41 53 01 04 20 05 at +0  ("AS.. .")
 *   41 53 01 04 41 05 at +0  ("AS..A.")
 *   41 53 01 04 61 05 at +0  ("AS..a.")
 *   41 53 02 00 20 05 at +0  ("AS.. .")
 *   41 53 02 00 41 05 at +0  ("AS..A.")
 *   41 53 02 00 61 05 at +0  ("AS..a.")
 *   41 53 02 1E 20 05 at +0  ("AS.. .")
 *   41 53 02 1E 41 05 at +0  ("AS..A.")
 *   41 53 02 1E 61 05 at +0  ("AS..a.")
 *   41 53 01 01 20 06 at +0  ("AS.. .")
 *   41 53 01 01 41 06 at +0  ("AS..A.")
 *   41 53 01 01 61 06 at +0  ("AS..a.")
 *   41 53 01 04 20 06 at +0  ("AS.. .")
 *   41 53 01 04 41 06 at +0  ("AS..A.")
 *   41 53 01 04 61 06 at +0  ("AS..a.")
 *   41 53 02 00 20 06 at +0  ("AS.. .")
 *   41 53 02 00 41 06 at +0  ("AS..A.")
 *   41 53 02 00 61 06 at +0  ("AS..a.")
 *   41 53 02 1E 20 06 at +0  ("AS.. .")
 *   41 53 02 1E 41 06 at +0  ("AS..A.")
 *   41 53 02 1E 61 06 at +0  ("AS..a.")
 *   41 53 01 01 20 07 at +0  ("AS.. .")
 *   41 53 01 01 41 07 at +0  ("AS..A.")
 *   41 53 01 01 61 07 at +0  ("AS..a.")
 *   41 53 01 04 20 07 at +0  ("AS.. .")
 *   41 53 01 04 41 07 at +0  ("AS..A.")
 *   41 53 01 04 61 07 at +0  ("AS..a.")
 *   41 53 02 00 20 07 at +0  ("AS.. .")
 *   41 53 02 00 41 07 at +0  ("AS..A.")
 *   41 53 02 00 61 07 at +0  ("AS..a.")
 *   41 53 02 1E 20 07 at +0  ("AS.. .")
 *   41 53 02 1E 41 07 at +0  ("AS..A.")
 *   41 53 02 1E 61 07 at +0  ("AS..a.")
 * Offset 0 is always tried as well.
 * Each candidate must be accepted by the diskexpress reader, which also measures it,
 * and named by the detector, both on a view that starts at the candidate.
 * See xx_format_extractor_engine.h.
 *
 * GENERATED by gen_extractors.py from the detector's prefilters.
 */

#include "../xx_format_extractor_engine.h"
#include "xxfclib/formats/diskexpress/xx_diskexpress.h"

static const uint8_t k_anchor0[] = { 0x41, 0x53, 0x01, 0x01, 0x20, 0x03 };
static const uint8_t k_anchor1[] = { 0x41, 0x53, 0x01, 0x01, 0x41, 0x03 };
static const uint8_t k_anchor2[] = { 0x41, 0x53, 0x01, 0x01, 0x61, 0x03 };
static const uint8_t k_anchor3[] = { 0x41, 0x53, 0x01, 0x04, 0x20, 0x03 };
static const uint8_t k_anchor4[] = { 0x41, 0x53, 0x01, 0x04, 0x41, 0x03 };
static const uint8_t k_anchor5[] = { 0x41, 0x53, 0x01, 0x04, 0x61, 0x03 };
static const uint8_t k_anchor6[] = { 0x41, 0x53, 0x02, 0x00, 0x20, 0x03 };
static const uint8_t k_anchor7[] = { 0x41, 0x53, 0x02, 0x00, 0x41, 0x03 };
static const uint8_t k_anchor8[] = { 0x41, 0x53, 0x02, 0x00, 0x61, 0x03 };
static const uint8_t k_anchor9[] = { 0x41, 0x53, 0x02, 0x1E, 0x20, 0x03 };
static const uint8_t k_anchor10[] = { 0x41, 0x53, 0x02, 0x1E, 0x41, 0x03 };
static const uint8_t k_anchor11[] = { 0x41, 0x53, 0x02, 0x1E, 0x61, 0x03 };
static const uint8_t k_anchor12[] = { 0x41, 0x53, 0x01, 0x01, 0x20, 0x04 };
static const uint8_t k_anchor13[] = { 0x41, 0x53, 0x01, 0x01, 0x41, 0x04 };
static const uint8_t k_anchor14[] = { 0x41, 0x53, 0x01, 0x01, 0x61, 0x04 };
static const uint8_t k_anchor15[] = { 0x41, 0x53, 0x01, 0x04, 0x20, 0x04 };
static const uint8_t k_anchor16[] = { 0x41, 0x53, 0x01, 0x04, 0x41, 0x04 };
static const uint8_t k_anchor17[] = { 0x41, 0x53, 0x01, 0x04, 0x61, 0x04 };
static const uint8_t k_anchor18[] = { 0x41, 0x53, 0x02, 0x00, 0x20, 0x04 };
static const uint8_t k_anchor19[] = { 0x41, 0x53, 0x02, 0x00, 0x41, 0x04 };
static const uint8_t k_anchor20[] = { 0x41, 0x53, 0x02, 0x00, 0x61, 0x04 };
static const uint8_t k_anchor21[] = { 0x41, 0x53, 0x02, 0x1E, 0x20, 0x04 };
static const uint8_t k_anchor22[] = { 0x41, 0x53, 0x02, 0x1E, 0x41, 0x04 };
static const uint8_t k_anchor23[] = { 0x41, 0x53, 0x02, 0x1E, 0x61, 0x04 };
static const uint8_t k_anchor24[] = { 0x41, 0x53, 0x01, 0x01, 0x20, 0x05 };
static const uint8_t k_anchor25[] = { 0x41, 0x53, 0x01, 0x01, 0x41, 0x05 };
static const uint8_t k_anchor26[] = { 0x41, 0x53, 0x01, 0x01, 0x61, 0x05 };
static const uint8_t k_anchor27[] = { 0x41, 0x53, 0x01, 0x04, 0x20, 0x05 };
static const uint8_t k_anchor28[] = { 0x41, 0x53, 0x01, 0x04, 0x41, 0x05 };
static const uint8_t k_anchor29[] = { 0x41, 0x53, 0x01, 0x04, 0x61, 0x05 };
static const uint8_t k_anchor30[] = { 0x41, 0x53, 0x02, 0x00, 0x20, 0x05 };
static const uint8_t k_anchor31[] = { 0x41, 0x53, 0x02, 0x00, 0x41, 0x05 };
static const uint8_t k_anchor32[] = { 0x41, 0x53, 0x02, 0x00, 0x61, 0x05 };
static const uint8_t k_anchor33[] = { 0x41, 0x53, 0x02, 0x1E, 0x20, 0x05 };
static const uint8_t k_anchor34[] = { 0x41, 0x53, 0x02, 0x1E, 0x41, 0x05 };
static const uint8_t k_anchor35[] = { 0x41, 0x53, 0x02, 0x1E, 0x61, 0x05 };
static const uint8_t k_anchor36[] = { 0x41, 0x53, 0x01, 0x01, 0x20, 0x06 };
static const uint8_t k_anchor37[] = { 0x41, 0x53, 0x01, 0x01, 0x41, 0x06 };
static const uint8_t k_anchor38[] = { 0x41, 0x53, 0x01, 0x01, 0x61, 0x06 };
static const uint8_t k_anchor39[] = { 0x41, 0x53, 0x01, 0x04, 0x20, 0x06 };
static const uint8_t k_anchor40[] = { 0x41, 0x53, 0x01, 0x04, 0x41, 0x06 };
static const uint8_t k_anchor41[] = { 0x41, 0x53, 0x01, 0x04, 0x61, 0x06 };
static const uint8_t k_anchor42[] = { 0x41, 0x53, 0x02, 0x00, 0x20, 0x06 };
static const uint8_t k_anchor43[] = { 0x41, 0x53, 0x02, 0x00, 0x41, 0x06 };
static const uint8_t k_anchor44[] = { 0x41, 0x53, 0x02, 0x00, 0x61, 0x06 };
static const uint8_t k_anchor45[] = { 0x41, 0x53, 0x02, 0x1E, 0x20, 0x06 };
static const uint8_t k_anchor46[] = { 0x41, 0x53, 0x02, 0x1E, 0x41, 0x06 };
static const uint8_t k_anchor47[] = { 0x41, 0x53, 0x02, 0x1E, 0x61, 0x06 };
static const uint8_t k_anchor48[] = { 0x41, 0x53, 0x01, 0x01, 0x20, 0x07 };
static const uint8_t k_anchor49[] = { 0x41, 0x53, 0x01, 0x01, 0x41, 0x07 };
static const uint8_t k_anchor50[] = { 0x41, 0x53, 0x01, 0x01, 0x61, 0x07 };
static const uint8_t k_anchor51[] = { 0x41, 0x53, 0x01, 0x04, 0x20, 0x07 };
static const uint8_t k_anchor52[] = { 0x41, 0x53, 0x01, 0x04, 0x41, 0x07 };
static const uint8_t k_anchor53[] = { 0x41, 0x53, 0x01, 0x04, 0x61, 0x07 };
static const uint8_t k_anchor54[] = { 0x41, 0x53, 0x02, 0x00, 0x20, 0x07 };
static const uint8_t k_anchor55[] = { 0x41, 0x53, 0x02, 0x00, 0x41, 0x07 };
static const uint8_t k_anchor56[] = { 0x41, 0x53, 0x02, 0x00, 0x61, 0x07 };
static const uint8_t k_anchor57[] = { 0x41, 0x53, 0x02, 0x1E, 0x20, 0x07 };
static const uint8_t k_anchor58[] = { 0x41, 0x53, 0x02, 0x1E, 0x41, 0x07 };
static const uint8_t k_anchor59[] = { 0x41, 0x53, 0x02, 0x1E, 0x61, 0x07 };

static const xx_format_search_anchor k_anchors[] = {
    { k_anchor0, sizeof(k_anchor0), 0U },
    { k_anchor1, sizeof(k_anchor1), 0U },
    { k_anchor2, sizeof(k_anchor2), 0U },
    { k_anchor3, sizeof(k_anchor3), 0U },
    { k_anchor4, sizeof(k_anchor4), 0U },
    { k_anchor5, sizeof(k_anchor5), 0U },
    { k_anchor6, sizeof(k_anchor6), 0U },
    { k_anchor7, sizeof(k_anchor7), 0U },
    { k_anchor8, sizeof(k_anchor8), 0U },
    { k_anchor9, sizeof(k_anchor9), 0U },
    { k_anchor10, sizeof(k_anchor10), 0U },
    { k_anchor11, sizeof(k_anchor11), 0U },
    { k_anchor12, sizeof(k_anchor12), 0U },
    { k_anchor13, sizeof(k_anchor13), 0U },
    { k_anchor14, sizeof(k_anchor14), 0U },
    { k_anchor15, sizeof(k_anchor15), 0U },
    { k_anchor16, sizeof(k_anchor16), 0U },
    { k_anchor17, sizeof(k_anchor17), 0U },
    { k_anchor18, sizeof(k_anchor18), 0U },
    { k_anchor19, sizeof(k_anchor19), 0U },
    { k_anchor20, sizeof(k_anchor20), 0U },
    { k_anchor21, sizeof(k_anchor21), 0U },
    { k_anchor22, sizeof(k_anchor22), 0U },
    { k_anchor23, sizeof(k_anchor23), 0U },
    { k_anchor24, sizeof(k_anchor24), 0U },
    { k_anchor25, sizeof(k_anchor25), 0U },
    { k_anchor26, sizeof(k_anchor26), 0U },
    { k_anchor27, sizeof(k_anchor27), 0U },
    { k_anchor28, sizeof(k_anchor28), 0U },
    { k_anchor29, sizeof(k_anchor29), 0U },
    { k_anchor30, sizeof(k_anchor30), 0U },
    { k_anchor31, sizeof(k_anchor31), 0U },
    { k_anchor32, sizeof(k_anchor32), 0U },
    { k_anchor33, sizeof(k_anchor33), 0U },
    { k_anchor34, sizeof(k_anchor34), 0U },
    { k_anchor35, sizeof(k_anchor35), 0U },
    { k_anchor36, sizeof(k_anchor36), 0U },
    { k_anchor37, sizeof(k_anchor37), 0U },
    { k_anchor38, sizeof(k_anchor38), 0U },
    { k_anchor39, sizeof(k_anchor39), 0U },
    { k_anchor40, sizeof(k_anchor40), 0U },
    { k_anchor41, sizeof(k_anchor41), 0U },
    { k_anchor42, sizeof(k_anchor42), 0U },
    { k_anchor43, sizeof(k_anchor43), 0U },
    { k_anchor44, sizeof(k_anchor44), 0U },
    { k_anchor45, sizeof(k_anchor45), 0U },
    { k_anchor46, sizeof(k_anchor46), 0U },
    { k_anchor47, sizeof(k_anchor47), 0U },
    { k_anchor48, sizeof(k_anchor48), 0U },
    { k_anchor49, sizeof(k_anchor49), 0U },
    { k_anchor50, sizeof(k_anchor50), 0U },
    { k_anchor51, sizeof(k_anchor51), 0U },
    { k_anchor52, sizeof(k_anchor52), 0U },
    { k_anchor53, sizeof(k_anchor53), 0U },
    { k_anchor54, sizeof(k_anchor54), 0U },
    { k_anchor55, sizeof(k_anchor55), 0U },
    { k_anchor56, sizeof(k_anchor56), 0U },
    { k_anchor57, sizeof(k_anchor57), 0U },
    { k_anchor58, sizeof(k_anchor58), 0U },
    { k_anchor59, sizeof(k_anchor59), 0U },
};

static const xx_file_type_t k_types[] = { XX_FILE_TYPE_DISKEXPRESS };

static Abstractformat *xx_diskexpress_search_open(xx_io_device *window) {
    xx_diskexpress *reader = xx_diskexpress_create(window, 0);
    return reader ? &reader->format : NULL;
}

static void xx_diskexpress_search_close(Abstractformat *format) {
    /* The format is the first member, so this is the reader itself. */
    xx_diskexpress_free((xx_diskexpress *)format);
}

static const xx_format_search_desc k_desc = {
    k_types, sizeof(k_types) / sizeof(k_types[0]),
    k_anchors, sizeof(k_anchors) / sizeof(k_anchors[0]),
    xx_diskexpress_search_open, xx_diskexpress_search_close
};

static xx_format_search_state *xx_diskexpress_create_format_search(
    xx_format_extractor *self, xx_io_device *device, const xx_list_s *options,
    xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_create(&k_desc, device, options, pd);
}

static const xx_format_search_info *xx_diskexpress_get_current_format_info(
    xx_format_extractor *self, xx_format_search_state *state) {
    (void)self;
    return xx_format_search_current(state);
}

static bool xx_diskexpress_format_search_find_next(xx_format_extractor *self,
                                          xx_format_search_state *state,
                                          xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_find_next(state, pd);
}

static void xx_diskexpress_free_format_search(xx_format_extractor *self,
                                     xx_format_search_state *state) {
    (void)self;
    xx_format_search_free(state);
}

xx_format_extractor xx_diskexpress_extractor = {
    xx_diskexpress_create_format_search,
    xx_diskexpress_get_current_format_info,
    xx_diskexpress_format_search_find_next,
    xx_diskexpress_free_format_search
};
