/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/atari_dos2/xx_atari_dos2.h"

XX_FORMAT_DEFINE_READER_ADAPTER(atari_dos2, XX_FILE_TYPE_ATARI_DOS2,
    xx_atari_dos2_create(device, 0), xx_atari_dos2_free, XX_READER_TYPE_FILL_UNKNOWN)

