/* Copyright (c)2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT. Bounded typed components; payloads never executed.
 */
/* Primary: https://github.com/safetensors/safetensors */
#include "xxfclib/formats/safetensors/xx_safetensors.h"
#include "xxfclib/data/xx_data.h"
#include "../xx_fourteenth_wrappers.h"

typedef struct jscan{nh_blob *b;uint64_t p,end;unsigned work,comparisons;uint64_t comparebytes;}jscan;
typedef struct tensor{char name[256];uint64_t first,last,bytes;}tensor;
static bool ws(jscan *j){while(j->p<j->end){uint8_t c=j->b->p[(size_t)j->p];if(c!=' '&&c!='\t'&&c!='\r'&&c!='\n')break;if(!nh_span(j->b,j->p++,1))return false;}return ++j->work<=65536;}
static bool token(jscan *j,uint8_t c){if(!ws(j)||j->p>=j->end||j->b->p[(size_t)j->p]!=c)return false;++j->p;return true;}
static int digit(uint8_t c){if(c>='0'&&c<='9')return c-'0';if(c>='a'&&c<='f')return c-'a'+10;if(c>='A'&&c<='F')return c-'A'+10;return -1;}
static bool unicode(jscan *j,uint32_t *v){uint32_t u=0;for(unsigned k=0;k<4;++k){if(j->p==j->end)return false;int n=digit(j->b->p[(size_t)j->p++]);if(n<0)return false;u=(u<<4)|(unsigned)n;}*v=u;return true;}
static bool text(jscan *j,char *out,size_t cap){size_t n=0;bool end=false;if(!token(j,34))return false;while(j->p<j->end){if(!nh_span(j->b,j->p,1)||n+5>=cap)return false;uint8_t c=j->b->p[(size_t)j->p++];if(c==34){end=true;break;}if(c<32)return false;if(c==92){if(j->p>=j->end)return false;c=j->b->p[(size_t)j->p++];if(c=='u'){uint32_t u;if(!unicode(j,&u))return false;if(u>=0xd800&&u<=0xdbff){uint32_t z;if(j->end-j->p<6||j->b->p[(size_t)j->p++]!=92||j->b->p[(size_t)j->p++]!='u'||!unicode(j,&z)||z<0xdc00||z>0xdfff)return false;u=0x10000+((u-0xd800)<<10)+(z-0xdc00);}else if(u>=0xdc00&&u<=0xdfff)return false;if(!u)return false;if(u<128)out[n++]=(char)u;else if(u<2048){out[n++]=(char)(192|(u>>6));out[n++]=(char)(128|(u&63));}else if(u<65536){out[n++]=(char)(224|(u>>12));out[n++]=(char)(128|((u>>6)&63));out[n++]=(char)(128|(u&63));}else{out[n++]=(char)(240|(u>>18));out[n++]=(char)(128|((u>>12)&63));out[n++]=(char)(128|((u>>6)&63));out[n++]=(char)(128|(u&63));}continue;}if(c=='b')c=8;else if(c=='f')c=12;else if(c=='n')c=10;else if(c=='r')c=13;else if(c=='t')c=9;else if(c!=34&&c!=92&&c!='/')return false;}out[n++]=(char)c;}out[n]=0;return end&&fourth_utf8((uint8_t *)out,n,j->b->pd);}
static bool number(jscan *j,uint64_t *v){uint64_t u=0;unsigned count=0;if(!ws(j))return false;while(j->p<j->end){uint8_t c=j->b->p[(size_t)j->p];if(c<'0'||c>'9')break;if(++count>10||!nh_span(j->b,j->p,1)||u>67108864/10)return false;if(count>1&&u==0)return false;u=u*10+c-'0';if(u>67108864)return false;++j->p;}*v=u;return count>0;}
static bool distinct(jscan *j,const char *a,const char *b){size_t n=xx_rt_strlen(a),z=xx_rt_strlen(b);if(++j->comparisons>1048576||fd_stop(j->b->pd))return false;if(n!=z)return true;if(n>16777216-j->comparebytes)return false;j->comparebytes+=n;return xx_rt_memcmp(a,b,n)!=0;}
static bool metadata(jscan *j){char names[256][256],value[2048];unsigned count=0;if(!token(j,'{')||!ws(j))return false;if(j->p<j->end&&j->b->p[(size_t)j->p]=='}'){++j->p;return true;}while(j->p<j->end){if(count>=256||!text(j,names[count],256))return false;for(unsigned i=0;i<count;++i)if(!distinct(j,names[i],names[count]))return false;++count;if(!token(j,':')||!text(j,value,sizeof(value))||!ws(j))return false;if(j->p<j->end&&j->b->p[(size_t)j->p]=='}'){++j->p;return true;}if(!token(j,','))return false;}return false;}
static bool descriptor(jscan *j,tensor *t){char key[64],dtype[32];unsigned flags=0,width=0;uint64_t count=1;bool shape=false;if(!token(j,'{'))return false;for(unsigned fields=0;fields<3;++fields){if(!text(j,key,sizeof(key))||!token(j,':'))return false;if(!xx_rt_strcmp(key,"dtype")){if((flags&1)||!text(j,dtype,sizeof(dtype)))return false;flags|=1;if(!xx_rt_strcmp(dtype,"BOOL")||!xx_rt_strcmp(dtype,"U8")||!xx_rt_strcmp(dtype,"I8"))width=1;else if(!xx_rt_strcmp(dtype,"F16")||!xx_rt_strcmp(dtype,"BF16")||!xx_rt_strcmp(dtype,"I16")||!xx_rt_strcmp(dtype,"U16"))width=2;else if(!xx_rt_strcmp(dtype,"F32")||!xx_rt_strcmp(dtype,"I32")||!xx_rt_strcmp(dtype,"U32"))width=4;else if(!xx_rt_strcmp(dtype,"F64")||!xx_rt_strcmp(dtype,"I64")||!xx_rt_strcmp(dtype,"U64"))width=8;else return false;}else if(!xx_rt_strcmp(key,"shape")){if((flags&2)||!token(j,'[')||!ws(j))return false;flags|=2;shape=true;if(j->p<j->end&&j->b->p[(size_t)j->p]==']')++j->p;else{unsigned dimensions=0;for(;;){uint64_t n;if(++dimensions>16||!number(j,&n)||!ws(j))return false;if(n&&count>67108864/n)return false;count*=n;if(j->p<j->end&&j->b->p[(size_t)j->p]==']'){++j->p;break;}if(!token(j,','))return false;}}}else if(!xx_rt_strcmp(key,"data_offsets")){if((flags&4)||!token(j,'[')||!number(j,&t->first)||!token(j,',')||!number(j,&t->last)||!token(j,']'))return false;flags|=4;}else return false;if(fields<2&&!token(j,','))return false;}if(flags!=7||!shape||!width||count>67108864/width||!token(j,'}'))return false;t->bytes=count*width;return t->last>=t->first&&t->last-t->first==t->bytes;}
static bool pm_parse(Abstractformat *f,pm_stream *s,xx_pd_struct *pd){nh_blob b;tensor *t=NULL;bool ok=false;unsigned count=0;bool meta=false,closed=false;if(!nh_load(f,&b,pd))return false;NH_NEED(b.n>=16);uint64_t hn=xx_data_get_u64(b.p, 8, 0, false);NH_NEED(hn>=2&&hn<=1048576&&nh_span(&b,8,hn)&&b.p[8]=='{');jscan j={&b,8,8+hn,0,0,0};t=(tensor *)xx_mem_alloc(1024*sizeof(tensor));NH_NEED(t&&token(&j,'{'));while(j.p<j.end){char name[256];NH_NEED(text(&j,name,sizeof(name))&&name[0]&&token(&j,':'));if(!xx_rt_strcmp(name,"__metadata__")){NH_NEED(!meta&&metadata(&j));meta=true;}else{NH_NEED(count<1024);for(unsigned i=0;i<count;++i)NH_NEED(distinct(&j,t[i].name,name));xx_rt_memcpy(t[count].name,name,xx_rt_strlen(name)+1);NH_NEED(descriptor(&j,t+count));++count;}NH_NEED(ws(&j));if(j.p<j.end&&b.p[(size_t)j.p]=='}'){++j.p;closed=true;break;}NH_NEED(token(&j,','));}NH_NEED(closed&&count>0&&ws(&j)&&j.p==j.end&&nh_add(f,s,&b,"safetensors-json-header",0,8+hn));uint64_t at=0;for(unsigned k=0;k<count;++k){unsigned found=count;for(unsigned i=0;i<count;++i)if(t[i].first==at&&(t[i].bytes==0||t[i].last>at)){if(found==count||t[i].bytes==0)found=i;}NH_NEED(found<count);NH_NEED(nh_add(f,s,&b,"stored-tensor",8+hn+t[found].first,t[found].bytes));at=t[found].last;t[found].first=UINT64_MAX;}NH_NEED(at==b.n-8-hn);s->size=(int64_t)b.n;ok=true;done:xx_mem_free(t);xx_mem_free(b.p);return ok;}

void xx_safetensors_init(xx_safetensors *r,xx_io_device *d,int64_t b){if(r){xx_mem_zero(r,sizeof(*r));pm_init(&r->format,d,b,XX_FILE_TYPE_SAFETENSORS,"bin");}}
xx_safetensors *xx_safetensors_create(xx_io_device *d,int64_t b){xx_safetensors *r=(xx_safetensors *)xx_mem_alloc(sizeof(*r));if(r)xx_safetensors_init(r,d,b);return r;}
void xx_safetensors_destroy(xx_safetensors *r){if(r)xx_format_cleanup_extra_parameters(&r->format);}
void xx_safetensors_free(xx_safetensors *r){if(r){xx_safetensors_destroy(r);xx_mem_free(r);}}
bool xx_safetensors_check_is_valid(Abstractformat *f,xx_pd_struct *pd){return pm_valid(f,pd);}
bool xx_safetensors_handle_base_info(Abstractformat *f,xx_pd_struct *pd){return pm_handle(f,pd);}
