/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/valve_gcf_cache/xx_valve_gcf_cache.h"

XX_FORMAT_DEFINE_READER_ADAPTER(valve_gcf_cache, XX_FILE_TYPE_VALVE_GCF_CACHE,
    xx_valve_gcf_cache_create(device, 0), xx_valve_gcf_cache_free, XX_READER_TYPE_FILL_UNKNOWN)

