/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 */

/* xx_cramfs_extractor.c - search raw data for CRAMFS.
 *
 * Scans for:
 *   45 3D CD 28 at +0  ("E=.(")
 *   28 CD 3D 45 at +0  ("(.=E")
 * Offset 0 is always tried as well.
 * Each candidate must be accepted by the cramfs reader, which also measures it,
 * and named by the detector, both on a view that starts at the candidate.
 * See xx_format_extractor_engine.h.
 *
 * GENERATED by gen_extractors.py from the detector's prefilters.
 */

#include "../xx_format_extractor_engine.h"
#include "xxfclib/formats/cramfs/xx_cramfs.h"

static const uint8_t k_anchor0[] = { 0x45, 0x3D, 0xCD, 0x28 };
static const uint8_t k_anchor1[] = { 0x28, 0xCD, 0x3D, 0x45 };

static const xx_format_search_anchor k_anchors[] = {
    { k_anchor0, sizeof(k_anchor0), 0U },
    { k_anchor1, sizeof(k_anchor1), 0U },
};

static const xx_file_type_t k_types[] = { XX_FILE_TYPE_CRAMFS };

static Abstractformat *xx_cramfs_search_open(xx_io_device *window) {
    xx_cramfs *reader = xx_cramfs_create(window, 0);
    return reader ? &reader->format : NULL;
}

static void xx_cramfs_search_close(Abstractformat *format) {
    /* The format is the first member, so this is the reader itself. */
    xx_cramfs_free((xx_cramfs *)format);
}

static const xx_format_search_desc k_desc = {
    k_types, sizeof(k_types) / sizeof(k_types[0]),
    k_anchors, sizeof(k_anchors) / sizeof(k_anchors[0]),
    xx_cramfs_search_open, xx_cramfs_search_close
};

static xx_format_search_state *xx_cramfs_create_format_search(
    xx_format_extractor *self, xx_io_device *device, const xx_list_s *options,
    xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_create(&k_desc, device, options, pd);
}

static const xx_format_search_info *xx_cramfs_get_current_format_info(
    xx_format_extractor *self, xx_format_search_state *state) {
    (void)self;
    return xx_format_search_current(state);
}

static bool xx_cramfs_format_search_find_next(xx_format_extractor *self,
                                          xx_format_search_state *state,
                                          xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_find_next(state, pd);
}

static void xx_cramfs_free_format_search(xx_format_extractor *self,
                                     xx_format_search_state *state) {
    (void)self;
    xx_format_search_free(state);
}

xx_format_extractor xx_cramfs_extractor = {
    xx_cramfs_create_format_search,
    xx_cramfs_get_current_format_info,
    xx_cramfs_format_search_find_next,
    xx_cramfs_free_format_search
};
