/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/northstar_nsi/xx_northstar_nsi.h"

XX_FORMAT_DEFINE_READER_ADAPTER(northstar_nsi, XX_FILE_TYPE_NORTHSTAR_NSI,
    xx_northstar_nsi_create(device, 0), xx_northstar_nsi_free, XX_READER_TYPE_FILL_UNKNOWN)

