/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/instalit_data/xx_instalit_data.h"

XX_FORMAT_DEFINE_READER_ADAPTER(instalit_data, XX_FILE_TYPE_INSTALIT_DATA,
    xx_instalit_data_create(device, 0), xx_instalit_data_free, XX_READER_TYPE_FILL_UNKNOWN)

