/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/cbm_d64/xx_cbm_d64.h"

XX_FORMAT_DEFINE_READER_ADAPTER(cbm_d64, XX_FILE_TYPE_CBM_D64,
    xx_cbm_d64_create(device, 0), xx_cbm_d64_free, XX_READER_TYPE_FILL_UNKNOWN)

