/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/pce_pbit/xx_pce_pbit.h"

XX_FORMAT_DEFINE_READER_ADAPTER(pce_pbit, XX_FILE_TYPE_PCE_PBIT,
    xx_pce_pbit_create(device, 0), xx_pce_pbit_free, XX_READER_TYPE_FILL_UNKNOWN)

