/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/atheos_fs/xx_atheos_fs.h"

XX_FORMAT_DEFINE_READER_ADAPTER(atheos_fs, XX_FILE_TYPE_ATHEOS_FS,
    xx_atheos_fs_create(device, 0), xx_atheos_fs_free, XX_READER_TYPE_FILL_UNKNOWN)

