/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/risc_os_sprite/xx_risc_os_sprite.h"

XX_FORMAT_DEFINE_READER_ADAPTER(risc_os_sprite, XX_FILE_TYPE_RISC_OS_SPRITE,
    xx_risc_os_sprite_create(device, 0), xx_risc_os_sprite_free, XX_READER_TYPE_FILL_UNKNOWN)

