/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 */

/* xx_warc_extractor.c - search raw data for WARC.
 *
 * Scans for:
 *   57 41 52 43 2F 31 2E at +0  ("WARC.1.")
 *   57 41 52 43 2F 30 2E at +0  ("WARC.0.")
 * Offset 0 is always tried as well.
 * Each candidate must be accepted by the warc reader, which also measures it,
 * and named by the detector, both on a view that starts at the candidate.
 * See xx_format_extractor_engine.h.
 *
 * GENERATED by gen_extractors.py from the detector's prefilters.
 */

#include "../xx_format_extractor_engine.h"
#include "xxfclib/formats/warc/xx_warc.h"

static const uint8_t k_anchor0[] = { 0x57, 0x41, 0x52, 0x43, 0x2F, 0x31, 0x2E };
static const uint8_t k_anchor1[] = { 0x57, 0x41, 0x52, 0x43, 0x2F, 0x30, 0x2E };

static const xx_format_search_anchor k_anchors[] = {
    { k_anchor0, sizeof(k_anchor0), 0U },
    { k_anchor1, sizeof(k_anchor1), 0U },
};

static const xx_file_type_t k_types[] = { XX_FILE_TYPE_WARC };

static Abstractformat *xx_warc_search_open(xx_io_device *window) {
    xx_warc *reader = xx_warc_create(window, 0);
    return reader ? &reader->format : NULL;
}

static void xx_warc_search_close(Abstractformat *format) {
    /* The format is the first member, so this is the reader itself. */
    xx_warc_free((xx_warc *)format);
}

static const xx_format_search_desc k_desc = {
    k_types, sizeof(k_types) / sizeof(k_types[0]),
    k_anchors, sizeof(k_anchors) / sizeof(k_anchors[0]),
    xx_warc_search_open, xx_warc_search_close
};

static xx_format_search_state *xx_warc_create_format_search(
    xx_format_extractor *self, xx_io_device *device, const xx_list_s *options,
    xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_create(&k_desc, device, options, pd);
}

static const xx_format_search_info *xx_warc_get_current_format_info(
    xx_format_extractor *self, xx_format_search_state *state) {
    (void)self;
    return xx_format_search_current(state);
}

static bool xx_warc_format_search_find_next(xx_format_extractor *self,
                                          xx_format_search_state *state,
                                          xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_find_next(state, pd);
}

static void xx_warc_free_format_search(xx_format_extractor *self,
                                     xx_format_search_state *state) {
    (void)self;
    xx_format_search_free(state);
}

xx_format_extractor xx_warc_extractor = {
    xx_warc_create_format_search,
    xx_warc_get_current_format_info,
    xx_warc_format_search_find_next,
    xx_warc_free_format_search
};
