/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/enigma_virtual_box/xx_enigma_virtual_box.h"

XX_FORMAT_DEFINE_READER_ADAPTER(enigma_virtual_box, XX_FILE_TYPE_ENIGMA_VIRTUAL_BOX,
    xx_enigma_virtual_box_create(device, 0), xx_enigma_virtual_box_free, XX_READER_TYPE_FILL_UNKNOWN)

