/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/vmdk_sesparse/xx_vmdk_sesparse.h"

XX_FORMAT_DEFINE_READER_ADAPTER(vmdk_sesparse, XX_FILE_TYPE_VMDK_SESPARSE,
    xx_vmdk_sesparse_create(device, 0), xx_vmdk_sesparse_free, XX_READER_TYPE_FILL_UNKNOWN)

