/* Generated by generate_die_music_files.py; do not edit. */
/* SPDX-License-Identifier: MIT */
#include "xxfclib/formats/die_music/xx_die_music.h"
#include "../../xx_format_extractor_engine.h"
#include "../../xx_format_abstract_extractor_adapter.h"

const xx_die_music_descriptor xx_die_music_packen_muap98_object_descriptor = {
    "PACKEN_MUAP98_OBJECT",
    "Packen/\343\201\261\343\201\243\343\201\217\343\202\223 Software MUAP98/\343\201\277\343\202\205\343\201\202\343\201\243\343\201\267 Object chiptune (.O,.OX+TONES.DTA)",
    "Binary/audio.1.sg",
    8881U,
    false,
    XX_FILE_TYPE_DIE_MUSIC_PACKEN_MUAP98_OBJECT
};

XXFC_API Abstractformat *xx_die_music_packen_muap98_object_create(xx_io_device *device, int64_t base)
{
    return xx_die_music_reader_create(&xx_die_music_packen_muap98_object_descriptor, device, base);
}

XXFC_API void xx_die_music_packen_muap98_object_free(void *reader)
{
    xx_die_music_reader_free(reader);
}

static const xx_file_type_t xx_die_music_packen_muap98_object_types[] = {
    XX_FILE_TYPE_DIE_MUSIC_PACKEN_MUAP98_OBJECT
};

static Abstractformat *xx_die_music_packen_muap98_object_open(xx_io_device *window)
{
    return xx_die_music_packen_muap98_object_create(window, 0);
}

static void xx_die_music_packen_muap98_object_close(Abstractformat *format)
{
    xx_die_music_packen_muap98_object_free(format);
}

static const xx_format_search_desc xx_die_music_packen_muap98_object_search_desc = {
    xx_die_music_packen_muap98_object_types, 1U, NULL, 0U,
    xx_die_music_packen_muap98_object_open, xx_die_music_packen_muap98_object_close, true
};

static xx_format_search_state *xx_die_music_packen_muap98_object_create_search(
    xx_format_extractor *self, xx_io_device *device,
    const xx_list_s *options, xx_pd_struct *pd)
{
    (void)self;
    return xx_format_search_create(&xx_die_music_packen_muap98_object_search_desc, device, options, pd);
}

static const xx_format_search_info *xx_die_music_packen_muap98_object_current(
    xx_format_extractor *self, xx_format_search_state *state)
{
    (void)self;
    return xx_format_search_current(state);
}

static bool xx_die_music_packen_muap98_object_next(
    xx_format_extractor *self, xx_format_search_state *state, xx_pd_struct *pd)
{
    (void)self;
    return xx_format_search_find_next(state, pd);
}

static void xx_die_music_packen_muap98_object_free_search(
    xx_format_extractor *self, xx_format_search_state *state)
{
    (void)self;
    xx_format_search_free(state);
}

xx_format_extractor xx_die_music_packen_muap98_object_extractor = {
    xx_die_music_packen_muap98_object_create_search,
    xx_die_music_packen_muap98_object_current,
    xx_die_music_packen_muap98_object_next,
    xx_die_music_packen_muap98_object_free_search
};

XX_FORMAT_DEFINE_ABSTRACT_EXTRACTOR(
    die_music_packen_muap98_object, xx_die_music_packen_muap98_object_search_desc)
