/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 */

/* xx_encrpted_img_extractor.c - search raw data for D-Link encrpted_img.
 *
 * Scans for:
 *   65 6E 63 72 70 74 65 64 5F 69 6D 67 at +0  ("encrpted_img")
 * Offset 0 is always tried as well.
 * Each candidate must be accepted by the encrpted_img reader, which also measures it,
 * and named by the detector, both on a view that starts at the candidate.
 * See xx_format_extractor_engine.h.
 *
 * GENERATED by gen_extractors.py from the detector's prefilters.
 */

#include "../xx_format_extractor_engine.h"
#include "xxfclib/formats/encrpted_img/xx_encrpted_img.h"

static const uint8_t k_anchor0[] = { 0x65, 0x6E, 0x63, 0x72, 0x70, 0x74, 0x65, 0x64, 0x5F, 0x69, 0x6D, 0x67 };

static const xx_format_search_anchor k_anchors[] = {
    { k_anchor0, sizeof(k_anchor0), 0U },
};

static const xx_file_type_t k_types[] = { XX_FILE_TYPE_ENCRPTED_IMG };

static Abstractformat *xx_encrpted_img_search_open(xx_io_device *window) {
    xx_encrpted_img *reader = xx_encrpted_img_create(window, 0);
    return reader ? &reader->format : NULL;
}

static void xx_encrpted_img_search_close(Abstractformat *format) {
    /* The format is the first member, so this is the reader itself. */
    xx_encrpted_img_free((xx_encrpted_img *)format);
}

static const xx_format_search_desc k_desc = {
    k_types, sizeof(k_types) / sizeof(k_types[0]),
    k_anchors, sizeof(k_anchors) / sizeof(k_anchors[0]),
    xx_encrpted_img_search_open, xx_encrpted_img_search_close
};

static xx_format_search_state *xx_encrpted_img_create_format_search(
    xx_format_extractor *self, xx_io_device *device, const xx_list_s *options,
    xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_create(&k_desc, device, options, pd);
}

static const xx_format_search_info *xx_encrpted_img_get_current_format_info(
    xx_format_extractor *self, xx_format_search_state *state) {
    (void)self;
    return xx_format_search_current(state);
}

static bool xx_encrpted_img_format_search_find_next(xx_format_extractor *self,
                                          xx_format_search_state *state,
                                          xx_pd_struct *pd) {
    (void)self;
    return xx_format_search_find_next(state, pd);
}

static void xx_encrpted_img_free_format_search(xx_format_extractor *self,
                                     xx_format_search_state *state) {
    (void)self;
    xx_format_search_free(state);
}

xx_format_extractor xx_encrpted_img_extractor = {
    xx_encrpted_img_create_format_search,
    xx_encrpted_img_get_current_format_info,
    xx_encrpted_img_format_search_find_next,
    xx_encrpted_img_free_format_search
};
