/* Copyright (c) 2026 hors<horsicq@gmail.com>
 * SPDX-License-Identifier: MIT
 * Generated by tools/generate_reader_only_abstract_extractors.py.
 * Readers without fixed scan anchors search offset zero only. */
#include "../adapters/xx_reader_adapter.h"
#include "xxfclib/formats/sgi_volume_header/xx_sgi_volume_header.h"

XX_FORMAT_DEFINE_READER_ADAPTER(sgi_volume_header, XX_FILE_TYPE_SGI_VOLUME_HEADER,
    xx_sgi_volume_header_create(device, 0), xx_sgi_volume_header_free, XX_READER_TYPE_FILL_UNKNOWN)

